### ISSUE TITLE
Il Vecchio Molino a #PieveTorina ha bisogno di beni alimentari di prima necessità

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1004]
<pre><yamldata>tel: '339 871 2991'
email: fronzice@tiscali.it
cosa: 'VECCHIO MOLINO - BISOGNO DI CIBO'
descrizione: 'Il Vecchio Molino di Casavecchia, Pieve Torina è una delle poche attività rimaste in piedi tra Castelsant''Angelo e Muccia. La struttura sfama oltre 150 vigili del fuoco a pasto e chi non ha più una casa. Non esiste più un negozio per fare la spesa nelle vicinanze. C''E'' BISOGNO DI CIBO: CARNE, PASTA, SUGHI, VERDURE,BEVANDE, CAFFÈ, Piatti e Bicchieri di plastica. Contattare Silvia Fronzi.'
indirizzo: 'Strada Provinciale 209 Valnerina, Pieve Torina, MC, Marche, Italia'
lat: '42.9978554'
lon: '13.0574021'
link: 'https://www.facebook.com/serefro91/posts/10211343643936769'
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Ristorante ancora aperto e funzionante ma non hanno più bisogno di cibo.
