### ISSUE TITLE
Beni di prima necessità - Porto Recanati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1005]
<pre><yamldata>tel: '335 565 1639'
email: ''
cosa: 'Beni di prima necessità - Porto Recanati'
descrizione: 'CAMPING BELLAMARE Porto Recanati: i cittadini di Ussita sono stati tutti trasferiti qui. Hanno bisogno di tutto: Alimentari a lunga scadenza (anche succhi di frutta, merendine), Prodotti per il bagno, Vestiti anche leggeri, Gonne, Biancheria per uomo/donna, Scarpe adulti e scarpe bambini, Giochi per bambini. Rivolgersi a Frontignano BikePark o portarle direttamente.'
indirizzo: 'Via Manin, Porto Recanati, MC, Marche, 62017, Italia'
lat: '43.4350815'
lon: '13.6630083'
link: 'https://www.facebook.com/frontignano.bikepark/posts/1813500948865652'
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
Christian Varani su facebook scirve che la raccolta è stata sospesa. https://www.facebook.com/groups/1758670357733881/permalink/1793431137591136/

**Comment by chiccap** [comment]
Raccolta conclusa.
