### ISSUE TITLE
Ad #Amatrice cercasi urgentemente un gazebo per camper e un container

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1008]
<pre><yamldata>tel: ''
email: ''
cosa: '#amatrice Cercasi urgentemente un gazebo per camper e un container'
descrizione: 'Cercasi urgentemente un gazebo per camper e un container non per uso abitativo per una famiglia colpita dal terremoto in grande difficoltà. La consegna deve avvenire sul posto, per chi potesse aiutare contattare 392 7015986.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/emanuela.bignami.9/posts/10154612533584449'
immagine: 'http://i.imgur.com/ufCGqwj.jpg'
data: 31/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
