### ISSUE TITLE
test da windows10 mobile lumia

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro_segnalazioni#101]
<pre><yamldata>tel: +393476409364
email: macorte@gmail.com
descrizione: test da windows10 mobile lumia 650
indirizzo: Viale dell'Arte, 66, 00144 Roma, Italia
lat: 41.8290647
lon: 12.473820100000012
link: http://www.acor3.it
immagine: 
data: 08/09/2016</yamldata></pre>

**Comment by marco-acorte** [comment]
x @Pinzauti  
non mi fa allegare img quando fotocamera smarthphone fa foto grandi (lumia 650 8-megapixel)

**Comment by marco-acorte** [comment]
es.
![wp_20160906_11_15_44_pro](https://cloud.githubusercontent.com/assets/6375935/18350671/3827986e-75d7-11e6-9b56-66b3210cb67e.jpg)

**Comment by Pinzauti** [comment]
Che ti dice @marco-acorte ? Immagine troppo grande (O file troppo pesante non ricordo)?
Se è quello l'ho fatto per mettere un limite ma nel caso lo posso alzare

**Comment by marco-acorte** [comment]
si alza un po il limite 8mpixel in jpg sono all 'incirca 2,2 mb

**Comment by marco-acorte** [comment]
test img pesanti passati. OK.
