### ISSUE TITLE
#Norcia acqua e recinti per gli animali

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1011]
<pre><yamldata>tel: ''
email: ''
cosa: 'acqua e recinti per gli animali'
descrizione: 'Valentina Fausti, imprenditrice locale, norcineria'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.repubblica.it/cronaca/2016/10/31/foto/terremoto_centro_italia_prosciutto-151028856/1/#1'
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Fabbisogno che non se accettare, rilancia una richiesta pubblicata su Repubblica senza aggiungere altro...

**Comment by chiccap** [comment]
Chiudiamo?

**Comment by cristigalas** [comment]
Sì.
