### ISSUE TITLE
Limite peso immagini alzato!

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro_segnalazioni#102]
<pre><yamldata>tel: +393272032790
email: francescopinzauti@gmail.com
cosa: Limite peso immagini alzato!
descrizione: Alzato il limite della dimensione delle immagini caricaibli.
indirizzo: Piazza della Repubblica, 10, 00185 Roma, Italia
lat: 41.90278349999999
lon: 12.496365500000024
link: https://www.google.it
immagine: https://terremoto.francescopinzauti.com/img/08-42-253827986e-75d7-11e6-9b56-66b3210cb67e.jpg
data: 08/09/2016</yamldata></pre>

**Comment by Pinzauti** [comment]
Alzato il limite a 3 mega.
Riprova @marco-acorte

**Comment by marco-acorte** [comment]
test ok vedi issue #103
