### ISSUE TITLE
Raccolta beni e indumenti - Centro di raccolta Palestra Diaz a #PortoRecanati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1022]
<pre><yamldata>tel: ''
email: ''
cosa: 'Raccolta beni e indumenti - Centro di raccolta Palestra Diaz a #PortoRecanati'
descrizione: 'Da ieri, 31 ottobre, è attivo a Porto Recanati il centro di raccolta alla Palestra della Scuola ex Diaz per raccogliere beni di prima necessità e indumenti per gli sfollati ospitati in vari camping e strutture di Porto Recanati. In particolare si raccolgono coperte, biancheria intima uomo/donna, pigiami, ciabatte, jeans uomo/donna taglia 44-46-48-50. Non portare altri tipi di indumenti. Il centro è l''unico abilitato a raccogliere questo tipo di materiale.'
indirizzo: 'Via Manin, Porto Recanati, MC, Marche, 62017, Italia'
lat: '43.4350815'
lon: '13.6630083'
link: 'http://www.ilcittadinodirecanati.it/porto-recanati/30794-porto-recanati-in-prima-linea-nell-accoglienza-agli-sfollati-sono-gia-quasi-500-in-tre-camping'
immagine: ''
data: 01/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Su Fb scrivono che hanno raccolto quanto era necessario e dunque il centro di raccolta per ora chiude. Qui il post: https://www.facebook.com/groups/1758670357733881/permalink/1793454687588781/
