### ISSUE TITLE
Test invio img 8megapixel

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro_segnalazioni#103]
<pre><yamldata>tel: 3476409364
email: macorte@gmail.com
descrizione: Test invio img 8megapixel
indirizzo: Viale della Letteratura, 30, 00144 Roma, Italia
lat: 41.83311
lon: 12.475630000000023
link: 
immagine: https://terremoto.francescopinzauti.com/img/09-33-21WP_20160908_16_33_01_Pro.jpg
data: 08/09/2016</yamldata></pre>

**Comment by marco-acorte** [comment]
test ok
