### ISSUE TITLE
Offro posto letto provincia di #Perugia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1033]
<pre><yamldata>tel: '3493088138'
email: pressoffice67@gmail.com
descrizione: 'Offro posto letto in camera singola per un breve periodo in contesto immerso nel vede a 20 km da Perugia. Necessaria auto per spostamenti.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 01/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Alloggio non più disponibile. Chiudo.
