### ISSUE TITLE
Disponibilità alloggio in albergo a Tornimparte (Abruzzo)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1038]
<pre><yamldata>tel: '333 2057945'
email: ''
descrizione: 'Ciao a tutti vi scrivo dall Hotel Grazia,Ristorante la Capricciosa mettiamo a disposizione dai prossimi giorni la nostra struttura alberghiera per ospitare le persone che sono state costrette a lasciare le proprie abitazioni a causa del sisma del centro Italia. Condividete questo post in modo da poter raggiungere le persone interessate. Indirizzo : Via Delle Conserve 14,Tornimparte, Telefono : Tel 0862 72765'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/photo.php?fbid=1173217876102051&set=a.440602599363586.1073741825.100002415508365&type=3'
immagine: ''
data: 01/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Offerta già presente.
