### ISSUE TITLE
non so se ho inserito l'ospitlità per una famiglia in modo corretto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1057]
<pre><yamldata>tel: '347 5758039'
email: franco.algieri@libero.it
cosa: 'non so se ho inserito l''ospitlità per una famiglia in modo corretto'
descrizione: 'ospito fino a gennaio in famiglia, una famiglia a Casalpusterlengo. non si riesce a mettere l''indirizzo di casa mia, come fare ?'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 02/11/2016
</yamldata></pre>

**Comment by favoeva** [comment]
l'issue esiste già ed è stata accettata
