### ISSUE TITLE
#Macerata - Raccolta giochi, cancelleria per bimbi, coperte e prodotti igiene personale

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1060]
<pre><yamldata>tel: '0733230046 / 0733234860'
email: bdl.ricerca@bdl.it
cosa: '#Macerata - Raccolta giochi, cancelleria per bimbi, coperte e prodotti igiene personale'
descrizione: 'E’ stato attivato un punto di raccolta per le cose che servono agli sfollati presso la Bottega del Libro di Macerata, corso della Repubblica 7/9. Chiara, la titolare, è in contatto con la Protezione Civile, che passerà in libreria a raccogliere quanto ricevuto. Per il momento servono: - GIOCATTOLI (non per neonati ma per bambini dai 4 anni in su) - COLORI - ALBUM PER DISEGNARE - LIBRI - COPERTE. Si raccolgono anche: prodotti per l’igiene personale (spazzolini, spugne, dentifrici, salviette umide corpo e intimo, shampoo, bagnoschiuma, deodoranti, rasoi, detergenti intimi, cuffie per la doccia, carta igienica, cotton fioc etc…), prodotti per la pulizia della casa (spugne, detergenti pavimenti, sgrassatori, scottex, stracci etc….), phon per i capelli, caricabatterie cellulari, prodotti per i bambini (prodotti, pannolini, vestiti). Ogni aggiornamento verrà reso pubblico anche attraverso il sito mammemarchigiane.it'
indirizzo: 'Corso della Repubblica, Centro Storico, Macerata, MC, Marche, 62100, Italia'
lat: '43.2991099'
lon: '13.4513634'
link: 'http://www.mammemarchigiane.it/2016/11/02/punto-di-raccolta-alla-bottega-del-libro-a-macerata-per-aiutare-i-terremotati/'
immagine: ''
data: 02/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
