### ISSUE TITLE
Comune di Pieve Torina

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1061]
<pre><yamldata>chi: 'Comune di Pieve Torina'
descrizione: 'Raccolta fondi per terremotati. #TerremotoCentroItalia'
intestazione: ''
iban: 'IBAN IT75U0605569080000000001554'
bic: ''
postale: ''
causale: 'EMERGENZA TERREMOTO 2016'
link: 'http://www.comune.pievetorina.mc.it'
email: ''
data: 02/11/2016
</yamldata></pre>

**Comment by favoeva** [comment]
segnalazione doppia
