### ISSUE TITLE
Offro ospitalità in famiglia 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1063]
<pre><yamldata>tel: '3475758039'
email: franco.algieri@libero.it
descrizione: 'Offro ospitalità in famiglia ad una famiglia fino a gennaio 2017. Potrebbe essere anche oltre.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 02/11/2016
</yamldata></pre>

**Comment by favoeva** [comment]
chiesto via email dove si trova l'alloggio
