### ISSUE TITLE
REGIONE LAZIO, ATTIVATO CAMPER A LEONESSA PER VALUTARE DANNI AZIENDE AGRICOLE

### ISSUE THREAD

**Issue by milanini** [emergenzeHack/terremotocentro_segnalazioni#1064]
La Regione Lazio ha trasferito da Accumoli, dove sono terminati i rilievi, al Comune di Leonessa, il camper regionale che fornisce servizio di assistenza e di intervento a sostegno degli allevatori e agricoltori dei Comuni gravemente danneggiati dalle ultime scosse di terremoto del 30 ottobre. 

http://www.comunedileonessa.eu/sisma-30102016-danni-aziende-agricole/

**Comment by favoeva** [comment]
chiudo e inserisco via web form
