### ISSUE TITLE
PRODOTTI ZONE TERREMOTATE: apre il sito Terremoviamoci

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1067]
<pre><yamldata>titolo: 'ACQUISTI SOLIDALI DI PRODOTTI DELLE TERRE COLPITE DAL TERREMOTO: apre il sito Terremoviamoci'
descrizione: 'Un aiuto concreto, un''idea solidale con la quale sostenere e salvaguardare un patrimonio cruciale del nostro territorio. Il contributo del sito va a tutte quelle attività umane che devono tornare ad essere per la coraggiosa continuità della propria storia. Nato come Facebook Group è ora un sito nel quale cercheremo di dare voce, grazie alle vostre segnalazioni, a tutte quelle attività da sostenere ed aiutare a ripartire.'
link: 'http://www.terremoviamoci.it/'
data: 02/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Sito non più disponibile.
