### ISSUE TITLE
A #Montemonaco (Ap) servono tende, moduli abitativi, psicologi, interventi nelle chiese

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1074]
<pre><yamldata>tel: '338 4104640'
email: martellinipaola@gmail.com, manuela.corbelli@hotmail.com
cosa: 'Terremoto Montemonaco'
descrizione: 'Il Comune di Montemonaco ha bisogno di tende, moduli abitativi, soccorso psicologico, messa in sicurezza beni architettonici (chiese). Spostamento opere di pregio altrove. Situazione aggiornata al 4/11: 150 dormono in auto, 50 container, 70 sfollati'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 02/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Stamani ci ha scritto su Twitter Marco Fioravanti di Anci Marche dandoci un indirizzo email a cui inviare la richiesta beni e necessità (che @cristigalas ha girato alla cittadina che ci aveva fatto la segnalazione) e poi la cittadina ci ha scritto che un gruppo di piscologi da Torino si sta muovendo per andare da loro.
![tci](https://cloud.githubusercontent.com/assets/21237278/20003592/a3f4ca94-a287-11e6-878b-b005d11908c4.png)

**Comment by chiccap** [comment]
@cristigalas aveva inviato la richiesta via twitter ai Psicologi per i popoli che a quanto pare si sono subito mossi e poi anche Marco Fioravanti di Anci Marche si è mosso subito ed è stato fondamentale anche aver agganciato su twitter Croce Gialla di Falconara.
