### ISSUE TITLE
Servono volontari al camping Medusa di #PortoRecanati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1077]
<pre><yamldata>tel: '071 7500725'
email: ''
cosa: 'Servono volontari al camping Medusa di #PortoRecanati'
descrizione: 'Serve aiuto per coprire dei turni di assistenza presso il camping Medusa di Porto Recanati dove sono ospitati i terremotati.'
indirizzo: 'Viale Ludovico Scarfiotti, Porto Recanati, MC, Marche, 62017, Italia'
lat: '43.4540987'
lon: '13.652593'
link: 'https://twitter.com/wineblogroll/status/793894894737711104'
immagine: ''
data: 02/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Il camping Medusa non ospita più sfollati.
