### ISSUE TITLE
Mettiamo a disposizione monolocale a Biella

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1095]
<pre><yamldata>tel: '3208395851'
email: info@domustutor.it
descrizione: 'Mettiamo a disponizione delle persone colpite dal sisma che hanno perso la loro casa un monolocale nel centro di Biella. L''abitazione è al piano rialzato quindi fruibile anche da persone anziane. Al momento non è arredato ma nel caso ci fosse interesse provvederemo a dotarlo degli arredi necessari. Disponibile fino alla primavera del 2017.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 03/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Non più disponibile.
