### ISSUE TITLE
Agli uffici del Parco Monti Sibillini occorrono 10 monitor, tastiere e mouse

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1100]
<pre><yamldata>tel: '3665667927'
email: ''
cosa: 'Agli uffici del Parco Mnti Sibillini occorrono 10 monitor, tastiere e mouse'
descrizione: 'Il Parco Nazionale dei Monti Sibillini, per ripristinare nel minor tempo possibile la funzionalità minima, necessita di reperire urgentemente 10 monitor, tastiere e mouse anche usati (o vecchi) in donazione o prestito (non PC). Chi volesse può contattare il seguente numero: 3665667927. Preferibilmente nelle immediate vicinanze di Tolentino oppure Foligno.'
indirizzo: 'Piazza del forno, Visso, MC, Marche, 62039, Italia'
lat: '42.930164'
lon: '13.0876826122235'
link: 'http://www.sibillini.net'
immagine: ''
data: 03/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
A seguito di un commento sul sito che chiedeva se ci fosse ancora bisogno del materiale, ho chiamato il numero di riferimento e mi è stato detto che sono riusciti a reperire l'attrezzatura ieri. Ho fatto una breve induction su TCI e gli ho girato tutti i nostri contatti per future segnalazioni. Ora chiudo issue!
