### ISSUE TITLE
Cercasi roulotte a #Amatrice per una famiglia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1110]
<pre><yamldata>tel: '3494639384'
email: valeria.patacchiola.arci@gmail.com
cosa: Roulotte
descrizione: 'Stiamo cercando una roulotte per una famiglia di Amatrice che ha deciso di rimanere a vivere vicino alla propria casa.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 04/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
