### ISSUE TITLE
Gus Gruppo Umana Solidarietà - Raccolta fondi per moduli abitativi

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1112]
<pre><yamldata>chi: 'Gus Gruppo Umana Solidarietà'
descrizione: 'Raccolta fondi per rendere fruibili i moduli abitativi per gli allevatori dell''Alto Maceratese che vogliono restare vicini ai loro animali. Le forniture dovrebbero essere consegnate entro fine novembre.'
intestazione: 'Allevatori - Moduli abitativi per restare accanto agli animali'
iban: 'IT66Y0335901600100000131559'
bic: ''
postale: ''
causale: 'Emergenza Terremoto Centro Italia'
link: 'https://goo.gl/3WfBz1'
email: 'alessio.ruta@gmail.com'
data: 04/11/2016
</yamldata></pre>

**Comment by favoeva** [comment]
Chiusa su richiesta via Mail del GUS
