### ISSUE TITLE
Servono beni prima necessità a #PortoRecanati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1114]
<pre><yamldata>tel: ''
email: ''
cosa: 'Necessità beni prima necessità a Porto Recanati'
descrizione: 'ATTENZIONE URGENTE 04/11/2016 - Ore 18,30 Siamo sommersi di richieste di: - Pigiami pesanti - Biancheria intima pesante per anziani (uomo donna) - Scarpe nuove (uomo - donna - bambini) - Lysoform e candeggina - Alimenti per cani e gatti secco e umido - intimo in generale Dateci una mano. CONDIVIDETE. Siamo a corto di questo materiale e ce lo stanno chiedendo da tutte le zone. Le consegne del predetto materiale vanno effettuate presso la ex scuola Diaz a Porto Recanati. AIUTATECI!!!!'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/largano.portorecanati/posts/648678321977944'
immagine: ''
data: 04/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Ho contattato la persona che ha fatto la segnalazione e mi ha confermato che hanno trasferito la richiesta alla prospezione civile che se ne sta occupando. Chiudo?
