### ISSUE TITLE
A San Benedetto del Tronto servono ferri, uncinetti, cotone e lana per anziane sfollate

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1128]
<pre><yamldata>tel: ''
email: ''
cosa: 'A San Benedetto del Tronto servono ferri, uncinetti, cotone e lana per anziane sfollate'
descrizione: 'Alla protezione civile di San Benedetto del Tronto (ex Scuola Curzi) stanno raccogliendo ferri per lana, uncinetti, matassine di cotone e lana per far passare qualche ora alle persone della terza età. Chi può portare li qualcosa o spedirla a me che la porto a mano appena arriva. Daniela Camusi'
indirizzo: 'Via Raffaello Sanzio, Marina centro, San Benedetto del Tronto, AP, Marche, 63039, Italia'
lat: '42.9525328'
lon: '13.8807144'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1795206237413626/'
immagine: ''
data: 06/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Stefano Pardini (commento sul sito) ha portato 2 scatoloni di materiale il 19/11. Non chiudo la issue in quanto Daniela Camusi, referente segnalazione, ha detto che ce n'è sempre bisogno.

**Comment by chiccap** [comment]
Raccolta conclusa.
