### ISSUE TITLE
PER UNA RETE DI PRESIDI CIVICI DELLE COMUNITA’ COINVOLTE DAL SISMA IN UMBRIA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1131]
<pre><yamldata>titolo: 'PER UNA RETE DI PRESIDI CIVICI DELLE COMUNITA’ COINVOLTE DAL SISMA IN UMBRIA'
descrizione: 'SISMA IN UMBRIA: CONVOCAZIONE INCONTRO PRESSO LA SEDE DI CITTADINANZATTIVA SPOLETO martedì 8 novembre ore 18,30 Via XXV Aprile 44 Spoleto - 0743 222208 #terremotocentroitalia #presidicivici PER UNA RETE DI PRESIDI CIVICI DELLE COMUNITA’ COINVOLTE DAL SISMA IN UMBRIA Chiunque sia interessato a dare una mano è benvenuto. L''invito è esteso alle associazioni di impegno civico. Importante la presenza di rappresentanti di tutti i comuni umbri terremotati. In questi giorni, a fronte di una gestione buona dell''emergenza da parte di Protezione civile e Autorità locali, la complessità delle situazioni (tante frazioni di montagna rimaste a lungo isolate e senza aiuti, la difficoltà di comunicazione e di viabilità) ha però evidenziato l''importanza del ruolo attivo dei cittadini e dei volontari che in molti casi hanno preso in mano direttamente le situazioni e risolto molti problemi di disagio, fin dalle primissime ore dopo le nuove crisi sismiche del mese di ottobre. Tutto quello che riguarda dunque il superamento dell’emergenza e soprattutto il prefigurare progressivamente uno specifico futuro per le zone colpite dal sisma nell’Italia centrale e quindi anche in Umbria, non può non passare attraverso una partecipazione e un consenso attivo dei cittadini e delle comunità locali interessate. “Fare i cittadini è il modo migliore di esserlo” anche in situazioni delicate e molto complesse come sono quelle che stiamo vivendo a seguito delle scosse. In questo stato di eccezione, bisogna pensare ad un modello di intervento che oltre all’assistenza e al supporto, introduca effettive condizioni e modalità per rendere pienamente protagoniste le comunità locali, in un rapporto di collaborazione e cooperazione con le istituzioni locali e la protezione civile. Per questo ci ritroviamo martedi 8 novembre alle ore 18,30 c/o la sede di Cittadinanzattiva in via XX Aprile n.44 (tel. 0743 222208) a Spoleto per valutare insieme la possibilità di costituire una rete di PRESIDI CIVICI delle comunità locali, come forma autonoma e diretta di partecipazione dei cittadini. Gli obiettivi operativi sono quelli di essere parte attiva come cittadini nelle attività di informazione e comunicazione, di organizzazione e gestione delle strutture allestite allo scopo, di ripristino delle attività e delle condizioni di progressiva “normalità” e di definizione dei criteri generali per la ricostruzione, che sappiamo, non è solo legate alle strutture, ma investe il futuro socio-culturale ed economico di queste zone. Chiunque sia interessato a dare una mano, è benvenuto. Estendiamo l''invito alle associazioni di impegno civico del territorio..'
link: ''
data: 06/11/2016
</yamldata></pre>

**Comment by favoeva** [comment]
issue doppia
