### ISSUE TITLE
AIUTI A #MONTEGALLO

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1139]
<pre><yamldata>tel: '3284671567'
email: a.ferri@casettadimarzapanebijoux.com
cosa: 'AIUTI A #MONTEGALLO'
descrizione: 'A Montegallo siamo abbandonati, c'' è l'' ordine di evacuazione, sono stati tutti portati sulla costa, siamo rimasti in pochissimi a sorvegliare i paesi e a resistere, non ci sono posti di blocco per impedire agli sciacalli di arrivare nel cratere abbandonato da tutti, il CAS (contributo per autonoma sistemazione) non è stato erogato, la protezione civile è andata via, non hanno portato tende nè container nè casette, noi siamo costretti a vivere in condizioni pietose.'
indirizzo: 'Strada Provinciale 89 Valfluvione, Montegallo, AP, Marche, 63094, Italia'
lat: '42.8473894'
lon: '13.3434963'
link: ''
immagine: ''
data: 06/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
La fonte ha chiesto di rimuovere la segnalazione.
