### ISSUE TITLE
AIUTIAMO Azienda Casetta di Marzapane Bijoux - #MONTEGALLO

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1140]
<pre><yamldata>tel: '3284671567'
email: a.ferri@casettadimarzapanebijoux.com
cosa: 'AIUTIAMO Azienda Casetta di Marzapane Bijoux - #MONTEGALLO'
descrizione: 'Azienda Casetta di Marzapane Bijoux produce gioielli fatti a mano, la produzione a Abetito di Montegallo ed è ferma da due mesi, il 4/10 è stato riaperto il negozio ad Ascoli per disperazione ma hanno solo giacenze di magazzino e devono affrontare il Natale. Serve un container in cui spostare l''attività. Contattare Anna.'
indirizzo: 'Strada Provinciale 89 Valfluvione, Montegallo, AP, Marche, 63094, Italia'
lat: '42.8473894'
lon: '13.3434963'
link: 'https://www.facebook.com/Casetta.Di.Marzapane.Bijoux/?fref=ts'
immagine: ''
data: 06/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
La fonte ha chiesto di rimuovere la segnalazione.
