### ISSUE TITLE
A Vallefoglia (Pu) raccolta beni fino a sabato 12 novembre

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1152]
<pre><yamldata>tel: ''
email: ''
cosa: 'A Vallefoglia (Pu) raccolta beni fino a sabato 12 novembre'
descrizione: 'Da sabato 5 fino a sabato 12 novembre presso Gio Calzature a Montecchio di Vallefoglia, Via Pio La Torre n.6 si raccolgono questi beni, in collaborazione con la Bottega del Libro di Macerata. ALIMENTARI IN GENERE A LUNGA CONSERVAZIONE SIA PER LE PERSONE (particolare attenzione per bambini e neonati) CHE PER GLI ANIMALI – DA COMPAGNIA E DA ALLEVAMENTO; ABITI PER UOMO – DONNA – BAMBINO; MATERIALE PER IGIENE INTIMA. In particolare: - Mutandine assorbenti - Assorbenti intimi - Schiuma barba, rasoi, salviettine e similari - Saponi e similari - MATERIALE PULIZIA CASA - LENZUOLA COPERTE ASCIUGAMANI E VARIO - MATERIALE PER PROTEGGERE LE ROULOTTE E IL FIENO - TELONI in plastica e vario materiale disponibile - TANICHE PER ACQUA E ALTRO MATERIALE UTILE - MATERIALE CANCELLERIA E GIOCHI PER I BIMBI (così si svagano e si deconcentrano dal pensiero del terremoto)'
indirizzo: 'Strada Provinciale Fogliense, Vallefoglia, PU, Marche, 61022, Italia'
lat: '43.8559848'
lon: '12.7622487'
link: 'https://www.facebook.com/permalink.php?story_fbid=539307819595964&id=288612484665500'
immagine: ''
data: 06/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
