### ISSUE TITLE
A #SANBENEDETTODELTRONTO servono beni e vestiario

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1167]
<pre><yamldata>tel: ''
email: ''
cosa: 'Beni - #SANBENEDETTODELTRONTO'
descrizione: 'Alla protezione civile di San benedetto del Tronto in provincia di Ascoli Piceno (scuola ex Curzi) servirebbero le seguenti cose: Detergenti per pavimenti Detersivi per la lavatrice Stracci per il pavimento Latte detergente Tonico Fazzolettini di carta Creme viso Creme corpo Forbicine Vestiario nuovo: felpe ma misure dalla L in su, maglieria donna, maglieria bimbo/a da 5 anni ai 14, tute'
indirizzo: 'Via Raffaello Sanzio, Marina centro, San Benedetto del Tronto, AP, Marche, 63039, Italia'
lat: '42.9525328'
lon: '13.8807144'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1796437600623823/'
immagine: ''
data: 08/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
