### ISSUE TITLE
Cercasi Modulo Abitativo o Casetta in legno o Container coibentato per famiglia in provincia di #Teramo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1171]
<pre><yamldata>tel: '+393289550204'
email: wcostcostw@gmail.com
cosa: 'Modulo Abitativo o Casetta In Legno, Anche senza Mobilio/Container Coibentato o Cassone Coibentato Dismesso da Adattare'
descrizione: 'Frazione Villafranca di Valle Castellana (Teramo): a seguito di abitazione principale gravemente lesionata, Si Chiede In Prestito, in Attesa Consegna S.A.E., Modulo Abitativo o Casetta in Legno Anche Sprovvisti di arredi/Container Coibentato o Cassone Camion Coibentato Dismesso e da Adattare, per Famiglia Composta da Due Persone Anziane, Figlio e Sua Compagna, Che Hanno Necessità di Rimanere In Loco Al Fine Di Attendere A Piccola Attività Agricola e Di Allevamento e Presidiare Abitazione Ubicata In Borgo Isolato. Walter Costantini: +39 3289550204/wcostcostw@gmail.com GRAZIE!!!!!'
indirizzo: ''
lat: '42.7366700'
lon: '13.4968743'
link: ''
immagine: ''
data: 08/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Incrociata questa richiesta di container/casetta con questa offerta di modulo abitativo http://terremotocentroitalia.info/issues/1147/index.html e scritto da posta TCI al primo segnalando l'offerta del secondo @cristigalas 

![426134553_14159382566887112240](https://cloud.githubusercontent.com/assets/21237278/20122178/28b098d0-a616-11e6-9862-ad8f1b428081.jpg)

**Comment by cristigalas** [comment]
Ricevuta email del sig.Walter che dice che alla fine il container offerto con issue #1147 non l'ha potuto prendere. Entrambe le segnalazioni (offerta e richiesta) rimangono quindi aperte.

**Comment by chiccap** [comment]
Motivo?

**Comment by cristigalas** [comment]
Ma non ho capito bene, pare che non entrasse nello spiazzo che aveva individuato... comunque mi ha chiesto di tenerlo presente per altre segnalazioni e che se risolve da solo ci farà sapere.

**Comment by chiccap** [comment]
Peccato. Ottimo che ci tiene aggiornati! Grazie mille Cristina :)

**Comment by chiccap** [comment]
Lo vogliamo ricontattare per avere aggiornamenti?

**Comment by cristigalas** [comment]
Sì forse è meglio... invio io una mail.
