### ISSUE TITLE
Disponibilità Camper da Villa Potenza (frazione MC)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1172]
<pre><yamldata>tel: ''
email: ''
cosa: 'Camper da Villa Potenza (frazione MC)'
descrizione: 'Buongiorno, mi chiamo Daniele Cartechini e sono proprietario di un camper mansardato Mirage dell''89 su Ducato 2500. Leggo che molti allevatori necessitano di una struttura dove poter dormire per rimanere accanto ai loro animali. Il mezzo in questione non è marciante a causa di una rottura al cambio, quindi andrebbe trasportato con un carroattrezzi. Io lo avrei demolito perché, data l''età e una infiltrazione, ho deciso di non ripararlo. Comunque, nonostante questi problemi, il camper può essere un valido riparo per la notte. Il mezzo ha 6 posti letto (se si trasforma la dinette), bagno nautico, stufa funzionante e boiler da rivedere (a volte quando le temperature sono molto basse, lo scorso inverno siamo andati in ghiacciao in Trentino, non si accende). Purtroppo, avendo pensato di non usarlo più ho anche venduto il frigorifero. Spero di non avervi fatto solo perdere tempo. Se credete che il mezzo possa essere comunque utile a qualcuno contattatemi pure, anche solo se volete avere maggiore informazioni o foto per rendervi conto delle condizioni. Il camper si trova a Villa Potenza e , ovviamente, ve lo darei gratuitamente, basta se possibile fare il passaggio di proprietà. Il mio telefono è 327 6377044, per motivi di lavoro contattatemi di mattina o durante la pausa dalle 18 alle 18.30.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 08/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Risposta dell'offerente al messaggio in cui gli si chiedeva di segnalarci eventuali richieste: "Buongiorno Chiara, io ho inviato la mail a lei e alla protezione civile la quale mi ha risposto che avrebbe girato la stessa a chi gestiva l'emergenza nel territorio. Oltre a questa risposta non ho avuto altre comunicazioni, quindi resto disponibile a qualsiasi vostra comunicazioni. A presto"

**Comment by chiccap** [comment]
Inviato oggi messaggio concordato con @cristigalas .

**Comment by cristigalas** [comment]
L'offerente ha comunicato oggi a @chiccap di aver donato il camper attraverso altri canali. Chiudo.
