### ISSUE TITLE
Offro gratuitamente alloggio per 4-5 persone a Monfalcone (Go)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1175]
<pre><yamldata>tel: '0481484346  -  3466317085'
email: flavianaclaudio@tiscali.it
descrizione: 'Offro gratuitamente alloggio indipendente su due piani in centro a Monfalcone (GO) per 4-5 persone, riscaldato, arredato (compreso accessori: stoviglie, biancheria, ecc.) e con tutte le utenze attive'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 08/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Alloggio non più disponibile. Chiudo.
