### ISSUE TITLE
Cercasi urgentemente lavatrice a #Varoni (#Amatrice)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1176]
<pre><yamldata>tel: '3338275919 - 3348847807'
email: ''
cosa: 'Lavatrice a #Scai'
descrizione: 'Serve urgentemente una lavatrice a Varoni (Amatrice). Contattare Carlo o Rosaria.'
indirizzo: 'SP19, Amatrice, RI, Lazio, Italia'
lat: '42.5980591'
lon: '13.2305149'
link: ''
immagine: ''
data: 08/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Rosaria Lunadei - frazione Varoni - 3348847807
