### ISSUE TITLE
Richiesta urgente di beni necessari per i  prossimi mesi invernali ad #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1183]
<pre><yamldata>tel: '3240887183'
email: christianvarani@gmail.com
cosa: 'Richiesta di beni necessari, per i  prossimi mesi invernali ad Amatrice'
descrizione: 'Si richiedono urgentemente i seguenti beni che servono ad Amatrice per affrontare il periodo invernale: generi alimentari come cibo a lunga conservazione; Scarponi da Trekking (anche da montagna preferibilmente impermeabili); Coperte invernali e piumoni; Giacche pesanti e giubbotti ; Cibo per animali (in particolare per cani, gatti e galline); Teloni (dimensione di almeno 10x10m ciascuno); Catene invernali e da neve per veicoli. Il recapito telefonico specificato con questa pubblicazione è di un Responsabile della Protezione Civile, presente tra i volontari sul luogo e di riferimento per gli aiuti.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 09/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Ho incrociato questa richiesta con l'offerta #1205 ed è andata a buon fine. Via email mi hanno comunicato che consegneranno vestiti e coperte ad Amatrice il 30/11. Ho chiesto cosa consegneranno esattamente così vediamo se chiudere segnalazione o aggiornarla.

**Comment by chiccap** [comment]
Mai ricevute notizie? Come procediamo?

**Comment by cristigalas** [comment]
Direi di chiudere...
