### ISSUE TITLE
Offresi camper con mansarda (letto matrimoniale + 2 letti singoli + 2 dinette)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1188]
<pre><yamldata>tel: '3497714772'
email: francibucci@hotmail.com
descrizione: 'Disponiamo di un camper con mansarda (posto letto matrimoniale) e 2 letti singoli in coda + due dinette trasformabili in posti letto (un letto ampio e uno molto piccolo) completo di lenzuola e piumoni, stoviglie se servono, tavolo e 5 sedie per esterno (in questa stagione poco utili purtroppo). Possiamo portarlo da Modena nella vostra zona se occorre e tornare a casa in treno. (PS: se resterà fermo occorre staccare la batteria dell''auto perchè tende a scaricarsi). Contattare Francesca o Cristiano'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 09/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Il camper segnalato sul nostro sito è andato al gruppo di volontari di Ussita rimasti ad aiutare. Qui descrizione: http://www.cronachemaceratesi.it/2016/11/09/linda-la-numero-uno-di-ussita-senza-casa-aiuta-i-soccorritori-e-il-suo-zabaglione-e-irrinunciabile/884915/

Dovremmo scrivere una storia da pubblicare sul sito!
