### ISSUE TITLE
Contatti Caritas #Spoleto - Centro raccolta aiuti Diocesi dell'#Umbria

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1192]
<pre><yamldata>nome: 'Caritas Diocesana di Spoleto - Archidiocesi di Spoleto – Norcia'
tel: '0743 22 04 85'
email: caritas@spoletonorcia.it
descrizione: 'Per l’Archidiocesi di Spoleto – Norcia e per le altre Diocesi dell’Umbria è la Caritas diocesana locale a coordinare la raccolta degli aiuti. Chi volesse collaborare con l’invio di generi di prima necessità, deve prima contattare gli operatori della Caritas al numero 0743-220485. I volontari, poi, distribuiranno nelle varie comunità della Valnerina quanto ricevuto.'
indirizzo: 'Via Aurelio Saffi, Spoleto, PG, UMB, 06049, Italy'
lat: '42.7346574'
lon: '12.7384492403508'
link: 'http://www.spoletonorcia.it'
data: 09/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Centro di raccolta chiuso.
