### ISSUE TITLE
A #Spoleto il gruppo "I ragazzi del 50/A"

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1193]
<pre><yamldata>nome: 'I ragazzi del 50/A'
tel: '393 01 20 789'
email: iragazzidel50a@gmail.com
descrizione: 'A Spoleto un gruppo di ragazzi si è formato dopo il terremoto del 24 Agosto 2016 per portare aiuto alle persone coinvolte dal sisma. Organizza anche raccolte di beni che consegna personalmente a chi ne ha bisogno. Il Centro di Raccolta è aperto dal Lunedì al Venerdì dalle 09:00 alle 12:00 e dalle 15:00 alle 18:00 ed è situato in Via Luigi Einaudi 49 – 06049 Spoleto (PG).'
indirizzo: 'Madonna di Lugo, Spoleto, PG, UMB, 06049, Italy'
lat: '42.7685858'
lon: '12.7510342'
link: 'https://www.facebook.com/iragazzidel50a/'
data: 09/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
centro di raccolta chiuso
