### ISSUE TITLE
Tappeto srotolabile 20m - #CASCIA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1198]
<pre><yamldata>tel: "‪338\_320\_2296‬"
email: carianisimone@gmail.com
cosa: 'Tappeto srotolabile 20m - #CASCIA'
descrizione: '1 tappeto srotolabile (tipo erba sintetica) per sopperire minimamente alla quantità di fango che si è creata in adiacenza delle tende e dei camper dove le persone stanno vivendo. Almeno 20 metri loc. palmaiolo di Cascia. Contattare Simone.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 10/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
@MyFriendTheBear gruppo telegram terremotocentroitalia ha fatto l'ordine del tappeto su amazon, ha parlato con la persona interessata che le ha fornito l'indirizzo di una parente, contattato telefonicamente il venditore e lo spedisce subito con bartolini quindi forse arriva domani.
Aspetto la consegna per chiudere issue.

**Comment by chiccap** [comment]
Arrivato!
