### ISSUE TITLE
Attrezzatura medica essenziale - #CASCIA #PERUGIA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1200]
<pre><yamldata>tel: '3383202296'
email: carianisimone@gmail.com
cosa: 'Attrezzatura medica essenziale - #CASCIA #PERUGIA'
descrizione: 'CASCIA - LOC. PALMAIOLO Il Dr. Simone Cariani ha perso tutto il materiale medico essenziale sotto le macerie. Per poter svolgere il suo lavoro ha bisogno di: 1 computer portatile, 1 analizzatore glicemia. Contattare il Dr. Cariani.'
indirizzo: 'Largo Monsignor Antonio Elemosina, Cascia, PG, UMB, 06043, Italia'
lat: '42.7170082'
lon: '13.0135022'
link: ''
immagine: ''
data: 10/11/2016
</yamldata></pre>

**Comment by marco-acorte** [comment]
rilanciato via twitter a FNOMCeO Portale della Federazione Nazionale degli Ordini dei Medici Chirurghi e degli Odontoiatri
https://twitter.com/acor3/status/796677593080729600

**Comment by chiccap** [comment]
Ha ricevuto sfigmomanometro e fonendoscopio da privato di Napoli e vanno bene!
Modifico issue.

**Comment by chiccap** [comment]
Ha ricevuto telefono.

**Comment by cristigalas** [comment]
Ha ricevuto borsa da medico e otoscopio.
