### ISSUE TITLE
Donazione di vestiario invernale e coperte. Consegna entro fine mese

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1205]
<pre><yamldata>tel: '3294262904'
email: mmior@libero.it
cosa: 'vestiario e altro'
descrizione: 'Disponibilita'' di coperte; giacconi e maglioni pesanti, usati ma in buonissimo stato. Cerchiamo contatto a cui consegnare a fine mese.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 10/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Ho incrociato questa offerta con il fabbisogno #1183 ed è andato a buon fine. Via email mi hanno comunicato che consegneranno vestiti e coperte ad Amatrice il 30/11. Ho chiesto se devo chiudere offerta o se hanno ancora disponibilità, attendo risposta prima di chiudere...
