### ISSUE TITLE
Donazione furgone Fiat Gran Ducato trasformato in #camper

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1206]
<pre><yamldata>tel: ''
email: 
cosa: camper
descrizione: 'Buongiorno, mio padre donerebbe il suo vecchio furgone Fiat Gran Ducato trasformato in camper. Mi sto informando per la revisione e per la sistemazione (era fermo da qualche tempo). Potrebbe essere una sistemazione comoda e dignitosa per 2-3 persone e se qualcuno ne avesse bisogno potrei portarlo in loco dal Trentino e tornare in treno. Mio padre chiede solo un contributo per le eventuali spese per la messa su strada (che documenteremo in anticipo, non dovrebbero esserci sorprese) e di sostenere il passaggio di proprietà. Potrei con l''occasione fare in zona una raccolta di indumenti pesanti o di quello che vi potrebbe servire. Elvira'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 10/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
In risposta all'email che ho inviato oggi 13/11, l'autrice della segnalazione scrive che ha trovato a chi destinare il camper attraverso altri canali e ci chiede di togliere l'offerta dal sito. Dunque chiudo issue @chiccap @favoeva.

**Comment by cristigalas** [comment]
L'autrice della segnalazione ci chiede via email di togliere i suoi recapiti, cancello quindi email e tel.
