### ISSUE TITLE
Telefono Azzurro cerca volontari per interventi ad #Amatrice e altre zone terremotate

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1210]
<pre><yamldata>tel: ''
email: ''
cosa: 'Telefono Azzurro cerca volontari per interventi ad #Amatrice e altre zone terremotate'
descrizione: 'A fronte del lavoro che ci aspetta nei prossimi mesi per cercare non solo di intervenire nell''emergenza, ma anche di offrire un lento e graduale ritorno alla normalità, invitiamo chiunque voglia impegnarsi come volontario nelle aree di AMATRICE e delle ALTRE ZONE DEL CENTRO ITALIA colpite dal TERREMOTO, che abbia maturato esperienza con i bambini e che condivida la mission di Telefono Azzurro a compilare il presente modulo. Tutti i candidati selezionati saranno adeguatamente formati e preparati dai nostri operatori professionisti, prima di intraprendere la loro esperienza sul campo. Al link il modulo da compilare per le candidature.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://docs.google.com/forms/d/e/1FAIpQLSf2L4vgBPRlG4WDyUtDkSOKKD__Mqzs2m5oesIxlVZJZSsWVg/viewform?c=0&w=1'
immagine: ''
data: 10/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Ricerca chiusa.
