### ISSUE TITLE
Appello della Cioccolateria CIOCK di #Norcia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1212]
<pre><yamldata>tel: ''
email: ''
cosa: 'Cioccolateria NORCIA CIOCK'
descrizione: 'Messaggio di Arianna Verucci, titolare a Norcia di una piccola azienda di cioccolato fortemente colpita dal sisma: "mi sono fatta forte e ho cominciato i lavori da sola contro tutto e contro tutti, è stata una sfida contro il tempo, adesso ho bisogno dell''aiuto di tutti, vi prego di aiutarmi... GRAZIE, la mia forza siete voi in questo momento [sito e-commerce: www.norciaciok.it]'
indirizzo: 'Piazza San Benedetto, Casa Coletti, Norcia, PG, UMB, 06046, Italia'
lat: '42.7927706'
lon: '13.0930812'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1797512140516369/'
immagine: ''
data: 10/11/2016
</yamldata></pre>

**Comment by TheBestMovieIsYourImagination** [comment]
è un doppione di [https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/1227](https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/1227)
direi di chiudere questa perchè l'altra è più completa.
