### ISSUE TITLE
Cercasi stufette elettriche per tende allevatori marchigiani. Punto di raccolta #Camerino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1232]
<pre><yamldata>telegram_user: ''
descrizione: 'Cercasi stufette elettriche da mettere all''interno delle tende di allevatori rimasti sul territorio. Punto di raccolta: sede ass. IoNonCrollo, Camerino, tel. 3345751368'
immagine: ''
lat: '43.156182'
lon: '13.052961'
data: 11/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Trovate 10 stufette e ritirate a Roma da Manuel dell'Ass. #iononcrollo di Camerino.

**Comment by chiccap** [comment]
Le stufe non andavano bene per le tende degli allevatori ma vanno bene per i garage.

Intanto, @cristigalas riceve una mail da Mo-El (azienda che produce stufe, ecc) in risposta alla mail che aveva inviato per le stufette --> attendiamo indicazioni da richiedente per dare info più precise all'azienda.

**Comment by cristigalas** [comment]
Dpo vari contatti, l'azienda Mo-El mi ha confermato oggi che consegnerà a Camerino altre 10 stufette, visto che comunque ne avevano ancora necessità.

**Comment by chiccap** [comment]
Mo-El ha consegnato a Fiastra 13 stufette (più di quante ne fossero state richieste) e 10 a Camerino.
