### ISSUE TITLE
Richiesta di 3 Roulotte ad #Amatrice per affrontare i prossimi mesi invernali

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1235]
<pre><yamldata>tel: '3240887183'
email: christianvarani@gmail.com
cosa: 'Richiesta di 3 Roulotte, per affrontare i prossimi mesi specialmente invernali ad Amatrice'
descrizione: 'Sono richieste 3 Roulotte ad uso abitativo urgentemente utili per dei cittadini di Amatrice, in questi periodi e maggiormente per i prossimi mesi invernali, in mancanza e in sostituzione alle Tende che erano state allestite o montate nella fase di Emergenza. Ricordo che per contatti utili alla donazione con consegna vi è un numero telefonico di un Responsabile della Protezione Civile presente ancora sul luogo.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Anna Serpeverde Cristallini'
immagine: ''
data: 11/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Bisogno soddisfatto, come comunicato via email da Christian Varani. Chiudo.
