### ISSUE TITLE
Vendita online dei salumi di #Arquata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1237]
<pre><yamldata>tel: ''
email: ''
cosa: 'Acquisti solidali: salumi di #Arquata'
descrizione: 'Sul sito della ProLoco di Arquata l''appello a sostenere una macelleria/salumeria a Trisungo, frazione di Arquata, distrutta da terremoto ma che ha potuto recuperare un po'' di prodotti che ora vende online.'
indirizzo: 'Strada Statale 4 Via Salaria, Arquata del Tronto, AP, Marche, Italia'
lat: '42.7740564'
lon: '13.3125245'
link: 'http://sosteniamoarquata.it/prodotto/prosciutto/'
immagine: ''
data: 11/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Sito non più attivo.
