### ISSUE TITLE
Giocattoli per i bambini di #Preci

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1248]
<pre><yamldata>tel: '3298140621'
email: dangelibarbara@yahoo.it
cosa: Giocattoli
descrizione: 'Siamo un gruppo di mamme con bambini dai 5 ai 10 anni di Preci con i propri cuccioli terrorizzati dalla paura del terremoto, chiedevano se per Natale potevano arrivare dei giochi e dei vestiti nuovi per rallegrare, soprattutto il loro animo, grazie Barbara D''Angeli.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 13/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Ho chiamato la referente Barbara e mi ha detto che già l'hanno contattata in 2 e che i beni richiesti sono arrivati. Non sono riuscita a risalire alla fonte della donazione.
