### ISSUE TITLE
Post terremoto: proposta di norma che obblighi l'immediata messa in sicurezza di tutti gli immobili

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1249]
<pre><yamldata>tel: '0733694125'
email: CREDIAWWF@GMAIL.COM
cosa: 'Intervento legislativo nell''ambito del Decreto post terremoto che sarà discusso dal Parlamento nelle prossime settimane'
descrizione: 'Dalla stampa si apprende che il Decreto del Governo per la gestione dell’emergenza post-terremoto in Italia centrale e’ stato firmato dal Presidente della Repubblica e sarà pubblicato nei prossimi giorni, tra oggi e lunedi’, sulla Gazzetta ufficiale. La prossima settimana dovrebbe partire l’esame degli emendamenti in Commissione ed arrivare in aula al Senato il 22-23 novembre. Non sono ancora noti in dettaglio i contenuti del decreto e pertanto quanto segnaliamo ci auguriamo sia inutile, se trattato in modo adeguato nel testo del decreto. Altrimenti chiediamo di prestare attenzione al seguente problema ed attivare se possibile una azione sui parlamentari al Senato in vista dell’esame del decreto. Molte attività produttive, nelle frazioni rurali ma anche nei centri storici, rischiano di essere chiuse se pur con strutture agibili a causa del rischio indotto da abitazioni vicine (spesso seconde case) che dovrebbero essere messe in sicurezza. Al momento secondo i Comuni non vi e’ l’obbligo da parte dei privati d’intervenire d’urgenza per mettere in sicurezza questi immobili che bloccano la ripresa delle attivita’ produttive. Il Comune potra’ intervenire solo in caso di pubblica incolumita’, problema al momento risolto con la delimitazione delle zone rosse. In definitiva attività produttive che potrebbero riprendere la loro attività rischiano la paralisi e la conseguente chiusura solo perche’ privati non residenti, titolari di seconde case, non intendono anticipare di tasca loro le spese per la messa in sicurezza ed attendono passivi il contributo dello Stato per la ricostruzione (avendo tra l’altro garantito il risarcimento del 100% del danno alla pari di chi sul territorio vive e lavora). In sede di discussione del decreto sarebbe necessario verificare la possibilita’ d’introdurre l’obbligo della messa in sicurezza immediata degli immobili e strutture che per rischio indotto determinano ostacolo alla ripresa delle attivita’ produttive ed economiche (situazione molto diffusa in borghi dove le seconde case sono spesso limitrofe o confinanti con le strutture produttive dei residenti). Crediamo si debba fare di tutto per assicurare la ripresa delle attività produttive e sociali nei Comuni colpiti dal sisma e questa situazione appare a dir poco paradossale, ancora di piu’ se consideriamo che per le aziende agricole il decreto prevede la possibilita’ d’intervento immediato per garantire proprio la continuita’ delle attivita’ produttive, che rischia di essere compromessa per inerzia da parte di proprietari non residenti che non hanno urgenza d’intervenire sui loro immobili. Basterebbe introdurre nel decreto una norma che preveda l’obbligo immediato della messa in sicurezza di tutti gli immobili che possono compromettere la continuità delle attività economiche confinanti per rischio indotto. Prevedendo la possibilita’ di ottenere il rimborso delle spese per la messa in sicurezza (se non si vuole gravare sulle tasche di questi privati cittadini). Non nascondiamo ovviamente un interesse diretto rispetto a questo problema, comunque molto diffuso. La ns struttura multifunzionale, con azienda agricola, agrinido, fattoria didattica, Cea del WWF e del Parco Nazionale dei Monti Sibillini nella frazione di Vallato a San Ginesio (MC) è stata colpita seriamente dalla scossa del 30 ottobre (www.querciadellamemoria.it ), e pur avendo realizzato a suo tempo un intervento di ristrutturazione antisismico in bioedilizia abbiamo parte dell’immobile non agibile ed una parte ancora agibile ed attualmente abitata, ma siamo circondati da seconde case ed annessi agricoli abbandonati gravemente lesionati che incombono sulla ns struttura. Siamo riusciti a restare operativi rimanendo al momento fuori dalla zona rossa delimitata dal Comune ma senza la messa in sicurezza delle abitazioni confinanti e vicine non possiamo riprendere l’attività, anche in forma provvisoria in attesa della ricostruzione. Garantire la continuità delle attività di un centro multifunzionale come il nostro, che svolge anche un servizio pubblico (come l’agrinido, il centro agrinfanzia e famiglie, il Centro d Educazione Ambientale) se pur gestito da un soggetto privato come una Societa’ agricola e’ fondamentale in questo momento, anche per rispondere alle richieste che arrivano dal territorio colpito dal sisma. Siamo a disposizione per ogni utile chiarimento. Federica Di Luca AD Società Agricola La Quercia della Memoria, San Ginesio'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: 'http://i.imgur.com/FOVSz6Y.jpg'
data: 13/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Presente nel decreto 189/2016.
