### ISSUE TITLE
A #Bolognola (Mc) servono urgentemente scarponi per uomo/donna

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1251]
<pre><yamldata>tel: '3356939826'
email: ''
cosa: 'A #Bolognola (Mc) servono urgentemente scarponi per uomo/donna'
descrizione: 'A Bolognola, piccolo centro del maceratese colpito dal sisma, servono con urgenza scarponi da montagna per uomo/donna, diverse misure. Chi può reperirli può contattare direttamente il sindaco Cristina Gentili, 3356939826.'
indirizzo: 'Strada Provinciale 47 Fiastra - Bolognola, Bolognola, MC, Marche, 62033, Italia'
lat: '42.994904'
lon: '13.2263425'
link: 'https://twitter.com/albertbrandi/status/797707747445841920'
immagine: ''
data: 13/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta, vedi tweet https://twitter.com/albertbrandi/status/800437642475270144 Chiudo.
