### ISSUE TITLE
A San Ginesio si cercano alimenti freschi per i centri di accoglienza sfollati 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1260]
<pre><yamldata>tel: '3337844354'
email: ostellosanginesio@gmail.com
cosa: 'cerchiamo alimenti ''''freschi'''''
descrizione: 'Per i centri di accoglienza del Comune di San Ginesio (Mc) abbiamo bisogno di alimenti ''''freschi'''' come frutta, verdura e carne'
indirizzo: 'Piazza Alberico Gentili, San Ginesio, MC, Marche, 62026, Italia'
lat: '43.1084806'
lon: '13.3187335'
link: ''
immagine: ''
data: 14/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Centri di accoglienza chiusi.
