### ISSUE TITLE
A #Fiastra (Mc) serve una lavasciuga o lavatrice + asciugatrice per la tensostruttura 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1270]
<pre><yamldata>tel: ''
email: 'sia_82@hotmail.com'
cosa: 'A Fiastra (Mc) servono stufette e lavasciuga'
descrizione: 'Al Comune di Fiastra (MC) serve almeno una lavasciuga (o una lavatrice + un''asciugatrice) per chi vive nelle tensostrutture. Chiunque possa aiutarci mi scriva su Facebook, anche in privato. Grazie!'
indirizzo: 'Via Roma, Fiastra, MC, Marche, 62035, Italia'
lat: '43.0361407'
lon: '13.1554547'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1799556680311915/'
immagine: ''
data: 14/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Ho contattato via email e poi per telefono un'azienda emiliana, la Mo-El, che sembra in grado di aiutarci fornendo termoventilatori e/o stufette ad infrarossi. Spero di avere presto buone nuove.

**Comment by cristigalas** [comment]
Qui il contatto della persona che fa da ponte e che ha postato la richiesta su Fb: Silvia Belli, sia_82@hotmail.com, abitante di Fiastra.

**Comment by cristigalas** [comment]
La Mo-El oggi mi ha telefonato per dirmi che consegnerà a Fiastre 7 stufette alogene. A breve dovrei ricevere l'indirizzo esatto della tensostruttura del Comune di Fiastre che inoltrerò a Mo-El. Quando il carico parte aggiorno la segnalazione.

**Comment by cristigalas** [comment]
Consegnate oggi da Mo-El 13 stufette! Aggiorno la segnalazione, tolgo le stufette. Rimane aperta la richiesta di lavasciuga.

**Comment by chiccap** [comment]
LG ci ha contattato dicendo che donerà una lavasciuga. La consegnerà nei prossimi giorni. Aspettiamo la consegna prima di chiudere.
