### ISSUE TITLE
Cercasi un'asciugatrice per famiglia a #Cascia con casa inagibile

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1282]
<pre><yamldata>tel: '3338623782'
email: federicalu.93@gmail.com
cosa: asciugatrice
descrizione: 'Buongiono sono una signora di Cascia terremotata, la mia casa è inagibile, ho una sistemazione provvisoria, ho una una bambina nata il 18 ottobre, avrei bisogno se possibile di una asciugatrice. Grazie infinite.'
indirizzo: 'Viale Cavour, Cascia, PG, UMB, 06043, Italia'
lat: '42.7183264'
lon: '13.0178778'
link: ''
immagine: ''
data: 16/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Materasso consegnato oggi da Gio Calzature, contatto stabilito via Facebook. Rimane aperta richiesta di asciugatrice.

**Comment by cristigalas** [comment]
Asciugatrice consegnata da associazione Poppai Bortolai, come comunicato da email di Christian Varani. Chiudo.
