### ISSUE TITLE
Si cerca un camper o roulotte per famiglia colpita dal sisma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1285]
<pre><yamldata>tel: '3281713034'
email: ultr75@libero.it
cosa: 'camper o roulotte'
descrizione: 'Vorrei sapere se ci fosse disponibilità di un camper o roulotte per una famiglia colpita dal terremoto.....o contatti utili per poter sapere chi le mette a disposizione ...grazie molte'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 16/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta come da comunicazione via email di Christian Varani.
