### ISSUE TITLE
#MadeWithLove, i pacchi-dono di Confindustria Ascoli con i prodotti di #Arquata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1289]
<pre><yamldata>tel: ''
email: ''
cosa: '#MadeWithLove: Confindustria Ascoli Piceno lancia pacchi-dono con i prodotti di #Arquata'
descrizione: '"#MadeWithLove ovvero “Fatto con amore” dai nostri produttori e “Fatto con amore” da chi come te, vorrà acquistare i nostri prodotti e donare il ricavato alle imprese delle zone terremotate di Arquata del Tronto, che in molti casi hanno perso tutto, ma non la voglia di creare e produrre il meglio delle prelibatezze del territorio piceno. Il Gruppo Giovani Imprenditori di Ascoli Piceno ha voluto così dare un segno di solidarietà alle imprese di Arquata del Tronto: un aiuto concreto in questo momento di difficoltà!". Sul sito dedicato è possibile scegliere tra vari prodotti e ordinare diverse tipologie di pacchi-dono.'
indirizzo: 'Piazza Umberto I, Arquata del Tronto, AP, Marche, Italia'
lat: '42.7723609'
lon: '13.2965826'
link: 'http://www.madewithloveap.org/'
immagine: ''
data: 16/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Iniziativa terminata.
