### ISSUE TITLE
Cercasi lavatrice a #Cascia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1308]
<pre><yamldata>tel: '3392543708'
email: renata.dinicola@gmail.com
cosa: lavatrice
descrizione: 'Salve, mi chiamo Renata Di Nicola ed abito a Cascia. Dopo il Terremoto ho casa inagibile con mia madre di 88 anni a mio carico. Avrei bisogno se possibile di una lavatrice. Grazie in anticipo.'
indirizzo: 'Strada provinciale di Cascia, Cascia, PG, UMB, 06043, Italia'
lat: '42.7256264'
lon: '13.0399312'
link: ''
immagine: ''
data: 18/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Contattata serve ancora la lavatrice urgentemente.

**Comment by cristigalas** [comment]
Richiesta soddisfatta dall'associazione Poppai Bortolai di Occhiobello, come da comunicazione via email di Christian Varani. Chiudo.
