### ISSUE TITLE
Una biblioteca per #Visso e #Matelica

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1315]
<pre><yamldata>tel: ''
email: ''
cosa: 'Una biblioteca per #Visso'
descrizione: 'Raccolgo l''appello lanciato da Loredana Lipperini che ha segnalato la bella idea di Silvia Sorana e Francesca Chiappa: una biblioteca per Visso e Matelica. Prima itinerante, poi stabile. Se volete, inviate libri. Per bambini, per adulti. Che contengano sogni e speranza. Inviateli a KINDUSTRIA - Viale Martiri della Libertà 65B 62024 Matelica (MC). E scrivete FUTURO INFINITO sulla prima pagina. Spedire libri è facilissimo, basta recarsi alle Poste e chiedere la spedizione Piego di libri che costa solo 1,28 euro. Se non volete spedire, potete portare i vostri libri ad Osimo presso la Libreria Il mercante di storie che si è gentilmente offerta di fare da punto di raccolta fino al 30 novembre oppure potete darli a me! Ilaria Silvestrini.'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'https://www.facebook.com/ilaria.silvestrini.9/posts/10154809394770087'
immagine: ''
data: 18/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
La biblioteca itinerante è nata! https://twitter.com/TgrMarche/status/815810425732431872
