### ISSUE TITLE
Sostieni le Marche: sito di Regione #Marche per promuovere imprese agroalimentari colpite dal sisma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1325]
<pre><yamldata>titolo: 'Sostieni le Marche: sito di Regione #Marche per promuovere imprese agroalimentari colpite dal sisma'
descrizione: 'Al fine di dare visibilità alle imprese agroalimentari marchigiane, e in particolare a quelle delle aree terremotate, che producono prodotti di qualità certificata e prodotti tradizionali, la Regione Marche ha predisposto questa sezione del proprio sito istituzionale nella quale saranno inserite le imprese agroalimentari marchigiane che ne faranno richiesta. La richiesta di inserimento può essere presentata, direttamente o tramite i CAA, accedendo nell''apposita sezione del SIAR che verrà attivata nei prossimi giorni. Non è prevista una scadenza per l’invio delle richieste di iscrizione. La Regione Marche si riserva la facoltà di effettuare controlli per verificare la veridicità delle informazioni inserite. Sul sito testo dell''Avviso pubblico e contatti telefonici per ulteriori informazioni.'
link: 'http://www.regione.marche.it/Regione-Utile/Agricoltura-Sviluppo-Rurale-e-Pesca/Sostieni-le-Marche'
data: 19/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Bando scaudto e pagina web non più disponibile
