### ISSUE TITLE
Cercasi camper o roulotte con 5  posti a #Norcia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1329]
<pre><yamldata>tel: ''
email: ''
cosa: 'Cercasi camper o roulotte con 5  posti a #Norcia'
descrizione: 'Cerco camper o roulotte 5 posti per tornare a Norcia, attualmente in albergo dal 30. Siamo una famiglia con tre figli, mio marito fa il pendolare Perugia-Norcia per lavorare in quanto ha investito tutto in un una attività a Norcia che fortunatamente ha resistito al sisma del 30 .Vogliamo stare tutti insieme, vi prego aiutateci.'
indirizzo: 'Piazza San Benedetto, Casa Coletti, Norcia, PG, UMB, 06046, Italia'
lat: '42.7927706'
lon: '13.0930812'
link: 'https://www.facebook.com/groups/993292824038901/permalink/1330348846999962/'
immagine: ''
data: 20/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
