### ISSUE TITLE
Si cerca lavatrice a Cascia per famiglia con due bimbi

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1331]
<pre><yamldata>tel: '3334147612'
email: yourreview.lc@gmail.com
cosa: Lavatrice
descrizione: 'Buon giorno mi chiamo Chiara e sono una mamma di due bambini di 5 anni e 6 mesi,come molti altri non abbiamo più la casa e avrei bisogno di una lavatrice dove poter lavare almeno i vestiti dei bambini se qualcuno ne ha una disponibile per favore'
indirizzo: 'Via Filippo Tagliolini, Cascia, PG, UMB, 06043, Italia'
lat: '42.7183459'
lon: '13.0187166'
link: ''
immagine: ''
data: 21/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta dall'associazione Poppai Bortolai di Occhiobello, come da comunicazione via email di Christian Varani. Chiudo.
