### ISSUE TITLE
Su Incibo.it vendita prodotti zone terremotate, 100% ricavato ai produttori

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1333]
<pre><yamldata>titolo: 'Acquisti Solidali - Vendita prodotti 100% ricavato ai produttori'
descrizione: 'Sulla piattaforma www.incibo.com si stanno mettendo in vendita prodotti delle zone terremotate dove il 100% del ricavato va ai produttori. Di alcuni si tiene anche la merce in conto deposito c/o il magazzino di inCIBO per tenere la merce al sicuro visto che molti hanno i magazzini non agibili. Ogni giorno vengono inseriti nuovi produttori. Aiutate a diffondere. Contattate pure i produttori per avere certezza dell''iniziativa. Sicura e garantita al 100%.'
link: 'https://www.incibo.com/'
data: 22/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Sito non più disponibile.
