### ISSUE TITLE
Lavatrice e asciugatrice #Cascia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1337]
<pre><yamldata>tel: '3383202296'
email: ''
cosa: 'Lavatrice e asciugatrice #Cascia'
descrizione: 'A Cascia (PG) servirebbe un''asciugatrice e una lavatrice piccola con il cestello sopra. Indirizzo: viale Cavour, 32 - 06043. Persona di riferimento Dr. Cariani Simone.'
indirizzo: 'Viale Cavour, Cascia, PG, UMB, 06043, Italia'
lat: '42.71867351380065'
lon: '13.01804780960083'
link: ''
immagine: ''
data: 22/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
L'associazione Poppi Bortolai (http://www.insiemeperricominciare.com/) ha contattato il referente della segnalazione e ha donato entrambi i beni.
