### ISSUE TITLE
Segnalazione cancellata su richiesta dell'offerente

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1358]
<pre><yamldata>tel: ''
email: 
cosa: ''
descrizione: ''
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 23/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
L'offerente chiede via email di chiudere la segnalazione perché non ha più la possibilità di offrire il proprio aiuto. Chiudo.

**Comment by cristigalas** [comment]
L'offerente con una nuova email ci ha chiesto di togliere i suoi recapiti telefonici e email.

**Comment by cristigalas** [comment]
L'offerente ci scrive ancora chiedendo di cancellare d l tutto la segnalazione. Non potendo eliminare la segnalazione cancello tutto il suo contenuto.
