### ISSUE TITLE
Cercasi materiale tecnologico per scuole e associazione Io non crollo di #Camerino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1367]
<pre><yamldata>tel: '334 5751368'
email: iononcrollo@gmail.com
cosa: 'Materiale tecnologico per scuole e sede associazione #CAMERINO'
descrizione: 'Visto l''inizio della scuola, l''Associazione #IONONCROLLO di Camerino si prende carico delle necessità e delle richieste sul territorio e di seguito trovate un elenco di materiale tecnologico che sarebbe molto d''aiuto. Grazie in anticipo per chiunque riuscirà a soddisfare anche solo una delle richieste. Trovate tutti i contatti di seguito, chiedere di Manuel, Marco o Giuseppe. Grazie ancora. Televisori: 1x Scuola Fiastra 1x Scuola Camerino 1x Sede / Sala ricreativa Proiettori: 1x Scuola Camerino 1x Scuola Serravalle 1x Sede / Cineforum (palazzetto con sfollati) Lavatrici: 1x Elementari Camerino 1x Asilo Camerino 1x Sede Asciugatrici: 1x Elementari Camerino 1x Asilo Camerino 1x Sede'
indirizzo: 'Piazza Cavour, Camerino, MC, Marche, 62032, Italia'
lat: '43.1357641'
lon: '13.0683092'
link: 'https://www.facebook.com/iononcrollo/'
immagine: ''
data: 24/11/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Materiale trovato e distribuito.
