### ISSUE TITLE
A #Scai, frazione di #Amatrice, servono stufette, pannelli, attrezzi da carpenteria

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1389]
<pre><yamldata>tel: ''
email: christianvarani@gmail.com
cosa: 'Richiesta di beni necessari ed utili,per la Frazione di Scai del Comune di Amatrice'
descrizione: 'Servono determinati beni che sono necessariamente richiesti al momento, proprio per la loro utilità per i prossimi mesi invernali, da cittadini assistiti e terremotati che si trovano anche in Roulotte o casette su ruote mobili a Scai (una frazione del Comune di Amatrice) in un loro campo di accoglienza. I beni richiesti sono: Stufette elettriche ed anche preferibilmente a "pellet" per permettere alle persone di potersi ben riscaldare specialmente con il freddo intenso; Pannelli coibentati per rivestimenti e coperture da fare; Pannelli da carpenteria e preferibilmente anche da copertura; Travetti preferibilmente da 12, 10, 8; Attrezzi vari da carpenteria come ad esempio: martelli, mazzette, chiodi, livelle , guanti da lavoro; Scale di diversa lunghezza; 1 Betoniera piccola. Per ulteriori info si può contattare via Facebook Barbara Angelini (vedi link) oppure via email Christian Varani.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Barbara Angelini'
immagine: ''
data: 28/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Tolta la richiesta di asciugatrici perché Christian Varani ci ha segnalato via email che la richiesta è stata soddisfatta.
