### ISSUE TITLE
A #Cascia famiglia cerca roulotte o camper

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1390]
<pre><yamldata>tel: '3271559663'
email: petrelligismondo@gmail.com
cosa: 'roulotte o camper'
descrizione: 'Siamo senza casa qui a Cascia a causa delle scosse del 26 e 30 ottobre e abbiamo una bimba di nove mesi. Cerchiamo una roulotte o camper a prezzo modico, nell''eventualità di una donazione provvediamo noi al trasporto, grazie.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 28/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta come da comunicazione via email di Christian Varani.
