### ISSUE TITLE
A #Cascia famiglia che vive in una casetta cerca asciugatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1395]
<pre><yamldata>tel: '3392750292'
email: caterina.fiordiani@alice.it
cosa: asciugatrice
descrizione: 'Siamo una famiglia che per ora vive in una casetta di legno di amici. Abbiamo un grosso problema: il freddo non ci permette di asciugare i panni e spesso ci troviamo in difficoltà. Un''asciugatrice ci risolverebbe il problema.'
indirizzo: 'Largo Monsignor Antonio Elemosina, Cascia, PG, UMB, 06043, Italia'
lat: '42.7170082'
lon: '13.0135022'
link: ''
immagine: ''
data: 29/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione soddisfatta. Vedi email Christian Varani.
