### ISSUE TITLE
A #Visso cercasi con urgenza un camper

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1398]
<pre><yamldata>tel: '3479119735'
email: silviavagni@vodafone.it
cosa: Camper
descrizione: 'Abbiamo bisogno urgentemente di un camper a Visso per mio marito che lavora lì. Noi siamo alloggiati a Porto Recanati ma lui non può fare avanti e indietro troppo dispendioso. Aiutateci.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 29/11/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
