### ISSUE TITLE
A #Cingoli (Mc) serve con urgenza un container 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1406]
<pre><yamldata>tel: '3404829219'
email: vailucia@hotmail.it
cosa: 'CONTAINER'
descrizione: 'Il terremoto mi ha distrutto casa e struttura ricettiva. Mi occupo da diversi anni della riabilitazione di cavalli e cani per la LAV e la Protezione Animali quindi per me, che dedico la vita a loro, non è pensabile lasciarli incustoditi e quindi mi preparo ai disagi che mi comporterà il passare l''inverno vicina a loro. Il container mi permetterebbe anche di poter recuperare le cose che ho in casa e che altrimenti andrebbero sicuramente perse visto che il tetto è aperto, entra l''acqua e probabilmente non sopporterà la neve che potrà cadere. Mi tiene in piedi sono il pensiero di poter ricominciare un giorno la mia vita!! Vi prego se potete di sostenere questo pensiero. Tel. Francesca (cell. 3404829219)'
indirizzo: 
lat: 
lon: 
link: 'https://www.google.it/maps/place/Via+Lipparelli,+62011+Cingoli+MC/@43.3963819,13.2525108,17z/data=!3m1!4b1!4m5!3m4!1s0x132d96a85b99b979:0xd44ab2f80ecefebc!8m2!3d43.3963819!4d13.2546995'
immagine: 
data: 02/12/2016</yamldata></pre>

**Comment by cristigalas** [comment]
Oggi l'associazione 3e32 dell'Aquila ha consegnato un container ad uso abitativo https://www.facebook.com/3e32LAquila/posts/10155521179177646 Chiudo.
