### ISSUE TITLE
A #Cascia e #Savelli servono stufette, scarponi, cibo anche per animali, addobbi per Natale e altri beni

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1414]
<pre><yamldata>tel: '3664008466'
email: maggi.monica@gmail.com
cosa: 'scarponi dal 36 al 46 pantaloni tuta dal 46 al 52 cibo per cani, gatti, conigli piatti di carta carta igienica detersivo lavatrice e a mano scottex stufette elettriche pasta, pelati, tonno, zucchero addobbi per Natale (luci e palline)'
descrizione: 'A Cascia e Savelli servono con urgenza: scarponi dal 36 al 46, pantaloni tuta dal 46 al 52 cibo per cani, gatti, conigli, piatti di carta carta igienica, scottex, detersivo lavatrice e a mano, stufette elettriche, pasta, pelati, tonno, zucchero, addobbi per Natale (luci e palline). In particolare stufette e detersivi servono a Savelli. Contatti Monica Maggi: 366-4008466'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/mmaggi'
immagine: ''
data: 03/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Aggiornata 11/12 su comunicazione via email di Christian Varani.
