### ISSUE TITLE
Offro ristorante in comodato d'uso in Piemonte a ristoratore colpito dal sisma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1416]
<pre><yamldata>tel: ''
email: ''
cosa: 'Ristorante in comodato d''uso in Piemonte'
descrizione: 'Offro ad uso gratuito il mio ristorante. Mi chiamo Giovanni Bottero, sono un pensionato di 66 anni che per molti anni ha lavorato come ristoratore. Vivo a Limone Piemonte, nota località turistica invernale in provincia di Cuneo, nota per il suo comprensorio (90km di piste da sci), sono proprietario di un locale “ristorante” che dopo il mio pensionamento e per motivi di salute è da più di un anno inattivo. Ieri sera, dopo aver visto, per l’ennesima volta, immagini catastrofiche delle zone terremotate del centro Italia, mi sono trovato a fare un pensiero. Mi sono immedesimato in uno di quei ristoratori che ad un tratto hanno visto il lavoro di una vita crollargli davanti agli occhi. Ho pensato a come mi sarei sentito se da un secondo all’altro, mi avessero detto che il mio ristorante non era più agibile e che ci sarebbero voluti mesi o forse anni per poter oltrepassare di nuovo la porta di ingresso. Sicuramente scoraggiato, disarmato, disperato. Quando investi tutto in un progetto che poi diventa un progetto di vita che da sostentamento a te ma soprattutto alla tua famiglia, per quanto possa calarmi nella situazione, non riesco e non posso quantificare lo stato d’amino che si possa provare. Sentire la terra che trema e che polverizza una tua creatura. Si perché, da ex ristoratore, credo fortemente che il proprio ristorante, sia una creatura, una parte di te, un’appendice di se stessi. Mentre facevo queste riflessioni, mi sono sentito pervaso da un sentimento di frustrazione e di rabbia e mi sono ritrovato a partorire quanto segue: PER TUTTI I RISTORATORI (unici proprietari o famiglia) DEL CENTRO ITALIA A CUI IL TERREMOTO HA DISTRUTTO O RESO INAGIBILE IL PROPRIO RISTORANTE…. Sono disponibile a dare in comodato d’uso gratuito il mio ristorante, totalmente attrezzato, fino a quando non sarete nella condizione di poter riappropriavi del vostro. Non voglio soldi, ne per l’affitto ne per altro. Dovrete solamente coprire personalmente le spese vive dell’utilizzo (luce, gas, tasse, imposte). Per il pernottamento, vi posso offrire ad un prezzo modico, un appartamento sito vicino all’attività ma non è un elemento vincolante. Per dirla in parole povere, potrete pernottare dove vorrete, il ristorante ve lo do in ogni caso. Non ci saranno condizioni legate alla durata. Appena potrete tornare a gestire la vostra attività, liberi di andare. Quello che vorrei, è dare la possibilità, a chi vorrà coglierla, di continuare il proprio mestiere e di sentirsi ancora parte di un progetto di vita. Il ristoratore è per sempre, io lo so bene! Info: Tel. Giovanni 380 5332937, Limone Piemonte.'
indirizzo: ''
lat: '44.2009100'
lon: '7.5786100'
link: 'https://www.facebook.com/Residenza-il-Girasole-285379791628622/'
immagine: ''
data: 04/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
L'offerta del ristoratore di Limone è stata raccolta da una famiglia di Torrita di Amatrice che a marzo ha preso in gestione il ristorante, come riporta un articolo del Secolo XIX: http://www.ilsecoloxix.it/Facet/amp/Uuid/278f2a6c-e52b-11e6-ad14-6ed5cba40ae1/Limone_offre_il_ristorante_ai_terremotati_sar%25C3%25A0_gestito_da_una_famiglia_di_Amatrice_CAPlimoneamitrce.xml
