### ISSUE TITLE
Pagina facebook "Residenza Il Girasole"

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1417]
<pre><yamldata>titolo: 'Pagina facebook "Residenza Il Girasole"'
descrizione: 'Sig. Giovanni Bottero da in comodato d''uso il suo ristorante'
link: 'https://www.facebook.com/Residenza-il-Girasole-285379791628622/'
data: 04/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione già presente.
