### ISSUE TITLE
Raccolta fondi per la scuola di Fiastra

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1424]
<pre><yamldata>titolo: 'Raccolta fondi per la scuola di Fiastra'
descrizione: 'Siamo un''associazione nata all''indomani del sisma, il nostro nome è RicistruiAMO Fiastra e, con il benestare dellamministrazione comunale di Fiastra abbimo lancuato una raccolta fondi su Eppela per acquistare arredamenti, mobili eche tutto il materiale necessario per rifornire la nuova scuola di Fiastra che il terremoto ha distrutto. Vi chiediamo un aiuto per condividere e renderci visibili il più possibile! Il link alla campagna è questo: https://www.eppela.com/it/projects/11106-spring-term Grazie mille del vostro supporto!'
link: 'https://www.eppela.com/it/projects/11106-spring-term'
data: 06/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione già presente.
