### ISSUE TITLE
lavatrice e asciugatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1443]
<pre><yamldata>tel: '3341735948'
email: caterina.fiordiani@alice.it
cosa: 'lavatrice e asciugatrice'
descrizione: 'Siamo una famiglia di Norcia e abbiamo difficoltà ad entrare in casa per lesioni dovute al terremoto. I disagi sono tanti...se potete aiutateci. Abbiamo bisogno di una lavatrice e una asciugatrice. Grazie.'
indirizzo: 'Piazza San Benedetto, Casa Coletti, Norcia, PG, UMB, 06046, Italia'
lat: '42.7927706'
lon: '13.0930812'
link: ''
immagine: ''
data: 11/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Chieste ulteriori informazioni via email perché una precedente richiesta di un'asciugatrice riferita allo stesso indirizzo email risultava soddisfatta (vedi comunicazione via email di Christian Varani) ed è stata quindi chiusa.

**Comment by cristigalas** [comment]
Ricevuta risposta attraverso webform e inserita nuova richiesta. Dunque questa non è più necessaria. Chiudo.
