### ISSUE TITLE
Famiglia di Verona regala roulotte per tre persone

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1445]
<pre><yamldata>tel: '3332301536'
email: paola12santi@gmail.com
cosa: roulotte
descrizione: 'Regaliamo roulotte datata ma perfetta, sana, adatta a tre persone. Se avete altre offerte da zona Verona - Lago di Garda metteteci in contatto che organizziamo transferimento. Tel. 0458622470'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 11/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Via email ci hanno comunicato di aver donato la roulotte ad una persona di Muccia (Mc), qui la richiesta soddisfatta: #1521
