### ISSUE TITLE
A #Fiastra (Mc) cercasi televisore per la tenda-mensa

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1449]
<pre><yamldata>tel: ''
email: sia_82@hotmail.com
cosa: 'A #Fiastra (Mc) cercasi televisore per la tenda-mensa'
descrizione: 'A Fiastra (Mc) un gruppo di famiglie che vive ancora in tensostrutture e roulotte avrebbe bisogno di un televisore per la tenda-mensa. Contattattare il Comune di Fiastra alla pagina Facebook (vedi link) oppure Silvia Belli: sia_82@hotmail.com'
indirizzo: 'Via Roma, Fiastra, MC, Marche, 62035, Italia'
lat: '43.0361407'
lon: '13.1554547'
link: 'https://www.facebook.com/ComuneDiFiastra/?fref=ts'
immagine: ''
data: 13/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Silvia Belli ci comunica che l'associazione sportiva Si Fuoristrada di Pesaro Urbino ha donato loro un televisore. Chiudo.
