### ISSUE TITLE
Ad #Amatrice servono con urgenza stufe a legna

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1453]
<pre><yamldata>tel: '3248824117'
email: christianvarani@gmail.com
cosa: 'Richiesta urgente di alcune stufe a legna con intervento ad Amatrice, per i mesi invernali'
descrizione: 'Servono necessariamente in questi periodi e per i prossimi mesi invernali, delle stufe o stufette a legna, per permettere ai cittadini terremotati di Amatrice e in determinate aree di accoglienza di riscaldarsi,anche quando manca la corrente elettrica a causa del maltempo, dei Black Out possibili di elettricità, come si è già verificato più volte nei periodi precedenti e che si può verificare ancora. Le stufe a legna mi sono state richieste telefonicamente da un Responsabile e volontario della Protezione Civile presente sul luogo stesso, che ne ha manifestato l''esigenza, per l''elettricità che è già mancata ad Amatrice anche in questi periodi più recenti.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 13/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha comunicato via email che alcune stufe sono state donate e quindi non c'è più bisogno. Chiudo.
