### ISSUE TITLE
A #Visso c'è bisogno di una roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1457]
<pre><yamldata>tel: '3927698337'
email: ''
cosa: 'Roulotte #Visso'
descrizione: 'Sono Angelo Lupidi e a Visso serve una roulotte per 3 adulti che non vogliono lasciare la propria terra. Grazie'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: ''
immagine: ''
data: 15/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Roulotte trovata e consegnata oggi, sabato 11 febbraio, dal gruppo Caravanisti Solidali, vedi https://www.facebook.com/groups/1758670357733881/permalink/1843010362633213/
