### ISSUE TITLE
A #Treia (Mc) c'è bisogno di una roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1459]
<pre><yamldata>tel: '3291693360'
email: pelange23@web.de
cosa: Ruolotte
descrizione: 'Sono "terremotata" da Agosto e sto cercando disperatamente una ruolotte per tornare sul mio posto. Mi servirebbe piccola ma pulita. La prendo o a prezzo modico, in dono o anche in prestito. Zona Treia (MC). Grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 16/12/2016
</yamldata></pre>

**Comment by chiccap** [comment]
già presente.
