### ISSUE TITLE
Cercasi roulotte a #Muccia (Mc)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1468]
<pre><yamldata>tel: '3389942731'
email: g.carlocop@alice.it
cosa: 'Roulotte vecchia in affitto o in prestito'
descrizione: 'Sono costretto per motivi di lavoro a tornare al mio paese di residenza Muccia, ho urgente bisogno di una roulotte vecchia per 4-5 mesi, non importa il suo stato.'
indirizzo: ''
lat: '43.0823200'
lon: '13.0432300'
link: ''
immagine: ''
data: 17/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Roulotte trovata. Vedi #1521. Chiudo.
