### ISSUE TITLE
A #Savelli di #Norcia è urgente la messa in sicurezza del campanile

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1471]
<pre><yamldata>tel: ''
email: ''
cosa: 'A #Savelli di #Norcia è urgente la messa in sicurezza del campanile'
descrizione: 'Dal terremoto del 30 ottobre il campanile della chiesa di Savelli è pericolante e ad oggi nessuno ha provveduto a metterlo in sicurezza (La foto è di Mauro Battiston).'
indirizzo: 'Strada provinciale di Norcia, Cascia, PG, UMB, 06043, Italia'
lat: '42.7264537'
lon: '13.1266875'
link: 'https://twitter.com/flaviaamabile/status/808652552380223489'
immagine: 'http://i.imgur.com/yDZgnMA.jpg'
data: 18/12/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Smontato e demolito dalla ditta Onori s.n.c. Norcia.
