### ISSUE TITLE
Comunicazione di corsi anche formativi organizzati a San Benedetto del Tronto per i cittadini terremotati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1474]
<pre><yamldata>tel: '0735.794213'
email: info@protezionecivilesbt.it
cosa: 'Comunicazione di corsi anche formativi organizzati a San Benedetto del Tronto per i cittadini terremotati'
descrizione: 'Si comunica per tutti i Signori interessati e terremotati, che la Protezione Civile di San Benedetto del Tronto sta organizzando dei corsi formativi e di qualificazione utili e ad essi indirizzabili, per delle attività lavorative e di altro genere e comunque culturalmente utili presso la sede attuale dell''Ex Scuola Media Statale "M. Curzi", di Via Golgi a San Benedetto del Tronto. Per maggiori informazioni anche dettagliate nello specifico, si invitano i possibili interessati a contattare i volontari della Protezione Civile ai recapiti comunque specificati in tale richiesta ed anche con l''aggiunta nel Link della loro pagina Facebook di riferimento.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Protezione Civile SBT San Benedetto del Tronto'
immagine: ''
data: 19/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
