### ISSUE TITLE
Azienda agricola di #Pretare ha bisogno di mangime per bovini, equini e ovini

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1475]
<pre><yamldata>tel: '3804323871'
email: mirkotrenta@libero.it
cosa: 'richiesta mangime'
descrizione: 'Buonasera, sono Santolini Santa, titolare dell''azienda agricola Le Terre delle fate, situata a Pretare, piccola frazione di Arquata del Tronto. Il mio paese è stato duramente colpito dal sisma, così come la mia azienda. Essa è composta da 20 bovini, 15 ovini e 4 equini. E'' a conduzione familiare, gestita da me, con l''ausilio dei miei due figli. Ogni giorno siamo costretti a recarci da San Benedetto a Pretare, percorrendo circa 70 chilometri. Abbiamo necessità di almeno 50 quintali di mangime per soddisfare tutti i nostri animali. Purtroppo, a causa delle spese ingenti che stiamo affrontando, considerando anche le innumerevoli perdite economiche ricevute a causa del sisma, ci troviamo nella condizione di chiedere aiuto. Teniamo a precisare che la necessità è reale e confidiamo nella comprensione di quanti vorranno darci una mano.'
indirizzo: ''
lat: '42.7978600'
lon: '13.3004100'
link: ''
immagine: ''
data: 19/12/2016
</yamldata></pre>

**Comment by paperinoarchimede** [comment]
Salve, potreste lasciare il vostro iban x eventuali donazioni? Grazie

**Comment by cristigalas** [comment]
Salve @paperinoarchimede TerremotoCentroItalia non ha un IBAN e non prende donazioni ma se vuoi puoi sostenere il progetto Ricostruzione Trasparente, di cui siamo partner. Qui il crowdfunding https://www.produzionidalbasso.com/project/ricostruzione-trasparente/ Grazie!

**Comment by cristigalas** [comment]
Richiesta soddisfatta come da comunicazione su Facebook https://www.facebook.com/groups/1758670357733881/permalink/1816684901932426/ Chiudo.
