### ISSUE TITLE
Il Comune di #Fiastra ha bisogno di due motoseghe

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1476]
<pre><yamldata>tel: '339 5803585'
email: sia_82@hotmail.com
cosa: 'Il Comune di #Fiastra ha bisogno di due motoseghe'
descrizione: 'Il Comune di Fiastra ha bisogno urgente di un paio di motoseghe professionali (Still o Usqvarna) perchè sono state rubate e il Comune è rimasto senza, mentre in questo momento sarebbero molto utili. Per contatti: Maurizio, geometra del Comune.'
indirizzo: 'Via Roma, Fiastra, MC, Marche, 62035, Italia'
lat: '43.0361407'
lon: '13.1554547'
link: ''
immagine: ''
data: 19/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Le due motoseghe sono state donate dall'associazione SiFuoristrada di Pesaro, come comunicato da Silvia Belli del comitato RicostruiamoFiastra. Chiudo.
