### ISSUE TITLE
Le "cuffie del cuore" di Arena per le popolazioni colpite dal sisma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1477]
<pre><yamldata>chi: 'Acquista la cuffia del cuore di Arena'
descrizione: 'A inizio mese, Arena comunicò che la sua sede di Tolentino, nelle Marche, era stata risparmiata dal terremoto, grazie ai criteri antisismici con cui è stata costruita. Ora, il marchio dei tre diamanti ha realizzato una cuffia in edizione limitata, rappresentante due mani che si uniscono a racchiudere un cuore, il cui ricavato sarà interamente devoluto alle popolazione devolute dal sisma. “Un aiuto semplice, ma concreto – commenta Enrico Maria Tricarico, General Manager di Arena per l’Europa Centro-Meridionale, il quale aggiunge che – questa iniziativa si inserisce in un più ampio progetto che ha visto arena promotrice di diverse iniziative direttamente sul territorio a supporto delle popolazioni colpite dal sisma”. Testimonial dell’iniziativa l’olimpionico di Sidney 2000 Massimiliano Rosolino “una bellissima idea di cui mi faccio promotore con grande entusiasmo – e Tania Cagnotto, doppio argento ai Giochi di Rio 2016 – mi auguro che il mio piccolo contributo possa davvero supportare il futuro delle persone colpite dal sisma”. Oltre alla Cuffia del cuore, Arena ha deciso di destinare alle popolazioni colpite dal sisma anche il 10% del fatturato, nel mese di dicembre, di tutti gli outlet e negozi di proprietà.'
intestazione: ''
iban: ''
bic: ''
postale: ''
causale: ''
link: 'http://www.swimbiz.it/portal/cagnotto-rosolino-cuffia-del-cuore-le-popolazioni-colpite-dal-sisma/'
email: ''
data: 20/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Non sono convinta che si debbano pubblicare segnalazioni del genere sul sito...

**Comment by marco-acorte** [comment]
??? non e' sempre un acquisto solidale? 
cioe' compro la cuffia e ARENA poi e cito:
"il cui ricavato sarà interamente devoluto alle popolazione devolute dal sisma."

**Comment by cristigalas** [comment]
Dici? Ok, sì hai ragione... ma è raccolta fondi o acquisto solidale?

**Comment by marco-acorte** [comment]
credo piu' acquisto solidale...
altro link per factcheck
https://www.facebook.com/Arena.Ita/photos/a.303552363076673.63329.270982799666963/1074965389268696/?type=3&theater

**Comment by marco-acorte** [comment]
ecco il link ufficiale
http://arenawaterinstinct.pr.co/140013-arena-sostiene-le-popolazioni-del-centro-italia-colpite-dal-sisma-con-una-cuffia-in-edizione-limitata

**Comment by cristigalas** [comment]
Ok, pubblico.
