### ISSUE TITLE
Arci Nazionale

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#148]
<pre><yamldata>chi: Arci Nazionale
descrizione: BIBLIOBUS ARCI – La Cultura per la Ricostruzione L'Arci sta cercando fondi per riempire di libri (e carburante) un autobus che porterà cultura e momenti di distensione alle persone colpite nelle zone del terremoto del 24 Agosto scorso.
intestazione: Arci
iban: IT 36 A 0501803200 000000000041
bic: 
postale: 
causale: Terremoto centro italia
link: https://www.produzionidalbasso.com/project/bibliobus-arci-la-cultura-per-la-ricostruzione/
email: 
data: 13/09/2016</yamldata></pre>

**Comment by cristigalas** [comment]
Raccolta fondi conclusa con il raggiungimento della somma necessaria. Chiudo.
