### ISSUE TITLE
MATERIALE PER LABORATORIO DI FALEGNAMERIA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1491]
<pre><yamldata>tel: '3249850445 - 3478794690'
email: guscentroascolto@gmail.com
cosa: 'MATERIALE PER LABORATORIO DI FALEGNAMERIA'
descrizione: 'GUS - GRUPPO UMANA SOLIDARIETÀ, associazione presente per la popolazione terremotata dal 24 agosto, cerca materiale per poter attivare un laboratorio di falegnameria a San Benedetto del Tronto, in via Camillo Golgi (ex scuola Curzi), per la popolazione di Arquata del Tronto e dintorni. In particolare servono: pirografo, pantografo, combinata, scalpelli di varie dimensioni e per la lavorazione del legno, morsetti, sega da traforo e i pannelli multistrato con spessore di 2,5-5,0 mm. Il materiale può essere consegnato direttamente in via Golgi. Per info 3478794690.'
indirizzo: 'Via Raffaello Sanzio, Marina centro, San Benedetto del Tronto, AP, Marche, 63039, Italia'
lat: '42.9525328'
lon: '13.8807144'
link: ''
immagine: ''
data: 23/12/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Laboratorio svolto.
