### ISSUE TITLE
A #Pretare azienda agricola ha bisogno urgente di un gruppo elettrogeno

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1496]
<pre><yamldata>tel: '3804323871'
email: mirkotrenta@libero.it
cosa: 'Richiesta urgente di 1 Gruppo elettrogeno a gasolio, utile presso l''azienda agricola, di Pretare (frazione di Arquata del Tronto)'
descrizione: 'Serve urgentemente un gruppo elettrogeno, preferibilmente a gasolio e con una potenza di almeno 5 kw, per l''azienda agricola a gestione famigliare "Le Terre delle Fate", ubicata sui Monti Sibillini a Pretare, frazione di Arquata del Tronto. Avere un generatore sarebbe importante e urgente perché spesso manca la corrente elettrica e ciò impedisce lo svolgimento delle attività in una situazione già precaria. Chi può dare una mano a reperire il gruppo elettrogeno può contattare la signora Santa Santolini e i figli al numero telefonico o indirizzo email indicati. Grazie!'
indirizzo: ''
lat: '42.7978600'
lon: '13.3004100'
link: ''
immagine: ''
data: 27/12/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Gruppo elettrogeno recuperato, come da email di Christian Varani. Chiudo.
