### ISSUE TITLE
Offresi sopralluoghi rilievi e progettazioni preliminari per beni vincolati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1507]
<pre><yamldata>tel: '3333842781'
email: studiolailafilippi@libero.it
cosa: 'sopralluoghi rilievi e progettazioni preliminari beni vincolati'
descrizione: 'siamo uno studio tecnico con esperienza di collaborazione con Mibact e Sovrintendenza in merito a beni pubblici vincolati sisma 2012 Emilia - Offriamo la nostra disponibilità per prestazioni gratuite di rilievo e progettazione preliminare.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 02/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Come ha detto @favoeva sa di "preventivi gratuiti". Non accetto e chiudo.
