### ISSUE TITLE
"RiapriAmo #Castelluccio di #Norcia", raccolta firme per aprire una via di accesso al paese

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1513]
<pre><yamldata>tel: ''
email: lacasasullalberoonlus@gmail.com
cosa: '"RiapriAmo #Castelluccio di #Norcia", raccolta firme per aprire una via di accesso al paese'
descrizione: 'Dal sisma del 30 ottobre 2016 che ha coinvolto diversi borghi del centro Italia, Castelluccio di Norcia non ha una via di accesso percorribile. Con oltre due mesi di tempo, nelle nostre strade non è stato spostato nemmeno un sassolino caduto. l''associazione La Casa sull''Albero ha lanciato su Change.org una petizione per chiedere il ripristino di una via di accesso al paese.'
indirizzo: 'Via Dietro la Torre, Norcia, PG, UMB, 06046, Italia'
lat: '42.8287758'
lon: '13.2076515'
link: 'https://www.change.org/p/la-casa-sull-albero-onlus-riapriamo-castelluccio-di-norcia'
immagine: 'http://i.imgur.com/BJDHl0Y.jpg'
data: 03/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Strada riaperta a luglio 2017.
