### ISSUE TITLE
Necessità trasporto aiuti da Udine

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1517]
<pre><yamldata>tel: ''
email: ''
cosa: 'Necessità trasporto aiuti da Udine'
descrizione: 'URGENTE.... Abbiamo 2 bancali di aiuti (vestiario e generi di conforto) da prelevare a Palmanova (UD) per portarli dove necessitano. Chi si offre di prelevarli e poi consegnarli a sua discrezione? Dobbiamo liberare il capannone entro lunedì. Grazie.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1823777244556525/'
immagine: ''
data: 04/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta, come comunicato via email da Christian Varani. Chiudo.
