### ISSUE TITLE
A #Muccia c'è bisogno di una roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1521]
<pre><yamldata>tel: '3389942731'
email: g.carlocop@alice.it
cosa: 'A Muccia c''è bisogno di una roulotte'
descrizione: 'Giancarlo Copponi, residente a Muccia in provincia di Macerata, cerca disperatamente una roulotte.'
indirizzo: 'Muccia, MC, Marche, Italia'
lat: '43.0817007'
lon: '13.0429675'
link: ''
immagine: ''
data: 05/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione già presente qui http://terremotocentroitalia.info/issues/1468

**Comment by cristigalas** [comment]
La roulotte è stata trovata grazie ad una donazione da Verona. Vedi conferma ricevuta dalla donatrice via email e via Twitter da un amico del richiedente https://twitter.com/calzolarig/status/817264984312856577 Chiudo.
