### ISSUE TITLE
Si ricerca una roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#153]
<pre><yamldata>telegram_user: ''
descrizione: 'Occorre una roulotte attrezzata per Enzo, unico rimasto nel borgo di Pescara del Tronto.'
immagine: ''
lat: '42.749867'
lon: '13.269536'
data: 13/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
manca il contatto. Impossibile fare incrocio con disponibilità :(

**Comment by chiccap** [comment]
Chiudo perchè Enzo vive sulla costa con tutti glia altri.
