### ISSUE TITLE
Offro ospitalità a famiglia di tre persone in provincia di Caserta

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1533]
<pre><yamldata>tel: '3396307148'
email: antonio.dott.comm.scognamiglio@gmail.com
descrizione: 'Ospito famiglia di massimo tre persone in Santa Maria Capua Vetere (CE)'
indirizzo: 'Corso Giuseppe Garibaldi, Sant''Andrea dei Lagni, Santa Maria Capua Vetere, CE, CAM, 81055, Italia'
lat: '41.080214'
lon: '14.256527'
link: ''
immagine: ''
data: 08/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non è mai stato contattato. Alloggio non più disponibile.
