### ISSUE TITLE
Canile Laterza

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1534]
<pre><yamldata>titolo: 'Canile Laterza'
descrizione: 'http://www.lagazzettadelmezzogiorno.it/news/notizie-nascoste/844823/laterza-raggiunto-il-canile-sommerso-dalla-neve-con-chiusi-300-cani.html'
link: ''
data: 08/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è una segnalazione che riguarda le zone colpite dal sisma. Chiudo.
