### ISSUE TITLE
Appello per riaprire la #Valnerina

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1538]
<pre><yamldata>tel: ''
email: ''
cosa: 'Appello per riaprire la Valnerina'
descrizione: 'Su Change.org l''appello di Sonia Fiorello, proprietaria di un''attività commerciale a Visso, perché venga riaperto quel tratto di strada della Valnerina che collega Visso al resto delle Marche e che è chiusa dal 30 ottobre. "È inammissibile che il Comune di Visso sia spaccato in due e che nessuno faccia nulla per riunirlo!! Noi abitanti delle frazioni di Visso siamo stufi di essere abbandonati a noi stessi e di percorrere 45 /60 km al giorno per raggiungere Visso Comune!! Quel tratto di strada va riaperto non solo per noi che ci viviamo e ci lavoriamo, ma anche per tutti i turisti e per coloro che hanno le seconde case da venire a visionare dopo quel maledetto 30 ottobre!!! Aiutateci a ripartire e a riavere un po'' di normalità!!"'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'https://www.change.org/p/prefetto-di-macerata-protezione-civile-regione-marche-regione-umbria-riapertura-della-valnerina?recruiter=659781299&utm_source=share_petition&utm_medium=facebook&utm_campaign=share_for_starters_page&utm_term=mob-xs-no_src-no_msg'
immagine: ''
data: 09/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Strada riaperta a ottobre 2018 
https://corrieredellumbria.corr.it/news/cronaca/526260/strada-valnerina-riaperta-il-2-ottobre.html
