### ISSUE TITLE
impianto stereo AIWA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1554]
<pre><yamldata>tel: '3929628733'
email: cesaroni.massimo@gmail.com
cosa: 'impianto stereo AIWA'
descrizione: 'impianto con radio, lettore cd e lettore audiocassette. E'' la segnalazione già fatta, voglio solo aggiungere una foto'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: 'http://i.imgur.com/G3xFeGv.jpg'
data: 12/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #1552
