### ISSUE TITLE
Comune di #Ussita: Apertura al pubblico degli uffici comunali e del Centro operativo comunale

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1576]
<pre><yamldata>titolo: 'Comune di#Ussita: Apertura al pubblico degli uffici comunali e del Centro operativo comunale'
descrizione: 'Si informa che dal 9 gennaio 2017 gli uffici comunali saranno aperti al pubblico dal lunedì al venerdì dalle ore 10.00 alle ore 12.30. Il C.O.C. (centro operativo comunale) sarà aperto anche il sabato.'
link: 'http://www.comune.ussita.mc.it/avvisi-cms/apertura-al-pubblico-degli-uffici-comunali-e-del-centro-operativo-comunale/'
data: 15/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #1577.
