### ISSUE TITLE
Raccolta aiuti per animali a Morlupo (Roma)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1578]
<pre><yamldata>tel: '340/5984563 - 06/9071822'
email: ''
cosa: 'Raccolta aiuti per animali a Morlupo (Roma)'
descrizione: 'Presso l''Agrizoo Market di Morlupo (Roma) è possibile portare cibo e altri beni per gli animali delle zone terremotate. Per ulteriori info telefonare o consultare pagina Facebook.'
indirizzo: 'Via San Michele, Morlupo, RM, Lazio, 00067, Italia'
lat: '42.1488565'
lon: '12.5030127'
link: 'https://www.facebook.com/Agrizoo-Market-1651433148428314/'
immagine: ''
data: 16/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
