### ISSUE TITLE
Libri per bambini e ragazzi

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#158]
<pre><yamldata>tel: '06.68408936'
email: c-ll@beniculturali.it
cosa: 'Libri per bambini e ragazzi'
descrizione: 'Il Centro per il libro e la lettura di Roma raccoglie libri da regalare a bambini e ragazzi (fino a 14 anni) colpiti dal sisma. I libri possono essere donati a mano o spediti al Centro. Sulla busta busta scrivere "Dono di libri – Terremoto 2016". Via Pasquale Stanislao Mancini 20, 00196 Roma'
indirizzo: 'Via Pasquale Stanislao Mancini 20, 00196 Roma'
lat: '41.91439'
lon: '12.47433'
link: 'http://www.comunicareilsociale.it/raccolta-libri-bambini-ragazzi-0-14/'
immagine: ''
data: 13/09/2016
</yamldata></pre>

**Comment by Manfro** [comment]
Georiferito.

**Comment by chiccap** [comment]
Raccolta chiusa.
