### ISSUE TITLE
A Pretare di Arquata del Tronto allevatore ha bisogno urgente di una motoslitta

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1586]
<pre><yamldata>tel: '3804323871'
email: ''
cosa: motoslitta
descrizione: 'Buonasera, siamo di nuovo qui a chiedere aiuto agli italiani e non alle assenti istituzioni, vista l''abbondante nevicata, chiediamo, anche in prestito per un piccolo periodo, una motoslitta efficiente, poiché non hanno montato le tensostrutture ed i nostri animali sono all''aperto, si riparano in una pineta. Grazie a chiunque voglia aiutarci. Mirko Trenta, frazione Pretare 4 B - Arquata del Tronto (AP).'
indirizzo: ''
lat: '42.7978600'
lon: '13.3004100'
link: ''
immagine: ''
data: 17/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Oggi, attraverso Subito.it, trovata una persona che pare essere in grado di offrire una motoslitta. Si chiama Matteo Muccia e ha fornito contatto email e telefonico che abbiamo inoltrato all'allevatore di Pratere. Purtroppo la cosa non è andata, chi offriva motoslitta si è tirato in dietro adducendo varie scuse.

**Comment by cristigalas** [comment]
Invece che una motoslitta abbiamo trovato una lama da neve per trattore e a Mirko questa soluzione va benissimo. La lama la offre una ditta di Asti, Geo Italy, che ci ha inviato una mail chiedendoci a chi poteva donarla. Oggi si sentivano e quindi ci fanno sapere.

**Comment by cristigalas** [comment]
La ditta di Asti spedirà domani, 27 gennaio, la pala da neve al sig.Trenta (vedi email). Chiudo.
