### ISSUE TITLE
#Visso urgente intervento in aiuto azienda agricola

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1588]
<pre><yamldata>tel: '3894703727'
email: ''
cosa: '#Visso urgente intervento in aiuto azienda agricola'
descrizione: 'Azienda Agricola Scolastici di Pieve Torina In tanti ci avete chiesto un aggiornamento riguardo la situazione, purtroppo è peggiorata e ha nevicato tutta la notte, anche stamattina c''è una bufera fortissima. L''altezza della neve è intorno a al metro e ottanta ma ci sono cumuli alti anche quattro metri. Siamo usciti a fatica da casa e non riusciamo a raggiungere le stalle neanche a piedi. Le strade provinciali sono interrotte da ieri sera e tutte le frazioni sono isolate. Stanotte sono crollate due stalle con mucche e pecore all''interno, una a Gualdo e una a Belforte. Non sappiamo in che condizioni siano i nostri animali e dalle sei di questa mattina stiamo contattando tutte le forze dell''ordine per richiedere un intervento.. sembra non ci siano abbastanza mezzi e comunque squadre mal equipaggiate. Speriamo che in giornata intervenga l''esercito perché gli animali sono senza cibo né acqua da ieri.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1830279550572961/'
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Aggiornamento. Ad oggi 19 gennaio non è intervenuto ancora nessuno e sono sempre bloccati.

**Comment by cristigalas** [comment]
Risolta.
