### ISSUE TITLE
EMERGENZA NEVE ED EMERGENZA TERREMOTO -  #Amatrice #Saletta

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1590]
<pre><yamldata>tel: '3391847914'
email: ''
cosa: 'EMERGENZA NEVE ED EMERGENZA TERREMOTO -  #Amatrice #Saletta'
descrizione: 'C''è QUALCUNO CHE RIESCE AD ARRIVARE A SALETTA A VEDERE SE LA STALLA DI EMIDIO MORETTI è ANCORA IN PIEDI? NON SO SE E QUANDO I NIPOTI RIUSCIRANNO AD ARRIVARE!!! CI SONO MUCCHE CAPRE PECORE GALLINE CANI! LA STALLA ERA GIà PERICOLANTE MA LA TENSOSTRUTTURA NON è MAI ARRIVATA E HANNO DOVUTO RIMETTERE Lì DENTRO GLI ANIMALI. Contattare Genny.'
indirizzo: 'SP20, Pedivilla, Amatrice, RI, Lazio, 02011, Italia'
lat: '42.6713248'
lon: '13.2720634'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
