### ISSUE TITLE
#Aquila Edifici comunali disponibili per l'accoglienza 18/01

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1591]
<pre><yamldata>titolo: 'Edifici comunali disponibili per l''accoglienza 18/01'
descrizione: 'Il Centro operativo comunale (Coc) dell'Aquila ha reso noto che, all''elenco degli edifici comunali disponibili e pronti per l''accoglienza per chi non volesse rimanere nelle proprie abitazioni, sono stati aggiunti il Musp della Scuola Primaria di Arischia e lo stadio di Acquasanta (palestra e spogliatoi)'
link: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
