### ISSUE TITLE
Gruppi elettrogeni #Montemonaco (AP)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1592]
<pre><yamldata>tel: '3455758496'
email: ''
cosa: 'Gruppi elettrogeni #Montemonaco (AP)'
descrizione: 'Serve aiuto a Montemonaco, sono isolati con 2 metri neve senza corrente gruppi elettrogeni down, non possono comunicare linee telefoniche interrotte.'
indirizzo: 'Strada Provinciale 83 Subappennina, Montemonaco, AP, Marche, 63088, Italia'
lat: '42.8991551'
lon: '13.3268587'
link: 'https://m.facebook.com/story.php?story_fbid=10210000862273070&id=1081124294'
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Enel comunica via Twitter che Montemonaco è di nuovo rialimentata. https://twitter.com/enelgroupit/status/821784386865659913
