### ISSUE TITLE
Numeri Utili emergenza neve #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1595]
<pre><yamldata>titolo: 'Numeri Utili emergenza neve #Amatrice'
descrizione: 'A chi rivolgersi in caso di EMERGENZA NEVE a Amatrice.'
link: 'https://www.facebook.com/1627862690838290/photos/a.1630299043927988.1073741828.1627862690838290/1680037208954171/?type=3&theater'
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione già presente.
