### ISSUE TITLE
Aiuti e gruppo elettrogeno a #Scorrano (TE)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1597]
<pre><yamldata>tel: '3288818703'
email: ''
cosa: 'Aiuti e gruppo elettrogeno a #Scorrano'
descrizione: 'A Scorrano frazione di Celleno Atanasio (TE) isolati da 2mt di neve e senza corrente. Servono aiuti e gruppo elettrogeno. Contatto Lusiana.'
indirizzo: ''
lat: '42.561'
lon: '12.1374'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
