### ISSUE TITLE
A #Coppito servono coperte e brandine

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1599]
<pre><yamldata>tel: ''
email: ''
cosa: 'Coperte e brandina #Coppito'
descrizione: 'La Portezione civile della Pro loco di Coppito ha attrezzato il Musp scolastico e servono coperte e brandine per la notte.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
