### ISSUE TITLE
Offro appartamento a Palestrina provincia di Roma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1610]
<pre><yamldata>tel: '334.7431815'
email: gabry9671.gc@gmail.com
descrizione: 'Palestrina provincia di Roma, offro alloggio temporaneo a terremotati centro Italia, è una porzione del mio villino bifamiliare. Alloggio con entrata indipendente, circa 80mq, salone doppio, camera da letto, bagno, cucina. Completamente arredato di tutto, potete usufruirne da subito. ideale per coppia anziani o giovani senza bimbi, unica condizione non dovete avere paura di cani e gatti perchè con me vivono due cani e due gatti. Contattatemi. Gabriella'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente
