### ISSUE TITLE
Salve siamo un associazione di

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1616]
<pre><yamldata>tel: '3803837260'
email: giulionoah@gmail.com
descrizione: 'Salve siamo un associazione di Terracina latina associazione culturale Maria Stella . Avremmo un appartamento con giardino piano terra per ospitare una famiglia dei paesi colpiti dal sisma appartamento piano terra con giardino a Sabaudia latina per un periodo di tempo fino a tre mesi tutto a nostre spese'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
