### ISSUE TITLE
A #ColliPerilli, frazione #Amatrice, serve urgentemente una turbina per la neve

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1625]
<pre><yamldata>titolo: 'A #ColliPerilli, frazione #Amatrice, serve urgentemente una turbina per la neve'
descrizione: 'L''azienda agricola Aureli di Colli Petrilli, Amatrice, lancia un appello per recuperare una turbina che permetta loro di liberarsi dalla neve e raggiungere i loro animali perchè temono che il capanno in cui sono ricoverati possa essere crollato. Tel. 338 468 0596.'
link: 'https://www.facebook.com/Azienda-Agricola-Bio-Aureli-Antonio-e-Capanna-Paola-1670113093223886/#'
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
