### ISSUE TITLE
#Rieti centri accoglienza popolazione per la notte

### ISSUE THREAD

**Issue by psykola** [emergenzeHack/terremotocentro_segnalazioni#1632]
titolo: 'Rieti centri accoglienza popolazione per la notte'
descrizione: 'L''Amministrazione comunale di Rieti, in seguito alle scosse di oggi e in via precauzionale, ha approntato un centro di stazionamento, dove la popolazione potra soltanto sostare sia all''esterno che all''interno, e due centri di accoglienza per trascorrere la notte. La sala operativa comunale del Coi rimane costantemente attiva e raggiungibile ai numeri 0746/287215 e 348/8856270. 
- Centro di stazionamento, operativo dalle 17 di oggi 18 gennaio: Pala Cordoni e Piazzale Leoni.
- Centro di accoglienza Rieti Nord, operativo dalle 20 di oggi 18 gennaio: Bocciodromo comunale (via De Gasperi).
- Centro di accoglienza Rieti Sud, operativo dalle 20 di oggi 18 gennaio: Campi da tennis (via Dupre Theseider)'
link: 'http://www.comune.rieti.it/article/17/01/emergenza-terremoto-elenco-centri-accoglienza-popolazione-la-notte'
data: 18/01/2017

**Comment by cristigalas** [comment]
Già presente.
