### ISSUE TITLE
#Rieti scuole chiuse fino a sabato 21

### ISSUE THREAD

**Issue by psykola** [emergenzeHack/terremotocentro_segnalazioni#1633]
titolo: '#Rieti scuole chiuse fino a sabato 21'
descrizione: 'Il Comune di Rieti comunica che in seguito alle scosse di questa mattina, in via precauzionale, il sindaco ha deciso di emanare una apposita ordinanza di sospensione delle attività didattiche nelle scuole pubbliche e private di ogni ordine e grado nei giorni dal 18 al 21 gennaio compreso per accertare l''assenza  di eventuali danni o lesioni presso gli edifici scolastici.'
   link: 'http://www.comune.rieti.it/article/17/01/emergenza-terremoto-scuole-chiuse-rieti-fino-al-21-gennaio-compreso'
    data: 18/01/2017

**Comment by cristigalas** [comment]
Già presente.
