### ISSUE TITLE
Offro alloggio gratuito in Sabina a famiglia terremotata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1634]
<pre><yamldata>tel: '3470716563'
email: guido@accascina.it
descrizione: 'Offro alloggio gratuito in Sabina a Castelnuovo di Farfa a una famiglia che volesse allontanarsi temporaneamente dalle zone terremotate. Sono disponibili 3 stanze con due letti ognuna, bagno in comune, da ora fino a fine febbraio. La struttura è moderna e antisismica. Ing. Guido Accascina 3470716563'
indirizzo: 'Strada vicinale Picarella, Fara in Sabina, RI, Lazio, 02040, Italia'
lat: '42.224322582561626'
lon: '12.73487091064453'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non è stato contattato. La casa non è più disponibile perchè ad oggi inagibile causa terremoto. Chiudo.
