### ISSUE TITLE
offresi casa in campagna per 6-8 persone ad Alberobello (Ba)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1639]
<pre><yamldata>tel: ''
email: rt.pcl@virgilio.it
descrizione: 'Mettiamo a disposizione casa in campagna ad Alberobello (BA) con n. 6/8 posti letto'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Offerta mai stata accolta. Non più disponibile.
