### ISSUE TITLE
C'è bisogno di abbigliamento da neve a #Cittareale

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1642]
<pre><yamldata>tel: '0746947006'
email: ''
cosa: 'Abbigliamento da neve #Cittareale'
descrizione: 'La Via del Sale Onlus segnala che servono tute, doposci e abbigliamento da neve. Per la consegna, contattare Centro di Smistamento di Cittareale.'
indirizzo: 'Corso Vittorio Emanuele, Cittareale, RI, Lazio, Italia'
lat: '42.6182543'
lon: '13.1596844'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Purtroppo non riusciamo ad avere notizie da Cittareale e anche l'associazione La Via del Sale, che ho sentito via Twitter, non ha informazioni in più da darci. Ci hanno suggerito di provare a contattare il centro smistamento di Posta: 3346125569. Domani proverò ed eventualmente aggiorno segnalazione.
