### ISSUE TITLE
**URGENTE** Soccorsi a #Ortolano #Campotosto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1643]
<pre><yamldata>tel: ''
email: ''
cosa: '**URGENTE** Soccorsi a #Ortolano #Campotosto'
descrizione: 'La frazione di Ortolano nel comune di Campotosto è sotto tre metri di neve. Continua a nevicare. I cittadini sono bloccati sia verso Teramo che verso L''Aquila. Questa mattina una slavina ha investito il paese e un concittadino è disperso. Ci sono anziani e bambini piccoli, uno di appena un mese. Servono urgentemente aiuti con mezzi necessari.'
indirizzo: 'Strada Statale 80 del Gran Sasso d''Italia, L''Aquila, AQ, Abruzzo, Italia'
lat: '42.5198625'
lon: '13.4234008'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
