### ISSUE TITLE
Benzina, gruppi elettrogeni #ValleCastellana #Teramo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1645]
<pre><yamldata>tel: ''
email: ''
cosa: 'Benzina, gruppi elettrogeni #ValleCastellana #Teramo'
descrizione: 'È finita la benzina nell''unico distributore di Valle Castellana, i pochi gruppi elettrogeni sono a secco. Portateci benzina e aiuto. Chiamate l''esercito, per favore. Ci sono 3 metri di neve.'
indirizzo: 'SP49, Corvino, Valle Castellana, TE, Abruzzo, Italia'
lat: '42.7361764'
lon: '13.4970995'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
