### ISSUE TITLE
AIUTI URGENTI #Atri

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1650]
<pre><yamldata>tel: ''
email: ''
cosa: 'AIUTI URGENTI #Atri'
descrizione: 'Nel Comune di Atri provincia di Teramo sono senza acqua, luce e riscaldamento da 48h, senza linea telefonica nè mobile nè fissa, scarsità viveri e isolamento viabilità. Situazione pesantissima e fuori dai canali di comunicazione: servono aiuti immediatamente.'
indirizzo: 'Piazza Duomo, Atri, TE, Abruzzo, 64032, Italia'
lat: '42.5801368'
lon: '13.9764121'
link: 'https://www.facebook.com/sara.capecci.7/posts/10211686939159472'
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
