### ISSUE TITLE
Cercasi stalli e adozioni per animali in zone terremotate

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1657]
<pre><yamldata>tel: '3396498145 - 3313121217'
email: ''
cosa: 'Cercasi stalli e adozioni per animali in zone terremotate'
descrizione: 'Sì cercano stalli e adozioni gli animali delle zone terremotate e invase dalla neve. Contatto: Bencini Paola 3396498145. fb: https://www.facebook.com/paola.bencini.391'
indirizzo: ''
lat: ''
lon: ''
link: 'https://twitter.com/poetyca/status/821822115762622470'
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Provata a chiamare più volte ma non risponde. Ieri sul profilo Fb della signora un post sembra un po' chiarire la segnalazione, ovvero la signora in realtà sembra cercare spontaneamente stalli per animali ma non vive nelle aree terremotate e non sembra avere nessun contatto 'diretto' con gli allevatori. Chiudo.
