### ISSUE TITLE
Disponibilità di 3 alloggi per famiglie a Radda in Chianti

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1658]
<pre><yamldata>tel: '3292606300'
email: protezionecivile@comune.raddainchianti.si.it
descrizione: 'Disponibilità n. 3 alloggi per famiglie a Radda in Chianti.'
indirizzo: 'Municipio, 1, Piazza Francesco Ferrucci, Lecci, Radda in Chianti, SI, TOS, 53017, Italia'
lat: '43.48662586225133'
lon: '11.374229192733765'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Riporto la risposta: "Ad oggi non è pervenuta nessuna richiesta di utilizzo dell’alloggio messo a disposizione da questa Amministrazione Comunale.
Precisiamo che saranno prese in considerazione SOLO richieste pervenute per il tramite degli Enti pubblici coinvolti dagli eventi sismici (Comuni, Province, Regioni) e non da singoli privati."
