### ISSUE TITLE
Offresi disponibilità di sgombraneve con operatore 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1659]
<pre><yamldata>tel: '3292606300'
email: protezionecivile@comune.raddainchianti.si.it
cosa: Sgombraneve
descrizione: 'Protezione Civile Radda in Chianti offre disponibilità ad inviare mezzo sgombraneve con operatore'
indirizzo: 'Propositura di San Niccolò, Piazza della Chiesa, Lecci, Radda in Chianti, SI, TOS, 53017, Italia'
lat: '43.48680489735277'
lon: '11.374293565750122'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
ProCiv Radda in Chianti ci comunica che sbloccaneve è già stato richiesto da Regione Toscana per alcune località delle Marche. Quindi chiudo issue.
