### ISSUE TITLE
Ospito coppia anche con un bim

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1665]
<pre><yamldata>tel: '3357726875'
email: lcaldino@hotmai.com
descrizione: 'Ospito coppia anche con un bimbo'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è indicato dove...
