### ISSUE TITLE
Offro ospitalità massimo a 3 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1673]
<pre><yamldata>tel: '3357726875'
email: lcaldino@hotmail.com
descrizione: 'Offro ospitalità massimo a 3 persone 2 adulti e un bimbo o una coppia a La Spezia'
indirizzo: 'Via XXIV Maggio, Migliarina, La Spezia, SP, LIG, 19100, Italia'
lat: '44.107033'
lon: '9.8282255'
link: ''
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
