### ISSUE TITLE
Diversi Gruppi Elettrogeni

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1677]
<pre><yamldata>tel: '331.6293213'
email: sindaco.amandola@gmail.com
cosa: 'Diversi Gruppi Elettrogeni'
descrizione: 'Abbiamo bisogno di gruppi elettrogeni per le frazioni del comune di Amandola che sono senza corrente da alcuni giorni Grazie mille'
indirizzo: 'SP239, Amandola, FM, Marche, 63857, Italia'
lat: '42.979965'
lon: '13.3560847'
link: 'http://www.comune.amandola.fm.it'
immagine: ''
data: 18/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
