### ISSUE TITLE
Offriamo vitto e stanza a fami

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1685]
<pre><yamldata>tel: '3488504467'
email: g.digiambelardini@gmail.com
descrizione: 'Offriamo vitto e stanza a famiglia con figli, noi siamo famiglia giovane con figlia piccola. Casa calda e accogliente a poggio catino prov rieti.'
indirizzo: 'Piazza Capizzucchi, Poggio Catino, RI, LAZ, 02034, Italia'
lat: '42.2949988'
lon: '12.6919216'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
