### ISSUE TITLE
Offro alloggio per 4 persone a Bagni di Lucca

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1686]
<pre><yamldata>tel: '3405392218'
email: gianlucamonticelli@ymail.com
descrizione: 'Buongiorno, metto a disposizione alloggio per max 4 persone a Bagni di Lucca, Lucca, toscana . Con possibilità di venire direttamente a prendere la famiglia necessitaria il giorno sabato 21/01 .'
indirizzo: 'Viale Umberto I, Paretaio, Desertoli, Bagni di Lucca, LU, TOS, 55022, Italia'
lat: '44.0099818'
lon: '10.590633'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuno l'ha contattato, non più disponibile.
