### ISSUE TITLE
Appartamento di 60 mq

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1687]
<pre><yamldata>tel: '3284614184'
email: nadiazucchi@gmail.com
descrizione: 'Appartamento di 60 mq'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è specificato dove.
