### ISSUE TITLE
Montegabbione,  frazione Monte Giove (Terni) isolata: richiesta di aiuto urgente

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1688]
<pre><yamldata>tel: ''
email: ''
cosa: 'Montegabbione,  frazione Monte Giove (Terni) isolata: richiesta di aiuto urgente'
descrizione: 'Montegabbione, in provincia di Terni, frazione Monte Giove è isolata ci sono persone.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1830607870540129/'
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
