### ISSUE TITLE
Offro a famiglia in famiglia v

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1689]
<pre><yamldata>tel: '3342163478'
email: robertapesucci1@gmail.com
descrizione: 'Offro a famiglia in famiglia vitto e alloggio gratuito, anche con animali.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è indicato dove.
