### ISSUE TITLE
Offresi pala da neve per trattore

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1692]
<pre><yamldata>tel: '3406569627'
email: guido.dipaolo@geo-agric.com
cosa: 'Pala da neve per trattore'
descrizione: 'Buongiorno, vi contatto dalla Geo Italy Srl. Siamo una ditta di Asti, costruiamo e commercializziamo attrezzatura agricola. Vorremmo donare una pala da neve per trattore. Si tratta di un aiuto specifico, ci serve qualcuno che abbia un trattore e gli serva una pala da neve per liberare le strade ai soccorsi. Potete darci un nominativo? Vorremmo saltare le lungaggini burocratiche ed arrivare subito a chi ne abbia veramente bisogno. Guido Di Paolo'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.geo-agric.com'
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Ricevuta dall'azienda Santolini Santa di Pretare.
