### ISSUE TITLE
Offresi alloggio a famiglia in provincia di Trento

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1693]
<pre><yamldata>tel: '3461227008'
email: danico_987@yahoo.it
descrizione: 'Siamo lontani, lo so...Siamo in Trentino Alto Adige, a Caldonazzo. Io e il mio compagno mettiamo a disposizione due stanze (forse tre) accoglienti per ospitare persone, coppie, famiglie che vogliono allontanarsi dalle zone di emergenza. Ripeto, siamo lontani ma con tanta voglia di aiutare. Abbiamo anche un bel giardino di 200mq, per chi avesse anche amici a quattro zampe. La casa è indipendente ma in centro storico...per chi ne avesse abbastanza della neve e della terra instabile...qui da noi splende il sole, neve non se ne vede da tanto tempo e il terra non trema...'
indirizzo: 'Via Roma, Brenta, Caldonazzo, Comunità Alta Valsugana e Bersntol, TN, Trentino-Alto Adige, 38052, Italia'
lat: '45.9937505'
lon: '11.2686023'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mai ricevuto richieste. Non più disponibile.
