### ISSUE TITLE
Offro bilocale con piccola cucina per 4 persone a Castelfiorentino.

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1697]
<pre><yamldata>tel: '3355941425'
email: giuliaperticucci@gmail.com
descrizione: 'Bilocake con piccola cucina per famiglia 4 persone , disponibile fino al 20 marzo 2017. Località in campagna a 3 km da Castelfiorentino ( Firenze)'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mai stata contattata. di nuovo disponibile da settembre.
