### ISSUE TITLE
Offresi alloggio per tre persone a Chiusi (Si)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1698]
<pre><yamldata>tel: '00000'
email: 
descrizione: 'metto a disposizione 3 posti letto in un appartamento a Chiusi (SI) confine con l''Umbria, a circa 2 ore dalle zona colpite dal Sisma.'
indirizzo: 'Strada Provinciale di Chianciano, Chiusi, SI, Tuscany, 53043, Italia'
lat: '43.017167'
lon: '11.9354319'
link: 'https://www.facebook.com/carmine.devivo1?lst=756693526%3A1569347704%3A1484814060'
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by CarmineDeVivo** [comment]
Chiedo che vengano cancellate le mie informazioni personali riportate in questo annuncio molto vecchio.
Grazie.

**Comment by cristigalas** [comment]
Tel e email cancellati come richiesto.
