### ISSUE TITLE
BISOGNO SOCCORSI A #PennaSantAndrea #Teramo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1781]
<pre><yamldata>tel: '3394907952'
email: candeloro.sabina@gmail.com
cosa: 'BISOGNO SOCCORSI A PENNA SANT''ANDREA (TE)'
descrizione: 'A Penna Sant''Andrea provincia di Teramo sono isolati, senza elettricità da 3 giorni, linee telefoniche fisse isolate e cellulari per lo più fuori uso. Alcune frazioni e contrade (ho notizie certe da fraz. Sant''Andrea)non hanno neppure accesso alle strade principali, causa neve e rami caduti. I mezzi del comune per la rimozione della neve non riescono a liberare i passaggi. Sono in trappola! C''è bisogno di soccorsi attrezzati.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
