### ISSUE TITLE
Offresi camera matrimoniale a Colle Val d'Elsa (Si)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1835]
<pre><yamldata>tel: '3474014376'
email: primodipalo@gmail.com
descrizione: 'Offro una camera matrimoniale in abitazione privata, comoda per 2 adulti con 1/2 bambini, nel comune di Colle Val d''Elsa (Siena)'
indirizzo: 'San Lorenzo, Via Gracco del Secco, Località Le Mosse, Faule, Colle di Val d''Elsa, SI, Tuscany, 53034, Italia'
lat: '43.4215075541024'
lon: '11.112713813781738'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già presente.

**Comment by chiccap** [comment]
nessun contatto, non più disponibile.
