### ISSUE TITLE
Offresi ospitalità a Siena

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1840]
<pre><yamldata>tel: '3336715855'
email: elisa.fantacci@libero.it
descrizione: 'Siamo una giovane coppia pronta ad ospitare in casa nostra chi ha bisogno. É una camera matrimoniale a 5km da Siena'
indirizzo: 'Via Fabrizio De Andrè, Ponte a Bozzone, SI, Tuscany, 53019, Italia'
lat: '43.3500531'
lon: '11.3726739'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non più disponibile.
