### ISSUE TITLE
Offro casa per 4-5 persone in provincia di Grosseto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1843]
<pre><yamldata>tel: '333 4227935'
email: maria.tecchi@fastwebnet
descrizione: 'offro gratuitamente fino ad emergenza , casa vacanza in maremma, comune di castiglione della pescaia/grosseto - casa per famiglia di 4/5 persone anche con aziani o bambini piccoli ( c''e un piano terra abitabile) un ettaro di terreno intorno adibito ad uliveto. possibilita di accogliere animali. la casa si trova in aperta campagna a circa 15 km da grosseto. possibilità di usare una autovettura gia in zona che mettiamo a disposizione. telefono e internet. persone di famiglia in zona . riscaldamento.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: 'http://i.imgur.com/ktQ23el.jpg'
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuno ha accolto l'offerta, non più disponibile.
