### ISSUE TITLE
#LAQUILA Servono aiuto e beni alla scuola Mazzini, ora centro di accoglienza

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1844]
<pre><yamldata>tel: ''
email: ''
cosa: 'Assistenza alla popolazione presso la scuola Mazzini #LAQUILA'
descrizione: 'Dall''I.C. Mazzini-Patini dell''Aquila: Assistenza alla popolazione presso la scuola Mazzini. Palestra, spogliatoi, bagni e corridoi messi a disposizione per i cittadini. Ieri notte 200 ospiti, per questa notte già prenotati in 150. Molti sono rimasti anche il giorno. La nostra scuola è gestita dalla Croce Rossa Italiana con l''ausilio dell''Esercito. Chi vuole dare un contributo può portare rotoloni, carta igienica e sapone liquido.'
indirizzo: 'Piazza Duomo, Pettino, L''Aquila, AQ, Abruzzo, 67100, Italia'
lat: '42.3488992'
lon: '13.3981375'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Action Aid Aquila via Twitter ci comunica che le scuole sono tornate ad essere scuole. Chiudo.
