### ISSUE TITLE
Da Bologna offresi roulotte con 4 posti letto e riscaldamento a gas

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1845]
<pre><yamldata>tel: ''
email: ''
cosa: 'Roulotte #Bologna'
descrizione: 'A Bologna ho una roulotte con riscaldamento a gas incluso, 4 letti, cucina e bagno. La metto gratis a totale disposizione di chi ne avesse necessità nelle zone terremotate a tempo indefinito. Necessita di essere prelevata perché io mi trovo ora in Puglia. Chi fosse interessato mi contatti anche in privato.'
indirizzo: 'Piazza Maggiore, Santo Stefano, Bologna, BO, Emilia-Romagna, 40121-40141, Italia'
lat: '44.4936714'
lon: '11.3430347'
link: 'https://www.facebook.com/andrea.cimino2/posts/10207823202644184'
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Come risulta da un commento del 21 gennaio in calce al post su Fb, la roulotte è stata presa da un'associazione di Norcia. Chiudo.
