### ISSUE TITLE
Alloggio e stallo animali #Velletri

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1847]
<pre><yamldata>tel: '3478153378'
email: ''
cosa: 'Alloggio e stallo animali #Velletri'
descrizione: 'Ho un terreno a Velletri ( Rm ) di 16mila mq. a pascolo e uliveto con una casa , la offro per stallo per i vostri animali e per voi, non ho stalle per i vostri animali per proteggerli dal freddo e dalla pioggia ma almeno non c''è la neve , per info 3478153378.'
indirizzo: 'Piazza Ottaviano Augusto, Velletri, RM, Lazio, 00049, Italia'
lat: '41.6867015'
lon: '12.7770433'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
