### ISSUE TITLE
Stalle per animali

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1848]
<pre><yamldata>tel: '3396498145'
email: ''
cosa: 'Stalle per animali'
descrizione: 'Si cercano stalle e adozioni per portare via gli animali dalle zone terremotate e invase dalla neve, contatto Bencini Paola 3396498145'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
