### ISSUE TITLE
Camper per Continuità Assistenziale #Cascia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1850]
<pre><yamldata>tel: '3383202296'
email: ''
cosa: 'Camper per Continuità Assistenziale #Cascia'
descrizione: 'Dopo le ultime forti scosse del 18 gennaio si richiede un camper per poter garantire un adeguato servizio di continuità assistenziale (ex guardia medica) nella sede di Cascia. Sarebbe opportuno per poter permettere al personale medico di poter svolgere il proprio lavoro in tranquillità e lavorare serenamente dal punto di vista nervoso. Contattare il dott. Cariani.'
indirizzo: 'Largo Monsignor Antonio Elemosina, Cascia, PG, UMB, 06043, Italia'
lat: '42.7170082'
lon: '13.0135022'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Chiudo: http://terremotocentroitalia.info/issues/2623/
