### ISSUE TITLE
Tende e Roulottes

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#186]
<pre><yamldata>tel: ''
email: ''
cosa: 'Tende e Roulottes'
descrizione: 'In questo momento alle famiglie colpite nella zona del sisma, agli allevatori e alla gente di cavalli servono tende e roulottes: vi preghiamo, se ne aveste una che potete mettere a disposizione, di farcelo sapere.'
indirizzo: ''
lat: 42.63289
lon: 13.28937
link: 'http://www.cavallomagazine.it/amatrice-servono-roulottes-per-stare-vicino-a-case-e-cavalli-1.2460099'
immagine: ''
data: 13/09/2016
</yamldata></pre>

**Comment by Manfro** [comment]
Georiferito.
