### ISSUE TITLE
Posto per due cani #Montegranaro

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1899]
<pre><yamldata>tel: '3397377884'
email: silviagirotti@hotmail.it
cosa: 'Posto per due cani'
descrizione: 'Metto a disposizione due posti per cani in un allevamento a Montegranaro'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
