### ISSUE TITLE
Alloggio disponibile per terre

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1900]
<pre><yamldata>tel: '3334822897'
email: ''
descrizione: 'Alloggio disponibile per terremotati. Chiamare Angela CRISTOFARI al numero indicato.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non c'è luogo.
