### ISSUE TITLE
PER SALVARE GLI ANIMALI

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1902]
<pre><yamldata>tel: '3396498149'
email: ''
cosa: 'PER SALVARE GLI ANIMALI'
descrizione: 'Chiamare PAOLA BENCINI al 3396498149 per provvedere agli animali in difficoltà sotto la neve'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
