### ISSUE TITLE
VALLE CASTELLANA (TERAMO)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1903]
<pre><yamldata>tel: ''
email: ''
cosa: 'VALLE CASTELLANA (TERAMO)'
descrizione: 'Il comune di VALLE CASTELLANA in provincia di TERAMO è in difficoltà. Aiuti urgenti.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non c'è nessun riferimento. Chiudo.
