### ISSUE TITLE
Offro alloggio per due persone

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1905]
<pre><yamldata>tel: '0000'
email:
descrizione: 'Offro alloggio per due persone. Chiusi (Siena)'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by CarmineDeVivo** [comment]
chiedo che vengano cancellate le mie informazioni personali riportate in questo annuncio molto vecchio

> (https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/1905) `

**Comment by cristigalas** [comment]
Cancellati nome, email e telefono dalla segnalazione su richiesta dell’utente.
