### ISSUE TITLE
VictoriaI have a bedroom and couch that sleeps 3 with all accommodations free everything included

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1912]
<pre><yamldata>nome: 'VictoriaI have a bedroom and couch that sleeps 3 with all accommodations free everything included'
tel: '393280247093'
email: tinkar2@aol.com
descrizione: 'I have a 2 bedroom all inclusive free bagno garden come let me help in bardano can care give'
indirizzo: ''
lat: ''
lon: ''
link: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già inserito
