### ISSUE TITLE
OFFRESI COPERTE, CIBO UMIDO E SECCO PER CANI E GATTI, CUCCE

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1914]
<pre><yamldata>tel: '3457733132'
email: blackangek76@gmail.com
cosa: 'OFFRESI COPERTE, CIBO UMIDO E SECCO PER CANI E GATTI, CUCCE'
descrizione: 'Siamo un canile in provincia di Torino: grazie alla generosità riscontrata in un nostro recente momento di bisogno, ora ci troviamo nelle condizioni di poter aiutare chi è più in difficoltà di noi. Possiamo far pervenire cibo, coperte e cucce. L''unica nostra difficoltà è il non poter spedire utilizzando un corriere in quanto non riusciremmo ad imballare tutto affinché ciò sia fattibile. La soluzione sarebbe trovare un punto raggiungibile, con viaggio andata e ritorno giornaliero, da furgone da noi noleggiato.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già inserita.
