### ISSUE TITLE
Offresi monolocale a #Savona

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1916]
<pre><yamldata>tel: '3355651812'
email: lorenzo.valenza@gmail.com
descrizione: 'Offro monolocale sito in Savona per coppia + eventuale bambino piccolo per qualche giorno.'
indirizzo: 'Via Turati, Albisola Capo, Albisola Superiore, SV, Liguria, 17011, Italia'
lat: '44.3381826'
lon: '8.5098994'
link: ''
immagine: 'http://i.imgur.com/JjJfJSd.jpg'
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta, non disponibile.
