### ISSUE TITLE
Offro a famiglia terremotata c

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1923]
<pre><yamldata>tel: '3398108879'
email: gandini.monia@yahoo.it
descrizione: 'Offro a famiglia terremotata camera matrimoniale + due letti per bambini/ragazzi in convivenza con noi che siamo in 4 iin provincia di Alessandria, piccola cittadina Ovada (vicino a genova) Vitto compreso!'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già inserito
