### ISSUE TITLE
Casa singola #Trentino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1924]
<pre><yamldata>tel: '3283333205'
email: cristianpovo@gmail.com
descrizione: 'in Trentino casa singola molto grande, libera, può ospitare anche due nuclei famigliari un pò lontana ma è sicuramente in grado di offrire tranquillità'
indirizzo: 'Via Parotto, Fracena, Castel Ivano, Comunità Valsugana e Tesino, TN, Trentino-Alto Adige, 38059, Italia'
lat: '46.05587080687053'
lon: '11.53558015823364'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessun contatto, non più disponibile.
