### ISSUE TITLE
Offresi appartamento a #Milano

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1937]
<pre><yamldata>tel: 'RIMOSSO SU RICHIESTA'
email: RIMOSSO SU RICHIESTA
descrizione: 'Metto a disposizione ovviamente gratuita appartamento molto confortevole a Milano centro con tre camere da letto (per un totale di 5 posti letto), corredato di tutto e con buon wifi, fino all''8 febbraio (e se riesco ad organizzarmi anche oltre).'
indirizzo: 'RIMOSSO SU RICHIESTA'
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
mai stata contattata, appartamento non più disponibile.
