### ISSUE TITLE
Coppia di Anziani intrappolata (23 ore fa) a Contrada Parlatina n1 Atri

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1940]
<pre><yamldata>tel: 333/4388415
email: ''
cosa: 'Coppia di Anziani intrappolata (23 ore fa) a Contrada Parlatina n1 Atri'
descrizione: 'AIUTO AIUTO AIUTO emergenza CONTRADA PARLATINA n1 ATRI COPPIA DI ANZIANI DI 74ANNI intrappolati in casa da tre giorni senza luce hanno bisogno di medicinali unico contatto l''ho avuto oggi alle ore 15:00 (scritto 23 ore fa) telefono 333/4388415 Alessandro Pepe chiedo aiuto urgente!!!'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Risolto.
