### ISSUE TITLE
A Colle Val d'Elsa (Siena) off

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1944]
<pre><yamldata>tel: '3474014376'
email: primodipalo@gmail.com
descrizione: 'A Colle Val d''Elsa (Siena) offro camera matrimoniale in abitazione privata, comoda per famiglia con 1/2 bambini piccoli.'
indirizzo: 'Via Gracco del Secco, Località Le Mosse, Il Poggino, Colle di Val d''Elsa, SI, Tuscany, 53034, Italia'
lat: '43.4208014'
lon: '11.1152978'
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
