### ISSUE TITLE
Offro camera matrimoniale con culla in provincia di Ancona

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1953]
<pre><yamldata>tel: '3382454845'
email: toderi.francesca@gmail.com
cosa: 'Offro camera marche'
descrizione: 'Offro una camera con possibilità di 2 letti ed eventuale culla per bambino. Regione Marche, località Castelleone di suasa provincia di Ancona'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
