### ISSUE TITLE
Metto a disposizione bella tav

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1961]
<pre><yamldata>tel: ''
email: ''
descrizione: 'Metto a disposizione bella taverna in provincia di Milano con posto letto in villetta a schiera, adatta a una persona,per il tempo necessario a superare le grandi difficolta'' causate dal sisma e dalla neve. Con tutto il cuore!!'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
