### ISSUE TITLE
BISOGNO SOCCORSI A #PENNA SANT'ANDREA (TE)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1977]
<pre><yamldata>tel: '3394907952'
email: candeloro.sabina@gmail.com
cosa: 'BISOGNO SOCCORSI A PENNA SANT''ANDREA (TE)'
descrizione: 'A Penna Sant''Andrea (TE) sono ancora isolati e senza corrente elettrica. Alcune contrade (in particolare fraz. Sant''Andrea) non sono state raggiunte nenache con i mezzi che pare siano arrivati dal Trentino. Ho notizie frammentarie ma la situazione è drammatica.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://m.facebook.com/story.php?story_fbid=10209724312398384&id=1047753465'
immagine: 'http://i.imgur.com/4e3C49m.jpg'
data: 19/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
