### ISSUE TITLE
Disponibilità di alloggi per 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1993]
<pre><yamldata>tel: '3345045769'
email: rotru67@libero.it
descrizione: 'Disponibilità di alloggi per famiglie delle zone in emergenza, il mio paese si trova in Calabria prov. di Catanzaro'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Troppo vago. Chiudo.
