### ISSUE TITLE
Offro miniappartamento #Tarquinia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#1999]
<pre><yamldata>tel: '3403129688'
email: angela.costantini@gmail.com
descrizione: 'Offro miniappartamento (camera matrimoniale + divano letto a una piazza) a persone autosufficienti e con auto propria. L’alloggio si trova in prossimità di Tarquinia (VT) e sarà disponibile per tutto il mese di febbraio. Scrivetemi o telefonatemi prima della fine del mese. Grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mai stata contattata, non più disponibile.
