### ISSUE TITLE
Offro ad Ancona appartamento

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2001]
<pre><yamldata>tel: '3388427028'
email: popi69@libero.it
descrizione: 'Offro ad Ancona appartamento con due camere.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mai stato contattato. Non più disponibile.
