### ISSUE TITLE
Offro appartamento in provincia di Siena

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2011]
<pre><yamldata>tel: '3470769190'
email: cosci3@unisi.it
descrizione: 'Offro alloggio in appartamento indipendente e dotato di tutti i confort con 4/5 posti letto a Monticiano (Siena). Appartamento nel centro del paese con servizi comodi, una rampa di scale per salire.'
indirizzo: 'Via Giuseppe Mazzini, Podere Orbano, Monticiano, SI, Tuscany, Italia'
lat: '43.1375172'
lon: '11.1786595'
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Doppia e non più disponibile.
