### ISSUE TITLE
La mia famiglia mette a dispos

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2017]
<pre><yamldata>tel: 346/8127207
email: cristina.delbuono@gmail.com
descrizione: 'La mia famiglia mette a disposizione 4 posti letto ( 2 adulti + 2 bambini ) per il periodo di emergenza neve e/o per mitigare lo stress. Abbiamo i un bambino di 7 anni. La casa è grande e può accogliere anche un piccolo animale domestico.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: 'http://i.imgur.com/EPS0sDX.jpg'
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non c'è luogo.
