### ISSUE TITLE
Offresi CAMPER in comodato d'uso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2023]
<pre><yamldata>tel: ''
email: ''
cosa: 'CAMPER in comodato d''uso'
descrizione: 'OFFRO IN COMODATO D''USO UN CAMPER X 4 PERSONE x due adulti e due bambini, ha tutto il comfort. Anche il riscaldamento, sono a disposizione'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/pcampoli1/posts/10206660981801862'
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Donato a una famiglia con una bambina.
