### ISSUE TITLE
Offro due posti letto #Milano

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2033]
<pre><yamldata>tel: ''
email: stunchia@libero.it
descrizione: 'Offro due posti letto a casa insieme a noi per questo periodo di emergenza invernale. Vorremmo dare preferenza a una coppia di anziani o a una mamma con bambino.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.google.it/maps/place/Piazzale+Dateo,+20129+Milano/@45.4682629,9.2143566,17z/data=!3m1!4b1!4m5!3m4!1s0x4786c69100568edf:0xcd42423bf1b24747!8m2!3d45.4682592!4d9.2165453'
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non ha avuto riscontro e al momento non ha più la disponibilità.
