### ISSUE TITLE
Offro una stanza con due posti #Livorno

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2035]
<pre><yamldata>tel: 328-1135636
email: marco.cavallini9@virgilio.it
descrizione: 'Offro una stanza con due posti letto in casa grande a Livorno centro.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mai stato contattato, non più disponibile.
