### ISSUE TITLE
Offro appartamento a #Monticiano (SI)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2037]
<pre><yamldata>tel: '3470769190'
email: cosci3@unisi.it
descrizione: 'Offro appartamento a Monticiano (Siena) 4-5 posti letto, nel centro del paese vicino ai servizi, a chi ne avesse bisogno. Completamente indipendente, dotato di tutti i comfort, disponibile subito.'
indirizzo: 'Via Giuseppe Mazzini, Podere Orbano, Monticiano, SI, Tuscany, Italia'
lat: '43.1375172'
lon: '11.1786595'
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Copio risposta: "la mia offerta non è stata mai accolta da nessuno.
Solo recentemente, qualche settimana fa, mi ha contattato una signora con accento straniero che cercava una casa in affitto.
Io le ho spiegato che non era una casa in affitto, si tratta della mia casa di famiglia ed era stata messa a disposizione da me  per un breve periodo come prima accoglienza."
