### ISSUE TITLE
Piccola dependance con tre pos

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2039]
<pre><yamldata>tel: '3886014559'
email: alessandra.isaia@attalpeadria.it
descrizione: 'Piccola dependance con tre posti letto. Autonoma. Giardino comune alla nostra abitazione con cani, segnalo in caso di allergie'
indirizzo: 'Via Fornalis, Bivio Romanutti, Cividale del Friuli, UD, Friuli Venezia Giulia, 33043, Italia'
lat: '46.0541164'
lon: '13.4608727'
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
