### ISSUE TITLE
A Cividale del Friuli offriamo dependance con tre posti letto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2042]
<pre><yamldata>tel: '3886014559'
email: alessandra.isaia@attalpeadria.it
descrizione: 'Cividale del Friuli offro piccola dependance tre posti letto autonoma'
indirizzo: 'Via Fornalis, Bivio Romanutti, Cividale del Friuli, UD, Friuli Venezia Giulia, 33043, Italia'
lat: '46.0541164'
lon: '13.4608727'
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta, non più disponibile.
