### ISSUE TITLE
HOTEL SALGETTI a MEZZANO ( Tre

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2043]
<pre><yamldata>tel: '043967172'
email: salgetti@libero.it
descrizione: 'HOTEL SALGETTI a MEZZANO ( Trentino); fino a meta Febbraio offriamo alloggio GRATUITO alle famiglie colpite da terremoto ed emergenza neve.'
indirizzo: 'Via Roma, Melai, Mezzano, Comunità di Primiero, TN, Trentino-Alto Adige, 38054, Italia'
lat: '46.1566846'
lon: '11.8147538460194'
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
