### ISSUE TITLE
Offresi podere in Toscana con 6 appartamenti, 26 ettari a pascolo, due stalle

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2047]
<pre><yamldata>tel: ''
email: roberta.angheben@gmail.com
descrizione: 'Desidero mettere a disposizione dei terremotati il mio podere in Toscana, ex agriturismo, comune Roccalbegna, Triana, tra Saturnia e Monte Amiata. 26 ettari senza neve al momento , altitudine dai 450 e raggiunge i 640. Solo 4 ettari a olivi il resto pascolo.. Sorgente da riattare. Si chiama Pian d''acquaio e lo potete vedere in google map. Magari sotto "agriturismo Pian d''acquaio". 700 mq. suddivisi in 6 appartamenti, acqua e luce da attaccare, caldaie rotte, caminetto in tutti gli appartamenti, però gli appartamenti non sono arredati. Stalle poca roba, una ex stalla sui 50 mq, un''altra ex stalla mq. 25, pollaio. Sto contattando i confinanti per sapere se ci sono stalle o capannoni coperti liberi.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Ci è stato chiesto di togliere numero telefonico e chiudere offerta.
