### ISSUE TITLE
Buongiorno a tutti, vi contatt

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2048]
<pre><yamldata>tel: '3332644919'
email: p.panie@alice.it
descrizione: 'Buongiorno a tutti, vi contatto da un piccolo paese in provincia di Torino. Sto cercando di creare un gruppo di cittadini attivi che in breve tempo riesca ad attivarsi per raccogliere i fondi necessari a livello territoriale per garantire l''affitto di uno o due appartamenti per otto persone. E'' tutto da fare ma credo nella buona volontà e nella velocità di raccolta fondi. Ciò che desidererei sapere da voi è se ci sono persone che almeno per 6 mesi sarebbero disposte a spostarsi così lontano.... anche un gruppo di anziani autosufficienti ai quali garantiremo un''assistenza. Attendo vs riscontro e vi ringrazio. Paola'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviata email perchè la proposta appare un po' 'nebulosa' e suggerito di fare una semplice raccolta fondi da donare a associazione o comitato in loco. Chiudo.
