### ISSUE TITLE
Mettiamo a disposizione la nos

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2050]
<pre><yamldata>tel: '3934682998'
email: ritamello@libero.it
descrizione: 'Mettiamo a disposizione la nostra casa ad una famiglia , garantendo una camera matrimoniale , una camerina e il bagno all''interno del nostro appartamento.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già presente
