### ISSUE TITLE
Offresi Alloggio a #Grosseto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2053]
<pre><yamldata>tel: '3934682998'
email: ritamello@libero.it
descrizione: 'La nostra casa è a disposizione per accogliere una famiglia tra quante stanno vivendo la tragedia del gelo e del terremoto: offriamo una camera matrimoniale, una camerina e un bagno all''interno del nostro appartamento. Siamo a Follonica in provincia di Grosseto.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non più disponibile.
