### ISSUE TITLE
Offresi alloggio in agriturismo e stallo per 20 ovini o 3-4 asini in prov. Reggio Emilia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2064]
<pre><yamldata>tel: 0522/843667
email: laborgaccia@gmail.com
descrizione: 'siamo un piccolo agriturismo situato a Baiso in provincia di Reggio Emilia. Ci rendiamo conto di essere un po'' distanti ma se qualcuno ne avesse urgenza mettiamo a disposizione per circa 2 mesi, 2 appartamenti da 5/6 posti l''uno e dimora nelle nostre stalle per circa una ventina di animali ( ovini e caprini oppure 3/4 asini)'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.laborgaccia.it'
immagine: 'http://i.imgur.com/XDwO6gN.jpg'
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non più disponibile.
