### ISSUE TITLE
Offresi postazioni lavoro a #Pescara zona aeroporto per chi ha uffici danneggiati dal sisma o neve

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2069]
<pre><yamldata>tel: '0854684949'
email: claudio.iezzi@gkollektiv.it
cosa: 'Offresi postazioni lavoro a #Pescara zona aeroporto per chi ha uffici danneggiati dal sisma o neve'
descrizione: 'Per chi ha bisogno di tornare al lavoro e ha uffici inagibili o problemi di elettricità, collegamenti telefonici etc, metto a disposizione il mio ufficio con la possibilità di installare 3/4 postazioni in zona aeroporto Pescara. L’ufficio include: scrivanie/sedie; accesso ad Internet Wi-Fi; tel/fax; stampante; riscaldamento; angolo ristoro e servizi igienici. Chi fosse interessato può contattarmi alla mail claudio.iezzi@gkollektiv.it o ai numeri 0854684949 3289772559.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/gkollektivlab/'
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
