### ISSUE TITLE
Metto a disposizione 4 posti l

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2071]
<pre><yamldata>tel: ''
email: zoetav@hotmail.it
descrizione: 'Metto a disposizione 4 posti letto a Ribolla frazione di Roccastrada provincia di Grosseto'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
già presente.
