### ISSUE TITLE
A #Basciano (TE) servono generatori, turbine e aiuto. Appello del sindaco

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2073]
<pre><yamldata>tel: ''
email: ''
cosa: 'Situazione a Basciano'
descrizione: 'Appello del sindaco di Basciano: abbiamo cittadini malati che devono fare la dialisi. Servono turbine, generatori elettrici, mezzi idonei ed assistenza, visto che sono quattro giorni che l''energia elettrica non è disponibile su tutto il territorio comunale, ma non è arrivato nulla. L''energia elettrica fornita attraverso i generatori ora è di vitale importanza. Sulla provinciale da oggi si transita su una sola corsia in mezzo a muri di neve alti 4 metri e rami di alberi abbattuti dal peso della neve. Le comunicazioni attraverso i cellulari è quasi impossibile ed abbiamo difficoltà anche a contattare i due operatori comunali a lavoro sul mezzo, per coordinarli. (Testo completo dell''appello del sindaco al link).'
indirizzo: ''
lat: '42.5963900'
lon: '13.7356100'
link: 'http://www.iduepunti.it/19_gennaio_2017/la-disperazione-del-sindaco-di-basciano-abbiamo-cittadini-malati-che-devono-fare-la-'
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta.
