### ISSUE TITLE
Sei posti letto disponibili a L'Aquila

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2075]
<pre><yamldata>tel: 'xxxxxxx'
email: xxxxxx
descrizione: 'casa mia con sei letti disponibili, in L''Aquila'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta pervenuta, non più disponibile.

**Comment by cristigalas** [comment]
Richiesto via email di togliere telefono e indirizzo mail.
