### ISSUE TITLE
Disponibilità di 4 posti letto a Taranto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2083]
<pre><yamldata>tel: '3930552149'
email: francesca.bungaro@gmail.com
descrizione: 'Ho disponibilità di 4 posti letto sono a taranto attendo una risposta grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by favoeva** [comment]
chiudo perché doppia
