### ISSUE TITLE
Offo alloggio per una DECINA di persone

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2088]
<pre><yamldata>tel: '3282154720'
email: chiara-1992@hotmail.it
cosa: 'Offo alloggio per una DECINA di persone'
descrizione: 'Mettiamo a disposizione gli appartamenti della nostra agenzia immobiliare per chi ha bisogno. Ci troviamo in Toscana a Marina di Massa (MS) e abbiamo la possibilita di offrire alloggio a 10 persone. Disponibilita immediata senza limiti per la durata dell''alloggio. Massima solidarieta e disponibilita ad aiutare.'
indirizzo: 'Via San Leonardo, Massa, MS, Tuscany, 54037, Italia'
lat: '44.0094968'
lon: '10.1019306'
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by favoeva** [comment]
chiudo perché doppia
