### ISSUE TITLE
Condividiamo la nostra abitazione in provincia di Treviso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2090]
<pre><yamldata>tel: '3404960668'
email: chiara.pazzaia@gmail.com
descrizione: 'Condividiamo la nostra abitazione con chi ne avesse bisogno. Siamo in provincia di Treviso.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by favoeva** [comment]
chiusa perché doppia
