### ISSUE TITLE
a Trento offro posto letto in camera privata a signora (anche con animale) 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2093]
<pre><yamldata>tel: ''
email:
descrizione: 'Offro posto letto in camera privata a signora (anche con animale). Si dovrà condividere bagno con me e mia figlia. A Trento.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta ricevuta, ancora disponibile.

**Comment by cristigalas** [comment]
La signora chiede via email di togliere i suoi recapiti tel e email e di chiudere la segnalazione.
