### ISSUE TITLE
Ospitalità a Caserta per famiglia con bimbi 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2099]
<pre><yamldata>tel: '3291516864'
email: legalizep2p@hotmail.it
descrizione: 'Segnalo la disponibilità della mia famiglia ad ospitare famiglia terremotata, possibilmente con bimbi in modo da poterli iscrivere a scuola e dare continuità scolastica. Possibilità di piccoli lavoretti per i genitori. Posso ospitare per tutto l''inverno o fino a fine anno scolastico. Vivo in provincia di Caserta, in condominio, max 4 posti letto (2 adulti + 2 bambini). Sebbene meritevoli, al momento non possiamo accettare animali.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non è mai stato contattato. Non più disponibile.
