### ISSUE TITLE
Ospitalità a Firenze 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2102]
<pre><yamldata>tel: '3334958973'
email: isa.cia@lycos.com
descrizione: 'ho un appartamento con due camere doppie, e spazio per un altro letto singolo. Due bagni, salottino e cucina. Il giardino condominiale è molto grande, dunque c''è posto anche per i vostri animali. Siamo due famiglie con bambini di 13 anni, 1 anno e 1 mese; abbiamo un cane, alcuni gatti, e qualche porcospino; condividiamo il giardino anche con un B&B. E siamo a Firenze :)'
indirizzo: 'Piazza della Signoria, Quartiere 1, Firenze, Metropolitan City of Florence, Tuscany, 50122, Italia'
lat: '43.7698712'
lon: '11.2555757'
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta, non più disponibile.
