### ISSUE TITLE
Bencini Paola 3396498145

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2105]
<pre><yamldata>titolo: 'Bencini Paola 3396498145'
descrizione: 'Fate girare a manetta, si cercano stalli e adozioni per portare via gli animali dalle zone terremotate e invase dalla neve,contatto Bencini Paola 3396498145....fate copia e incolla,x favore'
link: ''
data: 20/01/2017
</yamldata></pre>

**Comment by favoeva** [comment]
ho verificato profilo FB di Paola Bencini e le ho mandato link a nostre issue offerte stalli

**Comment by cristigalas** [comment]
È da due giorni che cerchiamo di contattarla inutilmente e il suo appello continua a girare "a vuoto" :(
