### ISSUE TITLE
Metto a disposizione appartamento per una famiglia a Lido di Fermo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2116]
<pre><yamldata>tel: '3478285302'
email: info@easytrad.it
descrizione: 'Metto a disposizione appartamento per 3-4 persone (ideale sarebbe genitori con 1 o 2 bambini) a Lido di Fermo (FM).'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Contattata da una persona ma le esigenze purtroppo non corrispondevano. Non più disponibile.
