### ISSUE TITLE
possiamo ospitare una famiglia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2123]
<pre><yamldata>tel: '3342300764'
email: leonardo.lucetti@gmail.com
descrizione: 'possiamo ospitare una famiglia o bambini'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non dice dove.
