### ISSUE TITLE
Dettagli mappa

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2128]
<pre><yamldata>tel: '3381749435'
email: rosicardi@gmail.com
cosa: 'Dettagli mappa'
descrizione: 'Ho inserito il mio alloggio che intendo mettere a disposizione dei terremotati . Sulla mappa il mio paese, Suvereto (LI) non risulta.Si trova a 7 Km da campiglia marittima (LI) 25 Km da Piombino'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risposto per email. Chiudo.
