### ISSUE TITLE
offresi alloggio per 2/3 perso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2136]
<pre><yamldata>tel: '3343173285'
email: dina.desantis@email.it
descrizione: 'offresi alloggio per 2/3 persone a Udine nella mia abitazione. Dina'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
