### ISSUE TITLE
Disponibile appartamento per 3

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2144]
<pre><yamldata>tel: 347-8285302
email: pamelabri@gmail.com
descrizione: 'Disponibile appartamento per 3-4 persone (ideale genitori con 1-2 bambini) a Lido di Fermo - Provincia di Fermo. Completo di tutto. Disponibile gratuitamente per superare emergenza terremoto e neve.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
