### ISSUE TITLE
offro appartamento a marostica

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2147]
<pre><yamldata>tel: '346 8555 368'
email: aeighenes1@gmail.com
descrizione: 'offro appartamento a marostica per famiglia di 4 persone con due camere bagno e cucina'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by Manfro** [comment]
Doppia Issue, mantenuta quella piu completa #2149
