### ISSUE TITLE
Offro alloggio in #Toscana presso Quarrata (Pistoia)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2159]
<pre><yamldata>tel: '3385248672'
email: carla@paroladicopy.it
descrizione: 'Offro alloggio in Toscana, Quarrata (PT) in porzione di corte perfettamente ristrutturata. Ho una camera disponibile con letto matrimoniale. Ideale per mamma con bambini. Coppia di anziani. Calda e confortevole.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta pervenuta,non più disponibile.
