### ISSUE TITLE
A Macerata raccolta di cibo, cucce e coperte per canili colpiti da sisma e gelo. Si cercano anche volontari

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2165]
<pre><yamldata>tel: '3277169217 - 3494356442'
email: ''
cosa: 'A Macerata raccolta di cibo, cucce e coperte per canili colpiti da sisma e gelo. Si cercano anche volontari'
descrizione: 'In collaborazione con Francesca del Mago Ranch (tel. 3277169217) stiamo organizzando un punto di raccolta presso il mio negozio "Amici Miei" a MACERATA, C.so Cairoli 8 per rifornire i canili di CAMERINO, MORROVALLE, JESI ed aiutare i tanti privati delle zone colpite dal sisma e dal gelo. Si cercano anche volontari per aiutare in loco. Potete contattarmi al 3494356442 o passare direttamente in negozio. Hanno bisogno di cibo, coperte, asciugamani, cucce e quant''altro. Se intendete fare contributi in denaro sarà mia premura acquistare e consegnare crocchette ai volontari che passeranno periodicamente per il ritiro e la consegna. Grazie.'
indirizzo: 'Piazza della Libertà, Centro Storico, Macerata, MC, Marche, 62100, Italia'
lat: '43.3007275'
lon: '13.4535897'
link: 'https://www.facebook.com/sonia.castellani.16/posts/1335454663185181'
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
