### ISSUE TITLE
Counselor offre supporto per superare difficoltà emotive causa terremoto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2168]
<pre><yamldata>tel: '3482446672'
email: cristina.rubegni@gmail.com
cosa: ascolto
descrizione: 'Sono una counselor professionista, offro gratuitamente il mio supporto per aiutare e ascoltare le persone con difficoltà emotive legate al terremoto. Cristina 3482446672.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Via email Cristina Rubegni ci ha chiesto di chiudere la segnalazione perchè ha trovato il modo di rendersi utile attraversoun'associazione.
