### ISSUE TITLE
**URGENTE** Civitella isolata senza elettricità nè telefoni

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2173]
<pre><yamldata>tel: 'Sindaco Cristina Di Pietro 3286827420'
email: ''
cosa: '**URGENTE** Civitella isolata senza elettricità nè telefoni'
descrizione: 'Nel comprensorio di Civitella del Tronto è caduta tantissima neve con accumuli fino a DUE METRI. E'' totalmente assente la corrente elettrica da 5 giorni, non ci sono riscaldamenti, acqua e le linee telefoniche fisse. I cellulari vanno a singhiozzo quando è possibile ricaricarli altrove. La situazione igienico-sanitaria è al collasso. E'' indispensabile l''intervento di mezzi idonei per la rimozione della neve. Moltissime frazioni sono ancora isolate. Per aiuti contattare il sindaco Cristina Di Pietro 3286827420'
indirizzo: 'Viale della Battaglia di Bosco Martese, Civitella del Tronto, TE, Abruzzo, 64016, Italy'
lat: '42.7725608'
lon: '13.665180439868'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1832212263713023/?match=dGVycmVtb3RvY2VudHJvaXRhbGlhLGNpdml0ZWxsYQ%3D%3D'
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Risolta. Ho parlato con ristoratore Daniele che mi ha detto che Enel, dopo nostra richiesta, è intervenuta ripristinando in gran parte del paese l'energia elettrica e sono anche riusciti a spalare gran parte della neve. Rimangono ancora dei problemi nelle frazioni (vedi anche #2243).
