### ISSUE TITLE
A #Visso allevatore ha bisogno di mangime (fioccato e gran turco) 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2175]
<pre><yamldata>tel: '3662535053 Marco Sebastiani'
email: ''
cosa: 'Mangime per allevatore a Visso'
descrizione: 'A Visso, Villa Sant''Antonio, all''allevatore Marco Sebastiani servono con urgenza fioccato e gran turco per gli animali. Al link articolo con la sua storia.'
indirizzo: 'Strada Provinciale 209 Valnerina, Visso, MC, Marche, 62039, Italy'
lat: '42.9400077'
lon: '13.0819231178949'
link: 'http://www.ilrestodelcarlino.it/macerata/cronaca/terremoto-oggi-allevatore-miracolato-1.2831489'
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Girata richiesta ad Antonello, commerciante di mangimi di Assisi (negozio si chiama Linea Verde) che ci ha contatto via Twitter https://twitter.com/antonello39/status/823224040554987520 Lui e il suo socio sono in contatto con due associazioni locali che da due mesi usano il loro negozio per raccogliere donazioni di mangime e portarlo agli allevatori terremotati. Ci farà sapere se e quando possono consegnare.

**Comment by cristigalas** [comment]
Venerdì 27 gennaio dovrebbero consegnare fieno e mangimi. Attendiamo conferma prima di chiudere.

**Comment by cristigalas** [comment]
Mangimi consegnati come comunicato da Antonello, commerciante di Assisi, con messaggio diretto su Twitter. Vedi anche qui https://twitter.com/antonello39/status/825068875272355848 Chiudo.
