### ISSUE TITLE
Disponibile appartamento per famiglia a Punta Marina (Ra) fino a maggio

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2177]
<pre><yamldata>tel: '3737084986'
email: cristianacedrini@fastwebnet.it
descrizione: 'Appartamento per famiglia a Punta Marina (Ra) disponibile fino a maggio'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non sono mai stati contattati, non più disponibile.
