### ISSUE TITLE
Raccolta beni del gruppo Io non crollo (Lazio)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2181]
<pre><yamldata>tel: 'Cristian Calabrese 3493646364, Manolo Valeri 328 6722208, Sandro Cinosi 331 8135801'
email: ''
cosa: 'Raccolta beni del gruppo Io non crollo (Lazio)'
descrizione: 'Il Gruppo Io non crollo sta organizzando in Lazio raccolte di beni per popolazioni colpite da sisma ed emergenza neve. Servono in particolare: Fioccato per mucche da latte; Latte in polvere per vitelli; Sale in cubi per mucche, questo per quanto riguada gli allevatori. Per gli abitanti Cibo a lunga conservazione (pasta, olio, ecc); prodotti igienici (dentifricio, saponi intimi, ecc). Non serve abbigliamento e coperte. E poi Tubi da tre quarti coibentati per esterni. I referenti che coordinano le raccolte in tutto il Lazio sono: Cristian Calabrese 3493646364, Manolo Valeri 328 6722208, Sandro Cinosi 331 8135801 (Magazzino). Il nostro centro raccolta più vicino possibile ad Amatrice sarà a Poggio Mirteto (uscita fiano romano). In più a Poggio mirteto ci sarà il gruppo dei fuoristrada che ci aiuterà a raggiungere le zone più impervie anche in condizioni climatiche impossibili. CHIUNQUE VOGLIA RACCOGLIERE deve contattare i seguenti responsabili.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/184616618663358/permalink/237617206696632/'
immagine: ''
data: 21/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
