### ISSUE TITLE
Offresi ospitalità ad una famiglia in provincia di Cuneo 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2192]
<pre><yamldata>tel: '3884697263'
email: k4tiu5h4@yahoo.it
cosa: Ospitalità
descrizione: 'Buongiorno siamo una famiglia di 3 persone con animali abitiamo in una casa singola con cortile su 2 piani a Cherasco, abbiamo la possibilità di ospitare una famiglia di 3 persone magari con un bimbo/a piccolo oppure qualche anziano.. de qualcuno fosse disposto a lasciare quel posto anche solo momentaneamente restiamo a disposizione.'
indirizzo: 'SP661, Cherasco, CN, Piemonte, Italia'
lat: '44.6240393'
lon: '7.8871561'
link: ''
immagine: ''
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
