### ISSUE TITLE
Cercasi stalli o adozioni per cani

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2193]
<pre><yamldata>tel: ''
email: ''
cosa: 'Cercasi stalli o adozioni per cani'
descrizione: 'Ciao a tutti, io sono Monica Censon, sono di Firenze. Sono semplicemente una volontaria nè Enci, nè Empi nè tutte quelle cose. Sono una donna che sa guidare i furgoni e ha deciso che ha due braccia e due gambe e devo fare qualcosa. Sono già stata giù a Campobasso, avevamo fatto una raccolta ma principalmente non per portare il mangiare, ma per prendere i cani. Noi bisogna prendere i cani. Sono sotterrati tutti. Sono sotterrati gli esseri umani figuriamoci i cani. Solo che per gli esseri umani ci sono delle Associazioni moolto più grosse. Noi non siamo grosse, noi siamo delle ragazze che hanno deciso di aiutare per quello che possono. Io quello che vi chiedo è per piacere, se avevate intenzione di prendere un cane, di dargli un''adozione o di avere uno stallo con la possibilità che se poi ve ne innamorate lo tenete in casa, io vi prego di contattarmi perché io devo ripartire e voglio riprendere altri cani. Nell''ultimo viaggio fatto ne abbiamo presi 36, non sono tanti, ma è tutto quello che potevamo fare. Sto cercando persone che ci aiutino. Siamo sono sommersi dalla neve. Io ho visto delle cose che hanno graffato gli occh. Non... ho bisogno di aiuto. Ho bisogno di persone che decidano di salvare un cane. Poi ci sarà chi si occuperà di tutti gli uomini, ma io non posso andare giù e prendere gli uomini e portarli su, posso farlo con i cani. é questo il mio motivo per cui chiedo di diffondere questo audio, di aiutarli perché non si possoo lasciarli morire sotto la neve in questa maniera. Non è giusto, non è umano. Io vi ringrazio per tutto quello che potete fare. Il mio numero di telefono è 3313121217... e che... niente... non so più che dirvi... sono veramente disperata. Aiutatemi"'
indirizzo: 'Piazza Gabriele Pepe, Campobasso, CB, MOL, 86100, Italia'
lat: '41.5597935'
lon: '14.6602725'
link: 'http://terremotocentroitalia.info/issues/1657/#comment-3112694397'
immagine: ''
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
La segnalazione non sembra attendibile vedi commento al link.
