### ISSUE TITLE
**URGENTE** Ad #ATRI serve aiuto: case sepolte dalla neve, mancano acqua e corrente da 4 giorni

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2194]
<pre><yamldata>tel: '3358222882 Paolo Castagna'
email: ''
cosa: '**URGENTE** Ad #Atri serve aiuto: case sepolte dalla neve, mancano acqua e corrente da 4 giorni'
descrizione: 'Atri, in provincia di Teramo, è sepolta dalla neve e da 4 giorni mancano acqua e corrente elttrica. Ci sono stati crolli e alcuni abitanti si sono rifugiati presso l''hotel Hermitge perché hanno le case inagibili. Ci sono dei generatori ma non bastano per dare corrente a tutti e il freddo è grande. Servono con urgenza acqua, uomini e mezzi per liberare strade, tetti e case dalla neve, sale a sacchi da spargere, e sopralluoghi VF. Qui per ora non si è visto nessuno se non qualche vigile del fuoco per poco tempo. Stiamo facendo tutto da soli ma non ce la facciamo! Serve subito aiuto! Paolo Castagna'
indirizzo: 'Piazza Duomo, Atri, TE, ABR, 64032, Italia'
lat: '42.5801368'
lon: '13.9764121'
link: ''
immagine: 'http://i.imgur.com/AaonwA6.jpg'
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Oggi ho parlato con Graziano il figlio di Paolo Castagna. La situazione ad Atri rispetto all'energia elettrica è migliorata grazie ad ulteriore intervento Enel. Stamani sono poi arrivati i volontari di Io non crollo che avevamo mobilitato ieri sera. Hanno aiutato a ripulire un po' le strade e hanno portato soccorso agli abitanti, che sono riusciti anche a fornirsi di acqua perché quella ancora manca... insomma si sta normalizzando e ci rinngraziano!
