### ISSUE TITLE
Ad #AcquasantaTerme servono urgentemente motoslitte per raggiungere le frazioni isolate

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2196]
<pre><yamldata>tel: ''
email: christianvarani@gmail.com
cosa: 'Richiesta urgente di possibili motoslitte,anche a noleggio per il Comune di Acquasanta Terme e le sue frazioni'
descrizione: 'Servono urgentemente motoslitte, anche a noleggio, per raggiungere le 56 frazioni di Acquasanta Terme, considerando la loro capacità di percorrere delle strade difficoltose da ripulire rimuovendone la neve, che si è accumulata nei giorni passati e che ancora risulta presente e in grandi quantità. Le motoslitte possono permettere di raggiungere le frazioni anche senza dover ripulire e spalare la neve adeguatamente per le strade interne con dei mezzi adeguati come ad esempio quelli spazzaneve e delle ruspe, che faticano ad arrivare. Vi allego in formato immagine anche un Post che mi è stato inviato in Chat tramite Facebook da una cittadina come referente di tale esigenza, terremotata ed originaria di Acquasanta Terme che si chiama Daniela Camusi.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Daniela Camusi'
immagine: 'http://i.imgur.com/TvPStBG.png'
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che una motoslitta è arrivata proprio domenica dal Nord Italia ed inoltre sono intervenuti quelli della "San Marco", quindi si son potute raggiungere le varie frazioni del comune di Acquasanta Terme che erano ancora isolate. Chiudo.
