### ISSUE TITLE
A #Treia (Mc) cercasi roulotte o camper 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2199]
<pre><yamldata>tel: '3291693360'
email: pelange23@web.de
cosa: 'Roulotte o container'
descrizione: 'Buongiorno, sto cercando un ruolotte o camper (piccolo, ma con i servizi funzionanti) fino a cessare l''emergenza. Ho la mia casa (zona Treia, MC) inagibile da agosto e bivacco da un allogio provisorio all''altro. Chi volesse aiutarmi sarei davvero contenta! Contatto: Petra 3291693369'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Ho chiamato la signora Petra per sentire se ne avesse ancora bisogno e mi ha detto che è in attesa di 3 conferme e in caso mi fa sapere. Ha inserito segnalazione autonomamente sul sito.

**Comment by cristigalas** [comment]
Ok grazie @chiccap!

**Comment by cristigalas** [comment]
Cristina Fustinoni di Caravanisti Solidali ci ha comunicato che sabato 11 febbraio consegneranno la roulotte alla signora di Treia. Vedi qui http://terremotocentroitalia.info/issues/1459/index.html#comment-3084851057
