### ISSUE TITLE
Due box 4x4, cavalli, asini o 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2205]
<pre><yamldata>tel: '3478539800'
email: simosarn@hotmail.it
descrizione: 'Due box 4x4, cavalli, asini o massimo 4 capi ovini o caprini.'
indirizzo: 'Via Marco Spurinas, Blera, Puntoni, Blera, VT, Lazio, 01010, Italia'
lat: '42.27381605'
lon: '12.027516216969'
link: ''
immagine: ''
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
