### ISSUE TITLE
#Visso# Ussita #Cupi - C'è bisogno di cibo e ripari per animali di diversi allevatori

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2206]
<pre><yamldata>tel: 'Contatti nel testo della segnalazione'
email: ''
cosa: 'Visso/Ussita/Cupi - Cibo e ripari per animali di diversi allevatori in zona'
descrizione: 'Diversi allevatori hanno bisogno cibo per gli animali e aiuto con i ripari degli animali che sono al freddo Cibo: fioccato col mais, granturco, fioccato, rulli di sale per le pecore ma NON devono contenere il RAME tra i componenti; e anche crocchette per i cani. 
**Raccogliamo in una segnalazione unica bisogni molto simili di questi allevatori che sono relativamente vicini tra loro**
--Sandra tel 3339965490 azienda il Pastorello di Cupi: servirebbe il fioccato col mais e le crocchette per i cani; le persone hanno ancora qualcosa --  Marco Sebastiani tel 3662535053 Visso, Villa Sant’Antonio serve fioccato e gran turco -- Mario Troiani cell 333 8135311 Visso Ripari per animali -- Giovanni Paris tel 334 7799659 Vallestretta di Ussita Ripari per animali -- Silvia Bonomi tel 3450775741 alleva pecore razza sopravvissana, Ussita. Fioccato e rulli di sale per le pecore ma NON devono contenere il RAME tra i componenti'
indirizzo: 'Ussita, MC, Marche, 62039, Italy'
lat: '42.9437596'
lon: '13.137908'
link: 'https://www.facebook.com/ambra.mattioli1/posts/10210416538082042'
immagine: ''
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Girata richiesta ad Antonello, commerciante di mangimi di Assisi che ci ha contatto via Twitter https://twitter.com/antonello39/status/823224040554987520 Lui e il suo socio sono in contatto con due associazioni locali che da due mesi usano il loro negozio per raccogliere donazioni di mangime e portarlo agli allevatori terremotati. Ci farà sapere se e quando possono consegnare.

**Comment by cristigalas** [comment]
Venerdì 27 gennaio dovrebbero consegnare fieno e mangimi ma non sa ancora se ne hanno per tutti. Ci aggiorna.
