### ISSUE TITLE
FALSI emissari Enel

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2207]
<pre><yamldata>titolo: 'FALSI emissari Enel'
descrizione: 'post di Federica Caucci in pagina di Riccardo Esse 20 gennaio alle ore 18:16. ATTENZIONE zona Cona via Bafile Teramo sono in tre accento napoletano due uomini e una donna cercano insistentemente di entrare per contratto enel. Attenzione e diffondete'
link: 'https://www.facebook.com/federica.caucci/posts/10211770733693871'
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Verificato post ma è secondo me troppo vago, non si capisce se è una notizia di prima mano o un sentito dire... non credo sia da accettare.
