### ISSUE TITLE
Appartamento per famiglia 3-4 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2212]
<pre><yamldata>tel: '3478285302'
email: info@easytrad.it
descrizione: 'Appartamento per famiglia 3-4 persone a Lido di Fermo. Disponibile per superare emergenza terremoto e neve.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
