### ISSUE TITLE
Offro appartamento con 6 posti letto in provincia di Chieti

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2219]
<pre><yamldata>tel: '3335916126'
email: giangiordano.laura@gmail.com
descrizione: 'Offro sistemazione temporanea e assolutamente gratuita,per aiutare queste persone a superare il freddo e i disagi del momento, in appartamento in un paesino della provincia di Chieti,ho 6 posti letto. Contattatemi in privato per i dettagli.Laura'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta, non disponibile.
