### ISSUE TITLE
Offresi 2 appartamenti in prov Livorno con possibilità di ospitare animali anche grandi

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2221]
<pre><yamldata>tel: '3938129961'
email: marcotoni78@gmail.com
descrizione: 'La mia famiglia mette a disposizione 2 appartamenti in villetta bifamiliare in campagna, vicino a Suvereto (LI) con ampia recinzione, adatta per ospitare anche animali domestici anche di grande taglia.Un appartamento dispone di 4 posti letto ed è libero fino al 15-02-17 e l''altro ha max 6 posti letto ed è disponibile fino a primavera.'
indirizzo: 'Via Val di Cornia, San Rocco, Suvereto, LI, Tuscany, 57028, Italia'
lat: '43.061884325836466'
lon: '10.665605664253235'
link: ''
immagine: 'http://i.imgur.com/3jQzMbN.jpg'
data: 23/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mai stato contattato, non più disponibile.
