### ISSUE TITLE
Centri Soi offrono aiuto in emergenza a Macerata, Ascoli e Fermo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2227]
<pre><yamldata>nome: 'SALE OPERATIVE PROTEZIONE CIVILE'
tel: '0733265130'
email: valy1c@alice.it
descrizione: 'Soi macerata si occuopa di tutto quanto concerne la situazione di emergenza e i fabbisogni. Ad esempio hanno procurato la spedizione dal Veneto di 35 balle fieno per un agriturismo a cui è crollato il fienile. Il numero della SOI, in base alla mia esperienza, ha poca visibilità . Per lo meno ho dovuto fare una ricerca per trovarlo. Chi si trova in situazione di emergenza ha difficoltà a cercare in internet. I vigili del fuoco, che sono i primi contatti, non sembrano esserne informati. Nel caso Della agriturismo ci sono anche problemi di comunicazione in quanto i proprietari dell''agriturismo sono di lingua tedesca. Cinzia Galassi contatto valy1c@alice.it Centri SOI anche ad Ascoli e fermo. Sarebbe opportuno dare maggiore visibilità . Grazie per il vostro impegno. Fate un ottimo lavoro'
indirizzo: ''
lat: ''
lon: ''
link: ''
data: 23/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Scusa @chiccap ho tolto l'accettazione perché in realtà nella segnalazione si dice soltanto che i contatti delle sale operative della protezione civile dovrebbero essere maggiormente visibili...
