### ISSUE TITLE
**URGENTE** Contrada villa alzano di fronte al cimitero manca la luce da 7 giorni #Tossicia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2230]
<pre><yamldata>tel: ''
email: 
descrizione: 'Contrada villa alzano di fronte al cimitero (tossicia) manca la luce da 7 giorni, ci sono persone anziane'
indirizzo: 'Contrada villa alzano, tossicia. zona cimitero'
lat: 42.551278
lon: 13.647401
link: ''
immagine: ''
data: 23/01/2017
necessita: ''
accesso: 'Accessibile a fuoristrada'
latStrada: ''
lonStrada: ''
notastrada: ''
</yamldata></pre>

**Comment by provinciateramo** [comment]
Segnalazioni inoltrata all'Enel
