### ISSUE TITLE
#ATRI serve aiuto: case sepolte dalla neve, mancano acqua e corrente da 4 giorni

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2243]
<pre><yamldata>tel: '3358222882'
email: ''
cosa: '#ATRI serve aiuto: case sepolte dalla neve, mancano acqua e corrente da 4 giorni'
descrizione: 'Atri, in provincia di Teramo, è sepolta dalla neve e da 4 giorni mancano acqua e corrente elettrica. Ci sono stati crolli e alcuni abitanti si sono rifugiati presso l’hotel Hermitage perché hanno le case inagibili. Ci sono dei generatori ma non bastano per dare corrente a tutti e il freddo è grande. Servono con urgenza acqua, uomini e mezzi per liberare strade, tetti e case dalla neve, sale a sacchi da spargere, e sopralluoghi VF. Qui per ora non si è visto nessuno se non qualche vigile del fuoco per poco tempo. Stiamo facendo tutto da soli ma non ce la facciamo! Serve subito aiuto! Paolo Castagna'
indirizzo: 'Piazza Duomo, Atri, TE, Abruzzo, 64032, Italia'
lat: '42.5801368'
lon: '13.9764121'
link: ''
immagine: ''
data: 23/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
