### ISSUE TITLE
Villa con 7-8 posti letto, con 5000mt di prato per animali

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2249]
<pre><yamldata>tel: '3334569527'
email: puppy69@tiscali.it
descrizione: 'Offro a famiglia di terremotati villa stupenda con 7-8 posti letto e prato 5000mt per eventuali animali, servita da tutto, la offro gratuitamente fino al passare dell''emergenza. Si trova in via Costa 21 ad Averara, provincia di Bergamo. E'' un paesino piccolo ma c''è tutto, la scuola vicino con pulmino gratuito e tutto quello che serve. Capisco che sono lontano ma se qualcuno avesse bisogno sarei felicissimo. Pierpaolo Ronzoni'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: 'http://i.imgur.com/XWXhpRw.jpg'
data: 24/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviata email per sapere località.

**Comment by cristigalas** [comment]
Dati ricevuti, aggiorno e pubblico.

**Comment by cristigalas** [comment]
Non più disponibile.
