### ISSUE TITLE
Cercasi tensostruttura a #Cesaproba (#Montereale) per 200 sfollati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2251]
<pre><yamldata>tel: '329 985 9980'
email: ''
cosa: 'Cercasi tensostruttura per Cesaproba (Montereale)'
descrizione: 'Cercasi tensostruttura per accogliere gli oltre 200 sfollati di Cesaproba di Montereale, chiusa su tutti i lati, di dimensione circa 12 mt x 12 mt.'
indirizzo: 'Strada Provinciale 105, Montereale, AQ, Abruzzo, Italia'
lat: '42.4991961'
lon: '13.1868431'
link: 'https://www.facebook.com/Cicomontorselli?fref=ts'
immagine: ''
data: 24/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Tensostruttura arrivata oggi, vedi http://news-town.it/cronaca/14689-cesaproba-una-settimana-dopo,-ecco-la-tensostruttura-per-accogliere-popolazione-pietrucci-protezione-civile-fallimentare.html
