### ISSUE TITLE
Offro alloggio in provincia di

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2259]
<pre><yamldata>tel: '3485244584'
email: daniela.fuccio@virgilio.it
descrizione: 'Offro alloggio in provincia di Bergamo per famiglia con uno o due figli. In qualità di insegnante, posso seguire i ragazzi nello studio per recuperare le lezioni perse.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 24/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
