### ISSUE TITLE
Protezione Civile San Casciano organizza raccolta alimenti e indumenti da neve

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2264]
<pre><yamldata>tel: ''
email: ''
cosa: 'Protezione Civile San Casciano organizza raccolta alimenti e indumenti da neve'
descrizione: 'RACCOLTA ALIMENTARE - Stiamo organizzando una raccolta alimentare (ma anche non alimentare). I prodotti raccolti verranno portati nelle zone terremotate questo fine settimana. Servono i prodotti elencati nelle liste che seguono e verranno raccolti mercoledì 25/1, giovedì 26/1 e venerdì 27/1 dalle ore 17.00 alle ore 19.00 presso la sede della protezione civile via grandi 1-S.Casciano VP. Per favore condividete questo messaggio ai vostri contatti. Grazie!!!!! Comune di Fiastra 100/150 persone: The Conserve Tonno Legumi Merendine Cibo gatti e cani Succhi di frutta Caffè / orzo Pannoloni anziani Muccia, la mensa serve 150 persone circa: Acqua The Conserve Tonno Legumi in scatola Merendine Mangime gatti e cani Succhi di frutta Caffè Caffè d''orzo Pieve Torina credo 150/200 persone: Acqua liscia e gasata Coca-Cola per ragazzi Se riuscite anche qualche tuta da neve, ti scrivo età e sesso 8 anni femmina 10 anni femmina 14 anni femmina taglia M 17 anni maschio taglia L Se riuscite anche scarpe da neve. Numero 36 femmina Numero 40 da femmina Numero 43 maschio Pievebovigliana la mensa serve circa 100/150 persone: Acqua The Conserve Tonno Legumi Merendine Mangime gatti e cani Succhi di frutta Caffè Caffè d''orzo Olio Traversine per letti per anziani'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1834044463529803/'
immagine: ''
data: 24/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
