### ISSUE TITLE
Offriamo alloggio ad una famiglia e postazione di lavoro a Bergamo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2265]
<pre><yamldata>tel: '3351253160'
email: bsg@ecap-sme.org
descrizione: 'Siamo una famiglia con 2 ragazzi di 15 e 17 anni e vorremmo essere di aiuto. Possiamo ospitare 2 adulti con bambino in una stanza nella nostra casa, a Bergamo, ben collegata con tutto. Cucina e bagno in condivisione. Se qualcuno deve lavorare in ufficio, può usare una postazione di lavoro nella mia stanza di ufficio, a 10 minuti a piedi da casa. WIFI e stampante disponibili.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 24/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Riporto risposta: "Non abbiamo ospitato nessuno.
L,unica richiesta che ci è arrivata ci è stata fatta da persona che, non dicendo nulla di sé, chiedeva informazioni private in maniera invadente e sospetta. La persona era probabilmente non italiana, dati gli errori nell,esprimersi.
Vi avevo segnalato il caso girandovi subito la mail ma non ho ricevuto nessun riscontro."
