### ISSUE TITLE
Sos animali, Cia: parte “Help foraggio”, la rete di solidarietà per gli allevatori bloccati da neve e terremoto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2266]
<pre><yamldata>titolo: 'Sos animali, Cia: parte “Help foraggio”, la rete di solidarietà per gli allevatori bloccati da neve e terremoto'
descrizione: '“Help foraggio”. Parte la rete di solidarietà della Cia-Agricoltori Italiani per portare un aiuto concreto alle aziende dell’Appennino stremate dalle nuove scosse di terremoto e sommerse dalla neve. Mentre si continua a lavorare per liberare le strade e agevolare la circolazione e i soccorsi, l’emergenza rimane alta per gli allevatori: sono tantissime le imprese agricole isolate, bloccate con le stalle pericolanti o crollate e il bestiame al freddo e senza cibo per l’impossibilità di rifornirsi di mangimi e foraggio e garantire l’alimentazione degli animali. Proprio per questo motivo la Cia, che già nei giorni scorsi aveva lanciato l’Sos animali, si è messa in moto con le sue strutture territoriali per sostenere gli agricoltori in difficoltà, contribuendo in primis a risolvere il problema approvvigionamento. I primi 160 quintali di fieno, donati dalla Cia Emilia Romagna, saranno consegnati domani, mercoledì 25 gennaio: una parte presso il centro di raccolta predisposto dalla Cia Abruzzo in provincia di Teramo, l’altra presso il centro di raccolta organizzato dalla Cia delle Marche nel comune di Monsampolo (Ascoli Piceno), per essere distribuiti alle aziende agricole in difficoltà. Seguirà a breve la Cia dell’Umbria, che sta raccogliendo circa 150 quintali di erba medica in pellet da donare agli allevatori associati per soddisfare le esigenze del bestiame. E’ un’azione di solidarietà concreta e importante -sottolinea la Cia- resa possibile dalla disponibilità delle nostre aziende e delle nostre strutture sul territorio, che vogliono aiutare ed essere vicine ai colleghi così duramente colpiti da sisma e maltempo. In Abruzzo, Marche, Umbria e Lazio il settore primario sta perdendo circa 100 milioni di euro a settimana, tra danni a coltivazioni e beni strumentali, perdite alla zootecnia e mancata commercializzazione. Troppe aziende, in aree a fortissima vocazione rurale, rischiano di chiudere senza interventi urgenti. Ecco perché, oltre a rivolgere un appello al Governo e all’Europa per attivare subito tutti gli strumenti necessari per indennizzare almeno parte dei danni subiti dagli allevatori, come Confederazione continueremo con iniziative utili -ribadisce la Cia-. L’obiettivo è creare una vera e propria rete “connessa” con il territorio per aiutare gli agricoltori delle aree colpite ad affrontare questo momento così drammatico. Per informazioni e donazioni si può scrivere all’indirizzo mail azionisolidali@cia.it.'
link: ''
data: 24/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
