### ISSUE TITLE
Offro casa con due camere da letto vicino Fara, in Sabina (Ri)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2269]
<pre><yamldata>tel: '342 7787366'
email: sallyreynolds523@gmail.com
descrizione: 'Offro casa con due camere da letto al primo piano a Canneto vicino a Fara in Sabina, RI - fino ad aprile/ maggio. Terrazza indipendente. D''estate funziona come casa vacanza allora e ben" attrezzata e arredata. Mi chiamo Sally, sono inglese e abito nella casa di sotto.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 24/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non più disponibile.
