### ISSUE TITLE
Disaster Tech Lab cerca volontari Ict per intervento a Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#227]
<pre><yamldata>tel: ''
email: volunteer@disastertechlab.org
cosa: 'Disaster Tech Lab cerca volontari Ict per intervento a Amatrice'
descrizione: 'Cercasi con urgenza volontari con competenze informatiche per intervento su Amatrice.'
indirizzo: ''
lat: '42.63289'
lon: '13.28937'
link: 'https://twitter.com/disastertechlab/status/775692848591151104'
immagine: ''
data: 14/09/2016
</yamldata></pre>

**Comment by iltempe** [comment]
possiamo georiferire?

**Comment by Manfro** [comment]
Georiferito.

**Comment by chiccap** [comment]
Non servono più volontari.
