### ISSUE TITLE
A #Cascia si cerca con urgenza container uso magazzino per officina meccanica

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2286]
<pre><yamldata>tel: '3462281941'
email: ''
cosa: 'Container uso magazzino'
descrizione: 'Avrei necessità di un container (anche due se possibile) per trasferirvi materiale dai locali della mia attività resa inagibili dal terremoto. Si tratta di un''officina meccanica a Cascia andata completamente distrutta. Il container mi serve perché devo mettere al riparo i materiali che ho recuperato in attesa dei lavori di ricostruzione. Chiunque possa aiutarmi può contattarmi al 3462281941. Grazie. Guerrino Aloisi'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 25/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviato sms per sapere nome e località, attendiamo queste info prima di accettare.

**Comment by cristigalas** [comment]
Christian Varani ci comunica di aver parlato con il sig. Aloisi e che il container è stato trovato.
