### ISSUE TITLE
Cercasi con urgenza trasporto per una roulotte da Roma a Treia (Mc)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2288]
<pre><yamldata>tel: '3291693369'
email: pelange23@web.de
cosa: 'Cercasi con urgenza trasporto per una roulotte da Roma a Treia (Mc)'
descrizione: 'Grazie al vostro sito ho finalmente trovato una roulotte che mi permetterà di stare nel paese dove vivo, Treia in provincia di Macerata. La roulotte è a Roma ma non può viaggiare e quindi cerco qualcuno che mi aiuti a trasportarla con un carrello o camioncino. Sono sfollata da agosto e sono passata da un alloggio precario all''altro ma adesso con questa roulotte potrei finalmente "stabilizzarmi". Grazie a chiunque potrà darmi un aiuto. Petra'
indirizzo: 'Viale Armando Diaz, Treia, MC, Marche, Italia'
lat: '43.310556'
lon: '13.311475'
link: ''
immagine: ''
data: 25/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Come ci ha comunicato via sms dalla signora Petra, la donazione della roulotte purtroppo è sfumata e quindi non c'è più bisogno di cercare un trasporto. Chiudo.
