### ISSUE TITLE
Associazione di volontariato offre scorte alimentari 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2289]
<pre><yamldata>tel: '3293684667 Luigi'
email: palma.luigi.lp@gmail.com
cosa: 'OFFRESI SCORTE ALIMENTARI'
descrizione: 'Siamo l''associazione A.E.O.P. di Torremaggiore (FG), associazione di volontariato e offriamo scorte alimentari: pasta , zucchero, farina, pelati, sale, passate, ecc ecc. Non potendo recarci sul posto, siamo disposti a spedire direttamente alle famiglie bisognose o presso centri di raccolta.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 26/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviata email per sapere che associazione è.

**Comment by cristigalas** [comment]
Hanno risposto. Aggiorno e pubblico.

**Comment by cristigalas** [comment]
Per email ci comunicano che hanno raccolto e consegnato e che quindi possiamo chiudere.
