### ISSUE TITLE
Richiesta di beni per #Scai, frazione di Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2296]
<pre><yamldata>tel: '3776982370'
email: christianvarani@gmail.com
cosa: 'Richiesta di beni necessari per Scai (Frazione del Comune di Amatrice)'
descrizione: 'A Scai, frazione di Amatrice, servono detersivi per lavatrice e a mano, ammorbidenti, sacchi neri per la raccolta dei rifiuti, guanti preferibilmente in lattice per uso domestico, candeggina, detersivi liquidi per lavare piatti e superfici, secchio (preferibilmente mocio) per lavare in terra, scope e palette. Per contatti Barbara Angelini (via Facebook o cellulare), Christian Varani (via email).'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Barbara Angelini'
immagine: ''
data: 26/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta come segnalato da Christian Varani via email.
