### ISSUE TITLE
Offresi due appartamenti per famiglie in provincia di Milano 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2297]
<pre><yamldata>tel: '3456731219'
email: l.baffoni@residenzevione.it
descrizione: 'Residenze Vione a Basiglio (MI) mette a disposizione due appartamenti uniti con sei camere e quattro bagni in un contesto residenziale particolarmente indicato per famiglie con bambini e ragazzi.'
indirizzo: 'SP122, Basiglio, Milano, Lombardia, 20089, Italia'
lat: '45.3439758'
lon: '9.1724181'
link: 'http://www.borgodivione.it'
immagine: ''
data: 26/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta non più disponibile.
