### ISSUE TITLE
Umbria, occhiali da vista gratis grazie a Federottica

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2300]
<pre><yamldata>titolo: 'Umbria, occhiali da vista gratis grazie a Federottica'
descrizione: 'Federottica Umbria, aderente a Confcommercio, con Luxottica offre occhiali gratis alle persone colpite dal terremoto. Le richieste saranno raccolte dalla segreteria di Federottica Umbria, presso Confcommercio Umbria (sede di Perugia, tel. 075.506711 – s.ragnacci@confcommercio.umbria.it), che provvederà a trasmetterle alla Scuola di Ottica e Optometria dell’Istituto Fermi per l’assemblaggio degli occhiali, e per concordare modalità e tempi i consegna. Per l’eventuale visita oculistica, è possibile contattare la Clinica oculistica di Perugia. Per una valutazione optometrica, le persone interessate potranno recarsi presso l’istituto Enrico Fermi di Perugia, nelle date e secondo le modalità descritte nel sito www.confcommercio.umbria.it.'
link: 'http://tuttoggi.info/terremoto-occhiali-vista-gratis-grazie-confcommercio/378604/'
data: 26/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Distribuzione terminata.
