### ISSUE TITLE
Raccolta di beni a Parma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2301]
<pre><yamldata>tel: '0521 671689'
email: info@spazioverdeparma.it
cosa: 'Raccolta di beni a Parma'
descrizione: 'A Parma il gruppo Io non crollo raccoglie beni presso il negozio di Roberto Zanella "Spazio Verde" - Via Emilia Ovest 323 (vicino al ponte di Pontetaro).'
indirizzo: 'Via Emilia Ovest, Parma, PR, EMR, 43126, Italia'
lat: '44.8064575'
lon: '10.3034503'
link: 'https://www.facebook.com/profile.php?id=100009804013677&fref=ts'
immagine: ''
data: 26/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
