### ISSUE TITLE
Donazione automobile, alimentari, stoviglie, biancheria #Alessandria

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2302]
<pre><yamldata>tel: '3664011910'
email: bosco.romina@gmail.com
cosa: 'Automobile, alimentari, stoviglie, biancheria'
descrizione: 'Buongiorno. Ho una Volkswagen Golf con gancio traino omologato. La macchina non è recente ma funzionante. Chiedo solo le spese di passaggio di proprietà. Non ho possibilità di portarla personalmente, quindi se qualcuno fosse interessato all''offerta, possiamo metterci d''accordo per il ritiro. Io abito ad Alessandria. Inoltre, alla persona o alle persone che verranno a prendere l''auto, posso donare anche cibo e/o beni di prima necessità (stoviglie, biancheria, abbigliamento). Chi fosse interessato solo agli alimentari e ai beni, può venire ad Alessandria, magari con un furgone perchè, come dicevo, non ho possibilità di raggiungere personalmente i luoghi terremotati. Contattatemi via telefono o via e-mail. Con i miei famigliari, amici, ed eventualmente coloro che abitano ad Alessandria e dintorni, possiamo organizzarci per raccogliere ciò che serve alle famiglie che in questo periodo sono davvero in difficoltà. E, cosa più importante, fare in modo che i beni offerti arrivino con certezza a chi ne ha bisogno, donando direttamente, senza passare attraverso terzi. Grazie anche a tutti coloro che vorranno partecipare alla raccolta. Romina.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 27/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
La signora Romina ci ha comunicato via email che ha trovato a chi donare l'auto e anche a chi dare i beni che ha raccolto. Chiudo.
