### ISSUE TITLE
Alloggio

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2305]
<pre><yamldata>tel: '3477770989'
email: matteuccimonica@hotmail.it
cosa: Alloggio
descrizione: 'Buonasera a tutti vi chiedo una cortesia. Una famiglia con casa inagibile di Tolentino si è rivolto a me (lavoro nel sociale)per avere un aiuto.Sono ospiti di una struttura ma da domenica saranno fiori. Stanno cercando una casa intorno a Porto Recanati, distante quel che basta per far andare il figlio a scuola. Lo hanno trasferito li dal terremoto. È una situazione particolare e non possono stare in macchina spiegherò in privato il perché. Sono brave persone e lui è disposto intanto che non trova un lavoro a fare lavori di restauro e sistemazione. Si accontenta anche di un monolocale o magari può fare il manutentore in qualche camping/residence. Contattatemi in privato grazie.Monica'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 27/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
