### ISSUE TITLE
Offro camera con bagno a Berga

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2307]
<pre><yamldata>tel: '3388583651'
email: pamelanodari@tiscali.it
descrizione: 'Offro camera con bagno a Bergamo. Mamma con 2 bambini disponibile ad ospitare mamma -bimbo o 2 persone. Cucina e salotto in condivisione. Zona ben servita.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 27/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
