### ISSUE TITLE
Disponibile appartamento per 3 persone in provincia di Lucca

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2312]
<pre><yamldata>tel: '3477679483; 3497494861'
email: nicoletta.gini@gmail.com
descrizione: 'Disponibile appartamento per 3 persone a Massa Macinaia, comune di Capannori, in provincia di Lucca. L''appartamento consiste in cucina/tinello, bagno, camera con letto matrimoniale e studio, adattabile a camera con un letto singolo.'
indirizzo: 'Via della Chiesa di Massa Macinaia, Corte Orsetti, Capannori, LU, Tuscany, Italia'
lat: '43.8044795'
lon: '10.5549581'
link: ''
immagine: ''
data: 28/01/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non è mai stata contattata. Non più disponibile.
