### ISSUE TITLE
Brigate di Solidarietà Attiva - Chiamata Volontari - Acquasanta e Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#232]
<pre><yamldata>tel: '3299837400 - 3394037385 - 3397616665'
email: volontaribsa@gmail.com
cosa: 'Brigate di Solidarietà Attiva - Chiamata Volontari - Acquasanta e Amatrice'
descrizione: 'Chiamata volontari per campi autogestiti. Qui modulo di adesione: https://goo.gl/forms/QyJsGtRQ65xbUqd63'
indirizzo: ''
lat: 42.63289
lon: 13.28937
link: 'https://www.facebook.com/terremotocentroitalia/posts/1365045246858821'
immagine: ''
data: 14/09/2016
</yamldata></pre>

**Comment by iltempe** [comment]
possiamo georiferire?

**Comment by Manfro** [comment]
Georiferita.
