### ISSUE TITLE
A #Saletta, fraz. #Amatrice, serve una lavatrice (anche usata)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2328]
<pre><yamldata>tel: ''
email: maggi.monica@gmail.com
cosa: 'A #Saletta, frazione di #Amatric, serve una lavatrice (anche usata)'
descrizione: 'Serve con urgenza una lavatrice anche usata ma funzionante a Saletta. Grazie. Monica Maggi'
indirizzo: 'SP20, Pedivilla, Amatrice, RI, LAZ, 02011, Italia'
lat: '42.6713248'
lon: '13.2720634'
link: 'https://twitter.com/libra2puntozero/status/825800680380194817'
immagine: ''
data: 29/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Lavatrice consegnata lo scorso febbraio dall'associazione Poppai Bortolai, come segnalato via email da Christian Varani.
