### ISSUE TITLE
Regione Lazio, sostegno al reddito per i lavoratori colpiti dal sisma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2330]
<pre><yamldata>titolo: 'Regione Lazio, sostegno al reddito per i lavoratori colpiti dal sisma'
descrizione: 'Le modalità per la richiesta dei contributi per l’indennità di 5.000 euro per i lavoratori autonomi e la presentazione dei moduli per la richiesta dei contributi per l’indennità una tantum di 5.000 euro per chi è stato colpito dal sisma.'
link: 'http://www.regione.lazio.it/rl_lavoro/?vw=newsDettaglio&id=165'
data: 30/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
