### ISSUE TITLE
Forno

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2332]
<pre><yamldata>tel: '3278651267'
email: vivacca12@tiscali.it
cosa: Forno
descrizione: 'Salve, dono impastatrici da 3 e 1 quintale e forno da 18 mq.Smontaggio e trasporto a vosyro carico. I macchinari sono a Oriolo Cs 87063'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 30/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente
