### ISSUE TITLE
REGIONE MARCHE: MISURE DI SOSTEGNO AL REDDITO DEI LAVORATORI DIPENDENTI ED AUTONOMI IN SEGUITO A SOSPENSIONI ATTIVITA’ POST-SISMA. DOMANDE ENTRO IL 31 MARZO 2017

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2338]
<pre><yamldata>titolo: 'REGIONE MARCHE: MISURE DI SOSTEGNO AL REDDITO DEI LAVORATORI DIPENDENTI ED AUTONOMI IN SEGUITO A SOSPENSIONI ATTIVITA’ POST-SISMA. DOMANDE ENTRO IL 31 MARZO 2017'
descrizione: 'Al via da oggi 30 gennaio 2017 le misure di sostegno al reddito per i lavoratori dipendenti ed autonomi delle zone colpite dal sisma del 24/8/2016 (allegato 1) e del 26/10/2016 (allegato 2). Ciò in base a quanto previsto dall’art.45 del DL n.189/2016 convertito in legge n.229/2016 e, per quanto riguarda la Regione Marche, dalla Convenzione stipulata col Ministero del Lavoro e Politiche Sociali, Ministero dell’Economia e delle Finanze del 20 gennaio 2017.'
link: 'https://bartolomeigiuliano.blog/2017/01/30/regione-marche-sostegno-al-reddito-di-lavoratori-dipendenti-ed-autonomi-in-seguito-a-sospensioni-attivita-post-sisma/'
data: 31/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
