### ISSUE TITLE
Cerchiamo Volontari

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2340]
<pre><yamldata>tel: '3297239367'
email: nirchi.v@gmail.com
cosa: 'Cerchiamo Volontari'
descrizione: 'L''associazione MAM beyond borders è in contatto con i referenti delle zone terremotate del centro Italia. Abbiamo bisogno di volontari, possibilmente automuniti, che diano un aiuto concreto sul posto. Possibilità di vitto e alloggio gratis. Assicuriamo i nostri volontari. Per info contattateci.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://m.facebook.com/profile.php?id=563881680324872'
immagine: 'http://i.imgur.com/sqqSuoh.jpg'
data: 31/01/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione simile già presente, ho aggiornato quella.
