### ISSUE TITLE
#Norcia: dalla Protezione Civile la lista di ciò che serve

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2356]
<pre><yamldata>titolo: 'Sisma, Norcia: dalla Protezione Civile la lista di ciò che serve'
descrizione: 'La Protezione civile di Norcia ha diffuso un comunicato con il quale spiega cosa manca in questo momento per le scorte. Di seguito, l’elenco completo degli alimenti e degli altri beni che necessitano e indicazioni su chi contattare.'
link: 'http://www.lanotiziaquotidiana.it/umbria/2017/02/01/sisma-norcia-dalla-protezione-civile-la-lista-di-cio-che-serve/'
data: 02/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
La stessa notizia era già stata inserita, vedi #2276, ma rimandando al post Facebook dell'associazione di protezione civile della Valnerina che è poi lo steso testo del comunicato di cui si parla qui... Comunque l'ho spostata in fabbisogni.

**Comment by chiccap** [comment]
Raccolta chiusa.
