### ISSUE TITLE
Cerchiamo un camper per Enzo, per farlo sentire al sicuro #SanBenedetto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2365]
<pre><yamldata>tel: '3887537144'
email: mazzanticlau@gmail.com
cosa: 'Cerchiamo un camper per Enzo'
descrizione: 'Enzo ha 58 anni ed è di Pescara del Tronto, una frazione del comune di Arquata del Tronto (AP). Nella sua vita ha combattuto tante battaglie in difesa del territorio cercando di tutelare le risorse naturali locali ed andando spesso contro-corrente. Da decenni raccoglieva pietre particolari, vere e proprie d’arte, con le quali sono state allestite esposizioni in Italia. Questo patrimonio è finito sotto le macerie di casa sua crollata - come tutte le altre - a Pescara del Tronto, luogo che ha presidiato sino alle terribili scosse del 30 ottobre. Enzo negli ultimi mesi risiedeva in una tenda nel campo tenda di Borgo d’Arquata. Proprio per questa sua scelta, oggi si trova in attesa di un processo giudiziario per interruzione di pubblico servizio, con la paura di vivere in un luogo chiuso da cemento e mattoni, ma con il bisogno di un posto che lo faccia sentire più al sicuro. Cerchiamo un camper per Enzo, per farlo sentire al sicuro!'
indirizzo: 'Via Raffaello Sanzio, Marina centro, San Benedetto del Tronto, AP, Marche, 63039, Italia'
lat: '42.9525328'
lon: '13.8807144'
link: ''
immagine: ''
data: 02/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
http://www.ascolinews.it/index.php/associazione-dona-una-roulotte-al-58enne-arquatano-arrestato/

Aspetto a chiudere per vedere se riusciamo a verificare la notizia

**Comment by cristigalas** [comment]
La notizia è verificata. Ho avuto scambio via Twitter con Lorenzo Schirru di European-Mediterranean Seismological Center che insieme al gruppo Io non crollo mi ha confermato che questa settimana porterà una roulotte ad Enzo e che è in contatto con il sindaco di Arquata per individuare una piazzola dove collocarla. Nel frattempo Enzo sta alloggiando in albergo grazie all'intervento dell'associazione Gus. Vedi qui https://twitter.com/lollo1963lollo/status/827600157076238337 e anche qui http://www.ilrestodelcarlino.it/ascoli/cronaca/roulotte-reduce-pescara-tronto-1.2865216

**Comment by cristigalas** [comment]
Chiudo.
