### ISSUE TITLE
Sisma, terzo decreto approvato - Gentiloni:"Risorse consistenti"

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2368]
<pre><yamldata>titolo: 'Sisma, terzo decreto approvato - Gentiloni:"Risorse consistenti"'
descrizione: 'Approvato il decreto legge in favore delle popolazioni del centro Italia colpite dal sisma del 2016 e 2017. Il Consiglio dei ministri ha dato il via libera al provvedimento che è il terzo dedicato al terremoto dopo quelli emanati dopo le scosse di agosto e ottobre. Il testo, anticipato dal senatore Remigio Ceroni su CM e commentato in conferenza stampa oggi dal premier Paolo Gentiloni, punta a semplificare e superare la burocrazia indicata dai più come il vero problema della gestione post sisma.'
link: 'http://www.cronachemaceratesi.it/2017/02/02/sisma-terzo-decreto-approvato-gentiloni-risorse-consistenti/919931/'
data: 02/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
articolo differente ma contenuto simile già inserito in notizie.
