### ISSUE TITLE
Approvato Decreto Terremoto: tutte le misure

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2369]
<pre><yamldata>titolo: 'Approvato Decreto Terremoto: tutte le misure'
descrizione: 'Il Consiglio dei ministri ha approvato il decreto legge in favore delle popolazioni del centro Italia colpite dai terremoti del 2016 e del 2017.'
link: 'http://www.ilcapoluogo.it/2017/02/02/approvato-decreto-terremoto-tutte-le-misure/'
data: 02/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
articolo diverso ma contenuto simile.
