### ISSUE TITLE
Ripresa post sisma, Confartigianato: "Troppa burocrazia e manca la Provincia"

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2370]
<pre><yamldata>titolo: 'Ripresa post sisma, Confartigianato: "Troppa burocrazia e manca la Provincia"'
descrizione: 'Grande partecipazione al primo incontro organizzato dall''associazione di categoria. Il vice segretario Giorgio Menichelli segnala le principali difficoltà per le aziende.'
link: 'http://www.cronachemaceratesi.it/2017/02/02/ripresa-post-sisma-confartigianato-troppa-burocrazia-e-manca-la-provincia/919776/'
data: 02/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
lo ritengo non adatto alla sezione "notizie" ma se a voi sembra adeguato cambiamo label

**Comment by cristigalas** [comment]
Infatti, ho appena commentato anch'io un'altra segnalazione simile... dobbiamo cercare di selezionare meglio la tipologia delle notizie che vogliamo diffondere. Direi solo notizie di pubblica utilità e preferibilmente provenienti da siti istituzionali...

**Comment by cristigalas** [comment]
Chiudo.
