### ISSUE TITLE
Sisma, Fucksia (Misto): "Ottimizzare emergenze coinvolgendo tutti"

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2372]
<pre><yamldata>titolo: 'Sisma, Fucksia (Misto): "Ottimizzare emergenze coinvolgendo tutti"'
descrizione: 'Il Senato ha approvato oggi un Odg della senatrice Serenella Fucksia (Gruppo Misto) relativo al ddl di riordino della Protezione Civile.'
link: 'https://picchionews.it/politica/sisma-fucksia-misto-ottimizzare-emergenze-coinvolgendo-tutti'
data: 02/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Vedo che via form stanno arrivando segnalazioni che, come questa, sono soprattutto articoli e notizie un po' generiche sul tema "terremoto" che io non accetterei perché mi sembrano più da agenzia di stampa che da TCI... io limiterei la diffusione sui nostri canali a notizie di pubblica utilità (precise nei contenuti e nei riferimenti, meglio se rimandano a siti di enti pubblici), oltre ovviamente a segnalazioni di richieste/offerte di aiuto. Che ne dite @chiccap @favoeva?

**Comment by chiccap** [comment]
io sono d'accordo!
