### ISSUE TITLE
REGIONE MARCHE: SOSTEGNO AL REDDITO DI LAVORATORI DIPENDENTI ED AUTONOMI IN SEGUITO A SOSPENSIONI ATTIVITA’ POST-SISMA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2373]
<pre><yamldata>titolo: 'REGIONE MARCHE: SOSTEGNO AL REDDITO DI LAVORATORI DIPENDENTI ED AUTONOMI IN SEGUITO A SOSPENSIONI ATTIVITA’ POST-SISMA'
descrizione: 'REGIONE MARCHE: MISURE DI SOSTEGNO AL REDDITO DEI LAVORATORI DIPENDENTI ED AUTONOMI IN SEGUITO A SOSPENSIONI ATTIVITA’ POST-SISMA. DOMANDE ENTRO IL 31 MARZO 2017'
link: 'https://bartolomeigiuliano.blog/2017/01/30/regione-marche-sostegno-al-reddito-di-lavoratori-dipendenti-ed-autonomi-in-seguito-a-sospensioni-attivita-post-sisma/'
data: 02/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
La notizia c'è già e comunque non rimanderei per notizie del genere a blog ma a siti istituzionali. Che ne dici @chiccap?

**Comment by cristigalas** [comment]
Chiudo.
