### ISSUE TITLE
Un aiuto alle popolazioni terremotate: ecco il grande dono agli allevatori di Norcia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2375]
<pre><yamldata>titolo: 'Un aiuto alle popolazioni terremotate: ecco il grande dono agli allevatori di Norcia'
descrizione: 'Continua l’attività di Confagricoltura Umbria volta a portare un aiuto alle popolazioni e agli allevatori delle aree colpite dal sisma, evento al quale si sono aggiunte le straordinarie precipitazioni nevose dei giorni scorsi che hanno ulteriormente isolato le zone colpite.'
link: 'http://www.perugiatoday.it/cronaca/donazione-fieno-aziende-norcia-aiuti-terremoto.html'
data: 02/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Secondo me questo tipo di notizie non servono e rischiano di appesantire inutilmente la nostra comunicazione... più che promuovere ciò che fa questo o quell'ente bisognerebbe, io credo, diffondere informazioni di pubblica utilità, call to action, ecc. Che ne dite?
