### ISSUE TITLE
La nostra famiglia gestisce un

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2377]
<pre><yamldata>tel: '3393028659'
email: gianluca.casini@ording.gr.it
descrizione: 'La nostra famiglia gestisce un agriturismo a Suvereto prov. di Livorno, possiamo mettere a disposizione 2 bilocali adatti per 3-4 persone ciascuno, disponibili fino a maggio. I bilocali comprendono una camera matrimoniale, bagno e ampia cucina con divano letto matrimoniale, sono al piano primo. Ripetiamo annuncio in quanto la prima volta non è venuto segnalato sulla mappa.'
indirizzo: 'Strada Provinciale 19 di Montioni, Calzalunga, Suvereto, LI, Tuscany, 57028, Italia'
lat: '43.063056195256685'
lon: '10.722506046295166'
link: 'http://www.agriturismocasavecchia.com/'
immagine: ''
data: 03/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
