### ISSUE TITLE
A #Visso cercasi con urgenza materiali per copertura di una stalla

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2386]
<pre><yamldata>tel: 347-9526902
email: ''
cosa: 'A #Visso cercasi con urgenza materiali per copertura di una stalla'
descrizione: 'Siamo appena tornati da una frazione di Visso, DEVASTATA, ove abbiamo portato generi alimentari per due ragazzi allevatori UNICI rimasti lì. Hanno bisogno ASSOLUTAMENTE di una copertura per la stalla delle pecore che é parzialmente crollata e semiaperta e ci piove dentro. E'' stata puntellata ma le continue scosse la stanno facendo crollare.... Chi conosce rivenditori di questo genere (pali 4 mt, coperture tipo ondulit ecc.) mi contatti 347-9526902 Manuela. Appena reperito il materiale andremo su ad aiutarli a sistemare la stalla. E'' IMPORTANTE, hanno già perso parecchi animali a causa dei crolli. GRAZIE.'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1839876672946582/'
immagine: ''
data: 03/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci dice che la richiesta è stata soddisfatta poco dopo la sua pubblicazione, come risulta anche da Facebook.
