### ISSUE TITLE
Cercasi roulotte ad #ArquataDelTronto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2397]
<pre><yamldata>tel: '3930083011'
email: ''
cosa: 'Cercasi roulotte #ArquataDelTronto'
descrizione: 'Sono di Arquata del Tronto, ho la casa inagibile e mio marito sta gravemente male, vorrei una roulotte di 4 posti se qualcuno me la può donare, vi ringrazio mille volte. Per contattarmi: Maura Lalli 3930083011'
indirizzo: 'Piazza Umberto I, Arquata del Tronto, AP, Marche, Italia'
lat: '42.7723609'
lon: '13.2965826'
link: ''
immagine: ''
data: 05/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani segnala via email che la richiesta di può chiudere.
