### ISSUE TITLE
Agriturismo in provincia di Brescia offre appartamenti gratuiti fino a maggio

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2400]
<pre><yamldata>tel: '3497895696'
email: augusta.casa@libero.it
descrizione: 'Buongiorno, ho avuto il Vostro riferimento tramite il Trio Medusa e Vi segnalo con grande piacere questa opportunità. L''Agriturismo Villa Gradoni in Franciacorta (Brescia) (www.villafranciacorta.it) mette a disposizione 20 appartamenti, gratuitamente, da oggi e fino a maggio, per le famiglie così duramente colpite dal terremoto e dagli eventi atmosferici degli ultimi mesi, credo sia un''ottima opportunità per concedere loro qualche giono di svago, anche psicologico in una struttura accogliente che potrete vedere sul sito. Si tratta di 10 bilocali (per 4 persone) e 10 trilocali (per 6 persone) completamente arredati e corredati: per l''utilizzo è richiesto solo un preavviso di un paio di giorni per l''accensione del riscaldamento. Resto a disposizione per qualsiasi ulteriore chiarimento e/o informazione. Cordiali saluti. Augusta Bianchetti'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.villafranciacorta.it'
immagine: ''
data: 06/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta, non più disponibile.
