### ISSUE TITLE
Offresi camper 5 posti

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2403]
<pre><yamldata>tel: '3389059437'
email: gio.mantovani@libero.it
cosa: 'Camper 5 posti'
descrizione: 'Fiat Ducato 2000 turbodiesel del 1994. Km. 90.000 - Marciante ma senza assicurazione - Bisogna riparare il lavandino del bagno. Il mezzo è disponibile per il ritiro in un campeggio del Castelletto Ticino (NO).'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 06/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Il signor Giovanni via sms mi ha comunicato che il camper andrà al Comune di Ussita. Siamo d'accordo che se per qualche motivo la cosa non andasse in porto me lo fa spere. Quindi chiudo e semmai riapriamo se il camper fosse ancora disponibile.
