### ISSUE TITLE
Cerco Trasporto per Roulotte Roma-Visso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2405]
<pre><yamldata>tel: '3479526902 Manuela o 3284089801 Massimo'
email: ''
cosa: 'Cerco Trasporto per Roulotte Roma-Visso'
descrizione: 'Stiamo cercando qualcuno disponibile a trasportare una roulotte a Visso presso un allevatore. Sarebbe meglio un carroattrezzi. La roulotte (piccola) si trova a Roma.'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: ''
immagine: ''
data: 06/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Il trasporto è stato trovato, come comunicato via Facebook. Chiudo.
