### ISSUE TITLE
Cercasi carro attrezzi a #Visso per trasportare roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2414]
<pre><yamldata>tel: '3284089801 Massimo'
email: ''
cosa: 'Cercasi carro attrezzi a #Visso per trasportare roulotte'
descrizione: 'Abbiamo trovato un autotrasportatore disposto a trasportare una roulotte da Roma fino a Villa S. Antonio (Visso) per un allevatore che ne ha bisogno. Ora però stiamo cercando una soluzione per scaricare la roulotte dal camion una volta arrivati. Ci servirebbe un carro attrezzi. Ci potete aiutare? Grazie!'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1841473929453523/'
immagine: ''
data: 07/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Vedi #2405

**Comment by cristigalas** [comment]
Oggi su Facebook è stato comunicato da Manuela Fazi che il trasporto per la roulotte è stato trovato. Chiudo.
