### ISSUE TITLE
Offresi appartamento a Grosio in Valtellina anche per l'estate

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2422]
<pre><yamldata>tel: '3498302251'
email: manuost@alice.it
descrizione: 'Salve offro a Grosio in Valtellina da marzo e per tutta l''estate appartamento per 4 persone in ordine e ben sistemato, ideale per famiglia con bambini (sopratutto questi ultimi troverebbero un ambiente pieno di ragazzini in età scolare con cui legare e spazio per giocare). Io abito a venti metri da questo appartamento perciò sono disponibile in caso di necessità. Grosio è un piccolo centro montano di 4500 persone con negozi, scuole, oratorio, ospedale a dieci minuti. Se qualcuno fosse interessato a salire anche solo per l''estate mi faccia sapere che lo tengo libero. Vi aspetto, forza amici!'
indirizzo: 'Via Roma, Grosio, Comunità Montana della Valtellina di Tirano, Sondrio, Lombardia, Italia'
lat: '46.2989301'
lon: '10.2745156'
link: 'http://www.grosio.info/'
immagine: ''
data: 08/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non è mai stata contattata e ad oggi l'alloggio non è più disponibile. Chiudo
