### ISSUE TITLE
Offro appartamento per quattro

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2423]
<pre><yamldata>tel: '3498302251'
email: manuost@alice.it
descrizione: 'Offro appartamento per quattro persone (letto matrimoniale e due singoli)a Grosio in Valtellina da marzo e per tutta l'' estate.Abito a venti metri dallo stesso perciò sono disponibile in caso di necessità. Grosio è un paese di 4500 abitanti con scuole,negozi,oratorio..questa sistemazione è l'' ideale se avete bambini in età scolare poichè nel quartiere ci sono diversi bambini e c'' è spazio per giocare.Se avete intenzione di salire solo per l'' estate fatemi sapere che lo tengo libero.Forza amici,vi aspetto!'
indirizzo: 'Via Roma, Grosio, Comunità Montana della Valtellina di Tirano, Sondrio, Lombardia, Italia'
lat: '46.2989301'
lon: '10.2745156'
link: 'http://www.grosio.info/'
immagine: ''
data: 08/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
