### ISSUE TITLE
Raccolta di crocchette e cibo umido per i gatti di #ArquatadelTronto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2428]
<pre><yamldata>tel: '3277786853'
email: scodinzolandiapet@gmail.com
cosa: 'Raccolta di crocchette e cibo umido per i gatti di Arquata del Tronto'
descrizione: 'Dopo il terremoto e le abbondanti nevicate Arquata del Tronto e le frazioni limitrofe sono rimaste isolate ed abbandonate. Qui tantissimi gatti sono rimasti soli. Vagano tra le case disabitate e non hanno nulla da mangiare, la loro sorte è nelle mani dei volontari che ogni giorno si recano nelle zone rosse per accudirli. Scodinzolandia Petshop Ambulatorio Veterinario di San Ginesio, da sempre sensibile alle sorti degli animali indifesi , sta raccogliendo crocchette e cibo umido da portare personalmente in queste zone. Abbiamo bisogno del "vostro piccolo aiuto" perché ...l''unione fa la forza! Un grande miaograzie da tutti i gatti di Arquata del Tronto! Leo e Angelita 3277786853 – 3498653579 - 0733663432 Scodinzolandia Petshop Ambulatorio Veterinario via Faleriense, 36 – 62026 - San Ginesio Facebook: scodinzolandia petshop ambulatorio veterinario'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.scodinzolandiapet.it/'
immagine: 'http://i.imgur.com/oKgZGCQ.jpg'
data: 09/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
