### ISSUE TITLE
Donati 110 quintali di mangimi ai comuni di Visso, Pieve Torina, Ussita e Castelsantangelo sul Nera

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2436]
<pre><yamldata>titolo: 'Donati 110 quintali di mangimi ai comuni di Visso, Pieve Torina, Ussita e Castelsantangelo sul Nera'
descrizione: 'Donati 110 quintali di mangimi alle aziende zootecniche dei comuni di Visso, Pieve Torina, Ussita, Castelsantangelo sul Nera. L’iniziativa, scaturita da un interessamento della Consulta provinciale del volontariato di protezione civile della Provincia di Arezzo, ha anche visto la collaborazione di numerose aziende agricole del Casentino che hanno offerto il loro fieno.'
link: 'http://www.ilrestodelcarlino.it/macerata/cronaca/terremoto-mangimi-allevatori-visso-ussita-1.2878272'
data: 10/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap questo tipo di notizie non le pubblicherei perchè trovano già abbastanza spazio nella stampa e in fondo non offrono nessuna vera notizia di pubblica utilità. Secondo me Tci non deve funzionare come un ufficio stampa o un'agenzia di stampa e quindi eviterei notizie che raccontano ciò che dona questo o quell'ente...

**Comment by chiccap** [comment]
Vero, hai ragione! Le nuove attiviste di actionaid devono ancora prenderci la mano. Colpa mia che accetto senza criterio :) grazie mille come sempre!

**Comment by cristigalas** [comment]
Figurati Chiara, grazie a te!
