### ISSUE TITLE
alloggio

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2454]
<pre><yamldata>tel: '3291809694'
email: ''
cosa: alloggio
descrizione: 'Salve, cerchiamo appartamento anche in affitto, casa inagibile siamo in prov di macerata ma va bene anche la prov di ancona , siamo in due ma abbiamo con noi un cane anziano e due mici, che non sporcano e non fanno danni, chi puo aiutarci perfavore ci contatti , fra poco ci troveremo in strada'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 11/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
