### ISSUE TITLE
Cercasi stufa a pellet a #Bolognola

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2460]
<pre><yamldata>tel: ''
email: irustichellididany@libero.it
cosa: 'Cercasi stufa a pellet #Bolognola'
descrizione: 'Cerco una stufa a pellet per appartamento di mq 70 donatomi per l''emergenza terremoto visto che ho casa inagibile e ci dobbiamo trasferire per un periodo. Grazie mille fin da ora da parte della mia famiglia. Il mio paese è Bolognola nell''epicentro. Contattare Daniela Cecchini.'
indirizzo: 'Strada Provinciale 47 Fiastra - Bolognola, Bolognola, MC, Marche, 62033, Italia'
lat: '42.994904'
lon: '13.2263425'
link: ''
immagine: ''
data: 13/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Stufa donata la scorsa settimana dall'associazione Alpini di Vicenza, come comunicato via email da Christian Varani.
