### ISSUE TITLE
Richiesta di una stufa elettrica, preferibilmente a pellet a Bolognola, per riscaldamneto in un'appartamento di 70 mq

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2463]
<pre><yamldata>tel: ''
email: christianvarani@gmail.com
cosa: 'Richiesta di una stufa elettrica, preferibilmente a pellet a Bolognola, per riscaldamneto in un''appartamento di 70 mq'
descrizione: 'Serve molto utilmente una stufa elettrica e possibilmente a "pellet", su richiesta della Signora terremotata, che si chiama "Daniela Cecchini" e dei suoi possibili famigliari, perché nel nuovo appartamento di 70 mq circa ricevuto in donazione, manca un riscaldamento necessario e sufficiente e a costi sostenibili economicamente per consumi ad esempio di gas naturale o metano, specialmente per la situazione lavorativa famigliare e personale della stessa Signora in questo periodo.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Daniela Cecchini'
immagine: ''
data: 13/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già inserita
