### ISSUE TITLE
“L’anima dei luoghi, un confronto sulla ricostruzione”

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2479]
<pre><yamldata>titolo_evento: '“L’anima dei luoghi, un confronto sulla ricostruzione”'
data_evento: '17 febbraio 2017'
ora_evento: 'ore 17'
promotore: 'CNA Provinciale di Macerata e CIA Confederazione Italiana Agricoltori organizzano, in collaborazione con il Centro Educazione Ambientale Casa Ecologica'
descrizione: '“Grazie alla disponibilità di autorevoli docenti delle migliori università italiane – spiega il Presidente Provinciale CNA Macerata Giorgio Ligliani – offriremo un’occasione di confronto tra esperti, istituzioni, tecnici e amministratori sul tema della ricostruzione post sisma. Vorremo che ad ascoltare e interloquire con i nostri ospiti fossero tutte quelle figure che saranno chiamate a governare la ricostruzione, per far sì che il lungo processo che abbiamo davanti possa essere consapevole e partecipato ad ogni livello".'
indirizzo: 'Viale Bigioli, San Severino Marche, MC, Marche, Italia'
lat: '43.2298533'
lon: '13.179076'
link: 'http://www.viverecamerino.it/2017/02/15/terremoto-un-confronto-sulla-ricostruzione-a-san-severino/627100/'
data: 14/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
