### ISSUE TITLE
Cercasi furgone e un volontario per trasportare materiale da #Roma a #Visso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2484]
<pre><yamldata>tel: '3479526902 Manuela Fazi'
email: ''
cosa: 'Cercasi furgone con carico 3mt + volontario per caricare il materiale (Roma-Visso)'
descrizione: 'Stiamo CERCANDO un FURGONE con carico per 3 mt per portare del materiale da Roma a Visso. Cerchiamo anche un volontario per caricare il materiale a Roma e portarlo a Visso. Un allevatore ne ha bisogno per mettere in SICUREZZA LA STALLA. Potete contattarmi al 3479526902 Manuela o 3284089801 Massimo, grazie in anticipo.'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: ''
immagine: ''
data: 15/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
La stalla è stata messa in sicurezza, non serve più il furgone.
