### ISSUE TITLE
Nasce Terziario Donna Umbria

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2496]
<pre><yamldata>titolo: 'Nasce Terziario Donna Umbria'
descrizione: 'Terziario Donna Confcommercio è prevalentemente rivolta all’assistenza e consulenza alle imprenditrici del terziario, sui temi legati al mercato del lavoro e le politiche per le pari opportunità, le leggi di finanziamento che riguardano l’imprenditoria femminile, attraverso la predisposizione delle pratiche di incentivazione alle donne che vogliono avviare una nuova attività o implementare un’impresa esistente.'
link: 'http://www.corrieredelleconomia.it/2017/02/07/confcommercio-umbria-nasce-terziario-donna/'
data: 15/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas tu questa inseriresti?

**Comment by cristigalas** [comment]
@chiccap Mah, mi pare che abbia a che fare col terremoto solo indirettamente... lascerei perdere.
