### ISSUE TITLE
36 Bus operator tedeschi in Umbria per rilanciare il turismo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2497]
<pre><yamldata>titolo: '36 Bus operator tedeschi in Umbria per rilanciare il turismo'
descrizione: 'Quattro giorni in Umbria per scoprire le sue ricchezze e vedere con i propri occhi che la regione è pronta ad accogliere i turisti per la prossima stagione. Sono in arrivo 36 Bus operatori tedeschi, per un Educational Tour organizzato da Come To Umbria. I turisti visiteranno Spoleto, Narni, Arrone, Assisi, Perugia e Todi.'
link: 'http://www.confcommercio.umbria.it/post/36-bus-operator-tedeschi-da-domani-in-umbria-per-rilanciare-il-turismo'
data: 15/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap anche questa non so se sia il caso di accettarla, che dici?

**Comment by chiccap** [comment]
No, non è inerente
