### ISSUE TITLE
Nuovi interventi urgenti in favore delle popolazioni colpite dagli eventi sismici

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2509]
<pre><yamldata>titolo: 'Nuovi interventi urgenti in favore delle popolazioni colpite dagli eventi sismici'
descrizione: 'Con il decreto-legge 9 febbraio 2017, n. 8, il legislatore ha introdotto ulteriori e urgenti disposizioni in favore delle popolazioni colpite nel Centro Italia dagli eventi sismici del 2016 e del 2017. Nel presente Documento sono illustrate le principali misure in ambito fiscale contenute nel decreto n. 8 del 2017, tra cui in particolare le disposizioni relative alla sospensione dei termini in materia di adempimenti e versamenti tributari.'
link: 'http://www.fondazionenazionalecommercialisti.it/node/1203'
data: 16/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetterei. Abbiamo segnalato già.

**Comment by chiccap** [comment]
concordo!
