### ISSUE TITLE
Un logo per Chiedi alla polvere - Concorso Creativo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2510]
<pre><yamldata>titolo_evento: 'Un Logo per chiedi alla polvere - Concorso Creativo'
data_evento: '2017-02-16'
ora_evento: ''
promotore: 'Chiedi alla Polvere'
descrizione: 'Dal 13/02/2017 al 26/02/2017 chiediamo a tutti gli amici che hanno fantasia e un po’ di abilità grafica di regalarci una nuova immagine che possa rappresentarci in modo semplice e diretto.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/events/1677801082520403/'
data: 16/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Messa così non la pubblicherei, andrebbe spiegata meglio (chi sono, cosa fanno, ecc.) perchè a chi non li il tutto risulta un po' criptico...
