### ISSUE TITLE
Calcio al Terremoto - Torneo per Saletta di Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2511]
<pre><yamldata>titolo_evento: 'Calcio al Terremoto - Torneo per Saletta di Amatrice'
data_evento: '2017-02-25'
ora_evento: '10:00'
promotore: ''
descrizione: 'Evento sportivo di calcio e di beneficenza dedicato al sostegno della popolazione di Saletta Frazione Di Amatrice (Rieti).'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/events/1423427827702046/'
data: 16/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
C'è già.
