### ISSUE TITLE
Volontario con Furgone

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2512]
<pre><yamldata>tel: '3479526902'
email: mafly66@tiscali.it
cosa: 'Volontario con Furgone'
descrizione: 'Abbiamo URGENTE bisogno di un volontario con furgone che possa trasportare del materiale vicino VISSO presso un allevatore. Sabato 18 febbraio ci aspetta x aiutarlo a risistemare la recinzione fortemente danneggiata causa neve e terremoto. Potete contattare 3479526902 Manuela o 3284089801 Massimo. Grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 16/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già presente
