### ISSUE TITLE
Fino al 23 febbraio a Rimini raccolta di beni e alimenti (anche freschi)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2515]
<pre><yamldata>titolo_evento: 'Aiuti ai terremotati raccolta di tutto dal vestiario al mangiare'
data_evento: '2017-02-23'
ora_evento: '12:00'
promotore: 'Aiuti ai terremotati raccollta di tutto dal vestiario al mangiare'
descrizione: 'Sabato 25 Febbraio scenderemo per dare il nostro aiuto agli amici terremotati. Il nostro obbiettivo come sempre sarà quello di raggiungere direttamente le famiglie più bisognose distribuendo i generi raccolti. Visto la grande necessità abbiamo bisogno x questo viaggio di reperire anche generi alimentari FRESCHI lanciamo l''appello per cercare di raccoglierne più possibile. Vi allego una lista di generi che scarseggiano per garantire un buon assortimento. ACQUA (a grande richiesta) PRIORITA''! FRUTTA (mele arance etc.) PRIORITA''! VERDURA (cavoli verze finocchi insalata etc.....) PRIORITA''! FORMAGGI INSACCATI Carne OLIO DI OLIVA RISO PASTA PANE FRESCO Scottex Tovaglioli Carta igenica Marmellate Succhi Merendine Marmellate NUTELLA Caffe SCATOLAME Tonno Piselli Ceci Fagioli Carne latte e alimentari di ogni genere MANGIMI PER ANIMALI Cani Gatti FIENO IGIENE PERSONALE Saponi Bagno schiuma shampo lamette schiuma da barba Salva slip donna assorbenti dentifricio IGIENE CASA Detersivi pavimento bucato sgrassatori stracci x pavimento secchi scopettoni x straccio Medicinali antidolorifici - tachipirina -antinfiammatori (da banco). Se qualcuno ha generatori/deumidificatori/stufette. Grazie al vostro aiuto possiamo continuare ad aiutare chi ne ha bisogno. RACCOGLIAMO FINO al 23 febbraio ENTRO le ore 12.00 a RIMINI, presso Bar Girasole, Viale Costantinopoli 38 Miramare, 3495560818 Paola. Grazie a tutti'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/Aiuti-ai-terremotati-raccollta-di-tutto-dal-vestiario-al-mangiare-1271979359553587/?ref=timeline_chaining'
data: 16/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
presente e aggiornata
