### ISSUE TITLE
Famiglia di 4 persone cerca roulotte a #Musicchio #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2530]
<pre><yamldata>tel: '348 3043184'
email: TORRESI6777@GMAIL.COM
cosa: 'ROULOTTE   USATA'
descrizione: 'CERCO UNA ROULOTTE, ANCHE USATA, PER UNA FAMIGLIA DI 4 PERSONE DA PORTARE A MUSICCHIO (AMATRICE). È urgente, ci sono bambini.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 18/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap Se ne sta occupando Albertino Pastorino che con la sua associazione Hopeful Giving Onlus dallo scorso agosto ha già consegnato oltre 60 roulotte ai terremotati. Vedi commenti in calce a questo post sul gruppo Facebook https://www.facebook.com/groups/1758670357733881/permalink/1846462342288015/

**Comment by chiccap** [comment]
Grandissimo. Ci aggiorna lui?

**Comment by cristigalas** [comment]
@chiccap spero, io gli ho chiesto di aggiornarci...

**Comment by cristigalas** [comment]
La famiglia ha ricevuto una roulotte come ci segnala Christian Varani per email. Chiudo.
