### ISSUE TITLE
Cercasi modulo abitativo/roulotte/camper ad #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2533]
<pre><yamldata>tel: ''
email: trossi606@gmail.com
cosa: 'cerco modulo abitativo/roulotte'
descrizione: 'Famiglia di 4 persone cerca in donazione modulo abitativo, roulotte o camper, ad Amatrice'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 19/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci segnala via email che la roulotte è stata donata da ha famiglia del Trentino. Chiudo.
