### ISSUE TITLE
Cercasi container per sede e centro operativo Protezione Civile #Isola del #GranSasso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2541]
<pre><yamldata>tel: '347 3388913'
email: protezionecivileisolaemergenze@gmail.com
cosa: 'Container per sede e centro operativo Protezione Civile #Isola del #GranSasso'
descrizione: 'APPELLO: la nuova associazione Protezione Civile Isola Emergenze, nata durante l''emergenza della grande nevicata e terremoto, a Isola del Gran Sasso, in prov. di Teramo, ha urgente bisogno di un container dove fare la sede e il centro operativo di Protezione Civile, in quanto tutti gli edifici comunali sono al momento inagibili. La donazione può anche essere temporanea sotto forma di noleggio, per il tempo necessario fino a quando non si riesce ad avere una sede fissa. Ci hanno lasciato fuori dal cratere nel 2009 e ci hanno lasciati fuori anche stavolta, beffeggiati dal terremoto, dalla neve e dai politici. Ci appelliamo al buon cuore degli italiani aiutateci. Grazie. Preghiamo di contattare protezionecivileisolaemergenze@gmail.com o telefonare al numero 347 3388913 Facciolini Rosetta'
indirizzo: 'SS491, Isola del Gran Sasso d''Italia, TE, Abruzzo, 64045, Italia'
lat: '42.5030579'
lon: '13.6595164'
link: ''
immagine: ''
data: 20/02/2017
</yamldata></pre>

**Comment by facciolini** [comment]
Buonasera, volevo chiedere se gentilmente qualcuno può cambiare la frase
"il nuovo gruppo di Protezione Civile Isola Emergenze"
con 
"la nuova associazione di Protezione Civile Isola Emergenze".
Chiedo scusa, avrei dovuto specificarlo prima. Grazie mille

**Comment by cristigalas** [comment]
@facciolini fatto! Grazie per la precisazione.

**Comment by cristigalas** [comment]
Christian Varani ci segnala che l'associazione è riuscita a reperire una sede.

**Comment by facciolini** [comment]
Bene mi fa piacere.
Non sono più in contatto con la suddetta associazione, per cui non ho altre info per aggiornarvi.
Quell'indirizzo email cmq non è più valido.
Saluti
