### ISSUE TITLE
Generi alimentari

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2543]
<pre><yamldata>tel: '3495560818 paola'
email: ''
cosa: 'Generi alimentari'
descrizione: 'APPELLO PRO TERREMOTATI Sabato 25 Febbraio,scenderemo per dare il nostro aiuto agli amici terremotati. Il nostro obbiettivo come sempre sarà quello di raggiungere direttamente le famiglie più bisognose distribuendo i generi raccolti. Visto la l grande necessità abbiamo bisogno x questo viaggio di reperire anche generi alimentari FRESCHI lanciamo l''appello per cercare di raccoglierne più possibile. Vi Allego una lista di generi che ci scarseggia per garantire un buon assortimento. ACQUA ( a grande richiesta) PRIORITA''!!!!!! FRUTTA (mele arance etc...) PRIORITA'' !!!!! VERDURA(cavoli verze finocchi insalata etc.....)PRIORITA'' !!!!! FORMAGGI INSACCATI /Carne OLIO DI OLIVA RISO PASTA PANE FRESCO Scottex Tovaglioli Carta igenica Marmellate Succhi Merendine Marmellate NUTELLA Caffe SCATOLAME Tonno Piselli Ceci Fagioli Carne latte e alimentari di ogni genere MANGIMI PER ANIMALI Cani Gatti FIENO IGIENE PERSONALE Saponi Bagno schiuma shampo lamette schiuma da barba Salva slip donna assorbenti dentifricio IGIENE CASA Detersivi pavimento bucato sgrassatori stracci x pavimento secchi scopettoni x straccio Medicinali antidolorifici- tachipirina -antinfiammatori (da banco) Se qualcuno ha un generatore /deumidificatori/stufette Grazie al vostro aiuto possiamo continuare ad aiutare chi ne ha bisogno. RACCOGLIAMO FINO al 23 febbraio ENTRO le ore 12.00 presso bar girasole viale Costantinopoli 38 miramare 3495560818 paola.grazie a tutti'
indirizzo: 'Viale Costantinopoli, Miramare, Rimini, RN, Emilia-Romagna, 47924, Italia'
lat: '44.0282063'
lon: '12.6176058'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1848531288747787/?comment_id=1848579195409663&ref=notif&notif_t=group_comment_mention&notif_id=1487598768976687'
immagine: ''
data: 20/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già presente
