### ISSUE TITLE
Crowdfunding per far rinascere L'albero del pane di #Visso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2555]
<pre><yamldata>titolo_evento: 'Facciamo rinascere l''albero del pane di visso'
data_evento: 19/02/2017
ora_evento: ''
promotore: 'Fabio Cerri'
descrizione: 'Avevo rilevato il panificio con mia moglie qualche anno fa con non pochi sacrifici investendo tutti i nostri risparmi, lo stavamo ancora pagando ma la cosa non ci preoccupava perchè lavoravamo. Avevamo tanti meravigliosi clienti ma il terremoto del 24 agosto ci ha inflitto un brutto colpo per poi affossarci definitivamente il 26 ottobre. Ora vorremmo recuperare i macchinari e far ripartire in un prefabbricato la nostra attività anche per far continuare a lavorare i nostri 7 dipendenti considerati come componenti della nostra famiglia e aiutare anche l''economia di Visso quasi annientata. Inutile dire di aspettare gli aiuti statali, per quando arriveranno saremo tutti in "pensione", quindi proviamo a rialzarci con le nostre deboli forze. Aiutateci a dare linfa al nostro Albero. Facciamo rinascere l''Albero del pane di Visso. Grazie. Fabio Cerri.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.produzionidalbasso.com/project/facciamo-rinascere-lalbero-del-pane-di-visso/'
data: 20/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Crowdfunding chiuso.
