### ISSUE TITLE
Cercasi trasporto 200 sedie e 100 banchi da Portogruaro a scuole di #Montefortino e #Montemonaco

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2560]
<pre><yamldata>tel: '3664008466'
email: maggi.monica@gmail.com
cosa: 'trasporto PORTOGRUARO-MARCHE (MONTEFORTINO)'
descrizione: 'Cerchiamo trasporto per 200 sedie e 100 banchi scolastici da Portogruaro (Venezia) a Montefortino (Fermo). Verranno collocati nelle scuole di Montefortino e Montemonaco. Grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Trasporto trovato: Ala di Trento trasporterà banchi e sedie lunedì come comunicato via Twitter dall'associazione Libra 2.0 https://twitter.com/libra2puntozero/status/834085268495937537

**Comment by cristigalas** [comment]
Qui il racconto di come è andata https://libraduepuntozero.wordpress.com/2017/03/01/200-sedie-e-100-banchi-in-dono-alle-marche-un-ex-istituto-professionale-del-veneto-offre-una-ditta-trentina-carica-e-le-marche-accolgono-ecco-come-funziona-la-solidarieta-in-rete/
