### ISSUE TITLE
Librotrekking solidale: Bukowski alle cascate di #Cerveteri per #Saletta

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2565]
<pre><yamldata>titolo_evento: 'Librotrekking solidale: Bukowski alle cascate di Cerveteri'
data_evento: 26/02/2017
ora_evento: '9:30'
promotore: 'Campareconipiedi Librotrekking'
descrizione: 'Domenica 26 febbraio non perdete una bellissima giornata tra natura, cultura e solidarietà. Campareconipiedi Librotrekking vi invita ad ammirare la bellezza delle cascate di Cerveteri e il fascino della Via degli Inferi. Durante le pause leggeremo le più belle poesie di Charles Bukowski e alcuni brani dal libro “Il capitano è fuori a pranzo”. Il ricavato di questa affascinante escursione sarà devoluto al Comitato Ricostruiamo Saletta, a sostegno dei progetti di utilità sociale da realizzare nella frazione Saletta di Amatrice, distrutta dal terremoto del 24 agosto. Info e prenotazioni su Campareconipiedi Librotrekking e al link https://www.facebook.com/events/1047043222066731/'
indirizzo: 'Via Sepolcrale Principale, Vigna della Casa, Cerveteri, RM, Latium, 00052, Italien'
lat: '42.0040364'
lon: '12.09576690556'
link: 'https://www.facebook.com/events/1047043222066731/'
data: 21/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap questo non lo avrei inserito in bollettino...

**Comment by chiccap** [comment]
Io tutte le iniziative a sostegno di associazioni/comitati/aziende locali le invio sempre al bollettino...sbaglio? Tu quale criterio usi? Dovremmo cominciare a fare una bozza di "vademecum"

**Comment by cristigalas** [comment]
@chiccap tendenzialmente invio al bollettino eventi che abbiano una certa rilevanza ma, hai ragione, bisognerebbe condividere una sorta di vademecum...
