### ISSUE TITLE
fieno per allevatore

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2575]
<pre><yamldata>tel: '3408440284'
email: d.bergagna@gmail.com
cosa: 'fieno per allevatore'
descrizione: 'Antonella Bombini 16 febbraio alle ore 15:39 · Roma · Chiedo a tutti ...avete conoscenze da tutta Italia per fare arrivare del fieno a CANTIANO vicino gubbio ho un allevatore in gravi difficolta ci sono 60 bestie affamate vi prego dategli una mano contattatemi e vi metto in contatto diretto grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas da verificare, che io sappia Cantiano non è nel cratere.

**Comment by cristigalas** [comment]
@chiccap sì, credo anch'io. Comunque le invio una email per avere ulteriori informazioni.

**Comment by chiccap** [comment]
hanno inviato una nuova richiesta per lo stesso allevatore, ho fatto una ricerca ed è nel cratere. accettato quella nuova, chiudo

**Comment by cristigalas** [comment]
Sì, hanno infatti risposto alla email che gli avevo inviato...

**Comment by cristigalas** [comment]
@chiccap scusa Chiara, ho visto la nuova segnalazione ma nella mail di risposta ci dicono di parlare con Antonella Bombini, che è poi quella che ha inserito la segnalazione, e ci hanno scritto lo stesso cellulare indicato nella segnalazione 3408440284, sottolineando che la situazione è drammatica. Ora vedo che la nuova segnalazione rimanda al Popolo dei terremotati. Forse varrebbe la pena parlare direttamente con questa Bombini per inquadrare meglio la situazione ed eventualmente capire come muoverci. Che ne dici?

**Comment by chiccap** [comment]
sì, hai ragione. proviamo a chiamarla domattina?

**Comment by cristigalas** [comment]
@chiccap sì direi che è meglio parlarci di persona ed eventualmente se la situazione è davvero grave forse bisognerebbe fare pressione su Coldiretti o CIA. Puoi chiamarla tu?

**Comment by chiccap** [comment]
certo poi ti aggiorno!

**Comment by cristigalas** [comment]
Ok, grazie! Comunque se serve, in posta TCI trovi lo scambio email...
