### ISSUE TITLE
Cercasi alloggio in provincia di #Ancona

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2577]
<pre><yamldata>tel: '3490905691'
email: federy82@gmail.com
cosa: 'cercasi alloggio'
descrizione: 'Una coppia di Cingoli (An) cerca un alloggio perché la loro casa è stata dichiarata inagibile. Io non posso farlo purtroppo, se qualcuno è disponibile mi contatti.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mandata mail per avere info.

**Comment by chiccap** [comment]
Stanno consegnando le casette, non hanno più bisogno.
