### ISSUE TITLE
Ad #Amatrice serve un box doccia per alloggio provvisorio 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2580]
<pre><yamldata>tel: '3248824117'
email: christianvarani@gmail.com
cosa: 'Richiesta utile ed urgente di un "Box" piatto da sistemare per Doccia ad Amatrice'
descrizione: 'Ad Amatrice serve un box doccia per un alloggio provvisorio con più persone. Per donazioni o ulteriori informazioni si può contattare Christian Varani, volontario della Protezione Civile, ai recapiti indicati.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta come comunicato via email da Christian Varani.
