### ISSUE TITLE
Cercasi tettoia 6x8 e piccolo pollaio #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2585]
<pre><yamldata>tel: '324784162'
email: ''
cosa: 'Roulotte, tettoia 6x8 e piccolo pollaio'
descrizione: 'WWF Umbria chiede aiuto per una famiglia di allevatori di Amatrice che è riuscita a trovare una roulotte e a tornare vicino ai propri animali ma adesso sta cercando una tettoia 6x8 e un piccolo pollaio. Per contatti: Massimo, 324784162.'
indirizzo: 'Piazza Cacciatori del Tevere, Casalene, Amatrice, RI, Lazio, 02012, Italia'
lat: '42.6292367'
lon: '13.2891755'
link: 'https://www.facebook.com/wwfumbria/posts/705489729657117'
immagine: ''
data: 22/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Aggiornata segnalazione con riferimento telefonico che WWF Umbria mi ha inviato via Messanger.

**Comment by cristigalas** [comment]
Christian Varani ci scrive per email che la roulotte è stata consegna il 1/03 grazie a Cristina Fustinoni e al gruppo "Caravanisti e Camperisti solidali". Quindi ora la richiesta è solo per pollaio e tettoia. Aggiorno testo issue.
