### ISSUE TITLE
Cercasi modulo abitativo/camper #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2586]
<pre><yamldata>tel: '3471738524'
email: fauro@inwind.it
cosa: 'Cercasi modulo abitativo/camper Amatrice'
descrizione: 'Cercasi modulo abitatvo o camper per 2 persone ad Amatrice'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani comunica via email che la richiesta è stata soddisfatta con una donazione di una roulotte.
