### ISSUE TITLE
Cercasi cibo per animali a #Cantiano (Marche)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2587]
<pre><yamldata>tel: '3472869633'
email: eurosportello@aeceuropa.eu
cosa: 'Cibo per animali - Cantiano'
descrizione: 'Allevatore di Cantiano (Marche): stalle piegate sotto il peso della neve e 60 animali stremati e affamati, cavalle e mucche partorienti, vitellini, bufali, pecore, capre e agnelli, tutti in attesa di cibo.'
indirizzo: 'Via Martiri della Resistenza, Cantiano, PU, Marche, 61044, Italia'
lat: '43.4743093'
lon: '12.6288151'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1849532775314305/'
immagine: ''
data: 22/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Il referente del gruppo Il Popolo dei Terremotati ci ha fatto sapere che il sindaco di Cantiano si è mosso per dare un aiuto concreto a questo allevatore. Chiudo.
