### ISSUE TITLE
Cercasi nuova sistemazione, anche transitoria nel centro-nord Italia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2592]
<pre><yamldata>tel: '3938908113'
email: menichelli.paolo@tiscali.it
cosa: 'cerco nuova sistemazione, anche transitoria (casa con annessi)'
descrizione: 'Nel centro/nord Italia (preferibilmente, ordine di opportunità logica e funzionale al mio lavoro, Marche, Umbria, Toscana, Emilia Romagna, Veneto, Lombardia), cerco in affitto transitorio o similare ( poiché in caso diverso perderei i diritti di eventuale rientro sull''immobile attuale dopo il ripristino), o meglio ancora in cambio di lavori di sistemazione, appartamento / immobile tipo casa di campagna o similare con : - Abitazione senza mobili o solo parzialmente arredata con bagno, 1 camera , 1 zona studio/uffico (per le mie attività professionali) e 1 zona cucina/ soggiorno /pranzo con spazio per eventuali ospiti su divano letto, (usualmente circa 60/80 mq) + - Zona laboratorio/magazzino/deposito/garage/annesso agricolo (purché chiuso e sano) per un totale minimo di 100/150 mq per tutte le attezzature, materiali, documenti, libri etc. di cui ancora dispongo. Molto riguarda direttamente o indirettamente il mio lavoro ovvero la sostenibilità ambientale, il riciclo, il recupero dei materiali e le tecnologie innovative per il risparmio energetico (ho materiali, attrezzature e libri tecnici di cui vorrei poter continuare ad usare per i miei lavori ed esperimenti, poiché in parte sono oramai introvabili) + - Minimo giardino/spazio recintato o simile per il cane (buono ma di grossa taglia), eventuale orto e lo spazio per parcheggiare in zona privata la roulotte che mi hanno prestato finché non la riprendono o la riporto (in zona Torino). Sono disponibile a valutare tutte le possibili soluzioni, anche di abitazioni "abitabili" ma da ristrutturare radicalmente, potendo occuparmi personalmente dei lavori (impiantistica elettrica e idraulica, riscaldamento, falegnameria, muratura etc.) accordandomi in merito con i proprietario, eventualmente anche cogliendo l''occasione per implementare soluzioni innovative.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Mandata mail per sapere se cerca ancora.

**Comment by chiccap** [comment]
Sta ancora cercando e utilizza la nostra pagina alloggi ogni 2 mesi per vedere se ci sono novità. Io rilancerei, che ne dici?

**Comment by cristigalas** [comment]
Via email ci ha informato che ha trovato un alloggio non lontano da Cingoli. Chiudo.
