### ISSUE TITLE
Ad Annifo, frazione montana de

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2596]
<pre><yamldata>tel: ''
email: ''
descrizione: 'Ad Annifo, frazione montana del comune di Foligno nella quale vivo e sita a 15 minuti scarsi di auto da Muccia, 20 da Pieve Torina e 30 scarsi da Camerino, ci sono una trentina di case in muratura costruite ed urbanizzate per il terremoto del ''97 e lasciate nel più totale abbandono dall'anno più anno meno, 2003. Oltre a queste, esistono un''altra trentina di casette di legno di cui forse una quindicina affittate come seconda casa vacanza e dunque abitate per un mese all''anno e completamente disabitate per i restanti 11 mesi. A Novembre, come abitanti della frazione, denunciammo la cosa tramite social pubblicando alcune delle foto che vedete e dopo qualche giorno, dopo anni di assenza, improvvisamente e magicamente apparvero a dare una ripulita degli omini armati di decespugliatori, motoseghe ecc ecc. e provenienti da..... comune di Foligno? Provincia di Perugia? Regione Umbria? Pianeta Terra? Galassia Andromeda? La nostra speranza era che, da chiunque fossero stati mandati, ripristinassero velocemente l''abitabilità al fine di permettere a qualcuno di voi di poter passare almeno l''inverno dentro una casa in muratura situata a 15-20-30 minuti dal proprio paese al posto di dover magari arrivare sull''Adriatico oppure dormire all''agghiaccio in una tensostruttura o in camper. Invece, passati 3 mesi (Febbraio), tutto tace nuovamente nel completo abbandono e silenzio. In serata ho mandato una mail per conoscenza anche ai sindaci di Pieve Torina e Muccia, che sono i comuni a noi più vicini.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 23/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap che facciamo? Accettiamo? La inserita qualcuna delle volontarie AA?

**Comment by chiccap** [comment]
Sì l'ha inserita una volontaria... anche io ho dubbi sull'accettazione.

**Comment by cristigalas** [comment]
Beh, se l'ha inserita una volontaria allora lascerei perdere, più complicato era non accettarla se l'avesse inserita un utente del sito... che dici?

**Comment by chiccap** [comment]
hai ragione, chiudo!
