### ISSUE TITLE
Cercasi roulotte #Arquata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2604]
<pre><yamldata>tel: '3472869633'
email: ''
cosa: 'Richiesta di aiuto. Un aiuto per il #popolo dei terremotati'
descrizione: 'Alessandra, terremotata di Arquata, chiede aiuto per una roulotte per lei e sua madre: “non possiamo permetterci di pagare un affitto” commenta e ringrazia anticipatamente quanti potranno darle una mano a risolvere questo loro grave problema. Per avere il numero diretto contattateci sul nostro cellulare 3472869633 grazie'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1850769768523939/?comment_id=1850841928516723&notif_t=group_comment_mention&notif_id=1487942809612470'
immagine: ''
data: 24/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che una roulotte da Grosseto è stata consegnata ad Arquata grazie al gruppo dei Caravanisti Solidali, vedi qui https://www.facebook.com/groups/CARAVANISTISOLIDALI/permalink/1860419227540063/
