### ISSUE TITLE
Vincenzo Correnti: il mio Henghel per la musica di #Camerino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2606]
<pre><yamldata>titolo_evento: 'Vincenzo Correnti: il mio Henghel per la musica di #Camerino'
data_evento: 01/01/1970
ora_evento: ''
promotore: ''
descrizione: ''
indirizzo: ''
lat: ''
lon: ''
link: 'http://laperonza.blogspot.it/2017/02/vincenzo-correnti-il-mio-henghel-per-la.html?spref=fb'
data: 24/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
incompleta
