### ISSUE TITLE
#calcioalterremoto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2612]
<pre><yamldata>titolo_evento: '#calcioalterremoto'
data_evento: 25/02/2017
ora_evento: '10:00'
promotore: ''
descrizione: 'Evento sportivo di calcio e di beneficenza dedicato al sostegno della popolazione di Saletta Frazione Di #Amatrice (Rieti).'
indirizzo: 'Via San Gaggio, Belpoggio, Municipio Roma III, Roma, RM, Lazio, 00188, Italia'
lat: '42.00419035'
lon: '12.5151314181097'
link: 'https://www.facebook.com/events/1423427827702046/'
data: 24/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già inserito
