### ISSUE TITLE
#calcioalterremoto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2613]
<pre><yamldata>chi: '#calcioalterremoto'
descrizione: 'Evento sportivo di calcio e di beneficenza dedicato al sostegno della popolazione di Saletta Frazione Di Amatrice (Rieti).'
intestazione: ''
iban: ''
bic: ''
postale: ''
causale: ''
link: 'https://www.facebook.com/events/1423427827702046/'
email: ''
data: 24/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già presente
