### ISSUE TITLE
Offresi abitazione antisismica

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2617]
<pre><yamldata>tel: ''
email: rossanoschiavi@tiscali.it
descrizione: 'Offresi abitazione antisismica non rifinita internamente per stoccaggio mobilio a 10 Km da Colfiorito - Foligno (PG)'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 25/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già presente
