### ISSUE TITLE
Regalo roulotte ferma a #PortoRecanati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2630]
<pre><yamldata>tel: '3391251111'
email: studiopeloni@tiscali.it
cosa: 'regalo roulotte con eventuale preingresso'
descrizione: 'Buongiorno, io ho una roulotte Elnag molto vecchia, non in grado di camminare, quindi va trasportata con carro attrezzi, ma con vetri nuovi e ben coibentata, all''interno è in buone condizioni ed abitabile. E'' parcheggiata in un camping a Porto Recanati. Ho anche un preingresso che regalo ma che deve essere penso portato con camion o smontato da chi lo sa fare, anche quello in buone condizioni. Regalo tutto ma dobbiamo pensare al trasporto. Ho visto che ci sono associazioni di carrozzieri che hanno messo a disposizione i loro mezzi. Contattemi e troviamo il sistema.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 27/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente. Vedi #2662
