### ISSUE TITLE
Modalità e scadenza per la presentazione delle istanze di sopralluogo con perizia asserverata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2638]
<pre><yamldata>titolo: 'Modalità e scadenza per la presentazione delle istanze di sopralluogo con perizia asserverata'
descrizione: 'Modalità per la presentazione delle istanze di sopralluogo con perizia asseverata: nuova scadenza 13/3/2017: DPC n. 14650 del 27 febbraio 2017: eventi sismici nell’Italia centrale.'
link: 'http://www.officina2630.it/wp-content/uploads/2017/02/DPC-n.-14650-del-272.2017-.-Eventi-sismici-nell%E2%80%99Italia-centrale.-Modalit%C3%A0-e-scadenza-per-la-presentazione-delle-istanze-di-sopralluogo-con-perizia-asseverata.pdf'
data: 28/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
