### ISSUE TITLE
Si cercano abitazioni per gli sfollati di #Castelraimondo (Mc)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2639]
<pre><yamldata>titolo: 'Terremoto: si cercano abitazioni per gli sfollati #Castelraimondo'
descrizione: 'Si cercano alloggi per sfollati. Stanno vivendo una situazione difficile tutti coloro che hanno perso le loro abitazioni, dichiarate inagibili a causa delle scosse sismiche. Proprio per questo il Comune di Castelraimondo lancia un appello a tutti coloro che hanno un’abitazione da poter mettere a disposizione per i terremotati.'
link: 'http://www.maceratanotizie.it/27622/terremoto-si-cercano-abitazioni-per-gli-sfollati'
data: 28/02/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Le persone stanno rientrando piano piano con la consegna delle casette. Chiudo.
