### ISSUE TITLE
Ancona, presentata l’iniziativa a favore di #Visso, #Pievebovigliana e #Belforte del Chienti

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2644]
<pre><yamldata>titolo: 'Ancona, presentata l’iniziativa a favore di #Visso, #Pievebovigliana e #Belforte del Chienti'
descrizione: 'Una donazione effettuata dalla Fondazione Cariverona metterà a disposizione dei tre comuni ingenti risorse'
link: 'http://www.anconanotizie.it/33938/ancona-presentata-liniziativa-a-favore-di-visso-pievebovigliana-e-belforte-del-chienti'
data: 28/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap non accetterei.
