### ISSUE TITLE
Sisma e solidarietà: il gruppo Salini Impregilo dona un'intera scuola a #Valfornace

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2645]
<pre><yamldata>titolo: 'Sisma e solidarietà: il gruppo Salini Impregilo dona un''intera scuola a #Valfornace'
descrizione: 'Una nuova scuola per bambini e ragazzi di Valfornace in provincia di Macerata, comune nato dalla fusione tra i comuni di Pievebovigliana e Fiordimonte, dopo le scosse di terremoto che hanno distrutto o reso inagibili gran parte delle strutture sul territorio nell’area.'
link: 'http://www.viverecamerino.it/2017/02/28/sisma-e-solidariet-il-gruppo-salini-impregilo-dona-unintera-scuola-a-valfornace/628913/'
data: 28/02/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap Io non la accetterei, questo tipo di notizie non ha bisogno di essere promosso da noi...
