### ISSUE TITLE
Politecnico di Torino: droni e scanner a #SanSeverinoMarche

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2647]
<pre><yamldata>titolo: 'Politecnico di Torino: droni e scanner a #SanSeverinoMarche'
descrizione: 'Il Politecnico di Torino in campo a San Severino Marche per i rilievi tecnici, ma anche per le attività di monitoraggio, di due dei più importanti monumenti.'
link: 'http://www.meteoweb.eu/2017/02/terremoto-politecnico-torino-droni-e-scanner-a-san-severino-marche/860606/'
data: 01/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non l'accetterei...
