### ISSUE TITLE
200 SEDIE E 100 BANCHI IN DONO ALLE MARCHE - Un ex istituto professionale del Veneto offre, una ditta trentina carica e le Marche accolgono - Ecco come funziona la solidarietà in rete

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2653]
<pre><yamldata>titolo: '200 SEDIE E 100 BANCHI IN DONO ALLE MARCHE - Un ex istituto professionale del Veneto offre, una ditta trentina carica e le Marche accolgono - Ecco come funziona la solidarietà in rete'
descrizione: '200 SEDIE E 100 BANCHI IN DONO ALLE MARCHE Un ex istituto professionale del Veneto offre, una ditta trentina carica e le Marche accolgono Ecco come funziona la solidarietà in rete 100 banchi e 200 sedie: questo il dono offerto tre giorni fa da un ex istituto professionale con sede a San Donà di Piave a due scuole terremotate nelle Marche, Montefortino vicino Fermo (92 studenti tra materna, primaria e medie) e Montemonaco (Ascoli Piceno) con una dozzina di bimbi alla materna. Il problema da risolvere era il trasporto. Qui la rete (della solidarietà e del web) ha fatto la sua parte. L''Associazione Libra ha lanciato l''appello via social, appello raccolto da una ditta di Ala di Trento che si occupa di trasporti, che si è offerta di andare a recuperare banchi e sedie tra Portogruaro e San Donà di Piave, nella sede dell''ex istituto professionale. Il tutto è stato caricato martedì 28 febbraio pomeriggio su un tir di 12 metri e dopo 12 ore scaricato nella scuola di Montefortino. Che avranno finalmente un arredo nuovo per le classi. Info 366-4008466 centro.culturale.libra@gmail.com'
link: 'https://libraduepuntozero.wordpress.com/2017/03/01/200-sedie-e-100-banchi-in-dono-alle-marche-un-ex-istituto-professionale-del-veneto-offre-una-ditta-trentina-carica-e-le-marche-accolgono-ecco-come-funziona-la-solidarieta-in-rete/'
data: 01/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap come sempre, non credo sia da accettare...
