### ISSUE TITLE
Norcia, il campanile della basilica di San Benedetto è finalmente al sicuro

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2656]
<pre><yamldata>nom: 'Vigili del Fuoco - Comune di Norcia'
tel: ''
email: ''
cosa: 'Norcia, il campanile della basilica di San Benedetto è finalmente al sicuro'
descrizione: 'Completata dai vigili del fuoco la messa in sicurezza della struttura. Il Comune ha reso noto sul proprio sito internet l''elenco dei primi edifici dichiarati agibili. Oggi l''inaugurazione di due nuovi container collettivi. Risultano circa 500 le case agibili nell’intero territorio comunale.'
indirizzo: 'Piazza San Benedetto, Casa Coletti, Norcia, PG, Umbria, 06046, Italy'
lat: '42.7927706'
lon: '13.0930812'
data: 01/03/2017
fonte: ''
link: 'http://www.comune.norcia.pg.it/2017/02/28/pubblicati-esiti-fast-edifici-agibili-e-non-agibili/'
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap dobbiamo chiarirci con Lorenzo Perone se queste sono notizie che interessano oppure no perchè io, ad esempio, questa non la acceterei... Gli scrivo subito nel gruppo Telegram.
