### ISSUE TITLE
Regalo roulotte Elnag 4/5 posti

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2664]
<pre><yamldata>tel: '3391251111'
email: studiopeloni@gmail.com
cosa: 'Regalo roulotte Elnag 4/5 posti'
descrizione: 'Roulotte Elnag 4/5 posti molto grande. Vecchia ma con vetri nuovi, ben coibentata interno tenuto benissimo non entra ne umidità ne altro, da trasportare, non in grado di camminare. Eventuale preingresso da smontare o trasportare 5mtx220 con bagno in buono stato. Se ci fosse qualcuno interessato anche in grado di organizzare il trasporto sarei ben lieta di donare tutto. Altrimenti va tutto al macero ed è un peccato non poter aiutare. Contattatemi in privato.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/photo.php?fbid=10210495057124353&set=pcb.1853641604903422&type=3&theater'
immagine: 'http://i.imgur.com/tkUNGAI.jpg'
data: 02/03/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già inserita
