### ISSUE TITLE
Giunta #Abruzzo proroga l’esenzione dal ticket per i comuni del cratere

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2665]
<pre><yamldata>titolo: 'Terremoto: Giunta Abruzzo proroga l’esenzione dal ticket per i comuni del cratere'
descrizione: 'La Giunta regionale ha esteso fino al prossimo 30 giugno l’esenzione dal pagamento dei ticket sanitari per i cittadini abruzzesi residenti nei centri del cratere sismico. La delibera relativa alla proroga, proposta dell’assessore alla programmazione sanitaria Silvio Paolucci, riguarda non solo i centri in cui l’esenzione era gia’ in vigore dal settembre scorso (Montereale, Capitignano, Campotosto, Valle Castellana, Rocca Santa Maria), ma anche quelli ricompresi successivamente nel cratere (Teramo, Cortino, Crognaleto, Montorio al Vomano, Campli, Castelli, Civitella del Tronto, Torricella Sicura e Tossicia). L’esenzione puo’ essere richiesta in tutte le farmacie convenzionate, e riguarda sia la partecipazione degli assistiti alla spesa farmaceutica, sia anche l’eventuale quota dovuta sui medicinali equivalenti che non si adeguano al prezzo di riferimento regionale. Sulla base di accordi con le Regioni Marche e Umbria, all’agevolazione possono accedere anche i residenti in queste regioni e temporaneamente domiciliati in Abruzzo. In questo caso, pero’, i termini per usufruire dell’esenzione sono fissati rispettivamente al 30 aprile e al 31 marzo prossimi.'
link: 'http://www.meteoweb.eu/2017/03/terremoto-giunta-abruzzo-proroga-lesenzione-dal-ticket-comuni-del-cratere/863528/'
data: 02/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
C'era già...

**Comment by chiccap** [comment]
allora chiudo, non me n'ero accorta!
