### ISSUE TITLE
Cercasi aiuto nel trasporto di libri, giochi e strumenti musicali per ludoteca a #Montefortino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2675]
<pre><yamldata>tel: '3664008466'
email: maggi.monica@gmail.com
cosa: 'Cercasi aiuto nel trasporto di libri, giochi e strumenti musicali per ludoteca a #Montefortino'
descrizione: 'L''associazione Libra cerca aiuto per Montefortino (Fermo), uno dei paesi colpiti dal terremoto. Qui Libra sta allestendo una ludo-biblioteca e chiede aiuto per portare libri, giochi, strumenti musicali e altro ancora da Riano (Roma) a Montefortino. C''è bisogno di 2 auto grandi o 1 furgoncino. Partenza prevista nella settimana 13-19 marzo. Contatto Monica Maggi.'
indirizzo: 'Via A. Petetta, Montefortino, FM, Marche, 63858, Italia'
lat: '42.9430952'
lon: '13.3448312'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1855451181389131/'
immagine: ''
data: 06/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Trasporto trovato vedi tweet https://twitter.com/libra2puntozero/status/841163942487547904 chiudo.
