### ISSUE TITLE
Cercasi aiuti: frigorifero, stufa a legna, fornelli, letto, tavolo, alimenti di qualsiasi genere

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2738]
<pre><yamldata>tel: '3485440004'
email: hoana@outlook.it
cosa: 'Aiuti del genere abitativo, frigorifero, stufa  a legna, stufa per cucinare, letto ,tavolo, alimenti  di qualsiasi genere'
descrizione: 'Siamo sfollati, quattro persone, madre, padre, una ragazzina e una persona anziana. Casa non è più agibile e abbiamo un esercizio commerciale che ora è completamente distrutto, noi siamo rimasti in un garage sotto casa, ma fa molto freddo e dormiamo ancora in macchina. Non possiamo più resistere, anche perché la ragazza è malata di diabete, insulina dipendente. Se qualcuno ci può aiutare con generi e beni di prima necessità. Abbiamo bisogno di: frigorifero, stufa a legna, stufa per cucinare, letto, tavolo, alimenti di qualsiasi genere. Saremo molto grati a coloro che hanno ancora nel cuore un po'' di umanità perché i comuni non hanno preocupazione per noi. Gli aiuti arrivati se li spartiscono tra di loro. Aiutateci!'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 16/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap invio email per chiedere ulteriori informazioni, ad esempio rispetto al luogo dove vivono, e poi semmai accettiamo.

**Comment by chiccap** [comment]
mai avute notizie? come procediamo?

**Comment by cristigalas** [comment]
@chiccap potremmo inviare una mail e chiedere se e cosa hanno ricevuto ed eventualmente chiudere.

**Comment by chiccap** [comment]
Mando io!

**Comment by chiccap** [comment]
Non hanno mai ricevuto nulla ma hanno provveduto in autonomia. Sono di Muccia (MC).
