### ISSUE TITLE
*Cercasi urgentemente* PC PORTATILE per Comitato Volontari Sisma (CVS) #PortoSElpidio

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2740]
<pre><yamldata>tel: '3395313809'
email: ''
cosa: 'Pc portatile'
descrizione: 'Mi chiamo Gabriele e sono di Visso, paese distrutto dal terremoto. Chiedo gentilmente un pc per poter seguire il lavoro del comitato di volontari che stiamo cercando di tirare su dopo il sisma.'
indirizzo: 'Via San Giovanni Bosco, Porto Sant''Elpidio, FM, Marche, 63018, Italia'
lat: '43.2589619'
lon: '13.7569828'
link: ''
immagine: ''
data: 17/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap abbiamo notizie?

**Comment by chiccap** [comment]
Gabriele ha ricevuto due proposte di donazione per il pc. Una da un pvt di Jesi ed una da un'associazione dell'Aquila che ha dei fondi da impiegare per queste iniziative. Carloni sceglierà la seconda opzione perché può chiedere il tipo di pc che vuole e gli verrà fatto un bonifico per permettergli di  comprarlo nuovo. Domani lo incontro e mi dirà! Appena so i dettagli aggiorno issue.

**Comment by cristigalas** [comment]
Ok ottimo @chiccap!

**Comment by chiccap** [comment]
Donazione effettuata oggi da Rete Attiva AQ, segnalato da Francesca Tarantino sia tramite commento sul sito che con commento alla segnalazione sul gruppo fb.
