### ISSUE TITLE
Cercasi Water per un Modulo abitativo ad #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2752]
<pre><yamldata>tel: '3248824117'
email: christianvarani@gmail.com
cosa: 'Richiesta necessaria di un water da bagno per un Modulo abitativo ad Amatrice'
descrizione: 'Serve urgentemente un water completo da bagno per un modulo abitativo provvisorio (casetta) ad Amatrice. Per maggiori informazioni contattare Christian Varani, volontario della Protezione Civile locale, ai recapiti specificati.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta soddisfatta come comunicato via email da Christian Varani.
