### ISSUE TITLE
Cercasi friggitrice per riapertura "Taverna del Ponte" #Visso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2753]
<pre><yamldata>tel: ''
email: latavernadelponte@gmail.com
cosa: 'Cercasi friggitrice per riapertura "Taverna del Ponte" #Visso'
descrizione: 'La proprietaria Lisa Maria Cetorelli e la sua famiglia hanno investito tutti i capitali che avevano e oltre per la riapertura della “Taverna del Ponte” di Visso in sede mobile. Sono quasi pronti ma avrebbero un disperato bisogno di una friggitrice a gas, anche usata. Chiunque potesse aiutarli, li contatti via mail a questo indirizzo: latavernadelponte@gmail.com oppure qui su Facebook Lisa Maria Cetorelli. Amici è davvero importante, chiunque riapra un’attività nei nostri Comuni rappresenta la più immediata speranza di rinascita e scongiura lo spopolamento di questi luoghi magici. Grazie.'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: ''
immagine: ''
data: 20/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci informa via email che il ristorante ha trovato la friggitrice.
