### ISSUE TITLE
Cercasi camion gru per trasporto roulotte #AcquasantaTerme

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2756]
<pre><yamldata>tel: ''
email: ''
cosa: 'Cercasi camion gru per trasporto roulotte #AcquasantaTerme'
descrizione: 'Cerco disponibilità di camion gru per portare una roulotte da Stienta (Rovigo) ad Acquasanta Terme (Ascoli P.) da dare a una famiglia di allevatori che hanno perso la casa. Il trasporto sarebbe da farsi sabato prossimo 25 marzo. Possiamo rimborsare autostrada e carburante.'
indirizzo: 'Strada Statale 4 Via Salaria, Acquasanta Terme, AP, Marche, 63095, Italia'
lat: '42.769944'
lon: '13.410185'
link: 'https://www.facebook.com/paolo.campagnoli3/posts/10155005638418950'
immagine: ''
data: 20/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
L'ho segnalata via Facebook a Cristina Fustinoni di Caravanisti Solidali.

**Comment by cristigalas** [comment]
Christian Varani via email ci comunica che hanno il 25 marzo la roulotte è stata consegnata insieme a beni alimentari, grazie alla collaborazione del Gruppo di Finale "Cuciniamo con Amore", dei volontari di un Gruppo AVIS e di altri volontari di Mirandola.
