### ISSUE TITLE
Offresi appartamento in casa colonica tra Macerata e Corridonia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2757]
<pre><yamldata>tel: '3393953939'
email: roberta.bianconi@yahoo.it
descrizione: 'Ho un appartamento disponibile al primo piano di una casa colonica. Zona fra Macerata e Corridonia. Può andare bene per persone sopra i 50 anni e se automunite..Non va bene se ci sono bambini, vicino ci sono un fiume e un lago e possono essere pericolosi. Possibilità di ospitare anche cane o gatto.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 20/03/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Nessun contatto, non più disponibile.
