### ISSUE TITLE
Arci

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#282]
<pre><yamldata>chi: Arci
descrizione: 'La cultura per la ricostruzione, crowdfunding per il Bibliobus. Inoltre si può donare su c/c Banca Etica'
intestazione: ''
iban: 'IT 36 A 0501803200 000000000041'
bic: ''
postale: ''
causale: 'Terremoto Centro Italia'
link: 'https://www.produzionidalbasso.com/project/bibliobus-arci-la-cultura-per-la-ricostruzione/'
email: ''
data: 14/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
issue doppia
