### ISSUE TITLE
Sosteniamo e ricostruiamo l'Albero del Pane di #Visso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2821]
<pre><yamldata>titolo: '...per fare un albero ci vuole il pane. Ricostruiamo l''Albero del Pane di Visso'
descrizione: 'Mi chiamo Fabio e insieme a mia moglie Lina abbiamo aperto il nostro forno, L’Albero del Pane a Visso (MC), nel 2005. Nel corso degli anni abbiamo pian piano fatto crescere la varietà dei nostri prodotti e le persone di staff. Siamo partiti dal pane per poi aggiungere pizza e dolci da forno. La nostra vita e il nostro lavoro si sono fermati al 30 ottobre. Dopo qualche giorno di smarrimento abbiamo fatto il punto della situazione: diversi macchinari e arredi distrutti dalle macerie. Dobbiamo ancora recuperare qualche macchina, il lavoro di recupero è faticoso, pericoloso e fatto da ditte specializzate. Dobbiamo ricomprare l’arredo del negozio e gli scaffali…Vogliamo far rinascere l’Albero del pane e con lui una parte dell’economia e del tessuto sociale dei nostri Borghi feriti.'
link: 'https://www.produzionidalbasso.com/project/per-fare-un-albero-ci-vuole-il-pane-ricostruiamo-lalbero-del-pane-di-visso/'
data: 22/03/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas da tenere in stand-by perchè i promotori vogliono prima farla girare "internamente".

**Comment by chiccap** [comment]
@cristigalas ricostruzione privata?

**Comment by cristigalas** [comment]
Crowdfunding chiuso.
