### ISSUE TITLE
Cercasi casa mobile su ruote #Visso

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2822]
<pre><yamldata>tel: '3479119735'
email: silviavagni@vodafone.it
cosa: 'Casa mobile su ruote a Visso'
descrizione: 'Cerco urgentemente casa mobile su ruote, 5 posti letto, per la mia famiglia a Visso, da poter collocare in giardino. Le casette tardano ad arrivare, case in affitto non si trovano se non nel raggio di 60/70 km. Vogliamo tornare a casa ma la nostra è gravemente lesionata, sarà per noi motivo di gioia anche solo sistemarci in giardino. Grazie di cuore a chi vorrà aiutarci in questo momento così difficile.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica che la richiesta di può chiudere perché non c'è più bisogno di una casetta mobile.
