### ISSUE TITLE
In arrivo un campus per tutte le scuole superiori di Tolentino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2830]
<pre><yamldata>titolo: 'In arrivo un campus per tutte le scuole superiori di Tolentino'
descrizione: 'Si è svolto nel tardo pomeriggio di lunedì 20 marzo in Regione, l’incontro per la realizzazione di un campus scolastico a Tolentino. Grazie a questa riunione è stato possibile finalizzare l’accordo per la creazione di una sede per tutte le scuole superiori del comune fortemente colpito dal sisma del 26-30 ottobre. I partecipanti hanno sottolineato più volte l’importanza di donare una nuova sede agli studenti della città, con il liceo classico, il coreutico e scientifico, l’istituto tecnico-economico e il professionale.'
link: 'http://www.maceratanotizie.it/28148/terremoto-in-arrivo-un-campus-per-tutte-le-scuole-superiori-di-tolentino'
data: 23/03/2017
</yamldata></pre>

**Comment by chiccap** [comment]
già presente!
