### ISSUE TITLE
Cercasi per volontari un B&B sulla tratta ascoli-amatrice con disponibilità per il 22-23 aprile

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2838]
<pre><yamldata>tel: ''
email: ''
cosa: 'Cercasi per volontari un B&B sulla tratta ascoli-amatrice con disponibilità per il 22-23 aprile'
descrizione: 'Volontari cercano B&B sulla tratta ascoli-amatrice per la notte del 22-23 aprile, max 50 a camera doppia. Serve come appoggio per consegna beni da eseguire in zona.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1865533770380872/'
immagine: ''
data: 24/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Alloggio trovato ad Ascoli, come comunicato via email da Christian Varani.
