### ISSUE TITLE
TM Italia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2841]
<pre><yamldata>chi: 'TM Italia'
descrizione: 'TM Italia LAB per il cuore d''Italia. Le icone di TM Italia nel progetto di solidarietà per il futuro delle zone colpite dal sisma del centro Italia. Innovare è anche questo: mettere a disposizione la propria ricerca per il beneficio collettivo. Quattro pezzi unici, con contenuti altamente innovativi, saranno venduti sulla piattaforma Archiproducts. Per ognuno di essi l’azienda devolverà un importo di 5.000€ in progetti a valore sociale destinati alle comunità marchigiane colpite dal sisma, che hanno estremo bisogno di riaggregarsi intorno ai propri borghi.'
intestazione: 'tm Italia srl'
iban: iT50T0200813507000040319914
bic: ''
postale: ''
causale: 'TM Italia LAB per il cuore d’Italia'
link: 'http://www.tmitalia.it/lab-cuore-italia/'
email: info@tmitalia.com
data: 26/03/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
c'è gia, vedi #2730. Chiudo.
