### ISSUE TITLE
Ad #Amatrice in funzione nuovo pass

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2873]
<pre><yamldata>titolo: 'Ad #Amatrice in funzione nuovo pass'
descrizione: 'E’ in funzione dallo scorso sabato il nuovo Pass (Posto di assistenza socio sanitaria) di Amatrice. La struttura è lunga 33 metri e si sviluppa su 400 metri quadri. E’ composta da otto container espandibili, undici monoblocchi prefabbricati più altri due per i servizi è ed è cablata per la connessione ad internet. Tutte le unità utilizzate sono coibentate e dotate di impianto di riscaldamento e aria condizionata. Si tratta un complesso solido in grado di operare al meglio con qualsiasi condizione atmosferica. Nel Posto di assistenza socio sanitaria sono attive prestazioni presso l’ambulatorio di medicina generale, quello infermieristico, di continuità assistenziale, di diabetologia, cardiologia e pediatria, oculistica. Attivo anche il servizio di assistenza sociale e di sostengo psicologico ed il punto prelievi.'
link: 'http://lanotiziah24.com/2017/04/regione-terremoto-ad-amatrice-in-funzione-nuovo-pass/'
data: 04/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
