### ISSUE TITLE
Cercasi sistemazione per 70 capre destinate al macello per chiusura attività

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2884]
<pre><yamldata>tel: '3806323851'
email: ''
cosa: 'Cercasi sistemazione 70 capre destinate al macello'
descrizione: 'Stiamo cercando di trovare casa a circa 70 capre destinate al macello per la chiusura dell''azienda in cui si trovano. Cerchiamo anche privati che possano ospitare questi animali compilando un apposito modulo di affido. Il termine è il 10 aprile. Contattare via facebook Anna Galastri o Alessandro Mosso, in alternativa telefonare a Animalisti Onlus al numero 3806323851.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 07/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap bisognerebbe aggiungere la località, potrebbe essere una richiesta che viene da qualsiasi luogo... Hai modo di saperne di più?

**Comment by chiccap** [comment]
Purtroppo no :( era una segnalazione su fb, non li conosco. Possiamo contattare le persone indicate nella segnalazione!

**Comment by cristigalas** [comment]
@chiccap sarebbe meglio, puoi farlo tu?

**Comment by chiccap** [comment]
Ho già scritto al tipo su fb, se non risponde chiamo il numero!

**Comment by chiccap** [comment]
Sentito il signore al numero sulla segnalazione. Non si tratta di una notizia legata al terremoto...scusa @cristigalas ! chiudo? intanto scrivo sotto la segnalazione su fb!

**Comment by cristigalas** [comment]
Sì chiudiamola... (quando non è specificata la località è sempre bene approfondire ;)
