### ISSUE TITLE
biciclette da bambino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2895]
<pre><yamldata>tel: '3929628733'
email: cesaroni.massimo@gmail.com
cosa: 'biciclette da bambino'
descrizione: 'Ho tre biciclette da bambino, usate ma in buone condizioni. Allego le foto. Foto 2'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: 'http://i.imgur.com/2nwX9Wh.jpg'
data: 08/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
