### ISSUE TITLE
vademecun legale sui terremotati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2897]
<pre><yamldata>tel: '3288765972'
email: sofia.cecchini@virgilio.it
cosa: 'vademecun legale sui terremotati'
descrizione: 'Oissa - vademecum redatto dallo studio legale Alterego il mio indirizzo: Sofia Cecchini - Collemoresco -frazione de Comune di Amatrice.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 09/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetto ma invierò una email per capire meglio cosa chieda o segnali.

**Comment by chiccap** [comment]
Vedi issue 2899. Io accetterei solo quella e questa la chiuderei, che dici @cristigalas ?

**Comment by cristigalas** [comment]
Ok! Fai tu? Io sono su mobile.

**Comment by chiccap** [comment]
certo!
