### ISSUE TITLE
Vademecun legale sui terremotati Oissa

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2898]
<pre><yamldata>tel: '3388765972'
email: sofia.cecchini@virgilio.it
cosa: 'Vademecun legale sui terremotati Oissa'
descrizione: 'Oissa - Vademecum legale sui terremotati, il mio indirizzo: Sofia.Cecchini - Collemoresco -frazione Comune di Amatrice oppure Roma Via Paolo Pericoli, 50 00166 è possibile farmelo recapitare?'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 09/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Vedi issue #2897
