### ISSUE TITLE
Situazione al C.O.M.

### ISSUE THREAD

**Issue by milesimarco** [emergenzeHack/terremotocentro_segnalazioni#29]
![Situazione al C.O.M.](https://terremotocentroitalia.mmilesi.ml/wp-content/uploads/telegram-bot/103/1472804379.jpg)
[Link Mappa](http://www.piersoft.it/terremotocentro/#7/42.795469/13.091145)

**Comment by fizzi** [comment]
Presa in carico

**Comment by c83n** [comment]
great!
