### ISSUE TITLE
Ufficio Unico Pianificazione Aree Interne

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2908]
<pre><yamldata>titolo_evento: 'Ufficio Unico Pianificazione Aree Interne'
data_evento: 04/11/2017
ora_evento: '17:00'
promotore: 'Ufficio Unico'
descrizione: 'Ufficio unico pianificazione "Aree Interne" risultati e prospettive per imprese e cittadini.'
indirizzo: 'Via Cesa Piana, Colledimacine, CH, ABR, Italia'
lat: '42.024534'
lon: '14.259115'
link: 'https://www.facebook.com/photo.php?fbid=1660143130677643&set=a.264300780261892.69499.100000459176745&type=3&theater'
data: 11/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas non sono sicura vada inserito

**Comment by cristigalas** [comment]
Sono d'accordo, non lo accetterebbe.
