### ISSUE TITLE
Mostra "Tesori della Valnerina"

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2911]
<pre><yamldata>titolo_evento: 'Mostra "Tesori della Valnerina"'
data_evento: 01/01/1970
ora_evento: ''
promotore: 'Regione Umbria e Ministero dei beni culturali e del Turismo'
descrizione: 'L''esposizione - visitabile fino al 30 luglio - ospita 30 opere provenienti dalle chiese danneggiate dal terremoto e dal Museo della Castellina di Norcia . La mostra è aperta dal martedì alla domenica dalle 9.30 alle 19.30, lunedì dalle 9.30 alle 13.30; aperture straordinarie in occasione di eventi speciali, ponti e festività. Ultimo ingresso 45 minuti prima della chiusura'
indirizzo: 'Piazza Bernardino Campello, Spoleto, Fortilizio dei mulini, Spoleto, PG, Umbria, 06049, Italy'
lat: '42.7339246'
lon: '12.7393844'
link: 'http://www.lanotiziaquotidiana.it/umbria/2017/04/11/rinascita-inaugurata-a-spoleto-la-mostra-tesori-dalla-valnerina/'
data: 12/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Già inserito.
