### ISSUE TITLE
Associazione Animalisti Onlus

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2915]
<pre><yamldata>chi: 'Associazione Animalisti Onlus'
descrizione: 'Abbiamo bisogno urgente di mangime fioccato, erba medica in pellet, fieno e antiparassitari per 17 cavalli di una azienda situata in una frazione di Amatrice. Emanuela Bignami al 392 7015986 che Francesca Bucefala Bucci al 340 1706776.'
intestazione: '''Associazione Animalisti Onlus'' Banca Etica Roma'
iban: 'IT 78 Z 05018 03200 000000 114187'
bic: ''
postale: ''
causale: 'aiuto cavalli amatrice'
link: 'https://www.facebook.com/groups/184616618663358/permalink/284964565295229/'
email: ''
data: 12/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas non mi sembra una raccolta fondi vera e propria, ho accettato in fabbisogni ma qui non accetterei, che dici?

**Comment by cristigalas** [comment]
Non accettare, concordo. Non è raccolta fondi ma fabbisogni.
