### ISSUE TITLE
#Arquata Scuola danneggiata (foto)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#292]
<pre><yamldata>telegram_user: ''
descrizione: 'Scuola danneggiata'
immagine: 'http://i.imgur.com/zTCZhMk.jpg'
lat: '42.776289'
lon: '13.29453'
data: 14/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
La scuola ha subìto ulteriori ingenti danni dopo la scossa del 30/10. Ora è stata demolita.
