### ISSUE TITLE
TERREMOTO : AVVIATA PROCEDURA PER RICOSTRUZIONE EDIFICI SCOLASTICI

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2932]
<pre><yamldata>titolo: 'TERREMOTO : AVVIATA PROCEDURA PER RICOSTRUZIONE EDIFICI SCOLASTICI'
descrizione: 'Avviata la procedura per la ricostruzione di 21 scuole distrutte dagli eventi sismici che hanno devasto l''Italia centrale tra l''agosto 2016 e il febbraio 2017. E'' stata completata, infatti, la progettazione definitiva dei plessi scolastici a cura della struttura commissariale per la ricostruzione in collaborazione con Invitalia. E da ieri e'' online sul sitowww.sisma2016.governo.it, ''l''avviso esplorativo per la formazione di un elenco di esecutori interessati alla realizzazione delle opere di edilizia scolastica di cui all’ordinanza commissariale 14 del 16 gennaio 2017''. In pratica un avviso rivolto ad aziende ed imprese artigianali interessate a partecipare alla costruzione dei 21 plessi scolastici individuati dal commissario straordinario Vasco Errani.'
link: 'http://www.liberoquotidiano.it/news/ultim-ora/12359013/terremoto-avviata-procedura-per-ricostruzione-edifici-scolastici.html'
data: 18/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
