### ISSUE TITLE
Servono 5 bombole GPL campo di Capricchia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#294]
<pre><yamldata>tel: '3420834926'
email: christian.quintili@actionaid.org
cosa: 'Servono 5 bombole GPL campo di Capricchia'
descrizione: 'Non è segnalazione di prova. Servono min 2 max 5 bombole a GPL al campo di Capricchia. Contatto di riferimento Tommaso (3408131341) che ha parlato al telefono con me. Siamo rimasti che lui continua a cercare e io pure tramite voi e chi per primo trova aggiorna l''altro via sms. Così posso chiudere segnalazione se lui fa prima di noi. Grazie'
indirizzo: 'Strada Regionale 577 Lago di Campotosto, Amatrice, RI, Lazio, Italy'
lat: '42.622907318456384'
lon: '13.340749740600586'
link: ''
immagine: ''
data: 14/09/2016
</yamldata></pre>

**Comment by annaluciont** [comment]
SEGNALAZIONE CHIUSA

**Comment by annaluciont** [comment]
Richiedente sensore campo Capricchia a cui fare induction si chiama Tommaso 3408131341
Fornitore: Marzi Nello 3335904576 
Distributore Campotosto che ha donato bombole assieme a moglie Luigina
