### ISSUE TITLE
Zone franche, stop a tasse e contributi. Le nuove misure per il terremoto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2943]
<pre><yamldata>titolo: 'Zone franche, stop a tasse e contributi. Le nuove misure per il terremoto'
descrizione: 'Nelle Zone Franche Urbane che saranno costituite nei comuni del cratere, oltre all’esenzione delle imposte sui redditi fino a 100 mila euro l’anno, di Irap e Imu, è previsto anche l’esonero dei contributi prevdenziali e assistenziali. Lo stabilisce l’articolo 47 del decreto legge varato dal governo l’11 aprile scorso. Sibilla-Online è in grado di pubblicare le norme che riguardano il sisma, contenute nel Titolo III del provvedimento, e che prevedono la proroga di alcune agevolazioni fiscali e l’istituzione di un Fondo da un miliardo di euro l’anno per un triennio. Soldi anche per le case Le risorse del Fondo saranno destinate, nei comuni del cratere, a finanziare le verifiche di vulnerabilità delle scuole e degli edifici pubblici, ma anche “per il finanziamento degli interventi di ricostruzione privata”. Sono fondi, dunque, che dovrebbero in qualche modo sommarsi ai 400 milioni di euro già stanziati per la ricostruzione privata nel 2017 attraverso il meccanismo del credito di imposta. Con lo stesso decreto il Ministero dell’Economia provvede anche a rimpinguare i fondi per l’emergenza a disposizione del Commissario, con 63 milioni per quest’anno e 132 per il ’18 e il ’19, mentre è autorizzata la spesa di 150 milioni per quest’anno “per consentire l’avvio di interventi urgenti per la ricostruzione pubblica e privata”. Tasse sospese Il decreto prevede poi la proroga di alcune misure tributarie, come la busta paga pesante, che sarà erogata anche a dicembre 2017. Sono previste poi le compensazioni ai Comuni per il mancato gettito dell’Imu, 17 milioni che potranno essere concessi dal commissario, e gli introiti ridotti della Tari, la tariffa rifiuti (16 milioni nel 2016, 30 nel ’17-’20). Le Zone franche Nei comuni del cratere sono poi istituite le Zone franche urbane. Le imprese che hanno sede principale o l’unità locale in questi comuni, e che hanno subito la riduzione del loro fatturato almeno pari al 25% della media relativa ai tre periodo di imposta precedenti, possono beneficiare di un’esenzione Irpef o Ires su un reddito fino a 100 mila euro annui, dell’Irap su un valore annuo della produzione di 300 mila euro, e dell’Imu. Le imprese sono anche esonerate dal versamento dei contributi previdenziali e assistenziali, con esclusione di quelli Inail, a carico dei datori di lavoro sulle retribuzioni di lavoro dipendente. Esenzioni per le nuove imprese Le esenzioni si applicano anche alle imprese che aprono nuove attività nei comuni del cratere entro il 31 dicembre 2017. Per le Zone franche urbane sono stanziati 194 milioni per il 2017, 167 per il 2018 e 141 per il 2019. Gli sconti fiscali che possono concessi a una singola impresa non possono superare i limiti del “de minimis” comunitario. Dunque, non più di 200 mila euro per ciascuna impresa nell’arco di un triennio. (m. sen.)'
link: 'https://sibilla-online.com/2017/04/zone-franche-stop-ai-contributi-nuovi-fondi-ricostruzione-privata/'
data: 20/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente!
