### ISSUE TITLE
Via alla costruzione delle 21 nuove scuole sostitutive

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2944]
<pre><yamldata>titolo: 'Via alla costruzione delle 21 nuove scuole sostitutive'
descrizione: 'Avviata la procedura per la ricostruzione di un primo gruppo di scuole distrutte dal terremoto. E’ stata completata, infatti, la progettazione definitiva dei plessi scolastici a cura della struttura commissariale per la ricostruzione in collaborazione con Invitalia. Ed è online l’avviso esplorativo per la formazione di un elenco di esecutori interessati alla realizzazione delle opere di edilizia scolastica di cui all’ordinanza commissariale 14 del 16 gennaio 2017. Bando online In pratica un avviso rivolto ad aziende ed imprese artigianali interessate a partecipare alla costruzione dei plessi scolastici individuati dal commissario. Gli interventi verranno realizzati previo affidamento di appalti che comprendono la progettazione esecutiva e la realizzazione dei lavori. L’affidamento dei lavori alle imprese avrà luogo attraverso la formula della procedura negoziata, disciplinate dall’Ordinanza a firma del commissario e gestite da Invitalia che svolgerà la funzione di centrale unica di committenza con la sorveglianza dell’Anac. (m. sen.)'
link: 'https://sibilla-online.com/2017/04/via-alla-costruzione-delle-21-nuove-scuole-sostitutive/'
data: 20/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
C'è già. Chiudo.
