### ISSUE TITLE
Da Unipol 1 milione per la ricostruzione della scuola di #Loro Piceno

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2946]
<pre><yamldata>titolo: 'Da Unipol 1 milione per la ricostruzione della scuola di #Loro Piceno'
descrizione: 'Il gruppo Unipol ha donato oltre un milione di euro per la ricostruzione della scuola elementare Pietro Santini di Loro Piceno (Macerata), dichiarata inagibile a causa dei danni subiti dal Terremoto del 24 agosto scorso. La somma, frutto della raccolta tra i dipendenti e di un contributo dell’azienda, e’ stata consegnata oggi a Vasco Errani, commissario straordinario per la ricostruzione delle zone dell’Italia centrale colpite dai terremoti negli ultimi mesi.'
link: 'http://www.meteoweb.eu/2017/04/terremoto-da-unipol-1-milione-per-la-ricostruzione-della-scuola-di-loro-piceno/889813/'
data: 21/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas io non accetterei...

**Comment by cristigalas** [comment]
@chiccap nemmeno io!
