### ISSUE TITLE
Triennio di gevolazioni su luce, gas e acqua per le zone terremotate

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2947]
<pre><yamldata>titolo: 'Triennio di gevolazioni su luce, gas e acqua per le zone terremotate'
descrizione: 'E'' di poche ore fa il comunicato stampa dell''Autorità Garante per l''energia elettrica e gas, riferito alla nuova delibera che prevede l''azzeramento per 36 mesi dei costi per tariffe di rete e oneri di sistema, rateizzazioni su due anni ed eliminazione di contributi per attivazioni e\o volture per i cittadini delle zone colpite dal sisma.'
link: 'https://picchionews.it/attualita/sisma-i-terremotati-per-tre-anni-pagheranno-la-meta-per-gas-e-luce-azzerate-le-tariffe-per-l-acqua'
data: 21/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente
