### ISSUE TITLE
Norcia, una super salsiccia da 700 metri per la rinascita

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2969]
<pre><yamldata>titolo: 'Norcia, una super salsiccia da 700 metri per la rinascita'
descrizione: 'NORCIA – 700 metri di salsiccia significano un altro passo verso la rinascita della città di San Benedetto. Martedì 25 aprile, a Norcia, ha avuto luogo presso il campo sportivo Europa il ‘Salsiccia day’, evento organizzato da ‘I love Norcia’ in collaborazione al consorzio ‘We are Norcia’. Tanti i nursini che hanno partecipato all’iniziativa. Elevato anche il numero di turisti, presenti in città durante il ponte del 25 aprile. “Realizziamo la salsiccia legata a mano più lunga della storia di questa città”, afferma Vincenzo Bianconi, numero uno di ‘I love Norcia’. Non a caso è stata scelta la data della festa della Liberazione per la creazione della salsiccia da record, perché, spiega Bianconi “anche noi vogliamo liberarci da questi mesi difficili”. Anche il sindaco Alemanno è voluto essere presente all’evento che, per il primo cittadino, assume “un significato importante, la nostra gente e il nostro territorio hanno voglia di guardare al futuro con ottimismo”.'
link: 'http://www.lanotiziaquotidiana.it/umbria/2017/04/25/norcia-una-super-salsiccia-da-700-metri-per-la-rinascita/'
data: 25/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas io non accetterei

**Comment by cristigalas** [comment]
@chiccap nemmeno io!
