### ISSUE TITLE
In arrivo 20 mln con bando 'Fare Centro'

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2972]
<pre><yamldata>titolo: 'In arrivo 20 mln con bando ''Fare Centro'''
descrizione: '(ANSA) - L''AQUILA, 24 APR - Verrà pubblicato il 26 aprile l''attesissimo bando ''Fare Centro'', frutto di mesi di gestazione, da 20 milioni di euro tra il 2016 e il 2018 per sostenere chi ha riaperto o intende farlo nei centri storici terremotati dell''Aquila, delle sue frazioni e dei comuni del ''cratere'', con contributi che vanno da 20 mila a 200 mila euro: 60 i giorni per presentare le domande a palazzo Silone. "Il contributo minimo sarà 20 mila euro, massimo di 200 mila - ha spiegato il capo dipartimento Vincenzo Rivera -: a coprire il 70% dell''investimento mentre il 30% dovrà essere cofinanziato dal privato. Sarà erogato il 40% a conto anticipo e il 60% a saldo. Tre sono le linee d''azione: la linea ''A'' finanzia coloro che erano già presenti al 6 aprile, e hanno subìto effetti della scossa, si sono trasferiti o hanno subìto un decremento di fatturato del 40%; la linea ''B'' sostiene i nuovi investimenti, la linea ''C'' si occupa di viale della Croce Rossa, per far sparire manufatti post-sisma ma anche promuovere la riqualificazione".'
link: 'http://www.ansa.it/abruzzo/notizie/2017/04/24/in-arrivo-20-mln-con-bando-fare-centro_1f4083d5-63ec-468c-8a9a-36ba1aa68e3d.html'
data: 26/04/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas notizia che riguarda il sisma dell'Aquila, inseriamo lo stesso?

**Comment by cristigalas** [comment]
@chiccap direi di no...
