### ISSUE TITLE
#AcquasantaTerme: 2° Laboratorio Territoriale INU Marche

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2980]
<pre><yamldata>titolo_evento: '#AcquasantaTerme: 2° Laboratorio Territoriale INU Marche'
data_evento: 27/04/2017
ora_evento: '15:00'
promotore: 'Comune Acquasanta Terme e INU Marche'
descrizione: 'Oggi, giovedì 27 Aprile si terrà il secondo Laboratorio Teatrale INU Marche dalle ore 15 alle ore 18 presso il Monastero di #Valledacqua, #AcquasantaTerme AP. Di seguito il programma dell''evento: Ore 15:00 apertura laboratorio e accoglienza partecipanti. Ore 15e15 presentazione del laboratorio. Ore 15:30-17e45 tavoli di lavoro con gli amministratori: 1) pianificare la ricreazione della comunità. 2) pianificare la ricostruzione degli edifici. 3) pianificare il ripristino del territorio. Ore 17e15 condivisione dei risultati.'
indirizzo: 'Strada Statale 4 Via Salaria, Acquasanta Terme, AP, Marche, 63095, Italia'
lat: '42.769944'
lon: '13.410185'
link: 'https://m.facebook.com/story.php?story_fbid=1363503973743037&substory_index=0&id=1065861773507260'
data: 27/04/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Evento scaduto.
