### ISSUE TITLE
Giovane terremotato cerca un motorino per andare al lavoro #PortoSantElpidio

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2990]
<pre><yamldata>tel: '3351584397'
email: cpt.rizzi@gmail.com
cosa: motorino
descrizione: 'Giovane terremotato ospite di una struttura alberghiera di Porto Sant''Elpidio nel fermano cerca mezzo di locomozione/scooter per raggiungere il luogo di lavoro dove è stato recentemente assunto. Grazie.'
indirizzo: 'Via Trieste, Porto Sant''Elpidio, FM, Marche, 63018, Italia'
lat: '43.2595075'
lon: '13.7601137'
link: ''
immagine: ''
data: 02/05/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Donazione arrivata da Michela di Cuneo!

**Comment by cristigalas** [comment]
Brava Michela, anche perché non solo ha donato la moto ma ha pagato anche revisione, spedizione e casco!
