### ISSUE TITLE
NUOVO BANDO PER IL REPERIMENTO DI ALLOGGI DA DESTINARE AI CITTADINI TERREMOTATI

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2995]
<pre><yamldata>titolo: 'NUOVO BANDO PER IL REPERIMENTO DI ALLOGGI DA DESTINARE AI CITTADINI TERREMOTATI'
descrizione: 'Sarà pubblicato martedì 2 maggio e resterà aperto per 15 giorni il secondo bando per il reperimento di alloggi invenduti e disponibili, che potranno essere utilizzati in sostituzione delle SAE (soluzioni abitative di emergenza - “casette”) dai cittadini colpiti dal sisma, in attesa della ristrutturazione o ricostruzione delle proprie abitazioni.'
link: 'http://www.regione.marche.it/Regione-Utile/Ricostruzione-Marche/News-ed-eventi/Post/22155/NUOVO-BANDO-PER-IL-REPERIMENTO-DI-ALLOGGI-DA-DESTINARE-AI-CITTADINI-TERREMOTATI'
data: 02/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
già presente.
