### ISSUE TITLE
Osservatorio nazionale per una ricostruzione di qualità

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#2996]
<pre><yamldata>titolo: 'Osservatorio nazionale per una ricostruzione di qualità'
descrizione: 'Legambiente, la principale associazione ambientalista, e la Fillea Cgil, il principale sindacato delle costruzioni, promuovono un Osservatorio nazionale per una ricostruzione di qualità, ubicato presso l’area del Cratere, a Muccia (MC), aperto ai contributi di tutte le forze sociali, del volontariato, del civismo, delle istituzioni che condividano le finalità di una ricostruzione pubblica e privata, residenziale e di impresa, di qualità avendo una visione unitaria e lungimirante per il futuro dell’area appenninica.'
link: 'http://osservatoriosisma.it/chi-siamo/'
data: 02/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
