### ISSUE TITLE
Scuola: inaugurato istituto Allerona

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3006]
<pre><yamldata>titolo: 'Scuola: inaugurato istituto Allerona'
descrizione: '(ANSA) - PERUGIA, 2 MAG - "Gli edifici scolastici devono essere innanzitutto sicuri, ma anche funzionali alle nuove esigenze della didattica moderna": così la presidente della Regione, Catiuscia Marini, stamani alla cerimonia per la conclusione dei lavori di ristrutturazione dell''Istituto comprensivo statale ''Muzio Cappelletti'' di Allerona, cui ha partecipato anche il sottosegretario alla presidenza del Consiglio, Maria Elena Boschi. Marini ha sottolineato che l''importante intervento di riqualificazione del plesso scolastico "è stato reso possibile grazie ad una attenta politica di programmazione e ad un ottimo lavoro di squadra".'
link: 'http://www.ansa.it/umbria/notizie/2017/05/02/scuola-inaugurato-istituto-allerona_0ea27f3a-588e-469e-9d7c-61babc580e2a.html'
data: 03/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è un comune del cratere.
