### ISSUE TITLE
Aiutiamo L’Albero del Pane di Visso a ripartire.

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3008]
<pre><yamldata>titolo: 'Aiutiamo L’Albero del Pane di Visso a ripartire.'
descrizione: 'Ricordiamo l''iniziativa di raccolta fondi per L''Albero del Pane di Visso (presente anche nel sito): "L''’appello lanciato dai titolari di un esercizio commerciale di Visso, Fabio e Lina, gente che vuole scommettere sul futuro di Visso nonostante tutto e, per farlo, è pronta a investire denaro ma soprattutto vita in un progetto imprenditoriale che guardi avanti. L’Albero del Pane è un’attività di panetteria e prodotti da forno nata a Visso nel 2005. Un’attività ben avviata che stava crescendo, dove i dipendenti amano lavorare perché, come dice Valentina sostenendo l''appello dei titolari, si fa parte di una famiglia e di un progetto. Il terremoto ha interrotto questo progetto. “Eravamo una squadra perfetta” dicono Lina e Fabio, “tanto lavoro ma anche tante soddisfazioni. I nostri dolci venivano acquistati da molti ristoranti e b&b della zona, così come il pane. Stava andando bene, la scorsa estate ci sono stati tanti turisti e abbiamo lavorato molto”. Poi il terremoto ha rotto la magia, distruggendo tutto, mandando via la gente, desertificando Visso. I danni subito da L’Albero del Pane sono ingenti ma non irreparabili. Occorre comprare qualche macchinario nuovo, recuperare i vecchi dal laboratorio inagibile e pericoloso. L’attività però deve proseguire, loro ci credono e vogliono andare avanti, lo vogliono fare a Visso. C’è un modulo provvisorio dove trasferire il punto vendita e il laboratorio ma occorre denaro. Lo avranno, forse, dallo Stato, ma ancora non si sa quanto e quando. Per questo L’Albero del Pane ha aperto una pagina per raccogliere fondi e ripartire. Se volete aiutarli potete cliccare su questo link (https://www.produzionidalbasso.com/project/per-fare-un-albero-ci-vuole-il-pane-ricostruiamo-lalbero-del-pane-di-visso/) e fare la vostra piccola donazione. Credo valga la pena, perchè chi vuole andare avanti senza abbandonare il territorio, lottando contro la desertificazione, va aiutato e sostenuto."'
link: 'https://www.produzionidalbasso.com/project/per-fare-un-albero-ci-vuole-il-pane-ricostruiamo-lalbero-del-pane-di-visso/'
data: 03/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
C'è già.
