### ISSUE TITLE
ORDINANZA N.21 REGISTRATA IL 02/05/2017 AL NUMERO 904

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3015]
<pre><yamldata>titolo: 'ORDINANZA N.21 REGISTRATA IL 02/05/2017 AL NUMERO 904'
descrizione: 'Pubblicato in data 2 maggio 2017 Assegnazione di contributi per le spese di traslochi e depositi temporanei di mobili di abitazioni dichiarate totalmente inagibili nei territori delle Regioni Abruzzo, Lazio, Marche ed Umbria, a seguito degli eventi sismici verificatisi a far data dal 24 agosto 2016 e modifiche all’articolo 4, comma 1, dell’ordinanza n. 19 del 7 aprile 2017. LINK ALL’ORDINANZA: ordinanza-n-21-del-28-4-20171'
link: 'https://sisma2016.gov.it/2017/05/02/ordinanza-n-21-registrata-il-02052017-al-numero-904/'
data: 03/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
