### ISSUE TITLE
Mam beyond borders cerca volontari per aiutare nella ricostruzione post sisma

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3020]
<pre><yamldata>tel: ''
email: nirchi.v@gmail.com
cosa: 'Cercasi Volontari'
descrizione: 'Mam beyond borders Onlus cerca volontari di ambo i sessi, automuniti, che vogliano intraprendere l'' esperienza di aiutare concretamente le persone e gli animali colpiti dal sisma nel Centro Italia. Richiesta massima serietà e capacità di adattamento. Le mansioni sono: ricostruzione, smistamento e distribuzione degli aiuti alle famiglie. Contattare l''associazione sulla pagina Facebook.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/MAMbeyondborder/?fref=ts'
immagine: 'http://i.imgur.com/OtSYZGB.jpg'
data: 03/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci segnala via email che l'associazione ha comunicato sulla sua pagina Facebook di non avere più bisogno di volontari.
