### ISSUE TITLE
Un aiuto per Angela, terremotata di #Castelsantangelo sul Nera

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3055]
<pre><yamldata>tel: ''
email: unaiutopercastelsantangelo@gmail.com
cosa: 'Un aiuto per Angela, terremotata di #Castelsantangelo sul Nera'
descrizione: 'Purtroppo il terremoto a Castelsantagelo sul Nera ha colpito praticamente tutti data l''altissima percentuale di crolli, lei è Angela e abitava da sempre nella parte più alta di Castelsantagelo a ridosso della Chiesa di S. Stefano. Fin dal 24 agosto la sua casa ha subito danni gravissimi e Angela non ha potuto recuperare nulla dalla sua abitazione. Dopo un breve periodo da sfollata sulla costa, Angela non ha resistito ed è tornata in paese, seppur in condizioni precarie. Avrebbe bisogno del vostro sostegno per acquistare il necessario per continuare la sua vita qui, dove desidera rimanere più di ogni altra cosa al mondo. Chiunque intenda aiutarla, ci scriva in privato e gli forniremo il suo contatto diretto. Grazie a tutti.'
indirizzo: 'Via Sant''Angelo, Castelsantangelo sul Nera, MC, Marche, Italia'
lat: '42.8944925'
lon: '13.1539297'
link: 'https://www.facebook.com/unaiutopercastelsantangelosulnera/photos/a.202969730115929.1073741828.195667160846186/311664655913102/?type=3'
immagine: 'http://i.imgur.com/pWE0XV7.jpg'
data: 09/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
L'associazione scrive su Fb che la richiesta è sta soddisfatta. Vedi qui https://www.facebook.com/unaiutopercastelsantangelosulnera/posts/311664655913102:0
