### ISSUE TITLE
Mappa interattiva delle casette, i dati per comune.

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3065]
<pre><yamldata>titolo: 'Mappa interattiva delle casette, i dati per comune.'
descrizione: 'La Protezione civile nazionale fa chiarezza con una mappa interattiva, per vedere dove sono dislocate le aree, dove sono iniziati i lavori e dove l’installazione vera e propria delle Sae. Scaricando i dati relativi ai Comuni della Provincia di Macerata sono 1.108 le casette riportate nelle aree individuate. Sulla cartina sono segnate le aree già individuate e consegnate dalle amministrazioni comunali, non per tutti i paesi è però riportato il numero di Sae ordinate. Possono esserci ulteriori aree, già individuate e magari non consegnate, perchè i Comuni potrebbero non ancora esserne venuti in possesso. Secondo i dati ufficiali della Protezione civile, nelle Marche sono state ordinate 1.782 Sae per 28 Comuni, con 47 aree affidate a ditte e su 4 ci sono i cantieri aperti. Nella provincia di Macerata, tutte le zone risultano come aree consegnate, senza che sia iniziato nessun lavoro, ma i dati vengono aggiornati settimanalmente dalla Protezione civile, sulla base delle segnalazioni degli uffici regionali.'
link: 'http://www.cronachemaceratesi.it/2017/05/11/la-mappa-delle-casette-i-dati-comune-per-comune/960080/'
data: 11/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Notizia già presente.
