### ISSUE TITLE
Allevatore di cavalli cerca camper/roulotte ad #ArquataDelTronto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3076]
<pre><yamldata>tel: '3485827086'
email: fabrizio.angelucci88@gmail.com
cosa: 'Cercasi camper/roulotte #ArquataDelTronto'
descrizione: 'Avrei bisogno di una sistemazione temporanea per poter tornare a vivere accanto ai miei cavalli e poterli accudire. L''ideale sarebbe una camper o una roulotte minimo 2 posti. Grazie di cuore'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 16/05/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Fabrizio è stato contattato e gli verrà portata direttamente ad Arquata una roulotte presumibilmente sabato 27/05. Lui dovrà farsi carico solo delle spese di trasporto (150€). Aggiornamenti ad inizio settimana prossima.

**Comment by chiccap** [comment]
In questi giorni stanno facendo il passaggio di proprietà, sabato gli verrà consegnata! La richiesta è stata postata sul gruppo Facebook "Caravanisti Solidali" da Christian Varani ed è stata vista dal Sig. Enrico che donerà la sua roulotte.

**Comment by chiccap** [comment]
La roulotte è arrivata!
