### ISSUE TITLE
Spettacoli e laboratori con "Le Fucine Vulcaniche" #Camerino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3087]
<pre><yamldata>titolo_evento: 'Spettacoli e laboratori con "Le Fucine Vulcaniche" #Camerino'
data_evento: 21/05/2017
ora_evento: ''
promotore: 'io non crollo Camerino, Actionaid, Gus'
descrizione: 'Evento di aggregazione e divertimento rivolto alle popolazioni colpite dal terremoto'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/photo.php?fbid=10211407494536099&set=gm.1894043600863222&type=3&theater'
data: 18/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
