### ISSUE TITLE
Convegno Sisma centroitalia. Ricostruire come e quando. #Amandola

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3089]
<pre><yamldata>titolo_evento: 'Convegno Sisma centroitalia. Ricostruire come e quando. #Amandola'
data_evento: 24/05/0007
ora_evento: ''
promotore: ''
descrizione: 'Durante la giornata oltre a un focus sui danni provocati dal terremoto e sui numeri legati alla gestione dell''emergenza, verranno trattati i seguenti temi: - lo stato della fase emergenziale e le ordinanze per la ricostruzione; - la tutela dei beni architettonici, artistici ed ecclesiastici; - i danni al patrimonio edilizio marchigiano; - i fenomeni di fatica e isteresi delle strutture murarie; - il Sisma Bonus.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.kimia.it/it/blog/ricostruire-come-quando-convegno-ad-amandola-2017'
data: 18/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
