### ISSUE TITLE
Sisma Centro Italia, al via la fase operativa dei lavori di ripristino delle strade danneggiate

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3097]
<pre><yamldata>titolo: 'Sisma Centro Italia, al via la fase operativa dei lavori di ripristino delle strade danneggiate'
descrizione: 'Entro maggio affidamenti da parte di Anas per 40 milioni di euro, che diventeranno 100 milioni entro giugno. Domani il primo bando di gara per la galleria “San Benedetto” sulla SS685 “delle Tre Valli Umbre” Entra nella fase operativa l’opera di ripristino delle strade compromesse dal sisma che ha colpito il Centro Italia tra agosto e ottobre. Dopo la fase di ricognizione e programmazione, che ha interessato direttamente 124 strade con oltre 750 sopralluoghi e circa 500 interventi finanziati, Anas in qualità di soggetto attuatore avvierà entro la fine del mese le procedure di affidamento dei lavori per circa 40 milioni di euro, che entro giugno raggiungeranno 100 milioni di euro. A luglio saranno attivi cantieri per 40 milioni di euro. Il punto della situazione è stato fatto questa mattina in un incontro tra il Ministro alle Infrastrutture e Trasporti Graziano Delrio, il Capo del Dipartimento di Protezione Civile Fabrizio Curcio, il Commissario straordinario alla ricostruzione Vasco Errani, il Presidente Anas Gianni Vittorio Armani, i presidenti della quattro regioni interessate: Luca Ceriscioli (Marche), Catiuscia Marini (Umbria), Nicola Zingaretti (Lazio) e Luciano D''Alfonso (Abruzzo) e i Soggetto Attuatore per il ripristino delle viabilità Fulvio M.Soccodato. Si tratta, in particolare, di interventi sulle strade in gestione Anas che non era stato possibile eseguire in regime di emergenza per l’entità dei danni che richiedevano rilievi tecnici, geologici e una approfondita fase di progettazione nonché di interventi di ricostruzione da eseguire su strade di competenza di Comuni, Province e Regioni che, in base al decreto legge n. 205 del 4/11/2016, hanno deciso di delegare all’attuazione di Anas in qualità di Soggetto Attuatore di Protezione Civile. Il “Programma di ripristino delle strade colpite dal sisma”, elaborato da Anas e approvato da tutti i soggetti competenti, ha attribuito un livello di priorità da 1 a 5 per ogni intervento, individuando – di concerto con il territorio – 497 interventi con priorità da 1 a 3, necessari per ripristinare la circolazione o le condizioni di sicurezza lungo la rete stradale principale, da realizzare nel primo stralcio del programma per un importo complessivo stimato in circa 474 milioni di euro. La riunione si è focalizzata in particolare su tre priorità: Strada statale 685 “delle Tre Valli Umbre” Il primo bando di gara sarà pubblicato domani sulla Gazzetta Ufficiale e riguarderà i lavori di ricostruzione della galleria “San Benedetto”, sulla strada statale 685 “delle Tre Valli Umbre”, gravemente compromessa dalla forte scossa del 30 ottobre. I lavori, del valore di circa 2 milioni di euro, saranno completati entro 200 giorni dall’affidamento. Tutti gli altri interventi relativi al ripristino del collegamento, per un valore di oltre 96 milioni di euro, saranno appaltati tra maggio e giugno. Di questi, 60 milioni di euro riguardano il tratto marchigiano attualmente chiuso (da Arquata del Tronto al confine umbro) dove saranno eseguiti importanti lavori di riparazione, consolidamento e risanamento di 8 viadotti e 9 gallerie che hanno subito gravi lesioni a causa del sisma, richiedendo attività di indagine, rilievo e progettazione adeguate alla complessità del caso. Altri interventi di sistemazione definitiva saranno eseguiti nel tratto Spoleto-Norcia, già riaperto al traffico subito dopo il sisma con interventi minori che è stato possibile eseguire in regime di emergenza. Strada regionale 209 “Valnerina” Anas (di concerto con Comuni di Visso, Ussita, Castelsantangelo, la Provincia di Macerata e la Regione Marche) ha eseguito una prima campagna di rilievi topografici e indagini ed ha completato il progetto di una soluzione temporanea con l’obiettivo di ripristinare nel più breve tempo possibile la circolazione in via provvisoria con la rimozione del corpo di frana e la costruzione di una viabilità provvisoria, utilizzabile sotto stretto monitoraggio ed in fasce orarie limitate. Il tratto è stato infatti coinvolto in una grave situazione idrogeologica generata dal sisma che ha interessato tutto il versante, con un’ampia frana di circa 60 mila metri cubi che ha deviato il corso del fiume Nera. Un tratto della strada è inoltre ricoperta da un bacino lacustre formatosi a causa dell’occlusione del fiume, mentre un ponte è stato gravemente lesionato dal dissesto e dalla caduta di massi fino a un metro cubo. I lavori necessari alla riapertura provvisoria riguardano 3 interventi di disgaggio massi pericolanti e protezione dei versanti, oltre all’intervento sul corpo stradale, per circa 10 milioni di euro. Contemporaneamente Anas ha avviato la progettazione per la soluzione definitiva che richiederà un anno di lavori. Viabilità di accesso a Castelluccio di Norcia Per migliorare quanto prima possibile l''accessibilità alla piana di Castelluccio, si è deciso di concentrare gli sforzi di tutte le Amministrazioni sull''itinerario che parte dalla SS4 da Arquata del Tronto attraverso Forca di Presta (strade provinciali 89, 34 e 477-III), al fine di avviare interventi provvisori che consentano di riaprire la viabilità, seppure con limitazioni. Sulla viabilità di accesso da Norcia (strada provinciale 477) che richiede sia interventi di ripristino della sede stradale che di messa in sicurezza dei fronti rocciosi, sta intervenendo direttamente la Provincia di Perugia.'
link: 'http://www.stradeanas.it/it/sisma-centro-italia-al-la-fase-operativa-dei-lavori-di-ripristino-delle-strade-danneggiate'
data: 19/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
