### ISSUE TITLE
Politiche del disastro di Silvia Pitzalis, un libro sul post-terremoto emiliano

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3099]
<pre><yamldata>titolo: 'Politiche del disastro di Silvia Pitzalis, un libro sul post-terremoto emiliano'
descrizione: 'L’Italia è un Paese che, periodicamente, fa esperienza di disastri e in cui l’esposizione ai rischi (geologici, innanzitutto) è spesso molto alta. Nonostante ciò, le scienze sociali italiane – e l’antropologia culturale, in particolare – si sono dedicate a questo specifico terreno di ricerca con un certo ritardo, rispetto ad altri contesti internazionali. Il libro di Silvia Pitzalis, Politiche del disastro. Poteri e contropoteri nel terremoto emiliano (Ombre Corte, 2016), è uno dei primi a collocarsi in questa peculiare congiuntura storico-politica, nonché scientifica e culturale italiana. Questo quadro è decisamente cambiato a partire dal 2009, sia per ragioni accademiche che, purtroppo, per il gravissimo terremoto che ha colpito la città dell’Aquila il 6 aprile. I primi studi antropologici effettuati sui disastri in Italia con una certa regolarità (non solo da studiosi italiani) si sono avuti a partire dagli anni ’70, in concomitanza con alcune calamità piuttosto gravi. In particolare, il bradisismo dell’area dei Campi Flegrei (nel 1970 e nel 1983), il terremoto in Friuli (1976) e il terremoto in Campania e Basilicata (1980) hanno rappresentato occasioni di ricerca sulle modalità di ricostruzione degli abitati distrutti e sulle dinamiche politiche messe in atto da tali eventi nefasti. Successivamente, sono andate sviluppandosi analisi in merito alla rielaborazione della memoria delle catastrofi e alla risposta culturale al disastro naturale. Come dicevo, è tuttavia dal 2009 che una generazione di giovani ricercatori italiani ha posto particolare attenzione alle catastrofi, non solo sul piano conoscitivo, ma anche con taglio pubblico e impegno applicativo In caso di calamità lo stravolgimento del territorio può causare un momento di disordine esistenziale che minaccia la stabilità della presenza delle persone che l’hanno vissuta. Tuttavia, l’idea di fondo di Pitzalis è che le catastrofi possano essere anche “generative”, possano cioè attivare degli elementi di intraprendenza e di ingegno che fungono da alternativa al trauma sociale e psicologico estremo. “Politiche del disastro” mostra una varietà di possibili reazioni socio-culturali ad una catastrofe naturale e alle conseguenti, innumerevoli implicazioni politiche. Il contributo principale di questa antropologia non va cercato nelle risposte definitive o nei suggerimenti operativi, bensì negli interrogativi che solleva e nelle prospettive di confronto che apre sulla logica emergenziale, sulle procedure della Protezione Civile, sulla definizione dei tempi del bisogno, sulla sussidiarietà come attività di recupero e di responsabilizzazione. Le differenze tra i dispositivi istituzionali e le pratiche “dal basso” illustrate nel volume sono lo stimolo a pensare un futuro diverso, tanto per il sistema degli aiuti, quanto per la gestione del territorio: è in quelle variazioni che si possono individuare forme nuove del politico che lasciano immaginare un mutamento o, per usare le parole di Pitzalis, una elaborazione di «alternative protese ad un avvenire migliore» (p. 136).'
link: 'http://www.lavoroculturale.org/antropologia-dei-dispositivi-emergenza/'
data: 19/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non attinente.
