### ISSUE TITLE
TERREMOTO: BORSE LAVORO, INCENTIVI ALLE ASSUNZIONI E INDENNITÀ AI LAVORATORI DIPENDENTI.

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3102]
<pre><yamldata>titolo: 'TERREMOTO: BORSE LAVORO, INCENTIVI ALLE ASSUNZIONI E INDENNITÀ AI LAVORATORI DIPENDENTI.'
descrizione: 'La Regione Marche, al fine di sostenere la ripresa economica e sociale delle aree del cratere, ha approntato diverse misure di sostegno al lavoro nelle aree colpite dagli eventi sismici 2016/17, ed in particolare il finanziamento di: -2,5 milioni di euro per finanziare 500 tirocini e 100 incentivi alle assunzioni; -43 milioni di euro per sostenere i lavoratori delle imprese colpite dal sisma. 1) Il primo bando, ancora in corso di approvazione, prevede l’attivazione di tirocini di inserimento/reinserimento al lavoro, della durata da 3 a 6 mesi e con una borsa lavoro di Euro 500,00 mensili, sono rivolti a soggetti disoccupati ai sensi del D.Lgs n. 150/2015, residenti nell’area marchigiana del cratere, e disoccupati (sempre ai sensi del D.Lgs n. 150/2015) che lavoravano in aziende situate nell’area del cratere. 2) Il secondo bando è invece già attivo e si chiuderà il 16 giugno 2017, in quanto trattasi della riapertura del bando precedente chiusosi il 14 aprile 2017 per quanto riguarda gli eventi sismici del 2016, ed ora riaperto in seguito alla Circolare INPS n. 83 del 4 maggio 2017 (di cui abbiamo parlato nei giorni scorsi), ma solo per i lavoratori dipendenti. Al momento quindi il bando non è aperto ai lavoratori autonomi.'
link: 'https://bartolomeigiuliano.blog/2017/05/18/terremoto-borse-lavoro-incentivi-alle-assunzioni-e-indennita-ai-lavoratori-dipendenti/'
data: 19/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
