### ISSUE TITLE
Camper o roulotte per un ragazzo di #ArquataDelTronto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3104]
<pre><yamldata>tel: '329 602 2189'
email: sante.corradetti@gmail.com
cosa: 'Camper o roulotte per un ragazzo di #ArquataDelTronto'
descrizione: 'Sante Corradetti è un ragazzo di Arquata del Tronto che fin dalle prime ore del disastro si è impegnato con tutte le sue forze nei soccorsi e in molti recuperi (è grazie a lui che la storica campana della Torre Civica di Arquata del Tronto è riemersa dalle macerie). Ad oggi continua a spendersi per tenere in vita il suo territorio e l’attenzione su di esso, molte delle iniziative vitali a questo scopo, tra le quali il recente "Picnic nel Cuore del mondo" a Forca di Presta, che ha visto più di 300 partecipanti, sono state possibili grazie al suo aiuto come membro del Gruppo Comunale di Protezione Civile ma soprattutto come persona dotata di un grande animo e di una grande generosità. Sante è sfollato in costa e non sa quando sarà possibile per lui un ritorno a casa, ma la sua presenza nei luoghi a lui cari è essenziale per dargli la possibilità di continuare la sua attività di sostegno e aiuto. Per questo vorremmo che gli fosse messo a disposizione un camper o una roulotte, non necessariamente in donazione, anche in prestito, fino a quando non avrà altra sistemazione. Grazie di cuore'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 23/05/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Ha trovato un'altra sistemazione.
