### ISSUE TITLE
Vissosteniamo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3113]
<pre><yamldata>titolo_evento: Vissosteniamo
data_evento: 06/11/2017
ora_evento: '11:30'
promotore: 'Comune di Visso, VISSO, Recanati Art Festival, SkaBeer Ska, Il Giardino delle Donne'
descrizione: 'L''evento "Insieme...Vissosteniamo" nasce dalla voglia di aiutare l''intera comunità di Visso colpita dal sisma del 2016, raccogliendo i fondi necessari allo sviluppo di progetti intesi alla rinascita del paese stesso. Quindi vi invitiamo : DOMENICA 11 GIUGNO 2017 dalle ore 11:30 c/o il Laghetto di VISSO'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, 62039, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'https://www.facebook.com/events/154771728394759/?acontext=%7B%22ref%22%3A%224%22%2C%22feed_story_type%22%3A%22308%22%2C%22action_history%22%3A%22null%22%7D'
data: 30/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
