### ISSUE TITLE
RI-creare #Sassotetto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3116]
<pre><yamldata>titolo_evento: 'RI-creare #Sassotetto'
data_evento: 07/02/2017
ora_evento: '11:00'
promotore: 'Sassotetto Active Park'
descrizione: 'Un nuovo progetto nato dalla passione per la montagna. Un progetto che era nato anni fa ad Ussita ma interrotto dagli ultimi avvenimenti sismici. E’ così che oggi il nostro sogno è far diventare Sassotetto una meta estiva e riavvicinare più gente possibile alla montagna. Da qui nasce Sassotetto Active Park. Un luogo per tutti. Un luogo fatto di sport natura buon cibo tanta passione e delle montagne vista mare. PARTECIPAZIONE: (gratuita) ARTISTI...ARTIGIANI...ILLUSTRATORI...VI STIAMO ASPETTANDO!! ISCRIZIONI APERTE FINO AL 18 GIUGNO 2017'
indirizzo: 'Strada Provinciale 120 Sarnano - Sassotetto - Bolognola, Bolognola, MC, Marche, 62033, Italia'
lat: '42.9950235'
lon: '13.2386854'
link: 'https://www.facebook.com/events/1532139993483854/?acontext=%7B%22ref%22%3A%224%22%2C%22feed_story_type%22%3A%22308%22%2C%22action_history%22%3A%22null%22%7D'
data: 30/05/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap  che dici di questa segnalazione? Mi lascia perplessa....

**Comment by chiccap** [comment]
A me sembra una bella iniziativa...anche se non conosco i promotori. Quali sono le perplessità? Ce non si tratti di un evento legato al terremoto?

**Comment by cristigalas** [comment]
@chiccap sì, anche se è vero che è in area cratere... Va bene l'accetto!

**Comment by chiccap** [comment]
Se vogliamo essere più sicuri provo a contattarli!
