### ISSUE TITLE
A #Muccia serve ombrellone grande per roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3127]
<pre><yamldata>tel: '3389942731'
email: g.carlocop@alice.it
cosa: 'ombrellone grande'
descrizione: 'Salve, sono un terremotato di Muccia e vivo in roulotte, avrei bisogno di un ombrellone (di quelli grandi) per metterlo davanti alla roulotte come una specie di veranda perché le temperature all''interno sono insopportabili. Grazie'
indirizzo: 'Muccia, MC, Marche, Italia'
lat: '43.0817007'
lon: '13.0429675'
link: ''
immagine: ''
data: 04/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci segnala via email che la persona che ha inviato la richiesta non vive più in roulotte ma in una casetta.
