### ISSUE TITLE
"Tutti agibili per un giorno", 24 giugno

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3135]
<pre><yamldata>titolo_evento: 'Tutti agibili per un giorno'
data_evento: 01/01/1970
ora_evento: '10:00'
promotore: 'Copagri Marche'
descrizione: 'L''evento che si svolgerà il 24 giugno è dedicato agli allevatori e alle attività economiche di Visso, Ussita e Castelsantangelo sul Nera. L''intento è quello di reperire aiuti da privati cittadini e imprenditori da tutta Italia al fine di sostenere la riapertura o il consolidamento delle attività economiche di questo territorio, tutte gravemente danneggiate o chiuse a causa dello sciame sismico iniziato il 24 agosto e non ancora terminato. Gli organizzatori sono: Un aiuto concreto per Castelsantangelo sul Nera, Cia Marche e Copagri Marche'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'https://www.facebook.com/events/1924587021108057/'
data: 06/06/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente!
