### ISSUE TITLE
Cercasi casa in zona #Camerino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3140]
<pre><yamldata>tel: ''
email: ''
cosa: 'casa in affitto zone limitrofe camerino'
descrizione: 'Cerco una casa in affitto zone limitrofe Camerino, urgentemente, chi può aiutarmi può contattarmi in privato, grazie mille.'
indirizzo: 'Piazza Cavour, Camerino, MC, Marche, Italia'
lat: '43.1357641'
lon: '13.0683092'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1902839473316968/'
immagine: ''
data: 06/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
