### ISSUE TITLE
Cercasi container uso magazzino per ristorante #ArquatadelTronto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3145]
<pre><yamldata>tel: '+393485827086'
email: fabrizio.angelucci88@gmail.com
cosa: 'Cercasi container uso magazzino per ristorante Arquanta del Tronto'
descrizione: 'Il ristorante "Il Ponticello" è l''unico ristorante ancora aperto ad Arquata del Tronto (AP): ogni giorno cuciniamo per tutte le forze dell''ordine che stanno aiutando il nostro Comune distrutto dal terremoto ma soprattutto cuciniamo per i cittadini arquatani che tornano nelle proprie terre, siamo un punto di incontro per la popolazione. Chiediamo un container o simili per il ristorante, dopo il terremoto e la neve la baracca ad uso magazzino è stata lesionata ed ora ci troviamo a non avere un posto dove poter depositare le scorte. Grazie mille a tutti per il supporto.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 09/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci inform avia email che il ristorante non ha più bisogno di container.
