### ISSUE TITLE
Brigate Solidarietà Attiva: raccolta beni per chi vive situazioni di disagio nelle aree del cratere

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3147]
<pre><yamldata>tel: ''
email: magazzinibsa@gmail.com
cosa: 'Brigate Solidarietà Attiva: raccolta beni per chi vive situazioni di disagio nelle aree del cratere'
descrizione: 'Brigate della Solidarietà Attiva, presenti nelle zone terremotate fin dallo scorso agosto, stanno raccogliendo beni da destinare a chi nelle aree del cratere sta vivendo una situazione di grande difficoltà soprattutto dal punto di vista economico e lavorativo. Come scrivono su Facebook, "In alcune zone, sopratutto nella zona di Amatrice, non ci sono ancora negozi aperti: non esiste cioè, se non a grandi distanze, un luogo dove fare la spesa. Inutile dire che la viabilità è ancora un grosso grosso problema, tra strade dissestate e macerie che stanno per compiere il primo anno di vita, ancora in gran parte abbandonate. Oltre a questo, se per qualcuno l''emergenza piano piano cessa, per altri invece non cessa mai: parliamo di coloro che hanno perso il lavoro a causa del terremoto, ma anche di coloro che, già prima delle molteplici scosse, vivevano in dissesto economico. Una difficoltà che il terremoto ha solo, ulteriormente, ampliato. Mentre pensiamo e proviamo a organizzare coi comitati locali strutture permanenti di solidarietà e mutuo soccorso da far vivere oltre e al di là della nostra presenza, chiediamo a tutti coloro che possono, un ultimo sforzo. Chi ha la possibilità di attivare raccolte di beni, ci contatti alla email magazzinibsa@gmail.com: riceverete tutte le istruzioni utili, la lista dei beni utili e vi sarà indicato un referente al quale fare riferimento per ogni necessità. Siamo una associazione che vive di auto finanziamento, possediamo ( e sempre e solo grazie a tutti voi) 3 furgoni e poco altro: per questo chiediamo a chi deciderà di aiutare la popolazione del cratere, di occuparsi anche del trasporto dei beni (e in conseguenza, di raccogliere quanto si è in condizione di trasportare, per evitare lunghi stoccaggi che deprimerebbero i beni): i nostri mezzi sono infatti impiegati ogni giorno nella distribuzione e nei rifornimenti dei nostri campi.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/terremotocentroitalia/posts/1707355635961112'
immagine: ''
data: 11/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci scrive via email che le BSA non effettuano più raccolte. Chiudo.
