### ISSUE TITLE
Cercasi cucina a #Bolognola per la mensa della tensostruttura

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3163]
<pre><yamldata>tel: ''
email: christianvarani@gmail.com
cosa: 'Richiesta per una nuova cucina, presso la mensa di Bolognola'
descrizione: 'Serve una cucina possibilmente con 4 fuochi, simile a quelle usate nei ristoranti, per poter regolarmente cucinare presso la mensa situata nella Tensostruttura principale di Bolognola, un paese della provincia di Macerata. La richiesta arriva dalla Signora Daniela Cecchini. Per contatti diretti e informazioni relative ad una eventuale donazione, rivolgersi ai recapiti specificati.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Daniela Cecchini'
immagine: ''
data: 14/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che la cucina è stata trovata da tempo.
