### ISSUE TITLE
Richiesta per una nuova cucina, presso la Tensostruttura allestita del Comune di Bolognola

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3165]
<pre><yamldata>tel: ''
email: christianvarani@gmail.com
cosa: 'Richiesta per una nuova cucina, presso la Tensostruttura allestita del Comune di Bolognola'
descrizione: 'Serve necessariamente una cucina possibilmente con 4 fuochi e quindi simile a quella, che può essere usata nei Ristoranti per poter cucinare presso la Tensostruttura ancora allestita del Comune, a Bolognola in provincia di Macerata. La cucina mi è stata richiesta tramite una cittadina terremotata di Bolognola con la quale sono anche in contatto a volte e per un bisogno riscontrato. Per informazioni più dettagliate, allo scopo di una possibile donazione, rivolgersi ai recapiti specificati in questa richiesta.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Daniela Cecchini'
immagine: ''
data: 19/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
