### ISSUE TITLE
A #ColleVerrico (Aq) cercasi arredi per 4 casette 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3169]
<pre><yamldata>tel: ''
email: ''
cosa: mobile
descrizione: 'Per arredare le 4 mobil home terminate nelle zone sismiche a Colle Verrico cerchiamo: 4 letti a castello completi dei materassi, 3 letti matrimoniali completi, una scrivania non più larga di un metro e mezzo, 2 tavoli da 4 se allungabili a 6 meglio, 12 sedie, 3 cucine a gas 4 fuochi 60x60, 4 lavabi a una buca x la cucina, 4 wc bidet sanitario unico, 3 piatti doccia 70 x 70, 4 cassette di scarico da incasso, 24 pannelli da copertura tipo sandwich spessore 4 cm da 4mt e 8 da 5,70 mt. Potete scrivere direttamente su Facebook sotto il post indicato nel campo link. Contattare su Facebook (vedi link) associazione Io non crollo 2.0. Grazie!'
indirizzo: 'SS266, Montereale, AQ, ABR, Italia'
lat: '42.5250955'
lon: '13.2440724'
link: 'https://www.facebook.com/groups/1830106400589774/permalink/1878242349109512/'
immagine: ''
data: 20/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci scrive via email che la segnalazione può essere chiusa.
