### ISSUE TITLE
Cercasi arredi esterni e attrezzature per bar-ristorante prossima riapertura a Fiastra (Mc)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3176]
<pre><yamldata>tel: '3407600651'
email: marcellococci@gmail.com
cosa: 'Richiesta arredi esterni e attrezzature per bar ristorante prossima riapertura a Fiastra (mc)'
descrizione: 'Scrivo per conto dell''attività "Il Gatto e la Volpe" di Rossi Patrizia a Fiastra, i proprietari non vorrebbero apparire ma possono essere contattati al n. 3452340620 sig. Franco. L''attività è inagibile dal 26.11.2016 e sarà probabilmente demolita, nel frattempo il Comune ha fornito una struttura prefabbricata posizionata nei pressi del locale. Purtroppo gran parte delle attrezzature non sono recuperabili o inutilizzabili, la proprietà è inattiva da oltre 7 mesi. La richiesta nello specifico è la seguente : -teli laterali per la chiusura di 4 gazebo esistenti, n.4 panchine da giardino , n. 2 tavoli da esterno, n. 1 affettatrice professionale, n.4 fioriere da esterno in legno, n. 20 tovaglie stoffa per tavoli 80x80 .'
indirizzo: 'Telecom Italia, Strada Provinciale 47 Fiastra - Bolognola, Fiastra, MC, Marche, Italia'
lat: '43.038171695632435'
lon: '13.165805339813232'
link: ''
immagine: ''
data: 20/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci segnala che il ristorante ha reperito tutta l'attrezzatura necessaria e ha riaperto in una struttura prefabbricata.
