### ISSUE TITLE
Tutti agibili per un giorno

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3184]
<pre><yamldata>titolo_evento: 'Tutti agibili per un giorno'
data_evento: 24/06/2017
ora_evento: '10:00'
promotore: 'Organizzato da Copagri Marche e Un aiuto concreto per Castelsantangelo sul Nera'
descrizione: 'L''evento è stato ideato da "Un aiuto concreto per Castelsantagelo sul Nera" ed è dedicato agli allevatori e alle attività economiche di Ussita, Castelsantangelo sul Nera e Visso. L''intento è quello di reperire aiuti da privati cittadini e imprenditori da tutta Italia al fine di sostenere la riapertura o il consolidamento delle attività economiche di questo territorio, tutte gravemente danneggiate o chiuse a causa dello sciame sismico iniziato il 24 agosto e non ancora terminato. Gli organizzatori sono: Un aiuto concreto per Castelsantangelo sul Nera, Cia Marche, Copagri Marche e Progetto Re-Cycle'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'https://www.facebook.com/events/1924587021108057/?__xt__=33.%7B%22logging_data%22%3A%7B%22profile_id%22%3A1924587021108057%2C%22event_type%22%3A%22clicked_view_profile%22%2C%22impression_info%22%3A%22eyJmIjp7InN0eWxlIjoiMzUiLCJwYWdlX2lkIjoiMTk1NjY3MTYwODQ2MTg2IiwicmVxdWVzdF9pZCI6Ik56TTVOVEE1TmpVeExUQXVNamMyT0RrNE1EQWdNVFE1T0RFeU16ZzNNeTB4TnpZeE9ESXlNREU9In19%22%2C%22surface%22%3A%22www_pages_home%22%2C%22interacted_story_type%22%3A%22509240112603598%22%2C%22session_id%22%3A%22ed866f0ee373db9c92c27e93be9f75e3%22%7D%7D'
data: 22/06/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente!
