### ISSUE TITLE
A Norcia ci sarà uno 'sportello sisma'

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3186]
<pre><yamldata>titolo: 'A Norcia ci sarà uno ''sportello sisma'''
descrizione: 'Uno sportello comune a più istituzioni, con funzioni di "front office", sarà attivato a Norcia per supportare cittadini e imprese nella ricostruzione post terremoto. Lo ha stabilito la Giunta regionale dell''Umbria, su proposta dell''assessore alla Salute, alla Coesione sociale e al Welfare, Luca Barberini. Lo ha fatto a seguito di un accordo che coinvolge Regione, Direzioni regionali di Inail e Inps, Usl Umbria 2, Ispettorato territoriale del Lavoro della provincia di Perugia, Centro edile per la sicurezza e formazione e la Cassa edile.'
link: 'http://www.ansa.it/umbria/notizie/2017/06/20/a-norcia-ci-sara-uno-sportello-sisma_1d102f83-a648-47fe-a651-998a74e8cbac.html'
data: 22/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
