### ISSUE TITLE
Radio Amatrice, una voce dal terremoto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3187]
<pre><yamldata>titolo: 'Radio Amatrice, una voce dal terremoto'
descrizione: '(ANSA) - MILANO, 21 GIU - "È il primo caso di una Radio nata all''indomani di un terremoto. Voluta con felice intuizione dal sindaco dopo la prima scossa il 24 agosto 2016 per garantire informazioni e aiuto e stabilire un canale di comunicazione tra le istituzioni e una comunità duramente provata. Di scossa in scossa, in tutti questi mesi e, fin nei difficili giorni in attesa della ricostruzione, la radio che trasmette con l''impegno di una piccola squadra di giornalisti e tecnici all''inizio ha utilizzato la frequenza concessa da Radio Dolce Musica per poi sfruttare la maggior potenzialità del web. Encomiabile esempio di ottima informazione di servizio e di passione civile": questa la motivazione con la quale la giuria ha assegnato il Premiolino 2017 alla redazione di Radio Amatrice. (ANSA).'
link: 'http://www.ansa.it/abruzzo/notizie/2017/06/21/radio-amatrice-una-voce-dal-terremoto_8c4ca979-f7b1-4847-955e-43762a72ab00.html'
data: 22/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Notizia già presente.
