### ISSUE TITLE
Associazione Pro #Camerino ha bisogno di un condizionatore

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3193]
<pre><yamldata>tel: '0737-632534  //  345-8855294'
email: proloco@camerino.sinp.net
cosa: condizionatore
descrizione: 'L''associazione turistica Pro-Camerino (Camerino - Provincia di Macerata), a causa del terremoto , si è trasferita in un container sprovvisto di condizionatore, per affrontare la stagione estiva avremmo bisogno di un condizionatore.'
indirizzo: 'Piazza Cavour, Camerino, MC, Marche, Italia'
lat: '43.1357641'
lon: '13.0683092'
link: ''
immagine: 'http://i.imgur.com/s0FFNIS.png'
data: 27/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che del condizionatore non c'è più bisogno.
