### ISSUE TITLE
Libri scolastici gratis per due anni nelle zone colpite

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3194]
<pre><yamldata>titolo: 'Libri scolastici gratis per due anni nelle zone colpite'
descrizione: 'Libri di testo gratuiti, a settembre, per gli studenti delle aree colpite dal terremoto, per un totale di 140 Comuni coinvolti. Lo prevede la convenzione siglata tra il Ministero dell''Istruzione e l''Associazione Italiana Editori (Aie), sintetizzata in una circolare che sarà inviata nei prossimi giorni alle scuole con modalità e scadenze per accedere all''agevolazione. La distribuzione gratuita dei testi varrà per i prossimi due anni scolastici, il 2017-2018 e il 2018-2019. Il nuovo accordo amplia quello siglato nell''autunno del 2016 per la fornitura di libri alle ragazze e ai ragazzi di Amatrice, Accumoli, Arquata del Tronto e Acquasanta Terme, allargando l''iniziativa a tutte le alunne e gli alunni delle aree colpite da eventi sismici.'
link: 'http://www.ilmessaggero.it/primopiano/cronaca/terremoto_libri_scolastici_gratis_prossimi_due_anni_nelle_aree_colpite-2519165.html'
data: 27/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
