### ISSUE TITLE
Leffe, una birra speciale per aiutare i monaci di #Norcia: 100mila bottiglie "uniche"

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3196]
<pre><yamldata>titolo: 'Leffe, una birra speciale per aiutare i monaci di #Norcia: 100mila bottiglie "uniche"'
descrizione: 'Tutti i proventi legati alla vendita delle bottiglie #leffepernorcia verranno donati ai monaci di Norcia per la costruzione della cappella in legno presso San Benedetto in Monte, località poco fuori dalle mura della città'
link: 'http://www.perugiatoday.it/economia/norcia-terremoto-birra-leffe-speciale-monaci-monastero.html'
data: 27/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
