### ISSUE TITLE
Bandi di finanziamento e concessione

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3200]
<pre><yamldata>titolo: 'Bandi di finanziamento e concessione'
descrizione: 'Imprenditori agricoli ai sensi dell’articolo 2135 del Codice Civile e loro coadiuvanti singoli o associati rientranti per dimensione nella definizione di micro o piccola impresa secondo l’allegato I del Regolamento UE 702 del 25.06.2014 ABER, ai sensi della raccomandazione della Commissione 2003/361/CE del 06.05.2003.'
link: 'https://www.regione.marche.it/Entra-in-Regione/Bandi?id_7590=440'
data: 27/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
