### ISSUE TITLE
Insieme Risorgeremo - Manifestazione

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3202]
<pre><yamldata>titolo_evento: 'Insieme Risorgeremo - Manifestazione'
data_evento: 07/08/2017
ora_evento: '10:00'
promotore: 'Insieme Risorgeremo'
descrizione: '08/07/2017 - 10:00-13:00. In questi mesi siamo caduti in un limbo...come avvolti da un sonno malefico, ma noi ESISTIAMO E RESISTIAMO. Sono state distrutte le nostre case e la nostra storia, ma non la nostra dignità. Manifestiamo nei nostri luoghi perchè il terremoto ha distrutto tutto ma il popolo del Centro Italia è devastato ancor più dal Sistema, dal non Stato. Non possiamo sostenere più i nostri carnefici. Chi ha le responsabilità se le deve assunere e ne deve rispondere. La manifestazione è stata organizzata da terremotati per i terremotati, siamo un unico popolo senza differenze regionali, ci troviamo tutti nella stessa situazione, abbiamo tutti lo stesso obiettivo: far rinascere la nostra terra. Come luogo dove manifestare è stato scelto Grisciano per la sua posizione strategica sulla Salaria e per la presenza di qualche servizio (bar e ristorante).'
indirizzo: 'Strada Statale 4 Via Salaria, Case Valentini, Accumoli, RI, LAZ, 02011, Italia'
lat: '42.7338658'
lon: '13.2681275'
link: 'https://www.facebook.com/events/835858773229716/?acontext=%7B%22ref%22%3A%224%22%2C%22feed_story_type%22%3A%22308%22%2C%22action_history%22%3A%22null%22%7D'
data: 27/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
