### ISSUE TITLE
24 MILIONI DI EURO PER LE SCUOLE ABRUZZESI, ECCO IL PIANO

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3205]
<pre><yamldata>titolo: '24 MILIONI DI EURO PER LE SCUOLE ABRUZZESI, ECCO IL PIANO'
descrizione: 'Gli istituti interessati sono: scuola dell''infanzia ''Leognano'' di Montorio al Vomano (Teramo), 390mila euro; scuola ''A. Gasbarrini'' di Civitella del Tronto (Teramo), 913.875 euro; scuola materna di Civitella del Tronto, 393.750 euro; Scuola media ''Niccola Palma'' di Campli (Teramo), 1.687.500 euro; scuola materna, elementare e media di Campli, in località Marrocchi, 2.262.135 euro; scuola materna ''Paolo Del Tosto'' di Pizzoli (L''Aquila), 1.119.622 euro; scuola dell''infanzia ed elementare ''San Giuseppe'' di Teramo, 4.111.773 euro; scuola dell''infanzia Villa Ripa di Teramo, 230.602 euro; Itc programmatori ''B. Pascal'' di Teramo, 5.379.345 euro; Itc ''G.Marconi'' piccola succursale di Penne, 611.065 euro; istituto superiore ''B. Spaventa'' di Città Sant''Angelo, 1.221.700 euro; scuola primaria direzione didattica plesso vecchio di Sant''Egidio alla Vibrata, 1.800.630 euro; complesso scolastico ''Carlo Forti'' di Crognaleto (Teramo), 817.500 euro; scuola infanzia e asilo nido ''Santa Maria degli Angeli'' di Mosciano Sant''Angelo (Teramo), 262.500 euro; scuola elementare di Rocca Santa Maria (Teramo), 285.000 euro. A Penne sono già andati 1,2 milioni di euro stanziati dalla Regione con risorse proprie sempre per interventi in materia di edilizia scolastica, mentre a Isola del Gran Sasso (Teramo) si sta procedendo con un intervento diretto del commissario straordinario per la ricostruzione, Vasco Errani, per 2,5 milioni di euro.'
link: 'http://www.abruzzoweb.it/contenuti/terremoto-2016-24-milioni-di-euro-per-le-scuole-abruzzesi-ecco-il-piano/631147-302/'
data: 27/06/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
