### ISSUE TITLE
#LEFFEPERNORCIA: UNA NUOVA BIRRA PER RICOSTRUIRE IL MONASTERO DI SAN BENEDETTO

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3220]
<pre><yamldata>titolo: '#LEFFEPERNORCIA: UNA NUOVA BIRRA PER RICOSTRUIRE IL MONASTERO DI SAN BENEDETTO'
descrizione: 'La distruzione del terremoto mobilita una nuova solidarietà tra produttori di birre, in particolare la Leffe storica birra belga che con l’hashtag #leffepernorcia lancia sul mercato centomila bottiglie per finanziare una struttura antisismica per il Monastero di Norcia. leffepernorciaLa Leffe, storica birra belga prodotta in abbazia a partire dal 1240 dai monaci norbertini, fa parte del colosso AB Inbey, ha indetto la produzione di una nuova bottiglia in edizione limitata. Si tratta della versione griffata della sua Blonde lanciata con l’hashtag #leffepernorcia, sarà distribuita solo in Italia a favore dell’iniziativa di ricostruzione e finanziamento per il Monastero di San Benedetto che si trova in difficoltà per le ripetute scosse sismiche del centro Italia nei mesi precedenti. La comunità internazionale dei giovani monaci in seguito al terremoto sono stati costretti ad allontanarsi dalla struttura e si trovano a San Benedetto in Monte, speranzosi di poter presto rivedere il loro luogo ricostruito.'
link: 'http://www.vocidicitta.it/attualita/leffepernorcia-una-nuova-birra-per-ricostruire-il-monastero-di-san-benedetto/'
data: 03/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
