### ISSUE TITLE
Azienda Agricola Brandimarte Alessia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3222]
<pre><yamldata>chi: 'Azienda Agricola Brandimarte Alessia'
descrizione: 'Alessia, titolare di un’azienda di allevamento di ovini con 92 capi e di un caseificio aziendale per la lavorazione del latte, ha perso il fabbricato principale e tutto ciò che conteneva, con gravi danni economici. Ha ottenuto 5000€ dalla campagna di Legambiente "La rinascita ha il cuore giovane" ed ha aperto un progetto di crowdfunding in bitcoin sulla piattaforma Helperbit. Nell''immediato ha bisogno di un pettine per la raccolta imminente delle lenticchie ed i primi fondi che raccoglierà tramite Helperbit saranno utilizzati proprio per l’acquisto di tale macchinario.'
intestazione: 'Un aiuto per il nuovo raccolto delle Lenticchie di Castelluccio di Norcia - Raccolta fondi in bitcoin'
iban: ''
bic: ''
postale: ''
causale: ''
link: 'https://helperbit.com/donateitale.php'
email: ''
data: 04/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
