### ISSUE TITLE
Richiesta urgente di 1 condizionatore, per una famiglia di Bolognola

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3233]
<pre><yamldata>tel: '3291631198'
email: christianvarani@gmail.com
cosa: 'Richiesta urgente di 1 condizionatore, per una famiglia di Bolognola'
descrizione: 'Serve urgentemente un condizionatore a Bolognola, presso un modulo abitativo provvisorio (container) dove vive una famiglia con dei bambini piccoli e con un caldo davvero afoso ed elevato, specialmente per poter stare all''interno del modulo abitativo durante la giornata. La richiesta arriva su segnalazione di una persona di Bolognola (vedi profilo Facebook segnalato), con la quale sono in contatto. Per informazioni più dettagliate e per poter donare e consegnare il condizionatore, rivolgersi ad uno o a tutti i recapiti specificati in questa richiesta. Grazie. Christian'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Daniela Cecchini'
immagine: ''
data: 09/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che una persona a Corridonia (Mc) ha donato il condizionatore.
