### ISSUE TITLE
Monte Cavallo (MC): niente comunicazioni telefoniche mobili. Comune isolato da un mese, funziona solo linea fissa del Comune e di alcune abitazioni

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3234]
<pre><yamldata>tel: ''
email: ''
cosa: 'Monte Cavallo (MC): niente comunicazioni telefoniche mobili. Comune isolato da un mese, funziona solo linea fissa del Comune e di alcune abitazioni'
descrizione: 'Da un mese isolato il Comune di Monte Cavallo. Praticamente inesistente la copertura telefonica mobile. Dopo che la Tim ha provveduto a sostituire il ripetitore di Pian della Noce, il Sindaco chiede a Infratel Italia di intervenire per installare due giunti in fibra ottica così da rendere finalmente fruibile il servizio.'
indirizzo: 'Giulo - Fiume, Pieve Torina, MC, Marche, Italia'
lat: '42.9944324'
lon: '13.0010217'
link: 'http://www.cronachemaceratesi.it/2017/07/09/monte-cavallo-dalle-scosse-allisolamento-cellulari-ko-aspettiamo-infratel-da-un-mese/985473/'
immagine: ''
data: 09/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Tim ci ha comunicato via Twitter che le linee sono state ripristinate. Chiudo.
