### ISSUE TITLE
Dopo quasi undici mesi, montata la prima stalla a Castelsantangelo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3240]
<pre><yamldata>titolo: 'Dopo quasi undici mesi, montata la prima stalla a Castelsantangelo'
descrizione: 'E'' stato ''''un parto lunghissimo'''', quasi 11 mesi, ma finalmente a Castelsantangelo sul Nera è stata montata e consegnata la prima stalla per le mucche rimaste senza un tetto dopo il terremoto. Lo annuncia il sindaco Mauro Falcucci, che continua a lamentare i tempi lunghi della ripresa, dovuti all''''''errore politico di considerare tutti i comuni del cratere sullo stesso piano: da quelli devastati, come il nostro, a quelli con danni contenuti''''. La stalla comunque, assegnata ad Angelo Stazi, una famiglia di allevatori storici, è un primo segnale positivo. ''''Altre sono in via di montaggio'''' dice il sindaco. (Ansa)'
link: 'https://picchionews.it/cronaca/dopo-quasi-undici-mesi-montata-la-prima-stalla-a-castelsantangelo'
data: 11/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
