### ISSUE TITLE
A #Montefortino cercasi smontagomme ed equilibratrice gomme per far ripartire attività

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3241]
<pre><yamldata>tel: '3396176626'
email: barchettigrazianosnc@gmail.com
cosa: 'Commerciante arigiana terremotata'
descrizione: 'Chiedo un aiuto per far ripartire la mia attività colpita dal terremoto del 24/08/2016. Io e mio marito viviamo e lavoriamo a Montefortino (Fm) e abbiamo sia la casa che il luogo dove lavoriamo inagibili. Abbiamo, infatti, una stazione di servizio carburanti IP con servizi di gommista, equilibratura, convergenza assetto ruote, cambio oli e filtri motori, autoaccessori auto e autolavaggio. Gran parte delle attrezzature sono andate distrutte e abbiamo bisogno almeno di smontagomme ed equilibratrice gomme per riprendere l''attività. Sono attrezzature che utilizziamo quotidianamente ma al momento sono spese molto costose da dover affrontare. Grazie alla donazione di un Comune lombardo siamo riusciti a trovare un container dove mettere un po di materiali e grazie ad una colletta abbiamo comprato uno scaffale per le gomme. Avremmo bisogno anche di due climatizzatori per il container.  Non riusciamo ad avere nessun aiuto dalla Regione. Non sappiamo più a chi rivolgerci per poter continuare tenere aperta la nostra attività, unico reddito della nostra famiglia. Speriamo voi troviate il modo per darci una mano. Grazie! Barelli Lucia.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 11/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Invio email per chiedere località e che tipo di attività svolge.

**Comment by cristigalas** [comment]
La signora Lucia ha risposto aggiungendo un po' di informazioni. Aggiorno segnalazione e accetto.

**Comment by cristigalas** [comment]
La signora Lucia ci ha inviato una email per dirci che il container lo hanno trovato (donazione di un Comune lombardo) e attraverso una colletta, nata in seguito alla pubblicazione su TCI della segnalazione, hanno acquistato gli scaffali per conservare le gomme. Sto aspettando di sapere se hanno trovato o meno anche il resto delle attrezzature che chiedevano e se hanno bisogno di altro.

**Comment by cristigalas** [comment]
La signora Lucia ha risposto via email confermando che al momento le necessità più importanti sono equilibratrice e smontagomme e 2 climatizzatori per il container ma sono benvenute anche collette e donazioni di denaro per comprare altri materiali.

**Comment by chiccap** [comment]
@cristigalas hai già modificato il testo della richiesta? ho notato che dal sito non compare il testo...forse dobbiamo chiamare i rinforzi!

**Comment by cristigalas** [comment]
@chiccap mancava un apice in un apostrofo! Maledetti apici! Ora dovrebbe andare...

**Comment by chiccap** [comment]
Funziona! Grazie mille.

**Comment by cristigalas** [comment]
Christian Varani ci segnala che la segnalazione può essere chiusa.
