### ISSUE TITLE
Associazione Mam Beyond Borders cerca ad #Amatrice volontari per la costruzione di casette 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3249]
<pre><yamldata>tel: ''
email: ''
cosa: 'FALEGNAMI VOLONTARI'
descrizione: 'Associazione Mam Beyond Borders cerca volontari! Falegnami, idraulici, elettricisti e manodopera varia. Dopo lunghe settimane di stop sono ripresi i lavori per il completamento delle mobil house (casette mobili) destinate alle famiglie di Amatrice! Ci sono alcuni cambiamenti sostanziali sia nel progetto che nella squadra di coordinamento. Abbiamo lavorato per superare le difficoltà organizzative e stabilire un sistema di lavoro più metodico ed in linea di massima affinché si evitasse il ripresentarsi dei problemi riscontrati da diversi volontari scesi per lavorare alle mobil house. Possiamo dire che ci sono ora i giusti presupposti per poter chiedere di nuovo il vostro supporto, se già prima il vostro aiuto come falegnami volontari era molto utile, ora diventa più che mai essenziale! Aiutiamo questi amici a ripartire? Ci aiutate a dare una mano? Dai, dai, dai, lo sappiamo che ci siete ancora ! Contattateci! Al link Facebook tutte le info.'
indirizzo: 'Piazza Cacciatori del Tevere, Casalene, Amatrice, RI, LAZ, Italia'
lat: '42.6292367'
lon: '13.2891755'
link: 'https://www.facebook.com/MAMbeyondborder/photos/a.563901896989517.1073741828.563881680324872/1576855872360776/?type=3&theater'
immagine: ''
data: 13/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica che non c'è più bisogno di volontari perché tutte le richieste di casette sono state soddisfatte.
