### ISSUE TITLE
Famiglia cerca roulotte a #CornilloNuovo, frazione di #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3253]
<pre><yamldata>tel: '3406029191'
email: kicca.62@gmail.com
cosa: Roulotte
descrizione: 'Buongiorno, cerco una roulotte per una mia amica di Cornillo Nuovo, frazione di Amatrice che vuole tornare nella sua terra, io grazie al buon cuore di una famiglia l''ho trovata ma è piccola e non posso ospitarli, qualcuno ci può aiutare? Grazie. Cristiana Bellini'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 14/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviata richiesta a gruppo Facebook dei Caravanisti Solidali. Qui il post https://www.facebook.com/groups/CARAVANISTISOLIDALI/permalink/1928108014104517/

**Comment by cristigalas** [comment]
Roulotte consegnata dal gruppo Caravanisti Solidali come comunicato via email da Christian Varani.
