### ISSUE TITLE
Appartamento a Cupra Marittima, 800 metri dal centro

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3254]
<pre><yamldata>tel: '3495900941'
email: stefaniag2002@gmail.com
descrizione: 'Cupra Marittima, 800 metri dal centro. Affitto annualmente o anche per brevi periodi. Cupra Marittima, 800 metri dal centro. Un appartamento 48 mq primo piano senza ascensore, ingresso indipendente una camera da letto matrimoniale un bagno con doccia un grande tinello con angolo cottura un terrazzo 100 mq un piccolo giardino e orto annesso già avviato alla produzione, gabbie per animali da cortile galline conigli volatili in genere. €. 400 mensili inclusa tassa rifiuti solidi urbani, acqua, Riscaldamento centralizzato. Libero dal 2 settembre 2017. Ripeto, affitto annuale o brevi periodi. Affitto annualmente o anche per brevi periodi.Cupra Marittima.800 metri dal centro. Un appartamento 101 mq piano seminterrato, ingresso indipendente due camere da letto matrimoniali senza finestre, un bagno con finestra con doccia idromassaggio e antibagno, una grande sala con finestrone a scorrimento, cucina e dietrocucina con dispensa, locale lavanderia-stireria di 30 mq con finestrone, un piccolo giardino, gabbie per animali da cortile galline conigli volatili in genere. Riscaldamento autonomo. €. 400 mensili. Libero dal 24 Luglio 2017. Ripeto, affitto annuale o brevi periodi.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 16/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap che facciamo? Io non accetterei, tu che dici?

**Comment by chiccap** [comment]
Anche io non accetterei.
