### ISSUE TITLE
Cercasi volontari a #Scai per lavori nelle mobilhouse

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3255]
<pre><yamldata>tel: feltrepernorciaedintorni@gmail.com
email: ''
cosa: 'Cercasi volontari a #Scai per lavori nelle mobilhouse'
descrizione: 'Stiamo cercando dei volontari, in particolare elettricisti e idraulici, per proseguire con i lavori delle mobilhouse vicino a Scai, frazione di Amatrice. Vitto e alloggio a carico dell''associazione Feltre per Norcia e dintorni. Per contatti vedi link Facebook o email movimentoperlaterra@gmail.com e feltrepernorciaedintorni@gmail.com. Grazie.'
indirizzo: 'SP19, Montereale, RI, ABR, Italia'
lat: '42.5980591'
lon: '13.2305149'
link: 'https://www.facebook.com/groups/CARAVANISTISOLIDALI/permalink/1925788624336456/'
immagine: ''
data: 16/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica che non c'è più bisogno di volontari perché a Scai le richieste di casette mobili sono state tutte soddisfatte.
