### ISSUE TITLE
Ricostruzione, al via il programma per la riapertura di trentotto chiese

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3259]
<pre><yamldata>titolo: 'Ricostruzione, al via il programma per la riapertura di trentotto chiese'
descrizione: 'PERUGIA – “...Parte in Umbria la ricostruzione di un consistente patrimonio culturale danneggiato dal terremoto, a partire dalle Chiese, per un importo complessivo di oltre 20 milioni di euro. L’auspicio è che per le Chiese oggetto degli interventi, le si possa restituire al culto entro la fine dell’anno”. E’ quanto ha affermato la presidente della Regione Umbria, Catiuscia Marini, nel corso della conferenza stampa svoltasi questa mattina a Perugia, a Palazzo Donini, convocata per fare il punto sugli interventi di messa in sicurezza e restauro dei beni culturali mobili danneggiati dagli eventi sismici, presente l’assessore regionale alla cultura, Fernanda Cecchini, cui hanno partecipato anche la soprintendente archeologia, belle arti e paesaggio dell’Umbria e coordinatore dell’Unità di Crisi dell’Umbria per il MiBACT, Marica Mercalli, il direttore generale della Fondazione Cassa Risparmio Firenze, Gabriele Gori, e Marco Ciatti, Direttore dell’Opificio delle Pietre Dure di Firenze... ...Lavori in 38 chiese “Con le ordinanze ‘23’ e ‘32’ potranno partire subito – ha affermato Marini – lavori di ricostruzione di ben 38 Chiese, la maggior parte delle quali ubicate nell’area del cratere, per un importo complessivo di 11 milioni di euro. Si tratta di strutture che non hanno subito danni gravissimi e per questo rapidamente riparabili, per poterle restituire al culto il prima possibile. C’è poi l’altro programma di primi interventi per opere pubbliche danneggiate dal sisma, per 9 milioni di euro”.'
link: 'http://www.lanotiziaquotidiana.it/umbria/2017/07/17/ricostruzione-al-via-il-programma-per-la-riapertura-di-38-chiese/'
data: 18/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
