### ISSUE TITLE
Uniti si riparte, è nata la cooperativa agricola ‘Città di Cascia’

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3264]
<pre><yamldata>titolo: 'Uniti si riparte, è nata la cooperativa agricola ‘Città di Cascia’'
descrizione: 'CASCIA – E’ stata presentata venerdì 14 luglio la “Cooperativa Agricola Città di Cascia”, formatasi dall’unione delle aziende di questo piccolo comune della Valnerina. Gli imprenditori del luogo, dopo il sisma del 30 ottobre uniti dall’amore per la propria terra, hanno deciso di mettere a disposizione le proprie competenze per qualificare, sostenere e promuovere il territorio e tutto quello che lo può far rinascere. All’evento presenti il Sindaco di Cascia Mario del Carolis, il Presidente della Cooperativa Damocle Magrelli, il Vice presidente Legacoop Umbria Vladimiro Zaffini, Andrea Radicchi responsabile ANCA Umbria e l’Assessore all’Agricoltura della Regione Umbria Fernanda Cecchini. Ripartire dalle eccellenze Attraverso i prodotti la cooperativa vuole raccontare la storia dei luoghi, delle loro risorse naturali e culturali; la qualità delle materie prime, rappresentate non solo dalle caratteristiche del prodotto stesso, ma anche dalle tecniche di preparazione che rappresentano l’esperienza degli agricoltori e degli artigiani. Sono eccellenze che hanno qualcosa da dire, frutto di un lavoro creativo e dell’impegno di generazioni, che descrivono per intero il contesto socio-culturale dove sono state realizzate. “A seguito del sisma -dice Damocle Magrelli presidente della cooperativa- si è mostrata tutta la debolezza del sistema economico della Valnerina, per cui allargare le opportunità di lavoro legate al mondo dell’agricoltura, che dalle nostre parti è sempre stato un mondo attivo e produttivo, far si che tutto ciò possa diventare sistema e creare le condizioni di maggiori opportunità per gli imprenditori agricoli”.'
link: 'http://www.lanotiziaquotidiana.it/umbria/2017/07/16/uniti-si-riparte-e-nata-la-cooperativa-agricola-citta-di-cascia/'
data: 18/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
