### ISSUE TITLE
Cercasi attrezzatura cucina per associazione #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3269]
<pre><yamldata>tel: '3926462066'
email: vanessapiccari@libero.it
cosa: 'Cercasi attrezzatura cucina per associazione #Amatrice'
descrizione: 'Serve materiale per attrezzare il locale cucina di A.I.P.S. associazione Insieme per Sant''Angelo, che resta al momento l''unico punto di riferimento della comunità. Qualsiasi tipologia di attrezzatura possa andare in un locale cucina è ben accetta: abbiamo bisogno di una cucina con fuochi e poi scaffalature, pentolame, stoviglie, frigo... Contattare Vanessa Piccari: 3926462066. Grazie per l''immensa disponibilità.'
indirizzo: 'SP20, Capovilla, Amatrice, RI, Lazio, Italia'
lat: '42.6496118'
lon: '13.3042554'
link: 'http://www.amatriceaips.it/'
immagine: ''
data: 19/07/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Aggiornamento rispetto a questa segnalazione: https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/784

**Comment by cristigalas** [comment]
Contatta da Enrico Ganassi via Twitter e sito web ditta Angelo Po di Reggio Emilia, specializzata in grandi cucine https://twitter.com/enricoseidue/status/888129599908978688

**Comment by chiccap** [comment]
Inviata mail ad Angelo Po, attendiamo risposta.

Tel Mario Feliziani presidente associazione: 3488197277

**Comment by cristigalas** [comment]
Christian Varani ci scrive via email che non c'è più bisogno della cucina. Chiudo.
