### ISSUE TITLE
A #Camerino cercasi fasciatoio

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3271]
<pre><yamldata>tel: '3334908040'
email: amoreperamorecamerino@gmail.com
cosa: Fasciatoio
descrizione: 'Un padre di famiglia di Camerino ha contattato la nostra associazione Amore per Amore per Camerino per sapere se ci fosse la disponibilità di un fasciatoio per la loro bimba nata subito dopo le scosse di ottobre 2016. A Luglio 2016 hanno acquistato una casa, chiedendo un mutuo alla banca, per venire ad abitare a Camerino. Il 20 agosto erano pronti ad entrarci, ma il sisma del 22 agosto già aveva lesionato tutta la loro abitazione. Da ottobre non sono più riusciti ad entrarci. Se qualcuno può aiutarli, l''associazione farà da tramite.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/07/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Il fasciatoio è stato donato e consegnato come comunicato da Christian Varani via email.
