### ISSUE TITLE
fondi / finanziamenti

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3299]
<pre><yamldata>titolo: 'fondi / finanziamenti'
descrizione: 'Vorrei Segnalare quanto segue : terremoto a Modena .. la mia abitazione a 30 Km, da epicentro, ha subito danni ma non è stata ritenuta nell''area interessata a ricevere aiuti in termini finanziari. Errani allora Commissario Straordinario ha ritenuto di devolvere 20.000.000,oo di Euro a Castelvetro Piacentino , a ben 130 Km dall''epicentro . Oggi grazie ai 20.000.000,oo La Lameri S.p.A. ha decentrato da Cavezzo ( Mo ) la sua unità produttiva ( che aveva subito danni per €1.000.000,oo ) in Castelvetro Piacentino, e ne sta costruendo una spendendo i 20.000.000,oo di cui sopra ... castruisce in un area agricola acquistata e pagata quasi 4 volte il suo valore... io non ho trovato provvedimenti legislativi che indicano Castelvetro Piacentino come Zona Terremotata.....solo n provvedimento di Errani.........'
link: 'http://www.laprovinciacr.it/news/cronaca/119762/Lameri-group-si-espande--sede.html'
data: 05/08/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente.
