### ISSUE TITLE
Sisma centro Italia, agevolazioni per le aree colpite

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3307]
<pre><yamldata>titolo: 'Sisma centro Italia, agevolazioni per le aree colpite'
descrizione: 'Il Ministero dello Sviluppo economico ha pubblicato le modalità e i termini per la presentazione delle domande di accesso alle agevolazioni in favore delle imprese localizzate nella zona franca istituita nei Comuni colpiti dagli eventi sismici in Abruzzo, Lazio, Umbria e Marche. La zona franca urbana (ZFU) è istituita ai sensi dell’art. 46 del decreto-legge 24 aprile 2017, n. 50 e le modalità operative sono contenute nella circolare 4 agosto 2017, n. 99473 Le risposte disponibili sono pari a oltre 490 milioni di euro, suddivisi tra il 2017 e il 2019. Le domande potranno essere presentate dal 23 ottobre 2017.'
link: 'http://www.abruzzosviluppo.it/new/2017/08/07/sisma-centro-italia-agevolazioni-le-aree-colpite/'
data: 08/08/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
