### ISSUE TITLE
Sfollato a Porto Sant'Elpidio con tre bimbi cerca auto e lavoro 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3320]
<pre><yamldata>tel: '3663796088'
email: 
cosa: 'Cerco aiuto, non ho più nulla, ho tre bambini piccoli e mi urge un auto possibilmente familiare'
descrizione: 'Mi chiamo Saturnino Quinzi, ho 57 anni, tre figli piccoli, sono senza casa e lavoro. Abito come sfollato a Porto Sant''Elpidio presso il camping Holiday (camera 213), cerco un''auto, possibilmente familiare, e un lavoro. Ero un commerciante di pellami per calzature ma posso fare il magazziniere o altro. Vi supplico aiutateci, con 3piccoli e senza lavoro, auto, soldi, non si vive. Grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 13/08/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviata email per avere ulteriori info su località e tipo di aiuto.

**Comment by cristigalas** [comment]
Email tornata indietro, indirizzo errato. Provo con sms.

**Comment by cristigalas** [comment]
Ricevuta risposta via sms con ulteriori informazioni. Aggiorno segnalazione (tolgo indirizzo email, chi segnala non è sicuro della correttezza dell'indirizzo) e pubblico.

**Comment by chiccap** [comment]
Trovato lavoro come carico scarico merci. E' ancora in cerca di un'auto. @cristigalas aggiorniamo o apriamo nuova segnalazione?

**Comment by cristigalas** [comment]
@chiccap Credo sia meglio chiudere questa e aprire nuova segnalazione per l'auto copiando semmai parte del testo di questa issue.

**Comment by cristigalas** [comment]
@chiccap aggiungerei anche rimando interno per collegare le due segnalazioni.
