### ISSUE TITLE
Aiuto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3321]
<pre><yamldata>tel: '3663796088'
email: quinzisaturnino@libero.it
cosa: Aiuto
descrizione: 'O 57 anni non lavoro da quattro, non o piu nulla, auto, soldi, casa, lavoro,... O tre figli molto molto piccoli alloggio all''holiday ...ora cerco urgentemente un auto x andare in giro x cercare, soldi e lavoro,... La mia priorieta sarebbe questa, aiutateci vi orego'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 13/08/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta già presente.
