### ISSUE TITLE
Associazione di #Caldarola (Mc) cerca container/modulo prefabbricato

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3329]
<pre><yamldata>tel: '3204283973'
email: caldarola_volley@libero.it
cosa: 'Container/modulo prefabbricato circa 35 mq'
descrizione: 'Salve, sono il Presidente dell''A.D.U.S. Caldarola Volley in Provincia di Macerata. Avremmo bisogno di un modulo/container di circa 35 mq per riporre tutta la nostra attrezzatura presente nella sede sociale purtroppo in zona rossa e inagibile. Chiunque abbia la possibilità di aiutarci in qualche maniera mi contatti!! Grazie.'
indirizzo: 'Via Pallotta, Caldarola, MC, Marche, Italia'
lat: '43.1380016'
lon: '13.2245669'
link: ''
immagine: ''
data: 23/08/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci segnala che non c'è più bisogno del container perché l'associazione da qualche mese ha a disposizione una palestra prefabbricata.
