### ISSUE TITLE
"Al centro dell'Italia, ai margini del Paese": da L'Aquila 3e32 lancia appello per le aree interne

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3331]
<pre><yamldata>titolo: '"Al centro dell''Italia, ai margini del Paese": da L''Aquila 3e32 lancia appello per le aree interne'
descrizione: '"La ricostruzione è un diritto, perché non esistono territori di serie A e territori di serie B". Termina così la nota di 3e32 / CaseMatte, collettivo nato dopo il terremoto del 2009 all''Aquila. Le parole del comitato del capoluogo abruzzese arrivano nel primo anniversario della forte scossa che il 24 agosto dell''anno scorso devastò l''Appennino piceno-laziale. Il 3e32, come fa dalla sua nascita (nell''aprile 2009), continua a chiedere che le risorse destinate alle grandi opere (come il Tav o il metanodotto Snam) vengano al contrario impiegate nella messa in sicurezza dei territori sismici: "Ormai da anni chiediamo, con modi e toni diversi, la messa in sicurezza dei nostri territori. Tanto è stato il tempo durante il quale abbiamo continuato a lottare con la fragilità e la precarietà delle nostre vite, per costruire un presente e un futuro migliore", si legge nella nota. Il quadro dipinto dalle parole del comitato aquilano è quello di aree interne appenniniche allo stremo, deprivate dall''austerità dei servizi di base, fiaccate dalle continue scosse di terremoto e gravate da una crisi economica senza precedenti: "ovunque, vicino e lontano, chiudono i presidi ospedalieri di prossimità, franano le montagne, vengono transennate le scuole e avvelenate le acque", le parole del 3e32.'
link: 'http://news-town.it/cronaca/17116-al-centro-dell-italia,-ai-margini-del-paese-da-l-aquila-3e32-lancia-appello-per-le-aree-interne.html'
data: 24/08/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap non accetterei, che dici?

**Comment by chiccap** [comment]
Nemmeno io accetterei, l'avevo lasciata in sospeso apposta per sentire il tuo parere!
