### ISSUE TITLE
Ricostruzione e futuro Ue per i giovani: Tajani incontrerà i cittadini a Norcia. E domani Bruxelles vota sui fondi

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3337]
<pre><yamldata>titolo: 'Ricostruzione e futuro Ue per i giovani: Tajani incontrerà i cittadini a Norcia. E domani Bruxelles vota sui fondi'
descrizione: 'NORCIA – Il presidente del Parlamento Europeo, Antonio Tajani, arriverà a Norcia nell’ambito dei dialoghi con i cittadini organizzati dall’Unione Europea. “Costruire un’Europa migliore con i cittadini per le generazioni future”, questo il titolo dell’evento, vedrà la presenza oltrechè di Tajani anche del commissario europeo per l’istruzione, la cultura, i giovani e lo sport, Tibor Navracsics, con la moderazione di Gigi Donelli, giornalista di Radio24. Tajani ed il commissario Navracsics discuteranno con il pubblico di ricostruzione della zone terremotate, corpo europeo di solidarietà e iniziative dell’Unione Europea, ma anche delle iniziative programmate nell’ambito dell’anno europeo del patrimonio culturale e del libro bianco sul futuro dell’UE. Scopo dei dialoghi è avvicinare i cittadini alle Istituzioni europee dando loro la possibilità di esprimere la loro opinione sulle politiche dell’UE e di ottenere delle risposte dirette su questioni che toccano la loro quotidianità.'
link: 'http://www.lanotiziaquotidiana.it/umbria/2017/08/29/ricostruzione-e-futuro-ue-per-i-giovani-tajani-incontrera-i-cittadini-a-norcia/'
data: 29/08/2017
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas io non accetterei...

**Comment by cristigalas** [comment]
Nemmeno io, semmai faccio un tweet informativo...

**Comment by chiccap** [comment]
Ok allora tu fai un tweet e io chiudo!
