### ISSUE TITLE
Regione #Marche: bando per 500 tirocini a favore di disoccupati residenti nel cratere

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3359]
<pre><yamldata>titolo: 'Regione #Marche: bando per 500 tirocini a favore di disoccupati residenti nel cratere'
descrizione: 'La Regione Marche, con deliberazione n. 456 in data 8 maggio 2017, ha definito le Linee guida per la realizzazione di circa cinquecento tirocini a favore di soggetti disoccupati, residenti nell’area marchigiana del cratere e/o che lavoravano in realtà economico produttive, ubicate nella zona marchigiana del cratere, e per la concessione di circa cento aiuti economici in caso di assunzioni. Al link tutte le info.'
link: 'http://www.regione.marche.it/News-ed-Eventi/Post/27379/Avviso-Pubblico-Tirocini-a-favore-di-soggetti-disoccupati-residenti-nell-area-marchigiana-del-cratere-e-o-che-lavoravano-in-realt%C3%A0-economico-produttive-ubicate-nella-zona-del-cratere-e-aiuti-in-caso-di-assunzioni'
data: 06/09/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Bando scaduto.
