### ISSUE TITLE
Cercasi modulo abitativo per due anziani #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3375]
<pre><yamldata>tel: '3471738524'
email: fauro@inwind.it
cosa: 'Cerco modulo abitativo'
descrizione: 'Ad Amatrice i miei genitori necessitano di una casa mobile per poter tornare nel loro paese visto che la loro casa è inagibile. Possono contribuire alle spese.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 18/09/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Contattata via Twitter l’associazione La Via del Sale che si è messa in contatto e ci farà sapere.

**Comment by cristigalas** [comment]
Ad Amatrice sono state consegnate tutte le casette necessarie. Chiudo.
