### ISSUE TITLE
Informazioni sui danni dei terremoti in centro Italia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3376]
<pre><yamldata>Nome: lucia
E-mail: lucia.panichi@gmail.com
Testo: >
  Informazioni sui danni provocati dai
  terremoti del 2016 nel Centro Italia
</yamldata></pre>

**Comment by lorenzoperone** [comment]
Ho risposto io via email il 5/10/2017 con il segunete testo:

Buongiorno Lucia,
scusandomi per il ritardo nella risposta, ti segnalo che allo stato attuale il quadro dei danni più completo è quello pubblicato nel report "L’attività del Commissario Straordinario ed 
il futuro della ricostruzione del Centro Italia: una strategia sostenibile", pubblicato sul sito del Commissario Straordinario per la Ricostruzione [1].
Esiste una versione in qui ho evidenziato i punti, secondo me, più rilevanti [2].
Buona giornata.

Lorenzo Perone
terremotocentroitalia.info
ricostruzionetrasparente.it

[1] https://sisma2016.gov.it/wp-content/uploads/2017/09/RAPPORTO-COMMISSARIO-STRAORDINARIO-08-09-2017.pdf
[2] https://hyp.is/TwEyTJxvEeeJUYuwaZAv8Q/sisma2016.gov.it/wp-content/uploads/2017/09/RAPPORTO-COMMISSARIO-STRAORDINARIO-08-09-2017.pdf

**Comment by lorenzoperone** [comment]
@iltempe se mi dai i poteri chiudo la issue ;)

**Comment by cristigalas** [comment]
Ps. @lorenzoperone @iltempe come mai i titoli di questo tipo di segnalazioni viene troncato?

**Comment by lorenzoperone** [comment]
Ciao @cristigalas  non ho una risposta @iltempe che dice?
