### ISSUE TITLE
Cercasi vestiti per inverno #Campotosto (AQ)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3378]
<pre><yamldata>tel: '336768989'
email: ''
cosa: 'Vestiti per inverno'
descrizione: 'A Campotosto serve vestiario per bambini/e e ragazzi/e dai 7 ai 20 anni. Necessitiamo di vestiario tecnico e preferibilmente nuovo o in ottimo stato per affrontare l''inverno. Per informazioni contattare Ercole Di Girolami, tel. 336768989. Grazie!'
indirizzo: 'Strada Regionale 577 del Lago di Campotosto, Campotosto, AQ, Abruzzo, Italia'
lat: '42.558839'
lon: '13.367987'
link: ''
immagine: ''
data: 21/09/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Non vi è più necessità.
