### ISSUE TITLE
Cercasi stufa a pellet per allevatore #Cascia (PG)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3382]
<pre><yamldata>tel: '389 5722461'
email: ''
cosa: 'stufa a pellet'
descrizione: 'Avremmo bisogno di una stufa a pellet per un nostro amico allevatore di mucche da latte di un paesino del comune di Cascia (PG). Gli è stato consegnato il container abitativo che prevede come fonte di riscaldamento dei condizionatori che, oltre ad incidere notevolmente sul consumo di energia elettrica, a -5 gradi non partono. Qui, oltre i -5 ci stiamo, se tutto va bene, da novembre a maggio. Siamo disponibili anche a pagarla non oltre 250€ (non abbiamo altro), grazie.'
indirizzo: 'Largo Monsignor Antonio Elemosina, Cascia, PG, Umbrien, 06043, Italien'
lat: '42.7170082'
lon: '13.0135022'
link: 'https://www.facebook.com/permalink.php?story_fbid=2017231521832931&id=1963924377163646'
immagine: ''
data: 21/09/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che una stufa a pellet nuova è stata donata e consegnata domenica 15 ottobre.
