### ISSUE TITLE
Cercasi Roulotte/Camper ad #Arquata per coppia di anziani

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3385]
<pre><yamldata>tel: '3382259644 (Giacomo Eupizi)'
email: ''
cosa: Roulotte/Camper
descrizione: 'Cerco una roulotte o camper per i miei genitori. Non hanno la SAE perché avendo bisogno di una badante, la casetta risulterebbe troppo piccola in quanto a loro ne spetterebbe solo una di 40 mq, con una sola stanza da letto. Sono molto anziani e con gravi problemi di salute e vivono con me in Ascoli, ma ancora in grado di fare una passeggiata nell''orto o in mezzo alle loro vigne, per questo avremmo bisogno di un punto di appoggio per permettere loro di poter passare qualche ora ad Arquata del Tronto, durante il giorno e farli godere ancora un pò di quella che era la loro casa (finché non verrà demolita) e soprattutto la loro terra che tanto hanno amato e coltivato. Grazie infinite a chi potrà aiutarci.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/09/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Parlato personalmente con sig. Giacomo che sta ancora cercando una roulotte per permettere ai suoi genitori, molto anziani, di stare vicino casa loro, distrutta dal terremoto, almeno di giorno e poi la note dormono a casa del figlio. Chiesto aiuto a Caravanisti Solidali.

**Comment by cristigalas** [comment]
Caravanisti Solidali - Ciurma di Certaldo hanno contattato sig. Giacomo e dovrebbero avere trovato una roulotte per i suoi genitori. Ci faranno sapere se e quando la consegna andrà a buon fine.

**Comment by cristigalas** [comment]
La Ciurma di Certaldo mi ha comunicato via Messanger che consegnerà la roulotte domenica 29 ottobre. Vedi [foto della consegna](https://www.facebook.com/giovanna.acquaroli.10/posts/1446835938765442). Chiudo.

**Comment by cristigalas** [comment]
Vedi [foto della consegna](https://www.facebook.com/giovanna.acquaroli.10/posts/1446835938765442).
