### ISSUE TITLE
Cercasi casa tra #Visso #Ussita #Frontignano per famiglia con bambina appena nata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3387]
<pre><yamldata>tel: ''
email: ''
cosa: 'Cercasi casa tra #Visso #Ussita #Frontignano per famiglia con bambina appena nata'
descrizione: 'I genitori, Romina e Giulio, sono ospiti di un campo di accoglienza e la piccola Giulia è venuta alla luce due mesi prima del previsto. Per il loro ritorno a Visso si cerca una sistemazione adeguata e non il ritorno nelle roulotte o nei prefabbricati messi su dal Comune all’indomani del sisma, inadeguati per una neonata. In particolare l’appello della famiglia è a tutti coloro che hanno a disposizione delle seconde case a Visso, Ussita e Frontignano o in altri paesi del cratere: "Troviamo una casa per Giulia e la sua famiglia, ma anche per tutti quelli che ne hanno bisogno. Mettetele a disposizione, non gratuitamente, a pagamento."'
indirizzo: 'Piazza Martiri Vissani, Visso, MC, Marche, Italia'
lat: '42.9312321'
lon: '13.087449'
link: 'http://www.cronachemaceratesi.it/2017/09/25/disperata-corsa-della-mamma-sfollata-dalla-roulotte-allospedale-giulia-nasce-prematura/1014047/'
immagine: ''
data: 25/09/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci segnala via email che la famiglia ha ricevuto una casetta.
