### ISSUE TITLE
Sfollato a #PortoSantElpidio con tre bimbi cerca auto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3391]
<pre><yamldata>tel: '3663796088'
email: ''
cosa: 'Sfollato a Porto Sant''Elpidio con tre bimbi cerca auto'
descrizione: 'Mi chiamo Saturnino Quinzi, ho 57 anni, tre figli piccoli e attualmente abito come sfollato a Porto Sant''''Elpidio presso il camping Holiday (camera 213). Cerco un''''auto per potermi spostare e ridare alla mia famiglia un minimo di normalità. Grazie.'
indirizzo: 'Via San Giovanni Bosco, Porto Sant''Elpidio, FM, Marche, 63018, Italia'
lat: '43.2589619'
lon: '13.7569828'
link: ''
immagine: ''
data: 30/09/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Segnalazione estratta da una [segnalazione precedente](https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/3320#issuecomment-332894833) chiusa.

**Comment by cristigalas** [comment]
Sig. Saturnino ha inviato oggi un’altra richiesta per l’auto, vedi #3419. Chiudo.
