### ISSUE TITLE
Cercasi urgentemente container o casetta per scuola dell’infanzia di #Fiastra

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3395]
<pre><yamldata>tel: '3398161481 (Silvia Belli)'
email: sia_82@hotmail.com
cosa: 'Cercasi urgentemente container o casetta per scuola dell’infanzia di #Fiastra'
descrizione: 'La scuola di Fiastra non è stata ancora ricostruita e quindi anche per quest''anno ci siamo dovuti organizzare. La scuola primaria e media sono state sistemate in un modulo in legno, mentre l''infanzia è stata rimandata in un agriturismo. Purtroppo però la sistemazione non è il massimo perché gli spazi sono molto limitati e ogni venerdì bisogna procedere con lo smontaggio di tutto e il lunedì rimontarlo. Per le insegnanti sta diventando una situazione pesante, soprattutto perché a livello didattico è molto limitante: non si possono appendere cartelloni, non si possono organizzare angoli dedicati e, insomma, è tutto molto precario. Avremmo quindi bisogno di un piccolo container (i bimbi sono circa 12) o una casettina di legno che possa accoglierli fin quando non arriverà una soluzione stabile per le nostre scuole. Grazie a chiunque potrà aiutarci! Silvia Belli, insegnante della scuola dell’infanzia di Fiastra.'
indirizzo: 'Via Roma, Fiastra, MC, Marche, 62035, Italia'
lat: '43.0361407'
lon: '13.1554547'
link: ''
immagine: ''
data: 07/10/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Contattati Miur e Italia Sicura - Scuole via Twitter. Miur ha risposto dicendo di aver contattato la task force dedicata alle aree terremotate che cercherà di trovare in tempi brevi una soluzione.

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che ha sentito Silvia Belli, secondo cui la richiesta si può chiudere perchè alla scuola di Fiastra è stata trovata una sistemazione più idonea.
