### ISSUE TITLE
Cercasi ditta che installi gratuitamente impianto fotovoltaico #Montegallo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3397]
<pre><yamldata>tel: '3403505371'
email: maurizio.bacchelli@medici.progetto-sole.it
cosa: 'Cercasi ditta che installi gratuitamente impianto fotovoltaico #Montegallo'
descrizione: 'L''associazione Insieme x Ricostruire ha in essere tre cantieri: uno ad Accumuli, uno a Pretare e uno a Montegallo. Per quelli di Pretare e Montegallo, prefabbricati che saranno spazi polifunzionali per la popolazione, è prevista l’’installazione di un impianto fotovoltaico. Mentre per Pretare abbiamo una ditta del posto che ha dato la propria disponibilità all’’installazione gratuita non altrettanto è successo per la struttura di Montegallo ove ci piacerebbe fare la stessa cosa. Serve disponibilità per la messa a  disposizione del materiale complementare ai pannelli e inverter. L’impianto previsto è di 16 KW e andrà montato su onduline metalliche. Grazie!'
indirizzo: 'Strada Provinciale 89 Valfluvione, Montegallo, Ascoli Piceno, Marche, 63094, Italia'
lat: '42.8473894'
lon: '13.3434963'
link: ''
immagine: 'https://i.imgur.com/ok5OWca.jpg'
data: 11/10/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Mancavano gli apici ad alcuni apostrofi, vediamo se adesso funziona....

**Comment by chiccap** [comment]
Montanto e inaugurato il centro.
