### ISSUE TITLE
Cercasi roulotte o camper per famiglia a #Ussita

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3398]
<pre><yamldata>tel: '3381314790'
email: ''
cosa: 'Roulotte o camper'
descrizione: 'Cercasi a Ussita roulotte o camper per una famiglia di 3 persone fino alla consegna delle SAE prevista per dicembre.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 12/10/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che questa famiglia non ha più bisogno di una roulotte.
