### ISSUE TITLE
Salve avrei bisogno delle mappe

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3405]
<pre><yamldata>Nome: Alessio
E-mail: muscialessio@gmail.com
Testo: |
  Salve avrei bisogno delle mappe dove sono individuati i danni alle strutture e i livelli di danno se possibile di:
  Amatrice
  Accumoli
  Sant'angelo
  Arquata del tronto
  Pescara del Tronto
  Visso
  Norcia
  
  grazie
</yamldata></pre>

**Comment by lorenzoperone** [comment]
**testo email inviata il 23/10/2017**
Ciao Alessio,
gli unici dati attualmente disponibili che conosco sono quelli prodotti, immediatamente dopo i sismi dal team Copernicus della commissione europea in collaborazione con la comunità Openstreetmap. E' una valutazione speditiva fatta partendo da foto satellitari di dettaglio. I dati non sono disponibili per tutti i comuni che segnalavi, puoi scaricare questi dati (utilizzabili con un software GIS) a [questo ](http://osmit3.wmflabs.org/check/cratere_sismico_2016/)indirizzo il file si chiama **geojson_damaged_buildings.json**.
Se hai difficoltà ad utilizzarti scrivimi pure.
Ciao.
Lorenzo Perone
terremotocentroitalia.info
ricostruzionetrasparente.it
