### ISSUE TITLE
Salve avre

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3406]
<pre><yamldata>Nome: Alessio
E-mail: muscialessio@gmail.com
Testo: |
  Salve avrei bisogno delle mappe dove sono individuati i danni alle strutture e i livelli di danno se possibile di:
  Amatrice
  Accumoli
  Sant'angelo
  Arquata del tronto
  Pescara del Tronto
  Visso
  Norcia
  
  grazie
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
