### ISSUE TITLE
Urge intervento presso cimitero di #Piedicava #AcquasantaTerme per crolli

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3412]
<pre><yamldata>tel: '3477329217'
email: stdean@tin.it
cosa: 'crolli presso il cimitero della frazione Piedicava di Acquasanta Terme'
descrizione: 'Ieri mi sono recato al cimitero della frazione Piedicava di Acquasanta Terme e ho visto alcuni crolli e l''edificio non è stato messo in sicurezza. L''edificio in oggetto ha anche alcuni cavi dell''Enel attaccati e pericolanti. Allego documentazione fotografica. Cordialmente Stefano De Angelis'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: 'https://i.imgur.com/V3IeQJ1.jpg'
data: 03/11/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Contatta Enel via Twitter: ha risposto che hanno provveduto ad inoltrare la segnalazione. Vedi tweet https://twitter.com/EnelGroupIT/status/927500766553821184

**Comment by cristigalas** [comment]
Via [Facebook ](https://www.facebook.com/paginaufficialedelcomunediacquasantaterme/posts/1540315796061853?comment_id=1540348632725236&notif_id=1509978332579178&notif_t=feed_comment) Comune di Acquasanta ci scrive che domani farà fare un sopralluogo all'ufficio tecnico.

**Comment by cristigalas** [comment]
Il Comune e Enel ci hanno comunicato via Facebook di essere intervenuti stamani sul posto. Chiudo.
