### ISSUE TITLE
Famiglia sfollata a Sant’Elpidio cerca automobile

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3419]
<pre><yamldata>tel: '3663796088'
email: quinzisaturnino@libero.it
cosa: 'Auto e urgente'
descrizione: 'Mi chiamo Quinzi Saturnino, ho bisogno urgentemente di un''auto, basta che cammini non pretendo altro... Ho 3 figli piccoli da spostare, in più ho perso il lavoro perché non posso arrivare sul posto.. Scusate mi vergogno.. Ma non ho pensioni o entrate varie, non lavoro da sette anni, e adesso sono senza casa, soldi, auto... Non mi resta che aspettare un miracolo.... Ma vedo che purtroppo sono finiti...Sono ora al camping Le Mimose a Porto Sant’’Elpidio.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 07/11/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Sono finalmente riuscita ad avere più informazioni sulla situazione. Il Sig. Saturnino è attenzionato sia dal GUS che dalla CARITAS. Gli sono arrivate diverse offerte di donazione in termini monetari dopo la segnalazione che sembra non aver mai accettato. Possiamo intanto rilanciare la richiesta di automobile.

**Comment by cristigalas** [comment]
Christian Varani ci scrive che ha parlato con il signore che è riuscito a recuperare una macchina adatta alle sue necessità. Chiudo.
