### ISSUE TITLE
Famiglia terremotata cerca cucina componibile  

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3420]
<pre><yamldata>tel: '3465336856'
email: ''
cosa: 'Cercasi Cucina Componibile in Regalo'
descrizione: 'Siamo una famiglia terremotata senza lavoro, siamo a porto Sant''Elpidio e abbiamo bisogno di un cucina lineare di circa 4 mt. entro i primi di dicembre poiché devo lasciare la struttura alberghiera e ho trovato una casa in locazione che ne è sprovvista. Grazie. Antonella'
indirizzo: 'Via San Giovanni Bosco, Porto Sant''Elpidio, FM, Marche, 63018, Italia'
lat: '43.2589619'
lon: '13.7569828'
link: ''
immagine: ''
data: 08/11/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica che si può chiudere la richiesta.
