### ISSUE TITLE
Cercasi giacche a vento invernali e scarponcini di varie misure e taglie #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3434]
<pre><yamldata>tel: '3248824117'
email: christianvarani@gmail.com
cosa: 'Richiesta di giacche a vento invernali e scarponcini di varie msure e taglie, per gli Amatriciani'
descrizione: 'Servono necessariamente, per i cittadini amatriciani, che ne sono sprovvisti e non hanno ancora la SAE (Soluzione Abitativa di Emergenza), per questo periodo e per i prossimi mesi invernali una quindicina di scarponcini di varie misure, quindi sia per bambini che adulti, e delle giacche a vento invernali, sempre di diverse taglie. Mi sono stati domandati da un volontario della Protezione Civile con il quale sono ancora in contatto di nome Baldo. Per maggiori informazioni e contatti diretti utili, anche al fine della donazione, rivolgersi ai recapiti specificati in questa richiesta. Grazie!'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Baldo Maggiore'
immagine: ''
data: 18/11/2017
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci informa che non c'è più bisogno. Chiudo.
