### ISSUE TITLE
Richiesta di giacche a vento invernali e scarponcini, per i cittadini di Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3435]
<pre><yamldata>tel: '3248824117'
email: christianvarani@gmail.com
cosa: 'Richiesta di giacche a vento invernali e scarponcini, per i cittadini di Amatrice'
descrizione: 'Servono necessariamente per questo periodo e per i prossimi mesi invernali ad Amatrice, almeno 15 paia di scarponcini sia per bambini che adulti e quindi di varie misure e 15 giacche a vento invernali, utili in modo particolare per i cittadini Amatriciani. Vi comunico che il quantitativo mi è stato specificato recentemente da un volontario e responsabile della Protezione Civile di nome Baldo, con la quale sono ancora in contatto e dal quale proviene la domanda di determinati beni. Per donazioni e per maggiori informazioni, rivolgersi ai recapiti utili, specificati in questa nuova richiesta!'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.facebook.com/Baldo Maggiore'
immagine: ''
data: 19/11/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente
