### ISSUE TITLE
errata corrige

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3436]
<pre><yamldata>titolo: 'errata corrige'
descrizione: 'Salve qualche tempo fa ho segnalato che mio padre aveva avuto problemi a causa del terremoto della Valnerina. Nel post è stato inserito un numero telefonico errato 3494501631 (la persona che risponde a quel numero si occupa di altro e non vive in Valnerina) Vi chiedo cortesemente di correggere il link visto che questa persona riceve continuamente chiamate. Il numero giusto è il 337 639867. Un altro errore è nel titolo: il negozio ha subito dei danni ma non è distrutto!'
link: 'https://terremotocentroitalia.info/issues/2825/'
data: 20/11/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Modificata: https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/2825
