### ISSUE TITLE
Auto e urgente

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3438]
<pre><yamldata>tel: '3663796088'
email: saturninoquinzi@libero.it
cosa: 'Auto e urgente'
descrizione: 'Ormai sono monotono ma continuo a cercare un auto qualsiasi essa sia x trovare lavoro x portare mia moglie incinta alle visite x urgenze x la scuola dei gli altri due piccoli di dieci e tre anni ,purtroppo non è facile e capisco ,ma x una famiglia senza casa auto soldi e senza lavoro con tre figli credetemi non si vive,e specialmente con il natale alle porte è un dramma....comunque grazie a tutti quelli che finora anno aiutato noi tutti e buon natale'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 11/12/2017
</yamldata></pre>

**Comment by chiccap** [comment]
Richiesta già presente qui: https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/3419
