### ISSUE TITLE
Cesti di Natale con prodotti di #Norcia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3440]
<pre><yamldata>Nome: >
  Cesti di Natale con prodotti di Norcia
E-mail: info@valnerinaonline.it
Testo: "Nella pagina web è possibile trovare l'’elenco delle aziende che hanno espresso la propria volontà di mettersi in mostra, di creare una vetrina virtuale per sopperire alla mancanza di utenza reale. Alcune aziende avevano un negozio distrutto, altre si sono formate per necessità economiche, altre spediscono i prodotti da magazzini provvisori, in attesa di effettuare i lavori per ritornare alla normalità."
URL: >
  https://web.valnerinaonline.it/cesti-di-natale-strenne-prodotti-norcia/
</yamldata></pre>

**Comment by cristigalas** [comment]
Copia #3442.
