### ISSUE TITLE
AIUTO

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3458]
<pre><yamldata>tel: '3663796088'
email: saturninoquinzi@libero.it
cosa: AIUTO
descrizione: 'Purtroppo non riesco a trovare lavoro con tre piccoli di 11/3/una settimana arriva il terzo,non abbiamo più soldi,siamo alloggiati al camping Mimose porto s Elpidio,i soldi a spettanti alla maternità tardano ad arrivare,non si più che fare,sono nel panico più totale, a58 anni nessuno ti apre le porte del lavoro,sto chiedendo a tutti anche al mio amico sindaco Franchellucci,ma non sa nemmeno lui cosa fare,cercò un Miserabile lavoro niente di più,o venduto pellami fino al 2007, poi x evasione fiscale o dovuto chiudere , quindi se si trovasse qualcosa nelle pelli o pelletterie,farei qualsiasi cosa,ma vi prego Aiutatemi,voglio solo lavorare non chiedo altro'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 17/01/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta già presente.
