### ISSUE TITLE
Signora di 83 anni autonoma of

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3461]
<pre><yamldata>tel: '3929323666'
email: lara1805@live.it
descrizione: 'Signora di 83 anni autonoma offre la sua casa in cambio di compagnia, rimasta vedova vorrebbe dare vitto e alloggio a 1/2 persone che sono in cerca di casa. Si trova in zona divino amore Roma.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/01/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap che facciamo? Io non accetterei.

**Comment by chiccap** [comment]
@cristigalas anche io non accetterei.
