### ISSUE TITLE
Cercasi a #Norcia modulo-container da usare come sala d'attesa medica

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3472]
<pre><yamldata>tel: '3398586465'
email: giacocariani@gmail.com
cosa: 'Modulo container che sarà usato come sala d''attesa medica #Norcia'
descrizione: 'Il Comune di Norcia ha ricevuto come donazione dalla Croce Rossa Italiana un modulo-container da utilizzare come ambulatorio medico per il nuovo medico di medicina generale che avrebbe svolto la sua attività a Norcia vista la grave situazione post sima 2016. È sorto però il problema di avere un container da utilizzare come sala d''attesa per i pazienti in attesa di entrare nell''ambulatorio-container già donato dalla Croce Rossa Italiana. Si richiede nei limiti del possibile se ci fosse la disponibilità di un container da utilizzare come sala d''attesa. Grazie!'
indirizzo: 'Piazza San Benedetto, Casale Carucci, Norcia, Perugia, Umbria, 06046, Italia'
lat: '42.7927706'
lon: '13.0930812'
link: ''
immagine: ''
data: 05/04/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci segnala via email che ha saputo che il container è stato donato al Comune di Norcia.
