### ISSUE TITLE
Cercasi trasporto per 15 tricicli da Roma ad #Arquata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3475]
<pre><yamldata>tel: 366-4008466
email: maggi.monica@gmail.com
cosa: 'Cercasi trasporto per 15 tricicli da Roma ad #Arquata'
descrizione: '15 tricicli sono stati donati all''associazione Libra 2.0 da un privato che vuole restare anonimo. Ma ABBIAMO BISOGNO DI UN FURGONCINO in grado di trasportarli da ROMA ad ARQUATA DEL TRONTO, in provincia di Ascoli Piceno. CHI CI VUOLE AIUTARE? Una ditta, un privato, uno sponsor che “SALGA” su questi tricicli. Contattaci! Grazie di cuore!'
indirizzo: 'Piazza Umberto I, Arquata del Tronto, Ascoli Piceno, Marche, Italia'
lat: '42.7723609'
lon: '13.2965826'
link: 'https://libraduepuntozero.wordpress.com/2018/04/26/cerchiamo-trasporto-per-15-tricicli-da-regalare-alla-scuola-di-arquata-del-tronto/'
immagine: 'https://i.imgur.com/cKbco7w.jpg'
data: 27/04/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
L'associazione ci comunica via Twitter che hanno trovato il trasporto e che i tricicli verranno consegnati il 16 maggio. https://twitter.com/Libra2puntozero/status/994518886186934272?s=19
