### ISSUE TITLE
"Le tue scarpe al centro", un progetto di economia circolare per #Amandola

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3476]
<pre><yamldata>titolo: '"Le tue scarpe al centro", un progetto di economia circolare per #Amandola'
descrizione: 'Continua in 49 Comuni dell''Emilia Romagna il progetto di economia circolare "Le tue scarpe al centro" che prevede per tutto il 2018 la raccolta di vecchie scarpe da ginnastica o infradito in gomma che, una volta riciclate, produranno granulato per realizzare tappetini antiurto per parchi giochi. Il materiale raccolto servirà a finanziare un parco giochi nel Comune di Amandola (FM), colpito dal sisma nel 2016. Al link ulteriori informazioni sul progetto e sui punti di raccolta.'
link: 'http://www.regione.emilia-romagna.it/infeas/documenti/progetti/educazione-alleconomia-circolare/le-tue-scarpe-al-centro'
data: 27/04/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
Progetto concluso.
