### ISSUE TITLE
Cercasi progetto, azienda, associazione a cui donare raccolta fondi EpiCentro Rock

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3486]
<pre><yamldata>tel: ''
email: alessandra.lamboglia@hotmail.com
cosa: 'EpiCentro Rock - donazione fondi raccolti dopo concerto di beneficenza'
descrizione: 'Buongiorno, siamo un gruppo di musicisti che hanno organizzato l''evento "EpiCentro Rock". Si tratta di un concerto tenutosi il 31 marzo 2017 nella frazione di Camugnano (BO), grazie al quale abbiamo raccolto fondi sufficienti a comprare una quantità discreta di fieno e sementi, che abbiamo poi portato fisicamente, con il patrocinio del comune di Camugnano, a due aziende agricole situate tra Pievebovigliana, Visso e Castelsantangelo sul Nera. Quest''anno ci piacerebbe riproporre il concerto per una nuova raccolta fondi: in questi giorni stiamo valutando le possibili destinazioni. Con questa segnalazione speriamo di ottenere notizie su possibili necessità riguardanti una scuola, o una casa per anziani, un ospedale, un centro ricreativo..qualunque cosa per cui possa servire un piccolo aiuto a migliorare la qualità della vita. Ci farebbe piacere acquistare qualcosa di concreto: a concerto/raccolta conclusa, ci piacerebbe venire di persona a portare il materiale. Potete contattarci a questo indirizzo email; visitate la pagina "EpiCentro Rock - il viaggio" per vedere l''esperienza dello scorso anno!'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 06/09/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
La signora Patrizia Vita del Comune di Ussita ha contattato gli organizzatori del concerto e il ricavato andrà a sostenere la costruzione di un centro sociale per bambini e anziani all'interno del comune. 
Il concerto sarà il 20 ottobre. Chiudo.
