### ISSUE TITLE
Cercasi con urgenza camper ad #Arquata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3487]
<pre><yamldata>tel: ''
email: laviadelsaleonlus@gmail.com
cosa: 'Cercasi con urgenza camper ad #Arquata'
descrizione: 'Abbiamo cercato a lungo una soluzione per Mauro, un boscaiolo residente a Tufo, frazione di Arquata del Tronto. La sua storia si accomuna a quella delle tante persone che hanno perso la propria casa nel terremoto, ma c''è una cosa che lo differenzia: la sua determinazione nel credere che la ricostruzione sarebbe iniziata in tempi brevi. Era così speranzoso di rientrare in casa propria tanto da non fare richiesta per la Sae. Ogni giorno da più di due anni, fa avanti e indietro da Ascoli per poter lavorare. Un errore di calcolo che lo ha costretto ad aprire gli occhi sulla realtà: la sua casa è ancora lì, distrutta, immutata (foto allegata). Mauro non può continuare così a lungo. Ha provveduto a fare richiesta per una Sae e nell''attesa della consegna di quest''ultima, abbiamo bisogno del vostro aiuto. Riusciamo a trovare un camper, almeno per un paio di mesi? Ci occuperemo noi dell''associazione La Via del Sale Onlus delle spese di trasporto.'
indirizzo: 'Arquata del Tronto, Ascoli Piceno, Marche, 63096, Italia'
lat: '42.7356059'
lon: '13.2528417'
link: ''
immagine: ''
data: 24/09/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ci comunica via email che ha parlato con l'associazione La Via del Sale e non c'è più bisogno del camper.
