### ISSUE TITLE
Cerco container #Arquata

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3488]
<pre><yamldata>tel: ''
email: mariafrancescapiermarini19@gmail.com
cosa: Container
descrizione: 'Cerco urgentemente un container o struttura simile dove poter mettere i mobili di casa mia sita ad Arquata del Tronto nella frazione di Pretare (AP), dato che tra qualche giorno sarà demolita. Grazie per l''attenzione!'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 27/09/2018
</yamldata></pre>

**Comment by luciroma** [comment]
nell'anteprima della segnalazione non compare la descrizione.

**Comment by cristigalas** [comment]
Mancava un apice dopo apostrofo. L'ho aggiunto vediamo se tra un po' si visualizza.

**Comment by cristigalas** [comment]
Christian Varani via email ci scrive che ha contattato la signora e gli ha detto di aver trovato un'altra soluzione: un deposito ad Ascoli dove può collocare mobili e arredi. Chiudo.
