### ISSUE TITLE
Conteiner

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3489]
<pre><yamldata>tel: '3389676804'
email: mariafrancescapiermarini19@gmail.com
cosa: Conteiner
descrizione: 'Cerco conteiner per deposito mobili , causa imminente demolizione della mia casa sita ad Arquata del Tronto nella frazione di Pretare.Grazie per l attenzione'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 27/09/2018
</yamldata></pre>

**Comment by chiccap** [comment]
chiudo già presente.
