### ISSUE TITLE
Cercasi libri per attivare un servizio di bookcrossing a #Norcia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3493]
<pre><yamldata>tel: '3479108946'
email: emanuele@abc-online.it
cosa: 'bookcrossing a Norcia'
descrizione: 'I commercianti già attivi nella Galleria Commerciale Artigianale hanno pensato di dedicare un piccolo spazio all’iniziativa dello SCAMBIO DI LIBRI, dando la possibilità a grandi e piccini di usufruire di un servizio gratuito e di pubblico interesse. Maggiori informazioni presso la Galleria Commerciale Artigianale di Norcia Se vuoi effettuare una consegna a mano è semplice: recati presso La Galleria – Centro Commerciale Artigianale e cerca le librerie che sono state predisposte lungo il vano centrale. Se vuoi effettuare una spedizione tramite poste o corriere, puoi indirizzare a ABC OnLine – c/o La Galleria – loc. Misciano – 06046 Norcia (PG) – tel 3479108946. Inserisci nella confezione un tuo indirizzo email e ti invieremo la foto dei tuoi libri nelle librerie del Booksharing di Norcia.'
indirizzo: 'Madonnabella, Norcia, Perugia, Umbria, 06046, Italia'
lat: '42.77923598671107'
lon: '13.09401869773865'
link: 'https://web.valnerinaonline.it/bookcrossing-a-norcia/'
immagine: ''
data: 05/10/2018
</yamldata></pre>

**Comment by cristigalas** [comment]
Chiesto via Twitter all'associazione Libra se possono aiutare in qualche modo. Ci faranno sapere.

**Comment by cristigalas** [comment]
Via Twitter l'associazione Libra ci ha confermato di aver preso contatti e che invierà un po' di libri.

**Comment by cristigalas** [comment]
Christian Varani ci fa sapere che il book crossing è stato attivato con oltre 1000 libri. Vedi qui http://www.bookcrossing.com/
