### ISSUE TITLE
Ruggero Emanuele

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3500]
<pre><yamldata>nome: 'Ruggero Emanuele'
tel: '3460533383'
email: rmegazzini@libero.it
descrizione: 'Spett.le Terremoto Centro Italia, Sono Ruggero Emanuele Megazzini, cittadino e residente presso il comune etneo di Aci Sant''Antonio. La contatto su suggerimento di Monithon per chiederLe come e quali steps si devono seguire per iniziare a tracciare la gestione dei fondi (10 Mln di euro) che sono stati stanziati dall''attuale Governo Conte per i comuni colpiti dal sisma, di giorno 26 Dicembre. Infatti tra i comuni destinatari dei fondi c''è anche Aci Sant''Antonio. Pertanto il meetup santantonese -di concerto con gli altri meetup della zona, ovvero quei centri urbani destinatari dei fondi governativi- ha intenzione di avviare una rendicontazione puntuale, precisa e chiara su come verranno spesi tali fondi dalle amministrazioni locali. In ogni caso, molto probabilmente sarà la protezione civile a farsi carico dei lavori, senza passare il "testimone" ai comuni interessati. In tal caso, come si potrebbe procedere? Ad ogni modo in attesa di una vostra risposta ringrazio anticipatamente per l''attenzione. Cordialmente Ruggero Emanuele Megazzini'
indirizzo: ''
lat: ''
lon: ''
link: ''
data: 02/01/2019
</yamldata></pre>

**Comment by cristigalas** [comment]
Girata richiesta a Ricostruzione Trasparente che lo contatterà quanto prima.
