### ISSUE TITLE
salve. desidero cancellare i m

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3511]
<pre><yamldata>tel: '3459585558'
email: roberta.angheben@gmail.com
descrizione: 'salve. desidero cancellare i miei dati dal vostro sito ma non ci riesco , soprattutto il numero di telefono. grazie. Roberta angheben'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 07/08/2019
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviata email per chiedere riferimenti sull'annuncio.

**Comment by cristigalas** [comment]
La segnalazione è questa https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/2047
Ho tolto il numero di telefono e chiusa la segnalazione.
