### ISSUE TITLE
CANCELLARE INFORMAZIO I PERSONALI

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3516]
<pre><yamldata>titolo: 'CANCELLARE INFORMAZIO I PERSONALI'
descrizione: 'chiedo che vengano cancellate le mie informazioni personali riportate in questo annuncio molto vecchio'
link: 'https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/2075'
data: 07/02/2020
</yamldata></pre>

**Comment by cristigalas** [comment]
Riferimenti personali eliminati e tolta label ‘accettato’.
