### ISSUE TITLE
biocontenimento BSL-4

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#3517]
<pre><yamldata>titolo: 'biocontenimento BSL-4'
descrizione: 'Circola su gruppi whatsapp il seguente alert: Il dipartimento della protezione civile, in collaborazione col governo ha deliberato che il 15 marzo se l’epidemia non è stata contenuta verrá dichiarato il biocontenimento BSL-4. Il più alto che prevede protocolli di contenimento estremamente stringenti. Se l’oms dichiara la pandemia significa che il mondo si fermerà completamente per 21 giorni. Borsa, parlamenti, scuole, aeroporti, treni, uffici, attività commerciali.. tutto. Solo un membro per ogni nucleo famigliare sarà dotato del kit necessario per recarsi ai checkpoint militari approntati per i rifornimenti necessari. Nessun’altra potrà lasciare la quarantena domiciliare, malato o sano, grave o no. Dopo 21 giorni sapremo che il virus è sconfitto ma faremo la conta di un isolamento così rigido.'
link: 'https://www.positanonews.it/2020/03/lultima-bufala-sul-coronavirus-verra-dichiarato-biocontenimento-bsl-4/3368964/'
data: 10/03/2020
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalo al nuovo progetto Covid19Italia https://github.com/emergenzeHack/covid19italia/issues

**Comment by tailot** [comment]
@cristigalas ancora non c'è l'avviso per cui non sappiamo se è stata segnalata alle autorià competenti. Segnalo per precauzione!
