### ISSUE TITLE
Cercasi animatori, animatrici

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#411]
<pre><yamldata>titolo: 'Cercasi animatori, animatrici'
descrizione: 'Urgono animatori ed animatrici per bambini, artisti di ogni genere ed intrattenitori. Maggiori info sulla pagina Facebook "Terremoto centro Italia, chiamata alle arti artisti e animazione" Emanuela Carocca 3934137960'
link: ''
data: 15/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Si trattava di richiesta per evento circoscritto. Chiudo fabbisogno.
