### ISSUE TITLE
Cercasi Roulotte a Scai (Amatrice)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#469]
<pre><yamldata>tel: '3393773303'
email: ''
cosa: Cercasi roulotte
descrizione: 'Serve una roulotte in buone condizioni per una famiglia di Scai (Amatrice) con un bimbo di due anni. Per il trasporto ho già chi può provvedere. Grazie!'
indirizzo: ''
lat: '42.59891'
lon: '13.23128'
link: ''
immagine: ''
data: 15/09/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
