### ISSUE TITLE
Cercasi CUOCO di AMATRICE per evento/mercato biologico il 5-6-novembre a RIVA del GARDA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#470]
<pre><yamldata>tel: '3334365401'
email: bertoni.angiolino@virgilio.it-
cosa: 'Cercasi CUOCO di AMATRICE per evento/mercato biologico il 5-6-novembre a RIVA del GARDA'
descrizione: 'durante l''evento ci sarà l''iniziativa di raccolta fondi "L''Amatriciana per Amatrice". Vitto e alloggio (credo anche il viaggio) offerti. Info e contatti: Bertoni Angiolino'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1769637063303877/'
immagine: ''
data: 15/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Chiudo fabbisogno. Ho inviato email per sapere se effettivamente è riuscito a mettersi in contatto con un cuoco per l'evento.

**Comment by chiccap** [comment]
nessuno l'ha contattato
