### ISSUE TITLE
Richieste beni Torrita, Sommati, Saletta, Nommisci

### ISSUE THREAD

**Issue by annaluciont** [emergenzeHack/terremotocentro_segnalazioni#478]
<pre><yamldata>tel: ''
email: ''
descrizione: 'Dai responsabili dei centri di raccolta di Torrita, Sommati, Saletta, Nommisci, S.Angelo ci giunge la richiesta dei seguenti materiali: PRODOTTI IGIENE CASA, MOCI, STRACCI, SCARPE DA TREKKING dal 37 in sù, SCARPE DA LAVORO dal 40 in sù, STIVALI IN GOMMA dal 41 in sù, IMPERMEABILI, STUFE ELETTRICHE, DETERSIVI BUCATO, OLIO DI SEMI, MANGIME PER ANIMALI.'
indirizzo: 'Torrita, Sommati, Saletta, Nommisci, S.Angelo'
lat: ''
lon: ''
link: ''
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by c83n** [comment]
@annaluciont se puoi edita la segnalazione mettendo quanti più dati possibile sul contatto da cui proviene (tipo anche chi l'ha segnalata su facebook). Poi prova a sentire questa persona via msg chat per capire bene il bisogno. Update quando fatto. Grazie

**Comment by c83n** [comment]
@iltempe / @aborruso / riuscite ad aggiungere questi users come collaborators alla repo?
- ChiaraParapini
- ilariawonder
- luciaroma
- veronicaboggini

**Comment by aborruso** [comment]
vado

**Comment by aborruso** [comment]
@c83n @iltempe , tutti invitati

**Comment by c83n** [comment]
@aborruso president!

**Comment by annaluciont** [comment]
Contatti https://m.facebook.com/Guardia-Rurale-Ausiliaria-1716061778613363/
Da Tel non posso modificare testo issue

**Comment by annaluciont** [comment]
Nella pag c'è loro n.Tel che ora non visualizzo

**Comment by c83n** [comment]
va bene grazie

**Comment by chiccap** [comment]
@aborruso non mi è arrivato nulla!

**Comment by aborruso** [comment]
@ChiaraParapini anche @c83n ha avuto problemi simili, per come aveva impostato le sue notifiche.

Come vedi sotto, c'è un invito pending. Nel testo si legge

> Invitations are sent via email and can be accepted at https://github.com/emergenzeHack

Probabilmente se fai click qui https://github.com/emergenzeHack dovresti trovare un qualche luogo in cui accettare l'invito.

Mi fai sapere?

![image](https://cloud.githubusercontent.com/assets/30607/18592013/48fdb646-7c35-11e6-86b1-9c1f56747d0a.png)

**Comment by chiccap** [comment]
@aborruso done! facilissimo, grazie!
