### ISSUE TITLE
GRUPPO ELETTROGENO

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#483]
<pre><yamldata>tel: ''
email: ''
cosa: 'GRUPPO ELETTROGENO'
descrizione: 'Campo autogestito di Capricchia segnalano la necessità di un gruppo elettrogeno, in quanto è stata staccata la corrente.'
indirizzo: ''
lat: '42.622598'
lon: '13.340167'
link: ''
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
issue datata. chiudo.
