### ISSUE TITLE
Cercasi Roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#486]
<pre><yamldata>tel: '3451629957'
email: ''
cosa: 'Cercasi Roulotte'
descrizione: 'Si cerca urgentemente 1 roulotte con due posti per portare avanti l''attività locanda che in questi giorni è frenetica.'
indirizzo: ''
lat: '42.55002'
lon: '13.36260'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1760699620864288/'
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
