### ISSUE TITLE
Cercasi Roulotte e Camper ad #Amandola

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#493]
<pre><yamldata>tel: '0736840731'
email: ''
cosa: 'Roulotte e Camper'
descrizione: 'Ad Amandola la pioggia rende impossibile la permanenza sotto le tende della protezione civile. Chi volesse mettere a disposizione roulotte o camper per alcuni mesi a favore di chi non ha più la casa agibile può contattare il numero 0736840731.'
indirizzo: ''
lat: '42.99726'
lon: '13.33343'
link: ''
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
