### ISSUE TITLE
Musicchio: servono nell'immediato ciabatte no infradito e antiscivolo per fare la doccia, e un accappatoio nuovo da ragazza (xs)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#503]
<pre><yamldata>tel: ''
email: ''
cosa: 'Musicchio: servono nell''immediato ciabatte no infradito e antiscivolo per fare la doccia, e un accappatoio nuovo da ragazza (xs)'
descrizione: 'servono nell''immediato ciabatte no infradito e antiscivolo per fare la doccia, e un accappatoio nuovo da ragazza (xs)'
indirizzo: 'Strada Regionale 260 Picente, Amatrice, RI, Lazio, Italy'
lat: '42.623587'
lon: '13.279079'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1761961677404749/'
immagine: ''
data: 30/08/2016
</yamldata></pre>

**Comment by marco-acorte** [comment]
tutto consegnato
https://www.facebook.com/groups/1758670357733881/permalink/1761961677404749/?comment_id=1762343957366521&comment_tracking=%7B%22tn%22%3A%22R0%22%7D
