### ISSUE TITLE
Punto di raccolta, esclusivamente per questo tipo di materiale, è presso l’Asilo Occupato, Aquila dalle 16.30 alle 20.30.

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#505]
<pre><yamldata>tel: ''
email: ''
cosa: 'Punto di raccolta, esclusivamente per questo tipo di materiale, è presso l’Asilo Occupato, Aquila dalle 16.30 alle 20.30.'
descrizione: '"LAZIO – CAPRICCHIA: bagni, asciugatrice; – SCAI: asciugatrice; – COSSITO: doccetta da campo, 5 brande, 5 materassi; – SALETTA: lavatrice, asciugatrice, ferro da stiro; – CAMPO SCOSSA SOLIDALE: pentolame, fornelli; accappatoi; MARCHE – CAMPO TRA COLLE E SPELONGA: televisore per gli anziani; ABRUZZO – COLLEVERRICO DI MONTEREALE: container."'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.3e32.org/'
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Punto di raccolta chiuso.
