### ISSUE TITLE
Centro Smistamento Cittareale è necessario avere i seguenti beni

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#506]
<pre><yamldata>tel: ''
email: ''
cosa: 'Centro Smistamento Cittareale è necessario avere i seguenti prodotti'
descrizione: 'A breve termine: Teli Impermeabili (massimo 4x5) Fornelli Scaldini e stufette x tende Asciugapanni da campeggio Stivali da Lavoro Brandine e reti Cibo x animali Rialzi per tende Tende Grandi Caricabatterie per telefoni Generatori elettricità lavatrici Olio in Latta materassi bombole del gas Contenitori Alimentari Bagni Chimici Docce Mobili Scatoloni da Assemblare Buste Supermercato Giacche e Giacconi Nuovi Tutte le Taglie A Lungo Termine Roulotte Camper Bungalow Container NO VETRO e NO ABBIGLIAMENTO USATO'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/centrosmistamentocittareale/photos/a.743568022464219.1073741828.743484932472528/743625872458434/?type=3&theater'
immagine: ''
data: 31/08/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Centro chiuso.
