### ISSUE TITLE
Sono necessari alimenti per animali da cortile e gabbie da degenza.

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#508]
<pre><yamldata>tel: ''
email: ''
cosa: 'Sono necessari alimenti per animali da cortile e gabbie da degenza.'
descrizione: 'Con urgenza servono gabbie trappola di media dimensione; gabbie pieghevoli (quelle di degenza) per cani e gatti di media dimensione; cibo per cani e gatti al momento è a sufficienza, quindi quello più urgente al momento è per gli animali "da reddito" dispersi sul territorio. Per maggiori info sulla lista dei beni cfr sito Oipa.'
indirizzo: ''
lat: ''
lon: ''
link: 'http://www.oipa.org/italia/emergenzaterremoto/'
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
sul loro sito ci sono i punti di raccolta 

PER ASCOLI PICENO:
CIAM c/o EMERGENZA SISMA OIPA - Via Piemonte 4, 63100 Ascoli Piceno; Tel. 0736 250484

PER RIETI: 
• Capannone sito in via Ternana 2, Colonnetta di Montopoli di Sabina (RI) - Concordare la consegna con la delegata dell'OIPA di Rieti, Maria Teresa De Carolis - Tel. 345 2151716 ; rieti@oipa.org ; (è possibile lasciare il materiale nell'area privata davanti al capannone avvisando la delegata). 

PER VITERBO: 
• Sede dell'OIPA di Viterbo: Via Caduti di tutte le Guerre 6 - Monterosi (VT); 
Aperta tutte le mattine e su appuntamento contattando Paola Menino, 
Delegata OIPA di Viterbo - Tel. 327 5712626 ; viterbo@oipa.org
• Zoo 2001 - Via Mazzini 93; 01100 Viterbo; Tel. 327 5712626

PER L'AQUILA:
• Centro Ricostruzione Unghie "Euphoria Nails", via Cardinale Mazzarino 49 - 67100 L'Aquila (quartiere Torrione); Tel. 0862 207608
• Vepafarm - Farmacia veterinaria, piazzale Giuseppe Porto 4, L'Aquila; Tel 0862 405917

PER PERUGIA: 
• PET STORE CONAD - VIA BERNARDINO DA SIENA - 06081 SANTA MARIA DEGLI ANGELI 06081 ASSISI (PG); Tel. 075 8043746

**Comment by chiccap** [comment]
Raccolta chiusa.
