### ISSUE TITLE
Per centro smistamento Cittareale servono travi di abete 15/15, morali 8x8, 120 I di ferri, viti da 20 cm e chiodi da 10

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#515]
<pre><yamldata>tel: ''
email: ''
cosa: '100 travi di abete 15/15, 100 morali 8x8, 120 I di ferri, 2 pacchi di viti da 20 cm e 2 pacchi di chiodi da 10'
descrizione: 'Il Centro di smistamento di Cittareale cerca questo materiale per ampliare il centro, costruendo una struttura in legno così da poter ospitare più materiale possibile.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/centrosmistamentocittareale/posts/746470725507282'
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
ho aggiunto Christian e Annalù, non trovo Giorgia nella lista
