### ISSUE TITLE
Cesenatico, FC - Camping Village Cesenatico

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#521]
<pre><yamldata>tel: '054781344'
email: info@campingcesenatico.it
descrizione: 'CAMPING VILLAGE CESENATICO'
indirizzo: 'Viale Giuseppe Mazzini, Valverde, Cesenatico, FC, Emilia-Romagna, 47042, Italia'
lat: '44.20651'
lon: '12.3874595'
link: ''
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
La struttura non ha mai ospitato nessuna persona dalle zone terremotate. Non più disponibile.
