### ISSUE TITLE
CEI e portale ospitalità

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#563]
<pre><yamldata>tel: '327 3842841'
email: info@ospitalitareligiosa.it
descrizione: "CEI e portale dell’ospitalità religiosa offrono posti-letto gratuiti agli sfollati. Fabio Rocchi, presidente dell’associazione Ospitalità Religiosa Italiana componente del Coordinamento nazionale CEI sulle Case per Ferie comunica che il portale www.ospitalitareligiosa.it, in collaborazione con la Conferenza Episcopale Italiana (Ufficio Nazionale per la pastorale del tempo libero, turismo e sport / Ufficio Nazionale per i beni culturali ecclesiastici), ha allertato le strutture di ospitalità religiosa nelle zone limitrofe all’epicentro del terremoto del 24 agosto, per mettere gratuitamente a disposizione posti-letto di emergenza in favore degli sfollati, in attesa di una sistemazione più duratura da parte delle istituzioni.\tProvincie di Ascoli, Rieti, Fermo, Roma, Frosinone, Viterbo, L'Aquila"
indirizzo: 'Roma, RM, Lazio, Italia'
lat: '41.8935085'
lon: '12.4825526'
link: 'http://www.ospitalitareligiosa.it/'
immagine: ''
data: 16/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Copio risposta: "a suo tempo abbiamo raccolto le disponibilità di alloggio delle strutture religiose della zona e le abbiamo inoltrate alla Protezione Civile.
Abbiamo poi lasciato che la medesima prendesse ogni decisione e contatto con le singole strutture, per cui non abbiamo dati o riscontri sull'effettivo utilizzo.
Il nostro portale raccoglie le strutture religiose di ospitalità per promuoverle ma non ne segue l'amministrazione e la gestione."
