### ISSUE TITLE
Faete, AP - Materiale per costruzione tettoia e un sistema di riscaldamento

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#569]
<pre><yamldata>tel: '3701377864'
email: ''
cosa: 'comunità autogestita ha bisogno di materiale per costruire una tettoia e un sistema di riscaldamento'
descrizione: 'A Faete di Arquata del Tronto, c''è una comunità autogestita che ha bisogno di materiale per costruire una tettoia e un sistema di riscaldamento. Per info su come aiutare contattateci. Grazie'
indirizzo: 'Strada Provinciale 20 Colle, Arquata del Tronto, AP, Marche, Italia'
lat: '42.7696827'
lon: '13.3043513'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1770419146559002/'
immagine: ''
data: 17/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
@annaluciont l'ho assegnata a te per verifiche e diffusione. Può andare?

**Comment by annaluciont** [comment]
Good!

**Comment by favoeva** [comment]
Mandato contatto? @annaluciont

**Comment by favoeva** [comment]
abbiamo contatto x stufe a pellet da una ditta veneta: sofia.zorzetto@zfzorzetto.net (contatto fornito da Enrico  Ganassi (lo trovate nel gruppone Telegram TCI)
