### ISSUE TITLE
Associazione Pescara del Tronto cerca supporto per realizzare t-shirt 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#588]
<pre><yamldata>tel: '3482422546'
email: pescaradeltronto@hotmail.com
cosa: 'Associazione Pescara del Tronto cerca supporto per realizzare t-shirt'
descrizione: 'L''associazione Pescara del Tronto Onlus cerca supporto per realizzare t-shirt da utilizzare per raccolta fondi da investire nella ricostruzione. Fa appello alle aziende di abbigliamento che possano mettere a disposizione gratuita degli stock di t-shirt (o felpe) tinta unita.'
indirizzo: ''
lat: '42.7510056'
lon: '13.2666277'
link: 'https://www.facebook.com/pescaradeltronto/posts/1362190600475318'
immagine: ''
data: 18/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Nel 2016 qualche azienda ha donato delle t-shirt all'Associazione ma non abbiamo traccia se sia avvenuto o meno a seguito dell'inserimento segnalazione in TCI.
Francesco De Angelis, membro dell'Ass., mi ha riferito di chiudere.
