### ISSUE TITLE
Task force agricoltura naturale ad Amatrice a sostegno delle aziende agricole

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#602]
<pre><yamldata>titolo: 'Task force agricoltura naturale ad Amatrice a sostegno delle aziende agricole'
descrizione: 'Sabato 24 e domenica 25 settembre un gruppo di tecnici agricoli sarà ad Amatrice per aiutare le aziende agricole colpite dal sisma. Per informazioni potete contattare RESEDA onlus - tel- 069364170 ecoistituto@resedaweb.org Attualmente il progetto è delineato in questo modo, prevedendo le seguenti azioni: supporto tecnico e impianti solari per le aziende agricole montane colpite dal sisma; supporto tecnico per il design in permacultura delle aziende agricole montane e per i paesi colpiti dal sisma; supporto sociale per la cittadinanza per sostenere le capacità di resilienza, di collaborazione e di azioni collettive (metodo Transition Town); supporto tecnico alla ricostruzione ecologica degli edifici.'
link: 'https://amatriceduepuntozero.wordpress.com/'
data: 19/09/2016
</yamldata></pre>

**Comment by c83n** [comment]
secondo me questo e' il tipico esempio di sensore a cui fare agganciarsi
ho segnalato lamcosa a chiara parapini, annalu, veronica e lucia

da contattare subitissimo per entrare come segnalatori / offerenti di
servizi (supporto imprese)
- individuato webmaster e kiesto embed
- individuato referente
- impostatp mail alert a referente ogni volta che segnalazioni sono
  coerenti con loro
- impostato con loro sistema adeguato di labeling specifico per imprese
- se accettano farli entrare in redazione
- chiedere di entrare nel team di dondivisione e analisi dei dati aziende

che ne dite?
c

Il sabato 1 ottobre 2016, Fabio Manfrin notifications@github.com ha
scritto:
