### ISSUE TITLE
Genova, GE - piccolo appartamento

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#627]
<pre><yamldata>tel: '0000'
email: 
descrizione: 'richiesta cancellazione.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 21/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Mai stata contattata, ancora disponibile.

**Comment by cristigalas** [comment]
Richiesta cancellazione di tutti i dati il 14/5/2021 via email.
