### ISSUE TITLE
Comacchio, FE - porzione di villa a schiera con giardino per famiglia con animali

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#645]
<pre><yamldata>tel: '3476438278'
email: 31betty@libero.it
descrizione: 'Offro a titolo gratuito porzione di villa a schiera con giardino privato a famiglia con animali a seguito, bisognosa dopo il sisma. Enrico Spaggiari'
indirizzo: 'Via della Luna, Comacchio, FE, Emilia-Romagna, 44022, Italia'
lat: '44.7098217'
lon: '12.2236475'
link: ''
immagine: ''
data: 22/09/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Non più disponibile. Chiudo
