### ISSUE TITLE
Melta di Gardolo, TN - casa 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#656]
<pre><yamldata>tel: ''
email: acellana@libero.it
descrizione: 'Trentino Buongiorno metto a disposizione inverno primavera la mia casa in trentino per ospitare terremotati. Anna Cellana'
indirizzo: 'Strada della Flora, Pinara, Melta di Gardolo, Trento, Territorio Val d''Adige, TN, Trentino-Alto Adige, 38121, Italia'
lat: '46.102869'
lon: '11.1296199265191'
link: ''
immagine: ''
data: 22/09/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta non più disponibile.
