### ISSUE TITLE
Cercasi casetta di pochi metri quadrati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#658]
<pre><yamldata>tel: '3319715161'
email: tizianofisio@gmail.com
cosa: 'Casetta di pochi metri quadrati'
descrizione: 'Cerchiamo casetta di pochi metri quadrati, di legno o qualsiasi altro materiale purché sia coibentata.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 22/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
mandare mail a tizianofisio@gmail.com per chiedere indirizzo o verificare se possiamo chiudere

**Comment by Manfro** [comment]
@favoeva faccio io
