### ISSUE TITLE
URGENTE Cercasi roulotte o camper per 4 famiglie zona Amatrice/Sommati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#665]
<pre><yamldata>tel: '3404874665'
email: ''
cosa: 'Cercasi con urgenza roulotte o camper per 4 famiglie zona Amatrice/Sommati'
descrizione: 'Per tutto il periodo invernale, in zona Amatrice e Sommati, servirebbero roulotte o camper a stazionamento per almeno 4 nuclei famigliari (circa 4 membri l''uno), preferibilmente in buono stato, da donare o da restituire a marzo. La richiesta è urgente. Contattare Sig.ra Norma Vincenzi tramite SMS'
indirizzo: 'Sommati e Amatrice, RI, Lazio, Italia'
lat: '42.642924705805214'
lon: '13.310043811798096'
link: 'https://www.facebook.com/groups/sosamatriceterremoto/?fref=ts'
immagine: ''
data: 23/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
@Manfro sono arrivate queste due segnalazioni di disponibilità roulotte / camper su gruppo FB TCI 
- Mantova: http://www.subito.it/caravan-e-camper/regalo-roulotte-mantova-178292782.htm
- Brescia: http://www.subito.it/caravan-e-camper/roulotte-con-veranda-pedana-e-tendalino-brescia-178481794.htm

**Comment by favoeva** [comment]
ho mandato messaggio a n. cell. indicato (non ho ancora accesso al gruppo fb chiuso) attendo risposta.

**Comment by iltempe** [comment]
contattata la Vincenzi su Facebook. attendo feedback.

**Comment by Manfro** [comment]
@favoeva Abbiamo feedback?

**Comment by iltempe** [comment]
nessuno. attendiamo.

**Comment by favoeva** [comment]
Per le due che ci hanno segnalato,   Il referente ha preso contatti. Teniamola aperta per altre famiglie.

**Comment by favoeva** [comment]
Confermato con sms alle 8.30 di oggi
