### ISSUE TITLE
A Cesa Ventre, fraz. Accumoli, servono generatori, bagni chimici e altro per campo autogestito

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#677]
<pre><yamldata>tel: ''
email: centro.culturale.libra@gmail.com
cosa: 'Da Accumoli richiesta di alcuni beni per campo autogestito'
descrizione: 'A Cesa Ventre, frazione di Accumoli, un gruppo di sfollati (agricoltori e allevatori) in campo autogestito ha bisogno di: 3 paia di calzettoni pesanti a numero (dal 36 al 46) per un totale di 30 paia di calzettoni; 3 paia di stivali di gomma (dal 36 al 46) per un totale di 30 paia di stivali; 1 generatore 8chilowatt (Santa Giusta, che offre pranzo e cena gratuitamente a decine di persone); 1 generatore 6 chilowatt; 1 bagno chimico (ne hanno 1 ma lo usano in 24 persone tra uomini e donne).'
indirizzo: 'Strada Statale 4 Via Salaria, Amatrice, RI, LAZ, Italia'
lat: '42.661814'
lon: '13.2148933'
link: 'https://www.facebook.com/mmaggi/posts/10209013074458606'
immagine: ''
data: 24/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
richiesto aggiornamento su fabbisogni a Monica Maggi https://www.facebook.com/mmaggi/posts/10209013074458606 per sapere se possiamo chiudere o rilanciare su nostri canali

**Comment by favoeva** [comment]
Monica maggi conferma arrivo quanto richiesto. Si chiude.
