### ISSUE TITLE
A Scai servono stufa a pellet e roulotte

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#682]
<pre><yamldata>tel: '-'
email: 'eurosportello@aeceuropa.eu'
cosa: 'Stufetta a pellet di piccole dimensioni da mettere in un container'
descrizione: 'Nella frazione Scai di Amatrice serve con urgenza una stufetta a pellet di piccole dimensioni da mettere in un container (non possono permettersi di pagare troppo per allacciare quelle elettriche perchè sono senza lavoro). Inoltre chiedono delle roulotte per aiutare tre famiglie, una di 5 persone una di 7 e una di 3, per passare l''inverno.'
indirizzo: 'SP19, Amatrice, RI, Lazio, Italia'
lat: '42.5980591'
lon: '13.2305149'
link: 'https://www.facebook.com/photo.php?fbid=10209705594975742&set=gm.537508186452576&type=3&theater'
immagine: ''
data: 25/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
verificato su gruppo fb stufa a pellet consegnata
