### ISSUE TITLE
DATI SU AREE INTERNE - Agenzia per la coesione

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro_segnalazioni#717]
Website dell'agenzia per la coesione sulle aree interne (situate tra Marche, Lazio e Abruzzo).  http://www.agenziacoesione.gov.it/it/arint

**Comment by psykola** [comment]
Perché l'hai messa in Segnalazioni?! Argh!

Open Data: http://www.agenziacoesione.gov.it/it/arint/OpenAreeInterne/index.html

**Comment by c83n** [comment]
pensavo fosse utile anke qui ma spostala :)

**Comment by psykola** [comment]
Google sheet aperto a chiunque: https://docs.google.com/spreadsheets/d/1QaWVnwD-oA_bwwZf20UmUEjPhx9oOPmt4jNbq-SfSYA/edit?usp=sharing
