### ISSUE TITLE
Consulenze gratuite di import-export ai terremotati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#728]
<pre><yamldata>titolo: 'Consulenze gratuite di import-export ai terremotati'
descrizione: 'Da oggi enti, aziende ed associazioni impegnate nella ricostruzione post terremoto possono massimizzare l''efficenza dei propri budget aumentandone il potere d''acquisto da 2 fino ad 8 volte grazie alla consulenza offerta a titolo gratuito da un team di professionisti dell''import-export. http://www.importaredallacina.eu/il-nostro-contributo-alle-popolazioni-colpite-dal-terremoto-che-ha-colpito-il-centro-italia/ Da Cagliari spiega Raffaele Bonaddio, import manager di ImportareDallaCina.EU: «tutte le fabbriche nostre partner sono state allertate: alcune di esse sono già pronte a fornire prodotti e materiali praticamente a costi di realizzo. Siamo pronti a fare la nostra parte ed invitiamo altre aziende e professionisti a fare altrettanto». L''import manager tiene a precisare inoltre che «I riflettori sui disastri causati dal sisma avvenuto nel Centro Italia si stanno via via spegnendo. Il terremoto non fa più tanta notizia, ed alla gente ed alle aziende dei luoghi colpiti resta il compito, di ripartire, di tornare alla vita di prima. Vogliamo stare al fianco delle associazioni, degli enti, dei gruppi spontanei che si stanno prodigando per una rapida ricostruzione». L''iniziativa di http://www.ImportareDallaCina.EU/ sembra in un certo qual modo capovolgere il paradigma della diffidenza nei confronti dell''onnipresente colosso cinese: in questo caso saranno proprio i beni da importare dalla Cina a contribuire a far ripartire l''economia locale e la vita quotidiana. CONTATTI: 070-7967731 www.importaredallacina.eu/chi-siamo/contatti/'
link: 'http://www.importaredallacina.eu/il-nostro-contributo-alle-popolazioni-colpite-dal-terremoto-che-ha-colpito-il-centro-italia/'
data: 30/09/2016
</yamldata></pre>

**Comment by favoeva** [comment]
parliamone...
