### ISSUE TITLE
Sos pecorino dei Monti della Laga - Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#731]
<pre><yamldata>tel: '3402334530'
email: info@pecorinoamatriciano.it
cosa: 'ACQUISTO SOLIDALE pecorino Monti della Laga'
descrizione: 'SOS PECORINO DI AMATRICE - Consorzio Monti della Laga: ACQUISTO SOLIDALE'
indirizzo: ''
lat: '42.66725'
lon: '13.46569'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1776217779312472/'
immagine: ''
data: 01/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
già inserito.
