### ISSUE TITLE
Sabato 1 ottobre dalle ore 19: Salaria chiusa al km 146, auto e mezzi pesanti deviati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#733]
<pre><yamldata>titolo: 'Sabato 1 ottobre dalle ore 19: Salaria chiusa al km 146, auto e mezzi pesanti deviati'
descrizione: 'Dalle 19 di sabato 1 ottobre ANAS ha disposto la chiusura della Salaria al km 146,200 (sottostante Pescara del Tronto) in entrambi i sensi di marcia per via cautelativa a causa di rischio smottamenti.
Non ancora nota la data di riapertura, ma i collegamenti verranno ripristinati appena le condizioni meteo lo consentiranno. Traffico consentito solo ai mezzi di soccorso, Protezione Civile e forze dell''ordine.
Per le auto da Ascoli Piceno a Rieti: deviare al km 148,800 (Trisungo) proseguendo su SS685 direzione Norcia. Poi SP476 in direzione Cittareale e SP17 per rimettersi sulla Salaria al km 121,400.'
link: 'https://www.picenooggi.it/2016/10/01/37630/alle-19-sara-chiusa-al-traffico-la-salaria-al-chilometro-146/'
data: 01/10/2016
</yamldata></pre>

**Comment by veronicaboggini** [comment]
Dalle 19 di sabato 1 ottobre ANAS ha disposto la chiusura della Salaria al km 146,200 (sottostante Pescara del Tronto) in entrambi i sensi di marcia per via cautelativa a causa di rischio smottamenti.
Non ancora nota la data di riapertura, ma i collegamenti verranno ripristinati appena le condizioni meteo lo consentiranno. Traffico consentito solo ai mezzi di soccorso, Protezione Civile e forze dell'ordine.
Per le auto da Ascoli Piceno a Rieti: deviare al km 148,800 (Trisungo) proseguendo su SS685 direzione Norcia. Poi SP476 in direzione Cittareale e SP17 per rimettersi sulla Salaria al km 121,400.
