### ISSUE TITLE
Sant'Angelo, RI - Richiesta aiuti per famiglie

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#748]
<pre><yamldata>tel: '3472869633'
email: 'eurosportello@aeceuropa.eu'
cosa: 'Aiuto per famiglie di Sant''Angelo'
descrizione: 'Quattro persone hanno bisogno di stufette possibilmente ad olio, mangime per galline e cani, almeno 30 kg, scarponi invernali numeri: 41 43 44 46, Marsupi, teloni verdi molto spessi'
indirizzo: 'SP20, Casale Zocchi, Amatrice, RI, Lazio, 02012, Italia'
lat: '42.6496118'
lon: '13.3042554'
link: 'https://www.facebook.com/permalink.php?story_fbid=1660800270916894&id=1657318057931782'
immagine: ''
data: 04/10/2016
</yamldata></pre>

**Comment by drizzt** [comment]
Chi ha editato il campo cosa: levando il doppio "'" per "San'tAngelo" che è obbligatorio per essere uno yaml valido?

**Comment by Manfro** [comment]
Non lo so, li mi era sfuggito, mancavano anche in altri punti.

**Comment by drizzt** [comment]
il webform e il bot telegram "dovrebbero" metterlo (se non lo fanno aprite un bug), per cui (forse) è qualcuno che l'ha editato a mano senza saperlo
