### ISSUE TITLE
#SantGiusta #Amatrice (RI): 2 librerie anche usate  misure: 80x110 - 40x110

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#754]
<pre><yamldata>tel: ''
email: ''
cosa: '#SantGiusta #Amatrice (RI): 2 librerie anche usate  misure: 80x110 - 40x110'
descrizione: 'per PAGINE VIAGGIANTI a Santa Giusta (Amatrice) cercasi 2 librerie anche usate misure: 80x110 - 40x110 grazie :)'
indirizzo: 'Santa Giusta, RI, Lazio, Italia'
lat: '42.6431126'
lon: '13.2528535'
link: 'https://twitter.com/Libra2puntozero/status/783580866836561920'
immagine: ''
data: 05/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
Controllato oggi: librerie arrivate. Chiudo issue
