### ISSUE TITLE
Cercasi attrezzature da cucina

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#784]
<pre><yamldata>tel: '3926462066'
email: vanessapiccari@libero.it
cosa: 'Attrezzature cucina'
descrizione: 'Buonasera vi contatto perché abbiamo ancora bisogno del vostro aiuto..... Le Tende e la Cucina del Campo Emergenza Sisma di S.Angelo di Amatrice saranno rimosse per una scelta organizzativa delle Amministrazioni preposte. Per questa ragione la nostra associazione AIPS di S.Angelo di Amatrice, interna al Campo per l''emergenza Terremoto, sta riorganizzando il locale della propria cucina a sostegno delle attività'' proprie della AIPS, migliorate ed adattate alla nuova condizione della Emergenza Sisma. In ragione di questa urgente necessita'' abbiamo bisogno delle necessarie attrezzature da cucina che descriviamo: Un Completo di Pentole, Padelle e Accessori. Una piccola scaffalatura in metallo inox. Un Forno a Micro onde e una Macchina per il caffè'' per il Banco Bar. Lanciamo questo appello per chiedere un sostegno da parte di chi può'' impegnarsi anche solo per alcuni delle attrezzature che elenchiamo, avendo compreso che la generosità'', l''altruismo e la gratuita'' di tutti i Volontari che abbiamo conosciuto, o semplicemente sentito al telefono, nel nostro Campo Emergenza di S.Angelo, sono i veri valori che la nostra Umanità'' Sommersa di Terremotati, chiede per ricostruire le Case e il Lavoro nei Paesi di Amatrice, in questa terra meravigliosa, selvaggia e generosa. Oggi e'' uscito il Decreto per la Ricostruzione che vogliamo utilizzare anche per creare lavoro da subito, come già'' facciamo. Sostenete le nostre azioni per la Ricostruzione dei Paesi di Amatrice perche'' lo stiamo già facendo. Un carissimo saluto. Vanessa Piccari AIPS Associazione Amatrice'
indirizzo: 'SP20, Casale Zocchi, Amatrice, RI, Lazio, 02012, Italia'
lat: '42.6496118'
lon: '13.3042554'
link: ''
immagine: ''
data: 11/10/2016
</yamldata></pre>

**Comment by iltempe** [comment]
Possiamo tuittare e postare?

**Comment by cristigalas** [comment]
Rilancio su Twitter...

**Comment by favoeva** [comment]
Rilanciato su FB

**Comment by favoeva** [comment]
sentita vanessa al tel. oggi. La scorsa settimana non avevano ancora trovato nulla. Le ho chiesto di fare una nuova verifica e di aggiornarci. Ha il mio Cell.

**Comment by chiccap** [comment]
Ho chiamato Vanessa e per quanto riguarda l'attrezzatura da cucina la necessità resta sempre ma la cucina non andrebbe nei locali per aiutare Augusto (che si occupava della cucina interna al campo) ma sarebbe utilizzata per attrezzare il locale cucina dell'associazione AIPS che resta al momento l'unico punto di riferimento della comunità. @cristigalas @favoeva rilanciamo?

**Comment by cristigalas** [comment]
@chiccap @favoeva forse conviene fare una nuova segnalazione e chiudere questa? Semmai con un rimando, che ne dite?

**Comment by chiccap** [comment]
Sono d'accordo! Se volete faccio io! Questa in caso la chiudiamo? Vogliamo chiedere prima a media team?

**Comment by cristigalas** [comment]
@chiccap io procederei e poi semmai fai rimando a questa issue che chiuderei.
