### ISSUE TITLE
Cesaventre #Accumoli, gli abitanti vogliono restare: ''cerchiamo 5 roulotte o camper''

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#790]
<pre><yamldata>tel: '3462865450'
email: sara.vegni@gmail.com
cosa: 'Segnalazione da Cesaventre'
descrizione: 'Nella frazione vivono 23 persone, ovvero 5 nuclei familiari, mentre una coppia di anziani si sono trasferite a L''Aquila. Ci sono minori (bambini e adolescenti) e anziani con problemi di salute. Non si registrano crolli maggiori, ma numerose case sono parzialmente inagibili e l''intera popolazione vive in roulotte da oltre 1 mese, tranne una famiglia che è riuscita a ottenere una casa su ruote tramite una donazione privata. 2 bagni chimici sono arrivati solo dieci giorni fa'' insieme all''allaccio di 6kw di corrente (prima andavano con un generatore). E'' un caso in cui si potrebbe ottenere il rientro nelle case vere dopo le ristrutturazioni in tempi brevi e in cui non dovrebbero essere necessario la costruzione di sae/map. La signora che ci ha contattate molte volte ha avanzato la richiesta di avere informazioni e supporto per l''ottenimento di 5 case su ruote. La signora (Cinzia) può essere contattata.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 12/10/2016
</yamldata></pre>

**Comment by iltempe** [comment]
Mi pare una questione su cui porre molta attenzione. per poi divulgare al massimo via social! @dontyna @favoeva che pensate?

**Comment by iltempe** [comment]
'Nella frazione vivono 23 persone, ovvero 5 nuclei familiari, mentre una coppia di anziani si sono trasferite a L''Aquila. Ci sono minori (bambini e adolescenti) e anziani con problemi di salute. Non si registrano crolli maggiori, ma numerose case sono parzialmente inagibili e l''intera popolazione vive in roulotte da oltre 1 mese, tranne una famiglia che è riuscita a ottenere una casa su ruote tramite una donazione privata. 2 bagni chimici sono arrivati solo dieci giorni fa'' insieme all''allaccio di 6kw di corrente (prima andavano con un generatore). E'' un caso in cui si potrebbe ottenere il rientro nelle case vere dopo le ristrutturazioni in tempi brevi e in cui non dovrebbero essere necessario la costruzione di sae/map. La signora che ci ha contattate molte volte ha avanzato la richiesta di avere informazioni e supporto per l''ottenimento di 5 case su ruote. La signora (Cinzia) può essere contattata.'

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
