### ISSUE TITLE
#Accumoli - richiesta cibo per papere, galline conigli e gatti

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#791]
<pre><yamldata>tel: '3336903233'
email: ''
cosa: 'cibo per papere, galline conigli e gatti'
descrizione: '#Accumoli - richiesta di cibo per papere, galline conigli e gatti - RAMIRO 3336903233'
indirizzo: 'Frazione Fonte del Campo, Case Marini, Accumoli, RI, Lazio, 02011, Italy'
lat: '42.694141'
lon: '13.247683'
link: 'https://www.facebook.com/angela.pignotti.5/posts/10210584989410747'
immagine: ''
data: 12/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
Della semola è già arrivata. chiesto oggi via fb aggiornamenti ad Angela Pignotti.
