### ISSUE TITLE
Richiesta di beni per affrontare l'inverno ad #Amatrice

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#804]
<pre><yamldata>tel: '3291631198'
email: christianvarani@gmail.com
cosa: 'RICHIESTA DI BENI'
descrizione: 'Sono necessari Scarponi impermeabili, 50 stufette elettriche anche economiche per potersi riscaldare e cucinare, Teloni della dimensione di 10*10, per poter coprire determinate cose, ma anche dei pannelli in coibentato utili per Roulotte, o Container, Stalle della dimensione ciascuno di almeno 4 cm.'
indirizzo: ''
lat: ''
lon: ''
link: 'https://www.facebook.com/pantera.laganord?ref=ts&fref=ts'
immagine: ''
data: 14/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
chiesto oggi via fb a Christian Varani se la richiesta è ancora valida.

**Comment by favoeva** [comment]
richiesta ancora valida ma per quanto riguarda stufette solo 50 
aggiorno issue

**Comment by cristigalas** [comment]
Christian Varani comunica su Fb che la richiesta è stata tutta soddisfatta, anche per le stufette. Chiudo.
