### ISSUE TITLE
Sito Pro Loco #Arquatadeltronto per sostenere la ripresa dei produttori e dell'economia locale

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#805]
<pre><yamldata>titolo: 'Pro Loco #Arquatadeltronto:  in sito per sostenere la ripresa dei produttori e dell''conomia locale'
descrizione: 'Sul nuovo sito della Pro Loco Arquata del Tronto è possibile sostenere le attività produttive della zona.'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1783214901946093/'
data: 15/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Sito non disponibile.
