### ISSUE TITLE
Richiesta di beni necessari

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#822]
<pre><yamldata>tel: ''
email: christianvarani@gmail.com
cosa: 'Richiesta di beni necessari'
descrizione: 'Si cercano con urgenza necessariamente per i cittadini di Amatrice determinati beni, che sono i seguenti: Scarponi preferibilmente impermeabili, "Goretex"; 50 stufette elettriche anche economiche per riscaldarsi specialmente in questo periodo autunnale e per i prossimi mesi invennali ed anche per poter cucinare; Alcuni teloni della dimensione minima di almeno (10x10) m ciascuno ; Pannelli in coibentato per poter coibentare delle Roulotte, Container presenti nella zona circostante e anche probabilmente per delle stalle;'
indirizzo: ''
lat: ''
lon: ''
link: 'HTTP://www.facebook.com/Anna Serpeverde Cristallini (Link per contatti utili)'
immagine: ''
data: 19/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione già presente http://terremotocentroitalia.info/issues/804/index.html
