### ISSUE TITLE
Ad #AcquasantaTerme cercasi scuolabus. Appello del sindaco

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#824]
<pre><yamldata>tel: '0736-801262'
email: 'comune.acquasantaterme@anutel.it'
cosa: 'Ad #AcquasantaTerme cercasi scuolabus. Appello del sindaco'
descrizione: 'Duecento studenti, cinquantaquattro frazioni, più di venti chilometri al giorno. Purtroppo l’unico scuolabus di Acquasanta Terme, colpito dal sisma, è vecchio. Va sostituito, ma ora il Comune non ha i soldi sufficienti. E così il sindaco lancia l’appello: “Aiutateci”.'
indirizzo: 'Strada Statale 4 Via Salaria, Acquasanta Terme, AP, Marche, 63095, Italia'
lat: '42.769944'
lon: '13.410185'
link: 'http://ilgiornaledellaprotezionecivile.it/dal-territorio/aaa-scuolabus-cercansi-appello-dopo-il-terremoto'
immagine: ''
data: 19/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
rilanciato su facebook

**Comment by chiccap** [comment]
Abbiamo aggiornamenti sulla raccolta fondi?

**Comment by iltempe** [comment]
No. dovremmo contattare https://www.gogobus.it/it/ si erano offerti di contattare il comune @chiccap fai tu?

**Comment by chiccap** [comment]
Sì me ne occupo io! Consiglio di inserire storico contatto con gogobus così teniamo traccia. @cristigalas le puoi reperire tu?

**Comment by chiccap** [comment]
![schermata 2016-11-07 alle 17 44 11](https://cloud.githubusercontent.com/assets/21237278/20066462/ea6b1136-a511-11e6-8f6b-e2bada261bb3.png)
![schermata 2016-11-07 alle 17 44 28](https://cloud.githubusercontent.com/assets/21237278/20066467/efbcc8aa-a511-11e6-861f-1077ad8b55a1.png)

**Comment by chiccap** [comment]
Gogobus ieri ci ha detto di aver trovato il bus! Gli abbiamo fornito i contatti del comune di Acquasanta ma ho paura che non siano attivi post-terremoto. Ho contattato Il Comune via FB chiedendo dei contatti diretti.

**Comment by chiccap** [comment]
Contatto Sindaco Sante Stangoni 3825882488.

**Comment by cristigalas** [comment]
@chiccap chiudiamo?

**Comment by chiccap** [comment]
Chiamo e chiedo per conferma!

**Comment by chiccap** [comment]
Parlato con l'assessore Elisa Ionni e sono in contatto con Gogobus per i documenti relativi alla donazione! Chiudo!
