### ISSUE TITLE
Roulotte o Camper per una famiglia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#855]
<pre><yamldata>tel: '335 6069775'
email: ''
cosa: 'Roulotte o Camper per una famiglia'
descrizione: 'Si segnala la necessità urgente di una sistemazione in roulotte o camper per una famiglia che vive in montagna e che ha la casa inagibile a causa del terremoto del 26 ottobre.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 27/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
