### ISSUE TITLE
Richiesta URGENTE - Cercasi gruppo elettrogeno di emergenza a #Norcia

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#867]
<pre><yamldata>tel: '3292860627'
email: ''
cosa: 'Gruppo elettrogeno di emergenza'
descrizione: 'Alla Pro Loco di Campi di Norcia serve urgentemente un gruppo elettrogeno di emergenza che permetterebbe di far funzionare gli impianti della struttura che attualmente sta garantendo assistenza alla comunità, il generatore dovrebbe essere da almeno 10/12kw con uscita 220. Si tratta di assoluta urgenza. Contattare Luca Tonellotto.'
indirizzo: 'Via Fiume, Casa Cupa, Norcia, PG, UMB, 06046, Italia'
lat: '42.853017366816786'
lon: '13.097312450408936'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1790456101221973/'
immagine: ''
data: 27/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
https://twitter.com/enelgroupit/status/793817247613652996
