### ISSUE TITLE
Leandro

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#869]
<pre><yamldata>nome: Leandro
tel: '3494152253'
email: Leandroliberati@gmail.com
descrizione: 'Posso dare una mano a voi ?'
indirizzo: ''
lat: ''
lon: ''
link: ''
data: 28/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
mandata mail da TCI
