### ISSUE TITLE
A #Ussita c'è bisogno di beni alimentari di prima necessità 

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#878]
<pre><yamldata>telegram_user: ''
descrizione: 'Ussita: il ristorante "la mezza luna" sta assicurando pasti per tutta la popolazione di Ussita e i volontari impegnati in zona da 3 giorni. Ha bisogno di una mano nel recuperare beni alimentari di prima necessità. L''elenco nella foto.'
immagine: 'http://i.imgur.com/5J7vNj6.jpg'
lat: '42.942536'
lon: '13.137668'
data: 29/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Emergenza cibo a Ussita è terminata.
