### ISSUE TITLE
A #Ussita c'è bisogno di bagni chimici per le tante persone che dormono in auto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#879]
<pre><yamldata>telegram_user: ''
descrizione: 'Ussita: per le tante persone che dormono in macchina e per coloro che sono impegnati nei recuperi c''è bisogno di bagni chimici.'
immagine: 'http://i.imgur.com/CyV6S3n.jpg'
lat: '42.942635'
lon: '13.139021'
data: 29/10/2016
</yamldata></pre>

**Comment by c83n** [comment]
Update 30 ottobre ore 09:40 

http://www.latinaoggi.eu/news/circeo/30367/terremoto-dal-comune-di-san-felice-circeo-un-container-con-servizi-igienici-per-ussita.html

Il Comune di San Felice Circeo invierà a Ussita un container predisposto con servizi igienici, doccia e uno spogliatoio come intervento utile e concreto per i terremotati. L’assessore Luciano Magnanti, promotore dell’iniziativa, ha contattato il Sindaco del Comune marchigiano che ha accettato l’offerta, ritenendola di grande utilità. Nei prossimi giorni l’Amministrazione provvederà all’approvazione degli atti formali che consentiranno l’invio della struttura, mentre da parte di alcuni privati ci si è affiancati all’iniziativa: la ditta Mastruzzo provvederà con i propri mezzi al trasporto, le spese del carburante saranno coperte dal Conad di borgo Montenero e il condizionamento interno –considerate le basse temperature che già si registrano- sarà fornito sempre gratuitamente dalla ditta Sirio.
L’ Amministrazione Comunale ringrazia quanti hanno collaborato alla realizzazione di questo atto di solidarietà, di fronte a una tragedia che colpisce popolazioni già duramente provate nei mesi scorsi.
