### ISSUE TITLE
A #Ussita c'è bisogno di 2 camper per alcune famiglie che dormono in auto

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#880]
<pre><yamldata>telegram_user: ''
descrizione: 'Ussita: per alcune famiglie che da 3 notti dormono in macchina c''è bisogno di 2 camper. Contatti: Sara Vegni Actionaid 3462865450'
immagine: ''
lat: '42.94261'
lon: '13.138755'
data: 29/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
