### ISSUE TITLE
COMUNE DI #PIEVETORINA: dove si può ricevere cibo

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#881]
<pre><yamldata>titolo: 'COMUNE DI #PIEVETORINA: COMUNICATO'
descrizione: 'Si comunica alla popolazione ed in particolar modo per la cittadinanza delle frazioni che è possibile mangiare presso la struttura della protezione civile nell''area camper vicino al campo sportivo. Si prega di fare il passa parola.'
link: 'https://www.facebook.com/ComunePieveTorina/?fref=nf'
data: 29/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Struttura disallestita a novembre 2016.
