### ISSUE TITLE
Offerta casa di campagna con 6 posti letto in provincia di Piacenza

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#895]
<pre><yamldata>tel: '349 5671721'
email: marc.lecannu@gmail.com
descrizione: 'Disponiamo di una casa di campagna con 6 posti letto e tre bagni. Anche se la nostra provincia è piuttosto distante dalla zona del terremoto, possiamo ospitare chi ha bisogno senza problema. I piccoli animali sono ben accetti. Il nostro indirizzo: Via Badenigo 7. 29010 Ziano Piacentino (PC), frazione di Vicobarone'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 30/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Nessuna richiesta pervenuta, non più risponibile.
