### ISSUE TITLE
Metto a disposizione appartamento in provincia di Forlì-Cesena

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#899]
<pre><yamldata>tel: '3494699977'
email: robertasama@libero.it
descrizione: 'Metto a disposizione un appartamento per i terremotati di Norcia e paesi limitrofi . Ha una camera matrimoniale, bagno, cucinotto e soggiorno con divano letto matrimoniale. Sarebbe bello se fossero anziani, ma non è prioritario. Sarà gioia grande ospitarvi'
indirizzo: 'Via Tosoni, Longiano, FC, Emilia-Romagna, Italia'
lat: '44.0712863'
lon: '12.3242981'
link: ''
immagine: 'http://i.imgur.com/oJ5mT4B.jpg'
data: 30/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Non più disponibile.
