### ISSUE TITLE
CERCASI ROULOTTE PER MAMMA CON BAMBINA PICCOLA

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#901]
<pre><yamldata>tel: '366 3434996'
email: ''
cosa: 'ROULOTTE PER MAMMA CON BAMBINA PICCOLA'
descrizione: 'Ad Amatrice serve urgentemente una roulotte per una mamma (24 anni) con una bambina piccola (3 anni). Contattare Antonella.'
indirizzo: 'Piazza Cacciatori del Tevere, Casalene, Amatrice, RI, Lazio, 02012, Italia'
lat: '42.6292367'
lon: '13.2891755'
link: ''
immagine: ''
data: 30/10/2016
</yamldata></pre>

**Comment by c83n** [comment]
Aggiorno con contatti fb a cui ho segnalato isue:

## ho scritto questo

"#terremoto #amatrice  salve sono christian quintili di actionaid italia stiamo mappando bisogni a seguito del sisma. vi segnaliamo questa necessità con tutti i contatti e se non disturbiamo mi permetto di inviarvene altre simili. per qualsiasi info mi trovate qui o al 342-0834926 grazie

## http://terremotocentroitalia.info/issues/901/

segue elenco:
- scegliilcamper.it https://goo.gl/QAlJNB (messaggio inviato)
- camperisti online https://goo.gl/VTiX7C (postato su wall)
- camperisti: https://goo.gl/nGM8Sw (messaggio inviato)
- camperisti (@camperworld): https://goo.gl/6XFQLw (postato su wall)
- camperisti di monzambano: https://goo.gl/OEsIq8 (wall)
- camperisti delle dolomiti: https://goo.gl/UhLVqL (wall)
- camperisti senza frontiere: https://goo.gl/PDv2Wc (wall)
- Associazione naz. coordinamento camperisti: https://goo.gl/DHLc8Y (messaggio)
- Camperisti (@camperclubcentotorri): https://goo.gl/zHtsZ7 (wall)
- Camperisti sardi: https://goo.gl/0W0KiA (messaggio)
- Camperisti and teenagers: https://goo.gl/ETfjY9 (wall)
- Associazione Camperisti Retorbido: https://goo.gl/58vhfZ (messaggio)
- Camperisti con pelosi a bordo: https://goo.gl/3IxYNo (wall)
- Camperisti fulminati: https://goo.gl/XEcItf (wall)
- Camperisti italiani: https://goo.gl/6e6ocz (wall)
- Camperisti abusivi year: https://goo.gl/shRFmQ (wall)
- Camperisti scooteristi: https://goo.gl/NMhAVP (wall)
- Camperisti toscani: https://goo.gl/aFPBuA (wall)

**Comment by c83n** [comment]
Update 
- Camperisti delle Dolomiti risponde e rilancia: https://goo.gl/1VS8L8

**Comment by chiccap** [comment]
- Perugia Caravan: https://goo.gl/0YYBsP (postato su wall)

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
