### ISSUE TITLE
Marco Serani

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#903]
<pre><yamldata>nome: 'Marco Serani'
tel: '3347694358'
email: seranimarco@gmail.com
descrizione: 'Vorrei essere contattato per capire come mettere a disposizione un immobile a Castelraimondo a favore dei soggetti terremotati grazie'
indirizzo: ''
lat: ''
lon: ''
link: ''
data: 30/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Inviata email da casella di TCI suggerendo di usare web form.
