### ISSUE TITLE
Tecnici per effettuare le prime verifiche post terremoto SAN SEVERINO MARCHE

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#905]
<pre><yamldata>tel: '0733641222'
email: ''
cosa: 'Tecnici per effettuare le prime verifiche post terremoto SAN SEVERINO MARCHE'
descrizione: 'Il sindaco di San Severino Marche lancia un appello. Nel Comune mancano tecnici per effettuare le prime verifiche post terremoto. Si richiedono geometri, architetti, ingegneri e professionisti qualificati che vogliano rendersi disponibili per gli accertamenti. APPELLO a chi intendesse mettersi a disposizione gratuitamente.'
indirizzo: 'Piazza del Popolo, San Severino Marche, MC, Marche, Italia'
lat: '43.2290211'
lon: '13.1779663'
link: 'http://l.facebook.com/l.php?u=http%3A%2F%2Fwww.comune.sanseverinomarche.mc.it%2Fcomunicati-cms%2Fterremoto-infinita-la-conta-dei-danni-ultimi-sopralluoghi-portano-inagibilita-degli-edifici-al-42%2F%23more-47080&h=pAQE4Dwmv'
immagine: ''
data: 30/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente.
