### ISSUE TITLE
A #CERRETO DI #SPOLETO #BORGOCERRETO (PG) servono roulotte o camper

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#910]
<pre><yamldata>tel: '3345978758'
email: ''
cosa: '#CERRETO DI #SPOLETO #BORGOCERRETO (PG) Servono roulotte o camper'
descrizione: 'A Cerreto di Spoleto Borgocerreto (Pg) servono roulotte o camper per aiutare famiglie in difficoltà senza casa che hanno bisogno di un posto dove potersi appoggiare. Se avete roulotte o camper da mettere a disposizione contattate Matilde D''Anania ai numeri 3345978758 oppure 3333550760. In alternativa chiedono posti letto.'
indirizzo: 'Piazza Pontano, Cerreto di Spoleto, PG, UMB, 06041, Italy'
lat: '42.8210425'
lon: '12.9176291'
link: 'https://www.facebook.com/groups/1758670357733881/permalink/1792004511067132/'
immagine: ''
data: 30/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
