### ISSUE TITLE
[Foto] Campanile della chiesa di San Giovanni pericolante

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#912]
<pre><yamldata>telegram_user: MarcoAlici
descrizione: 'Campanile della chiesa di S. Giovanni pericolante, minaccia crollo su chiesa o abitazioni vicine.'
immagine: 'http://i.imgur.com/jdVWDf5.jpg'
lat: '43.111742'
lon: '13.603804'
data: 30/10/2016
</yamldata></pre>

**Comment by MarcoAlici** [comment]
Comune di #Grottazzolina.
Posizione: http://www.openstreetmap.org/way/292617870
Aggiornamento: Pianificato ieri sera intervento urgente di messa in sicurezza, da attuarsi già a partire da oggi.
Ancor più grave la situazione nella chiesa del SS. Sacramento (http://www.openstreetmap.org/node/2601005082). Lesioni preesistenti alle pareti laterali stanno provocandone il cedimento sotto il carico del tetto. Anche qui si sta lavorando già da stamattina per la messa in sicurezza urgente del fabbricato, che si trova nelle vicinanze della scuola primaria "A. Diaz" e del Teatro comunale "E. Novelli", oltre che di diverse abitazioni private.
