### ISSUE TITLE
BENI DI PRIMA NECESSITA' - Centro di raccolta Palestra Diaz a #PortoRecanati

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#933]
<pre><yamldata>tel: '071 7500725'
email: 'info@campinglamedusa.it'
cosa: 'BENI DI PRIMA NECESSITA'' - Camping Medusa, Porto Recanati'
descrizione: 'Occorrono beni di prima necessità ai nuovi sfollati collocati al Camping Medusa di Porto Recanati (MC). In particolare servono asciugamani, saponi, vestiti, omogeneizzati e cibo per bambini. Portare i beni al centro di raccolta allestito alla Palestra Diaz di Porto Recanati.'
indirizzo: 'Via Manin, Porto Recanati, MC, Marche, 62017, Italia'
lat: '43.4350815'
lon: '13.6630083'
link: ''
immagine: ''
data: 30/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta chiusa.
