### ISSUE TITLE
#NEWS - Vice Sindaco Acquasanta a Rainews

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro_segnalazioni#935]
15:32: vice sindaco acquasanta a Rai News 

"non sappiamo se in frazioni abbiamo feriti sotto alle macerie" (...) "non abbiamo mezzi e uomini, stiamo lavorando con due mezzi, 6 uomini protezione civile locale. La gente è sul piazzale del municipio, ci sono scene da panico: bambini che non parlano, genitori che non entrano a casa e sono ancora in pigiama (...) tutti i concittadini sono fuori e stiamo cercando hotel per farli ospitare. Abbiamo fatto richiesta alla prefettura di monitorare tutto nostro territorio anti sciacallaggio (...). Faccio appello a Governo: rimandiamo referendum e devolviamo le risorse ai terremotati"

**Comment by favoeva** [comment]
Oggi dichiarazioni vice sindaco su referendum non sono state riprese dai giornali.

**Comment by favoeva** [comment]
Condivisa linea con media team:  non pubblichiamo
