### ISSUE TITLE
Offresi alloggio 80mq a Torino

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#972]
<pre><yamldata>tel: '3493270414'
email: statino@yahoo.it
descrizione: 'Alloggio 80mq mettiamo a disposizione in Torino.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 30/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Contattato da una signora ma non è andato a buon fine. Non più disponibile.
