### ISSUE TITLE
Materiale per sfollati da Croce Azzurra

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#979]
<pre><yamldata>tel: '3396822184'
email: matteougolotti@libero.it
cosa: 'Materiale per sfollati da Croce Azzurra'
descrizione: '[Segnalazione pervenuta via email in Data: 31 ottobre 2016 10:30:07] Dalla scossa di agosto abbia ancora nei nostri magazzini del materiale di prima necessità per gli sfollati. Vi chiediamo di farci sapere se gli ospiti hanno bisogno di questo materiale. Se ci dite dove dislocare il materiale o dove portarlo agli sfollati provvederemo alla distribuzione senza alcuna spesa. Sicuri di una vs risposta vi salutiamo. 
2 scatoloni di sciarpe guanti cuffie 
4 maglioni maglie donna 
3 scatoloni maglioni uomo 
+ indumenti sportivi uomo 
+ calze calzettoni 
+ giacche donna 
2 scatoloni giacche uomo 
2 scatoloni jeans pantaloni uomo 
+ pantaloni gonne donna 
+ pigiami donna 
+ giacconi uomo/donna 
2 scatoloni abbigliamento bimbo/a 
- giacche bimbo/a 
- scarpe bimbo/a 
- scarpe uomo/donna 
1 scatolone trapunte/coperte/sacco a pelo 
2 scatoloni bagnoschiuma 
2 scatoloni sapone 
1 scatoloni giochi e libri x bimbi 
2 scatoloni spray multiuso igiene cada 
1 scatolone libri favole x bimbi 
1 scatolone peluche 
4 scatoloni piatti plastica 
3 bicchieri plastica 
1 scatolone assorbenti e pannolini 
1 scatolone assorbenti 
2 scatoloni tovaglioli \fazzoletti 
1 scatoloni carta igienica 
2 scatoloni disinfettanti x casa 
2 scatoloni set posate 
1 scatolone materiale didattico 
1 scatolone spugne 
1 scatolone detersivi x piatti 
1 scatolone spazzatura 
1 scatolone detersivi pavimenti 
1 scatolone salviette monouso 
1 scatolone detersivi x panni 
1 lettino x neonati 
5 scope e palette'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by iltempe** [comment]
Tutto il materiale è stato consegnato ieri a porto Recanati e porto sant’Elpidio, contatto privato eseguito da Matteo Ugolotti. chiudo.
