### ISSUE TITLE
Offro camera matrimoniale a Briosco (MB)

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#981]
<pre><yamldata>tel: '3475469312'
email: an.ma.colombo@alice.it
descrizione: 'Vivo solo in una casa indipendente con tre camere da letto. Metto a disposizione una camera matrimoniale per il periodo invernale a persone autonome, perchè ci sono le scale.'
indirizzo: 'Via Galileo Galilei, Briosco, Monza e della Brianza, Lombardia, 20836, Italia'
lat: '45.7230251'
lon: '9.2520767'
link: ''
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by chiccap** [comment]
Riporto testo risposta: "Devo informarvi che nessuno ha usufruito della mia offerta. Data la distanza è anche capibile che diventa difficile per qualsiasi persona allontanarsi dai propri luoghi ed affetti. Attualmente l'alloggio non è disponibile perche utilizzato da familiari. Seguo ancora il vostro sito per verificare se posso essere utile in altro modo."
