### ISSUE TITLE
Appartamento in centro storico

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#983]
<pre><yamldata>tel: '3297606112'
email: andrea.cannavicci@cblelectronics.com
descrizione: 'Appartamento in centro storico a Todi. 3 posti letto cucina camera e bagno. Disponibilità immediata'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by cristigalas** [comment]
Offerta già inserita.
