### ISSUE TITLE
Cercasi due roulotte zona #Preci

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#994]
<pre><yamldata>tel: '0758012737'
email: ''
cosa: 'Cercasi due roulotte zona Preci'
descrizione: 'RICHIESTA IMPORTANTE siamo alla ricerca di un paio di roulotte per la zona di Preci. Chiunque fosse interessato a metterle a disposizione può contattarci tramite messaggio o telefono. Grazie.'
indirizzo: 'Via della Libertà, Preci, Casale Maggiori, Preci, PG, UMB, 06047, Italia'
lat: '42.87848895'
lon: '13.0390821148298'
link: 'https://www.facebook.com/permalink.php?story_fbid=1100543740061243&id=128113723970921'
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
Ima roulotte trovata da protezione civile bastia umbra che ha letto post FB (ora sta cercando l'altra)

**Comment by favoeva** [comment]
Trovata ieri anche l'altra da privato in rimessaggio a ravenna

**Comment by chiccap** [comment]
https://twitter.com/terremotocentro/status/793349675139076096
