### ISSUE TITLE
A #Cascia cercasi con urgenza roulotte o camper

### ISSUE THREAD

**Issue by terremotocentroita** [emergenzeHack/terremotocentro_segnalazioni#997]
<pre><yamldata>tel: '3477320592'
email: paolonifabio@libero.it
cosa: 'Roulotte o camper.'
descrizione: 'Buongiorno, sono residente nel Comune di Cascia, mio padre e la famiglia di mio fratello avrebbero bisogno di un camper o una roulotte dato che l'' abitazione è lesionata e al momento l''unica soluzione proposta dalle istituzioni è quella di recarsi negli hotel del Trasimeno ma, avendo una attività sul posto preferirebbero rimanere. Ringrazio in anticipo per la disponibilità e resto in attesa. Cordiali saluti.'
indirizzo: ''
lat: ''
lon: ''
link: ''
immagine: ''
data: 31/10/2016
</yamldata></pre>

**Comment by favoeva** [comment]
contatto telefonico 3487710091-99 Puccetta Stefano
Ieri ci ha scritto: Protezione Civile C.O.V.E.R. Passignano sul Trasimeno noi possiamo mettere a disposizione modulo abitativo da 70mq a bisogno di qualche lavoro interno e mobilio una volta aperto dispone di grande sala con angolo cucina due camere e bagno l'unico problema e portarlo li da voi se riuscite ad organizzarvi

**Comment by favoeva** [comment]
mandata mail a Fabio Paoloni che ci ha inviato segnalazione

**Comment by cristigalas** [comment]
Christian Varani ha verificato con Cristina Fustinoni di Caravanisti Solidali che la richiesta è ormai chiusa.
